////

|metadata|
{
    "name": "breaking-changes-2010-volume-2-sr-1",
    "controlName": [],
    "tags": ["Known Issues"],
    "guid": "a1049796-b13b-4b78-97ec-236ce6e9d38d",  
    "buildFlags": [],
    "createdOn": "2012-01-31T21:16:05.5637973Z"
}
|metadata|
////

= 2010 Volume 2 August Service Release

== Moved Classes

[options="header", cols="a,a"]
|====
|Former Namespace|New Namespace

|Infragistics.Controls.Maps.DataMapping 

({ApiPlatform}Controls.Maps.XamMap.v10.2.dll)
|Infragistics.DataMapping 

({ApiPlatform}DataVisualization.v10.2.dll)

|Infragistics.Controls.Maps.DataMappingPair 

({ApiPlatform}Controls.Maps.XamMap.v10.2.dll)
|Infragistics.DataMappingPair 

({ApiPlatform}DataVisualization.v10.2.dll)

|====

== Renamed Classes

[options="header", cols="a,a"]
|====
|Former Class Name|New Class Name

|Infragistics.Controls.Charts.Animation 

({ApiPlatform}Controls.Charts.XamGauge.v10.2.dll)
|Infragistics.Controls.Charts.GaugeAnimation 

({ApiPlatform}Controls.Charts.XamGauge.v10.2.dll)

|====