////

|metadata|
{
    "name": "breaking-changes-2010-volume-3",
    "controlName": [],
    "tags": ["Known Issues"],
    "guid": "c8f42f89-d4ed-4845-b803-6f91c0fe6c7f",  
    "buildFlags": [],
    "createdOn": "2012-01-31T21:16:05.5667976Z"
}
|metadata|
////

= 2010 Volume 3

== xamMap

The authentication method for Bing Maps® imagery service which is used by the link:{ApiPlatform}controls.maps.xammap.v{ProductVersion}~infragistics.controls.maps.xammap.html[xamMap]™ control’s link:{ApiPlatform}datavisualization.v{ProductVersion}~infragistics.controls.maps.bingmapstilesource.html[BingMapsTileSource] to acquire imagery data, has been updated and now Microsoft® recommends usage of Bing Maps Keys instead of tokens. As result, we updated the link:xamwebmap-add-bing-maps-as-geo-imagery-data-source.html[Binding Bing Maps] topic to use this new method of the Bing Maps imagery service authentication in the Developer’s Guide for xamMap control. For more information on changes made in Bing Maps imagery service please refer to this Microsoft’s link:http://msdn.microsoft.com/en-us/library/cc980937.aspx[website] and to request your own Bing Maps Keys please refer to this link:http://msdn.microsoft.com/en-us/library/ff428642.aspx[website].