////

|metadata|
{
    "name": "breaking-changes-2010-volume-2",
    "controlName": [],
    "tags": ["Known Issues"],
    "guid": "c536c031-c7a6-40e3-a437-cccc3c153b02",  
    "buildFlags": [],
    "createdOn": "2012-01-31T21:16:05.5617971Z"
}
|metadata|
////

= 2010 Volume 2

The following breaking changes apply to all controls in the {ProductName} Data Visualization product.

== Infragistics.Silverlight.DataVisualization (Now: {ApiPlatform}DataVisualization)

*NAMESPACE CHANGES:*

Infragistics.Silverlight $$->$$ Infragistics

*URIs:*

ig:(http://schemas.infragistics.com/xaml) represents: (Infragistics)

*DESIGN ASSEMBLIES:*

Infragistics.Silverlight.DataVisualization.v9.2.Design - > {ApiPlatform}DataVisualization.v10.2.Design

== Infragistics.Silverlight.DataVisualization.Controls (Now: {ApiPlatform}Controls)

*NAMESPACE CHANGES:*

Infragistics.Silverlight.Controls $$->$$ Infragistics.Controls

*URIs:*

ig:(http://schemas.infragistics.com/xaml) represents: (Infragistics.Controls)

*CLASS NAME CHANGES:*

XamWebZoombar $$->$$ xamZoombar

XamWebDock $$->$$ xamDock

*DESIGN ASSEMBLIES:*

Infragistics.Silverlight.DataVisualization.Controls.v9.2.Design - > {ApiPlatform}Controls.v10.2.Design

== Infragistics.Silverlight.DataVisualization.Gauge (Now: {ApiPlatform}Controls.Charts.XamGauge)

*NAMESPACE CHANGES:*

Infragistics.Silverlight.Gauge $$->$$ Infragistics.Controls.Charts

*URIs:*

ig:(http://schemas.infragistics.com/xaml) represents: (Infragistics.Controls.Charts)

*CLASS NAME CHANGES:*

XamWebLinearGauge $$->$$ xamLinearGauge

XamWebRadialGauge $$->$$ xamRadialGauge

XamWebSegmentedDisplay $$->$$ xamSegmentedDisplay

XamWebBulletGraph $$->$$ xamBulletGraph

*DESIGN ASSEMBLIES:*

Infragistics.Silverlight.DataVisualization.Gauge.v9.2.Design - > {ApiPlatform}Controls.Charts.XamGauge.v10.2.Design

== Infragistics.Silverlight.DataVisualization.Map (Now: {ApiPlatform}Controls.Maps.XamMap)

*NAMESPACE CHANGES:*

Infragistics.Silverlight.Map $$->$$ Infragistics.Controls.Maps

*URIs:*

ig:(http://schemas.infragistics.com/xaml) represents: (Infragistics.Controls.Maps)

*CLASS NAME CHANGES:*

XamWebMap $$->$$ xamMap

*DESIGN ASSEMBLIES:*

Infragistics.Silverlight.DataVisualization.Map.v9.2.Design - > {ApiPlatform}Controls.Maps.XamMap.v10.2.Design

== Infragistics.Silverlight.DataVisualization.Timeline (Now: {ApiPlatform}Controls.Timelines.XamTimeline)

*NAMESPACE CHANGES:*

Infragistics.Silverlight.Timeline $$->$$ Infragistics.Controls.Timelines

*URIs:*

ig:(http://schemas.infragistics.com/xaml) represents: (Infragistics.Controls.Timelines)

CLASS NAME CHANGES:

XamWebTimeline $$->$$ xamTimeline

SeriesPane - EventTitlesPanel

*REMOVED CLASSES:*

GridArea

*ADDED CLASSES:*

StripesPanel

GridLinesPanel

AxisEventsPanel

LabelsPanel

TickMarksPanel

PreviewAxis

*CHANGED CLASSES:*

Axis $$->$$ TimelineAxis

Series $$->$$ TimelineSeries

SeriesCollection $$->$$ TimelineSeriesCollection

Legend $$->$$ TimelineLegend

*DESIGN ASSEMBLIES:*

Infragistics.Silverlight.DataVisualization.Timeline.v9.2.Design - > {ApiPlatform}Controls.Timelines.XamTimeline.v10.2.Design

== Infragistics.Silverlight.DataVisualization.Chart (Now: {ApiPlatform}Controls.Charts.XamWebChart)

*URIs:*

ig:(http://schemas.infragistics.com/xamWebChart) represents: (Infragistics.Silverlight.Chart)

*DESIGN ASSEMBLIES:*

Infragistics.Silverlight.DataVisualization.Chart.v9.2.Design - > {ApiPlatform}Controls.Charts.XamWebChart.v10.2.Design