////

|metadata|
{
    "name": "breaking-changes-2011-volume-2",
    "controlName": [],
    "tags": ["API","Known Issues"],
    "guid": "f43b45a6-564d-466d-92ce-a223732c92da",  
    "buildFlags": [],
    "createdOn": "2012-01-31T21:16:05.5747984Z"
}
|metadata|
////

= 2011 Volume 2

This topic lists breaking changes in the 2011 Volume 2 release of the {ProductName} product.

== xamDataChart™ – Renamed Classes

[options="header", cols="a,a"]
|====
|Former Name|New Name

|Infragistics.Controls.Charts.CategoryErrorBarsSettings 

{ApiPlatform}Controls.Charts.XamDataChart.v11.1.dll
|Infragistics.Controls.Charts.CategoryErrorBarSettings 

{ApiPlatform}Controls.Charts.XamDataChart.v11.2.dll

|====

ifdef::wpf[]
== xamMap™ - Moved Classes
endif::wpf[]

ifdef::wpf[]

[options="header", cols="a,a"]
|====
|Former Namespace|New Namespace

|Infragistics.Controls.Maps.BingMapsTileSource 

{ApiPlatform}Controls.Maps.XamMap.v11.1.dll
|Infragistics.Controls.Maps.BingMapsTileSource 

{ApiPlatform}DataVisualization.v11.2.dll

|Infragistics.Controls.Maps.OpenStreetMapTileSource 

{ApiPlatform}Controls.Maps.XamMap.v11.1.dll
|Infragistics.Controls.Maps.OpenStreetMapTileSource 

{ApiPlatform}DataVisualization.v11.2.dll

|Infragistics.Controls.Maps.CloudMadeTileSource 

{ApiPlatform}Controls.Maps.XamMap.v11.1.dll
|Infragistics.Controls.Maps.CloudMadeTileSource 

{ApiPlatform}DataVisualization.v11.2.dll

|====

endif::wpf[]

ifdef::wpf[]
== xamPivotGrid™ - Replaced Classes
endif::wpf[]

ifdef::wpf[]
The whole query generation model was changed in order to provide more flexibility and control over the final MDX query:
endif::wpf[]

ifdef::wpf[]

[options="header", cols="a,a"]
|====
|Former Class|New Class

|Infragistics.Olap.Xmla.IQuery 

{ApiPlatform}Olap.Xmla.v11.1.dll
|Infragistics.Olap.Xmla.IMdxQuery 

{ApiPlatform}Olap.Xmla.v11.2.dll

|====

endif::wpf[]

ifdef::wpf[]
The link:{ApiPlatform}olap.xmla.v{ProductVersion}~infragistics.olap.data.xmla.sqlanalysisservices2008.query.html[Query] class now implements the link:{ApiPlatform}olap.xmla.v{ProductVersion}~infragistics.olap.xmla.imdxquery.html[IMdxQuery] interface instead of IQuery interface:
endif::wpf[]

ifdef::wpf[]

*In C#:*

----
// Derived classes
public class Query : IMdxQuery
// Class properties
protected IMdxQuery XmlaDataSource.CurrentQuery
// Class methods
public void XmlaCommand.ExecuteCommandAsync(IMdxQuery)
public void XmlaCommand.ExecuteCommandAsync(IMdxQuery, XmlaConnection)
protected virtual string XmlaCommand.GenerateCommand(IMdxQuery)
protected virtual string XmlaSapCommand.GenerateCommand(IMdxQuery)
protected virtual string XmlaOracleCommand.GenerateCommand(IMdxQuery)
----

endif::wpf[]

ifdef::wpf[]
All classes derived from the link:{ApiPlatform}olap.xmla.v{ProductVersion}~infragistics.olap.xmla.xmlacommand.html[XmlaCommand] and has overridden the XmlaCommand.GenerateCommand(IMdxQuery) method should refer to the link:{ApiPlatform}olap.xmla.v{ProductVersion}~infragistics.olap.xmla.imdxquery.html[IMdxQuery] API documentation in order to get information about the type and the purpose of members exposed by the link:{ApiPlatform}olap.xmla.v{ProductVersion}~infragistics.olap.xmla.imdxquery.html[IMdxQuery] interface.
endif::wpf[]

ifdef::wpf[]
Also the PivotSimpleClickableContainer is no longer used.
endif::wpf[]