////

|metadata|
{
    "name": "control-persistence-framework",
    "controlName": ["IG Control Persistence Framework"],
    "tags": ["Getting Started","Persistence"],
    "guid": "{7A949FAA-D54D-4B8B-8444-EDB4F6106B69}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:53.5360358Z"
}
|metadata|
////

= Infragistics Control Persistence Framework

This section gives you an overview of the use of link:{ApiPlatform}persistence.v{ProductVersion}~infragistics.persistence_namespace.html[Infragistics Persistence Framework]™ library. This section contains valuable information about the Infragistics Control Persistence Framework, ranging from what it does and why you would want to use it in your application, to step-by-step procedures on how to accomplish common tasks using the library.

Click the links below to access important information about the Infragistics Control Persistence Framework.

== link:persistence-about-ig-control-persistence-framework.html[About Infragistics Control Persistence Framework]

In this section you’ll find any information that will help you to better understand the functionalities of the Infragistics Control Persistence Framework, as well as why you would want to use it as part of building your applications.

pick:[sl,wpf,win-rt="== link:persistenceframework-getting-started-with-infragistics-control-persistence-framework.html[Getting Started with Infragistics Control Persistence Framework]"]

ifdef::sl,wpf,win-rt[]
In order to get you up and running as quickly as possible with the Infragistics Control Persistence Framework, we've provided you with information on how to get started.
endif::sl,wpf,win-rt[]

pick:[win-phone="== link:persistence-getting-started-with-ig-control-persistence-framework.html[Persisting the Settings of an Object Using Infragistics Control Persistence Framework]"]

ifdef::win-phone[]
In order to get you up and running as quickly as possible with the Infragistics Control Persistence Framework, we've provided you with information on how to get started.
endif::win-phone[]

== link:persistence-using-ig-control-persistence-framework.html[Using Infragistics Control Persistence Framework]

This section contains information on the key features and functionalities provided by the Infragistics Control Persistence Framework.

== link:persistence-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the Infragistics Control Persistence Framework. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the {ProductName} help.