////
|metadata|
{
    "name": "default-xml-namespace-mappings",
    "controlName": [],
    "tags": ["API","Getting Started"],
    "guid": "{DE0A8062-FCCA-4A14-9FF0-073AA3057678}",
    "buildFlags": ["sl","wpf"],
    "createdOn": "2012-01-31T16:16:07.8403347Z"
}
|metadata|
////

= Default XML Namespace Mappings

For reference purposes here is a list of all the default namespace mappings defined by the NA/WPF assemblies:

[options="header", cols="a,a,a"]
|====
|Assembly|Clr-namespace|Generated XAML

.2+|{ApiPlatform}v{ProductVersion}
|Infragistics.Windows.Controls
|---- 
xmlns:igWPF=http://schemas.infragistics.com/xaml/wpf
or
xmlns:igWindows="http://infragistics.com/Windows"
----

|Infragistics.Windows.Themes
|---- 
xmlns:igWPF=http://schemas.infragistics.com/xaml/wpf
or
xmlns:igThemes="http://infragistics.com/Themes"
----

|{ApiPlatform}Ribbon.v{ProductVersion}
|Infragistics.Windows.Ribbon
|---- 
xmlns:igWPF=http://schemas.infragistics.com/xaml/wpf
or
xmlns:igRibbon="http://infragistics.com/Ribbon"
----

|{ApiPlatform}DockManager.v{ProductVersion}
|Infragistics.Windows.DockManager
|---- 
xmlns:igWPF=http://schemas.infragistics.com/xaml/wpf
or
xmlns:igDock="http://infragistics.com/DockManager"
----

|{ApiPlatform}DataPresenter.ExcelExporter.v{ProductVersion}
|Infragistics.Windows.DataPresenter.ExcelExporter
|---- 
xmlns:igWPF=http://schemas.infragistics.com/xaml/wpf
or
xmlns:igExcelExporter="http://infragistics.com/ExcelExporter"
----

|{ApiPlatform}Reporting.v{ProductVersion}
|Infragistics.Windows.Reporting
|---- 
xmlns:igWPF=http://schemas.infragistics.com/xaml/wpf
or
xmlns:igReporting="http://infragistics.com/Reporting"
----

|{ApiPlatform}OutlookBar.v{ProductVersion}
|Infragistics.Windows.OutlookBar
|---- 
xmlns:igWPF=http://schemas.infragistics.com/xaml/wpf
or
xmlns:igOutlookBar="http://infragistics.com/OutlookBar"
----

|{ApiPlatform}Calculations.XamCalculationManager.v{ProductVersion}
|Infragistics.Calculations
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Charts.XamDataChart.v{ProductVersion}
|Infragistics.Controls.Charts
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Charts.XamDiagram.v{ProductVersion}
|Infragistics.Controls.Charts
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamCalendar.v{ProductVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamColorPicker.v{ProductVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamComboEditor.v{ProductVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamDateTimeInput.v{ProductVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamMaskedInput.v{ProductVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamPropertyGrid.v{ProductVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamRichTextEditor.v{ProductVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamSlider.v{ProductVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Grids.XamGrid.v{ProductVersion}
|Infragistics.Controls.Grids
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Grids.XamSpreadsheet.v{ProductVersion}
|Infragistics.Controls.Grids
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Intreractions.XamDialogWindow.v{ProductVersion}
|Infragistics.Controls.Intreractions
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Interactions.XamFormulaEditor.v{ProductVersion}
|Infragistics.Controls.Intreractions
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Intreractions.XamSpellChecker.v{ProductVersion}
|Infragistics.Controls.Intreractions
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Layouts.XamTileManager.v{ProductVersion}
|Infragistics.Controls.Layouts
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Math.v{ProductVersion}
|Infragistics.Math
|

|{ApiPlatform}Controls.Menus.XamDataTree.v{ProductVersion}
|Infragistics.Controls.Menus
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Menus.XamMenu.v{ProductVersion}
|Infragistics.Controls.Menus
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Menus.XamRadialMenu.v{ProductVersion}
|Infragistics.Controls.Menus
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Menus.XamTagCloud.v{ProductVersion}
|Infragistics.Controls.Menus
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Schedules.v{ProductVersion}
|Infragistics.Controls.Schedules
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.SchedulesExchangeConnector.v{ProductVersion}
|Infragistics.Controls.Schedules
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}DataVisualization.v{ProductVersion}
|Infragistics.Controls
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}DragDrop.v{ProductVersion}
|Infragistics.DragDrop
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Persistence.v{ProductVersion}
|Infragistics.Persistence
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|Infragistics4.Services.Schedules.WcfConnectorService.v{ProductVersion}
|Infragistics.Services.Schedules
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|====