////
|metadata|
{
    "name": "default-xml-namespace-mappings",
    "controlName": [],
    "tags": ["API","Getting Started"],
    "guid": "{DE0A8062-FCCA-4A14-9FF0-073AA3057678}",
    "buildFlags": ["sl","wpf"],
    "createdOn": "2012-01-31T16:16:07.8403347Z"
}
|metadata|
////

= Default XML Namespace Mappings

For reference purposes here is a list of all the default namespace mappings defined by the NA/WPF assemblies:

[options="header", cols="a,a,a"]
|====
|Assembly|Clr-namespace|Generated XAML

.2+|{ApiPlatform}{ApiVersion}
|Infragistics.Windows.Controls
|---- 
xmlns:igWPF=http://schemas.infragistics.com/xaml/wpf
or
xmlns:igWindows="http://infragistics.com/Windows"
----

|Infragistics.Windows.Themes
|---- 
xmlns:igWPF=http://schemas.infragistics.com/xaml/wpf
or
xmlns:igThemes="http://infragistics.com/Themes"
----

|{ApiPlatform}Ribbon.{ApiVersion}
|Infragistics.Windows.Ribbon
|---- 
xmlns:igWPF=http://schemas.infragistics.com/xaml/wpf
or
xmlns:igRibbon="http://infragistics.com/Ribbon"
----

|{ApiPlatform}DockManager.{ApiVersion}
|Infragistics.Windows.DockManager
|---- 
xmlns:igWPF=http://schemas.infragistics.com/xaml/wpf
or
xmlns:igDock="http://infragistics.com/DockManager"
----

|{ApiPlatform}DataPresenter.ExcelExporter.{ApiVersion}
|Infragistics.Windows.DataPresenter.ExcelExporter
|---- 
xmlns:igWPF=http://schemas.infragistics.com/xaml/wpf
or
xmlns:igExcelExporter="http://infragistics.com/ExcelExporter"
----

|{ApiPlatform}Reporting.{ApiVersion}
|Infragistics.Windows.Reporting
|---- 
xmlns:igWPF=http://schemas.infragistics.com/xaml/wpf
or
xmlns:igReporting="http://infragistics.com/Reporting"
----

|{ApiPlatform}OutlookBar.{ApiVersion}
|Infragistics.Windows.OutlookBar
|---- 
xmlns:igWPF=http://schemas.infragistics.com/xaml/wpf
or
xmlns:igOutlookBar="http://infragistics.com/OutlookBar"
----

|{ApiPlatform}Calculations.XamCalculationManager.{ApiVersion}
|Infragistics.Calculations
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Charts.XamDataChart.{ApiVersion}
|Infragistics.Controls.Charts
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Charts.XamDiagram.{ApiVersion}
|Infragistics.Controls.Charts
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamCalendar.{ApiVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamColorPicker.{ApiVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamComboEditor.{ApiVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamDateTimeInput.{ApiVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamMaskedInput.{ApiVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamPropertyGrid.{ApiVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamRichTextEditor.{ApiVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamSlider.{ApiVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Grids.XamGrid.{ApiVersion}
|Infragistics.Controls.Grids
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Grids.XamSpreadsheet.{ApiVersion}
|Infragistics.Controls.Grids
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Intreractions.XamDialogWindow.{ApiVersion}
|Infragistics.Controls.Intreractions
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Interactions.XamFormulaEditor.{ApiVersion}
|Infragistics.Controls.Intreractions
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Intreractions.XamSpellChecker.{ApiVersion}
|Infragistics.Controls.Intreractions
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Layouts.XamTileManager.{ApiVersion}
|Infragistics.Controls.Layouts
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Math.{ApiVersion}
|Infragistics.Math
|

|{ApiPlatform}Controls.Menus.XamDataTree.{ApiVersion}
|Infragistics.Controls.Menus
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Menus.XamMenu.{ApiVersion}
|Infragistics.Controls.Menus
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Menus.XamRadialMenu.{ApiVersion}
|Infragistics.Controls.Menus
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Menus.XamTagCloud.{ApiVersion}
|Infragistics.Controls.Menus
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Schedules.{ApiVersion}
|Infragistics.Controls.Schedules
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.SchedulesExchangeConnector.{ApiVersion}
|Infragistics.Controls.Schedules
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}DataVisualization.{ApiVersion}
|Infragistics.Controls
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}DragDrop.{ApiVersion}
|Infragistics.DragDrop
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Persistence.{ApiVersion}
|Infragistics.Persistence
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|Infragistics4.Services.Schedules.WcfConnectorService.{ApiVersion}
|Infragistics.Services.Schedules
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|====