////
|metadata|
{
    "name": "default-xml-namespace-mappings",
    "controlName": [],
    "tags": ["API","Getting Started"],
    "guid": "{DE0A8062-FCCA-4A14-9FF0-073AA3057678}",
    "buildFlags": ["sl","wpf"],
    "createdOn": "2012-01-31T16:16:07.8403347Z"
}
|metadata|
////

= Default XML Namespace Mappings

For reference purposes here is a list of all the default namespace mappings defined by the NA/WPF assemblies:

[options="header", cols="a,a,a"]
|====
|Assembly|Clr-namespace|Generated XAML

.2+|{ApiPlatform}{DllVersion}
|Infragistics.Windows.Controls
|---- 
xmlns:igWPF=http://schemas.infragistics.com/xaml/wpf
or
xmlns:igWindows="http://infragistics.com/Windows"
----

|Infragistics.Windows.Themes
|---- 
xmlns:igWPF=http://schemas.infragistics.com/xaml/wpf
or
xmlns:igThemes="http://infragistics.com/Themes"
----

|{ApiPlatform}Ribbon.{DllVersion}
|Infragistics.Windows.Ribbon
|---- 
xmlns:igWPF=http://schemas.infragistics.com/xaml/wpf
or
xmlns:igRibbon="http://infragistics.com/Ribbon"
----

|{ApiPlatform}DockManager.{DllVersion}
|Infragistics.Windows.DockManager
|---- 
xmlns:igWPF=http://schemas.infragistics.com/xaml/wpf
or
xmlns:igDock="http://infragistics.com/DockManager"
----

|{ApiPlatform}DataPresenter.ExcelExporter.{DllVersion}
|Infragistics.Windows.DataPresenter.ExcelExporter
|---- 
xmlns:igWPF=http://schemas.infragistics.com/xaml/wpf
or
xmlns:igExcelExporter="http://infragistics.com/ExcelExporter"
----

|{ApiPlatform}Reporting.{DllVersion}
|Infragistics.Windows.Reporting
|---- 
xmlns:igWPF=http://schemas.infragistics.com/xaml/wpf
or
xmlns:igReporting="http://infragistics.com/Reporting"
----

|{ApiPlatform}OutlookBar.{DllVersion}
|Infragistics.Windows.OutlookBar
|---- 
xmlns:igWPF=http://schemas.infragistics.com/xaml/wpf
or
xmlns:igOutlookBar="http://infragistics.com/OutlookBar"
----

|{ApiPlatform}Calculations.XamCalculationManager.{DllVersion}
|Infragistics.Calculations
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Charts.XamDataChart.{DllVersion}
|Infragistics.Controls.Charts
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Charts.XamDiagram.{DllVersion}
|Infragistics.Controls.Charts
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamCalendar.{DllVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamColorPicker.{DllVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamComboEditor.{DllVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamDateTimeInput.{DllVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamMaskedInput.{DllVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamPropertyGrid.{DllVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamRichTextEditor.{DllVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Editors.XamSlider.{DllVersion}
|Infragistics.Controls.Editors
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Grids.XamGrid.{DllVersion}
|Infragistics.Controls.Grids
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Grids.XamSpreadsheet.{DllVersion}
|Infragistics.Controls.Grids
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Intreractions.XamDialogWindow.{DllVersion}
|Infragistics.Controls.Intreractions
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Interactions.XamFormulaEditor.{DllVersion}
|Infragistics.Controls.Intreractions
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Intreractions.XamSpellChecker.{DllVersion}
|Infragistics.Controls.Intreractions
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Layouts.XamTileManager.{DllVersion}
|Infragistics.Controls.Layouts
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Math.{DllVersion}
|Infragistics.Math
|

|{ApiPlatform}Controls.Menus.XamDataTree.{DllVersion}
|Infragistics.Controls.Menus
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Menus.XamMenu.{DllVersion}
|Infragistics.Controls.Menus
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Menus.XamRadialMenu.{DllVersion}
|Infragistics.Controls.Menus
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Menus.XamTagCloud.{DllVersion}
|Infragistics.Controls.Menus
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.Schedules.{DllVersion}
|Infragistics.Controls.Schedules
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Controls.SchedulesExchangeConnector.{DllVersion}
|Infragistics.Controls.Schedules
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}DataVisualization.{DllVersion}
|Infragistics.Controls
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}DragDrop.{DllVersion}
|Infragistics.DragDrop
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|{ApiPlatform}Persistence.{DllVersion}
|Infragistics.Persistence
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|Infragistics4.Services.Schedules.WcfConnectorService.{DllVersion}
|Infragistics.Services.Schedules
|---- 
xmlns:ig="http://schemas.infragistics.com/xaml"
----

|====