////
|metadata|
{
    "name": "designers-guide-what-is-a-theme",
    "controlName": [],
    "tags": ["Styling","Theming"],
    "guid": "323d02eb-901a-448f-84a4-8baab303d568",
    "buildFlags": ["sl","wpf"],
    "createdOn": "2012-01-30T16:50:12.2108012Z"
}
|metadata|
////

= What is a Theme?

A Theme is a set of ResourceDictionaries that contain a collection of Styles that target the {ProductName} controls. Because controls like the link:{ApiPlatform}controls.charts.xamdatachart.v{ProductVersion}~infragistics.controls.charts.xamdatachart.html[xamDataChart]™ are actually composed of many smaller controls (e.g., Legend), it is necessary to create Styles that target each of the smaller controls to completely alter the appearance of the encompassing control. Instead of targeting a single control, like a Style does, the Theme includes multiple Styles to target all of these smaller controls at once.

You should think of a Theme just as you would an external ResourceDictionary. When working with ResourceDictionaries, you can define styles that target specific control types, whether they are system controls (e.g., Button and Scrollbar) or {ProductName} controls (e.g., xamDataChart, xamRadialGauge, and etc.). Just like a ResourceDictionary, you can merge a Theme at the Application, Page, Window, or Control level.

== Related Topics:

link:designers-guide-using-themes.html[Using Themes]

link:designersguide-styling-ig-controls.html[Styling Infragistics Controls]