////
|metadata|
{
    "name": "designers-guide",
    "controlName": [],
    "tags": [],
    "guid": "08d41825-570a-43b2-93b2-26befeff9f41",
    "buildFlags": [],
    "createdOn": "2012-02-02T16:12:55.7602387Z"
}
|metadata|
////

= Designers Guide

The Designer’s Guide is a resource for stylers and designers. This guide will help you learn about the various styling points of the {ProductName} controls. You will find diagrams that illustrate the various target types of each control, as well as topics that will help educate you by in using different techniques to make your application look great. With the information contained in this guide, you will be able to achieve unsurpassed styling in your {ProductName} powered applications.

link:designersguide-location-of-generic-xaml-file.html[Location of Generic.xaml File]

link:designersguide-styling-ig-controls.html[Styling Infragistics Controls]

link:designersguide-editing-style-properties-using-expression-blend.html[Editing Style Properties Using Expression Blend]

link:themes.html[Themes]

link:designersguide-styling-points.html[Styling Points]