////
|metadata|
{
    "name": "developers-guide-upgrading-your-project",
    "controlName": [],
    "tags": ["How Do I"],
    "guid": "e7379b1a-1668-4978-b481-c65454c8eed6",
    "buildFlags": ["wpf","sl"],
    "createdOn": "2012-01-30T15:17:19.5645983Z"
}
|metadata|
////

= Upgrading Your Projects

Prior to the {ProductName} 2010 Volume 2 release, Infragistics maintained separate development efforts for WPF and Silverlight controls. As a result, the naming for Types, Namespaces and assemblies on each platform were not always consistent and there was very little code sharing between the two platforms. In order to move to a unified foundation for our SL and WPF components it was necessary to make some breaking changes that will affect your applications in the short term. However, these changes give you numerous advantages going forward:

* Leveraged Learning – once you learn a control for one platform, you already know the control for the other platform.
* It’s easier to share and reuse source code between WPF and Silverlight applications.
* It’s faster to port WPF applications to Silverlight and vice versa.
* There is greater parity between the UI controls we offer for WPF and Silverlight, with new controls and features being released at the same time for both platforms.
* You can cater to your customer’s needs more easily by being able to quickly provide solutions between platforms.

*Getting Help*

Upgrading your previous {ProductName} applications will require some steps, outlined in this topic. The steps should be straight-forward and you should not encounter any issues. If by any chance you do experience any issues, you can submit a support request which will be treated with the highest priority. Follow these steps:

[start=1]
. Click on the following link:
+
link:https://www.infragistics.com/Login.aspx?ReturnUrl=%2fsupport%2fsubmitrequest.aspx[https://www.infragistics.com/Login.aspx?ReturnUrl=%2fsupport%2fsubmitrequest.aspx]
[start=2]
. *Fill in the Summary title to read: NAMESPACE.* You will hear from our Developer Support team within one business day.

== Related Topics:

link:developers-guide-restoring-version-upgrade-utility-backup-undoing-upgrade.html[Restoring Version Upgrade Utility Backup Undoing Upgrade]

link:developers-guide-upgrading-to-11-1-using-version-utility.html[Upgrading Your Projects to Infragistics {PlatformName} Using Version Utility]