////

|metadata|
{
    "name": "drag-and-drop-framework",
    "controlName": ["IG Drag and Drop Framework"],
    "tags": ["Getting Started"],
    "guid": "{887B3EBA-FDAB-4B42-888C-F2BBAB87C6D4}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:53.7070374Z"
}
|metadata|
////

= Infragistics Drag and Drop Framework

This section gives you an overview of the use of Infragistics Drag and Drop Framework. This section contains valuable information about the Infragistics Drag and Drop Framework, ranging from what it does and why you would want to use it in your application, to step-by-step procedures on how to accomplish common tasks using the framework. Click the links below to access important information about the Infragistics Drag and Drop Framework.

== link:drag-and-drop-framework-about-ig-drag-and-drop-framework.html[About Infragistics Drag and Drop Framework]

In this section you’ll find any information that will help you to better understand the functionalities of the Infragistics Drag and Drop Framework, as well as why you would want to use it as part of building your applications.

== link:drag-and-drop-framework-getting-started-with-ig-drag-and-drop-framework.html[Getting Started with Infragistics Drag and Drop Framework]

In order to get you up and running as quickly as possible with the Infragistics Drag and Drop Framework, we've provided you with information on how to get started.

== link:drag-and-drop-framework-using-ig-drag-and-drop-framework.html[Using Infragistics Drag and Drop Framework]

This section contains information on the key features and functionalities provided by the Infragistics Drag and Drop Framework.

== link:drag-and-drop-framework-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the Infragistics Drag and Drop Framework. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the {ProductName} help.