////

|metadata|
{
    "name": "drag-and-drop-framework-using-ig-drag-and-drop-framework",
    "controlName": ["IG Drag and Drop Framework"],
    "tags": ["Getting Started"],
    "guid": "1ed501c0-530d-4b32-863f-4337d4764767",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:53.6650343Z"
}
|metadata|
////

= Using Infragistics Drag and Drop Framework

This section is your gateway to important conceptual and task-based information that will help you to use the various features and functionalities provided by the link:{ApiPlatform}dragdrop.v{ProductVersion}.html[Infragistics Drag and Drop Framework]™ library.

link:drag-and-drop-framework-ig-drag-and-drop-framework-events.html[Infragistics Drag and Drop Framework Events]

This topic describes the drag and drop framework events and event arguments and how you can use them to tune your drag and drop application.

link:drag-and-drop-framework-set-custom-cursors-for-different-drag-and-drop-situations.html[Set Custom Cursors for Different Drag and Drop Situations]

This topic provides you an example how you can set MoveCursorTemplate and DropNotAllowedCursorTemplate to indicate whether or not the dragged element is moved over a valid drop target.

link:drag-and-drop-framework-set-drag-and-drop-channels.html[Set Drag and Drop Channels]

This topic describes how you can specify the areas (channels) where the end user can successfully perform drag and drop operations.