////

|metadata|
{
    "name": "drag-and-drop-framework-api-overview",
    "controlName": ["IG Drag and Drop Framework"],
    "tags": ["API"],
    "guid": "{5B58F83D-57A1-4F98-8AF5-26382DB355B0}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:53.671035Z"
}
|metadata|
////

= API Overview

This section lists each namespace that is relevant to the link:{ApiPlatform}dragdrop.v{ProductVersion}.html[Infragistics Drag and Drop Framework]™ library. There are also several key classes listed that you will be using while programming with this control. The namespaces and classes on this page link directly into our API documentation.

[cols="a,a"]
|====
|*Infragistics Drag and Drop Framework Namespaces*
|*Key Classes*

| link:{ApiPlatform}dragdrop.v{ProductVersion}~infragistics.dragdrop_namespace.html[Infragistics.DragDrop]
| link:{ApiPlatform}dragdrop.v{ProductVersion}~infragistics.dragdrop.dragdropmanager.html[DragDropManager] 

link:{ApiPlatform}dragdrop.v{ProductVersion}~infragistics.dragdrop.dragsource.html[DragSource] 

link:{ApiPlatform}dragdrop.v{ProductVersion}~infragistics.dragdrop.droptarget.html[DropTarget]

|====