////

|metadata|
{
    "name": "generalprogrammingconcepts-wcf-ria-support",
    "controlName": [],
    "tags": [],
    "guid": "31051282-833c-4604-95e9-882bd7a52bbf",  
    "buildFlags": ["sl"],
    "createdOn": "2012-02-06T14:15:43.8879709Z"
}
|metadata|
////

= WCF RIA Support

This section gives you an overview of the Microsoft RIA Services support in {ProductName} controls.

The Microsoft RIA Services allows you to create the client and server data transport portion of your application by using a data source control called DomainDataSource. This control allows the developer to easily interact with the middleware generated by the RIA Service and also querying server side data. Moreover it provides mechanism to page data responses, which lowers the data transport overhead as well as data grouping and filtering.

Now a number of Infragisitics controls are compatible with WCF RIA Services, which allows you to build easily and flawless your line-of-business applications.

== link:generalprogrammingconcepts-using-wcf-ria-and-xamgrid.html[Using WCF RIA and xamGrid]

This topic is showing how to use the WCF RIA services with xamGrid