////

|metadata|
{
    "name": "generalconcepts-data-binding",
    "controlName": [],
    "tags": [],
    "guid": "{AD39F282-8DFF-43DC-9B1B-2012881F0479}",  
    "buildFlags": ["wpf"],
    "createdOn": "2012-02-01T16:01:19.6178361Z"
}
|metadata|
////

= Data Binding

This section contains topics that demonstrate how to retrieve data from a database, XML file, or an object, and display that information. Most of the content in this section is designed to be control-independent. The only part of the section that is not control-independent is where we specify the property off the control to which to connect the data, so that it can be reused with any of the data-driven controls offered in the {ProductName} product.

* link:creating-a-flat-dataset.html[Creating a Flat DataSet]
* link:creating-an-objectdataprovider.html[Creating an ObjectDataProvider]
* link:creating-an-xmldataprovider.html[Creating an XmlDataProvider]
* link:using-the-data-context-for-data-binding.html[Using the Data Context for Data Binding]