////
|metadata|
{
    "name": "generalconcepts-assemblies",
    "controlName": [],
    "tags": [],
    "guid": "fee36866-529f-4d32-a69c-c60504965bac",
    "buildFlags": [],
    "createdOn": "2012-01-31T16:13:29.3453347Z"
}
|metadata|
////

= Assemblies

An assembly is the core of the common language runtime (CLR). It's a collection of the types and resources required by the CLR to execute an application, and is typically stored as a single executable (.exe) or dynamic-link library (DLL). An assembly controls important aspects of an application including deployment, version control, and security permissions.

To learn about {ProductName} assemblies, click the links below.

==== link:netadvantage-assemblies.html[{ProductName} Assemblies]

In this topic, you'll find a list of all the Microsoft® Windows® Presentation Foundation assemblies included in the {ProductName} product, along with their corresponding controls and components.

==== link:default-xml-namespace-mappings.html[Default XML Namespace Mappings]

In this topic, you'll find a list of all the default XML namespace mappings for the assemblies included in the {ProductName} product.

==== link:adding-assembly-to-a-visual-studio-project.html[Adding an Assembly to a Visual Studio Project]

This topic explains how to quickly add an {ProductName} assembly to your Microsoft Visual Studio® .NET project.

==== link:adding-an-assembly-to-an-expression-blend-project.html[Adding an Assembly to an Expression Blend Project]

This topic explains how to quickly add an {ProductName} assembly to your Microsoft Expression® Blend project.

==== link:generalconcepts-signed-andunsigned-assemblies.html[Signed and Unsigned Assemblies]

This topic explains when to use signed and unsigned assemblies.

==== link:version-free-assemblies.html[Version-Free Assemblies]

This topic is a conceptual overview describing the benefits of using of the Version-Free assemblies.