////
|metadata|
{
    "name": "wpf-netadvantage-win-client-wpf",
    "controlName": [],
    "tags": ["Getting Started"],
    "guid": "{9041122F-2640-4BB0-AC36-C11B21BE21CA}",
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:51.5896711Z"
}
|metadata|
////

= {ProductNameVersion}

The {ProductName} product is a suite of next-generation controls, designed to create polished, commercial-class UIs based on Microsoft® Windows® Presentation Foundation.

With the Full version of the {ProductName} product, you get the entire suite of controls allowing you to create:

* enterprise-ready applications for Windows environment
* XBAP applications for Web-based applications
* completely styled applications using ThemePacks
* custom StylePacks to enforce a corporate design standard

The {ProductName} controls are designed and written from the ground up to take advantage of the power that the Windows Presentation Foundation provides. The controls leverage Windows Presentation Foundation features including high-resolution graphics, rich styling and animation capabilities, and integrated UI virtualization technology. In fact, all of our Windows Presentation Foundation controls are written in 100% managed C# code, with default styles and templates defined in XAML resources.