////

|metadata|
{
    "name": "ig-calculators-data-calculator",
    "controlName": ["IG Math Calculators"],
    "tags": ["Calculations"],
    "guid": "4405c663-39ab-43ac-a132-f92d005c3455",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:53.7280367Z"
}
|metadata|
////

= Infragistics Data Calculator

This topic introduces you to the link:{ApiPlatform}math.calculators{ApiVersion}~infragistics.math.calculators.datacalculator.html[DataCalculator] which is part of the link:{ApiPlatform}math.calculators{ApiVersion}~infragistics.math.calculators_namespace.html[Infragistics Math Calculators]™ library.

== Overview

The topic is organized as follows:

* <<Introduction,Introduction>>
* <<Properties,Properties>>
* <<Requirements,Requirements>>
* <<Example,Example>>
* <<RelatedTopics,Related Topics>>

== Introduction

The link:{ApiPlatform}math.calculators{ApiVersion}~infragistics.math.calculators.datacalculator.html[DataCalculator] is used to create custom error bars for Series objects in the link:datachart-datachart.html[xamDataChart]™ control.

== Properties

This section provides a list of properties of the link:{ApiPlatform}math.calculators{ApiVersion}~infragistics.math.calculators.datacalculator.html[DataCalculator] class.

[options="header", cols="a,a,a"]
|====
|Property Name|Property Type|Description

| link:{ApiPlatform}math.calculators{ApiVersion}~infragistics.math.calculators.itemssourcecalculator~itemssource.html[ItemsSource]
| link:http://msdn.microsoft.com/en-us/library/system.collections.ienumerable.aspx[IEnumerable]
|Gets or sets the source of data items for the calculator.

| link:{ApiPlatform}math.calculators{ApiVersion}~infragistics.math.calculators.itemssourcecalculator~valuememberpath.html[ValueMemberPath]
|string
|Gets or sets the Value member path of a data item. This property must be mapped to a name of numeric property of a data item.

|====

== Requirements

In order to use the DataCalculator, the following assemblies must to be added to a {PlatformName} project.

[options="header", cols="a,a"]
|====
|Assembly|Description

|{ApiPlatform}Math.Calculators.v{ProductVersion}.dll
|{ProductName} assembly containing mathematical calculators to compute correlation, mean, median, standard error, standard deviation and many more mathematical values.

|{ApiPlatform}Math.v{ProductVersion}.dll
|{ProductName} assembly containing standard mathematical constants and all-purpose mathematical functions designed to act on a variety of mathematical objects.

|{ApiPlatform}v{ProductVersion}.dll
|{ProductName} assembly containing shared functionality used by the Infragistics assemblies.

|====

== Example

Refer to the link:datachart-series-error-bars.html[Series Error Bars] topic for examples on how to integrate the DataCalculator with the xamDataChart control in order to create error bars with custom lengths for Series objects.

== Related Topics

* link:ig-math-calculators-api-overview.html[API Overview]
* link:datachart-series-error-bars.html[Series Error Bars]