////

|metadata|
{
    "name": "ig-calculators-percentage-calculator",
    "controlName": ["IG Math Calculators"],
    "tags": ["Calculations"],
    "guid": "f9361a27-8693-460a-b241-def0c158913c",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:53.7570404Z"
}
|metadata|
////

= Infragistics Percentage Calculator

This topic introduces you to the link:{ApiPlatform}math.calculators.v{ProductVersion}~infragistics.math.calculators.percentagecalculator.html[PercentageCalculator] which is part of the link:{ApiPlatform}math.calculators.v{ProductVersion}~infragistics.math.calculators_namespace.html[Infragistics Math Calculators]™ library.

== Overview

The topic is organized as follows:

* <<Introduction,Introduction>>
* <<Properties,Properties>>
* <<Requirements,Requirements>>
* <<Example,Example>>
* <<RelatedTopics,Related Topics>>

== Introduction

The link:{ApiPlatform}math.calculators.v{ProductVersion}~infragistics.math.calculators.percentagecalculator.html[PercentageCalculator] is used to generate percentage error bars for Series objects in the link:datachart-datachart.html[xamDataChart]™ control.

== Percentage Calculator Properties

This section provides a list of properties of the PercentageCalculator class.

[options="header", cols="a,a,a"]
|====
|Property Name|Property Type|Description

|Value
|double
|Gets or sets the value for generating length of percentage error bars.

|====

== Requirements

In order to use the PercentageCalculator, the following assemblies must be added to a {PlatformName} project.

[options="header", cols="a,a"]
|====
|Assembly|Description

|{ApiPlatform}Math.Calculators.v{ProductVersion}.dll
|{ProductName} assembly containing mathematical calculators to compute correlation, mean, median, standard error, standard deviation and many more mathematical values.

|{ApiPlatform}Math.v{ProductVersion}.dll
|{ProductName} assembly containing standard mathematical constants and all-purpose mathematical functions designed to act on a variety of mathematical objects.

|{ApiPlatform}v{ProductVersion}.dll
|{ProductName} assembly containing shared functionality used by the Infragistics assemblies.

|====

== Example

Refer to the link:datachart-series-error-bars.html[Series Error Bars] topic for examples on how to integrate the link:{ApiPlatform}math.calculators.v{ProductVersion}~infragistics.math.calculators.percentagecalculator.html[PercentageCalculator] with the xamDataChart control in order to calculate error bars with percentage of data values bound to Series objects.

== Related Topics

* link:ig-math-calculators-api-overview.html[API Overview]
* link:datachart-series-error-bars.html[Series Error Bars]