////

|metadata|
{
    "name": "ig-calculators-fixed-value-calculator",
    "controlName": ["IG Math Calculators"],
    "tags": ["Calculations"],
    "guid": "949e4db7-ce41-45a7-8b87-4b65d421e840",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:53.7340386Z"
}
|metadata|
////

= Infragistics Fixed Value Calculator

This topic introduces you to the link:{ApiPlatform}math.calculators{ApiVersion}~infragistics.math.calculators.fixedvaluecalculator.html[FixedValueCalculator] which is part of the link:{ApiPlatform}math.calculators{ApiVersion}~infragistics.math.calculators_namespace.html[Infragistics Math Calculators]™ library.

== Overview

The topic is organized as follows:

* <<Introduction,Introduction>>
* <<Properties,Properties>>
* <<Requirements,Requirements>>
* <<Example,Example>>
* <<RelatedTopics,Related Topics>>

== Introduction

The link:{ApiPlatform}math.calculators{ApiVersion}~infragistics.math.calculators.fixedvaluecalculator.html[FixedValueCalculator] is used to generate values of error bars for Series objects in the link:datachart-datachart.html[xamDataChart]™ control.

== Fixed Value Calculator Properties

This section provides a list of properties of the link:{ApiPlatform}math.calculators{ApiVersion}~infragistics.math.calculators.fixedvaluecalculator.html[FixedValueCalculator] class.

[options="header", cols="a,a,a"]
|====
|Property Name|Property Type|Description

|Value
|double
|Gets or sets the value for generating length of error bars.

|====

== Requirements

In order to use the FixedValueCalculator, the following assemblies must be added to a {PlatformName} project.

[options="header", cols="a,a"]
|====
|Assembly|Description

|{ApiPlatform}Math.Calculators.{DllVersion}dll
|{ProductName} assembly containing mathematical calculators to compute correlation, mean, median, standard error, standard deviation and many more mathematical values.

|{ApiPlatform}Math.{DllVersion}dll
|{ProductName} assembly containing standard mathematical constants and all-purpose mathematical functions designed to act on a variety of mathematical objects.

|{ApiPlatform}{DllVersion}dll
|{ProductName} assembly containing shared functionality used by the Infragistics assemblies.

|====

== Example

Refer to the link:datachart-series-error-bars.html[Series Error Bars] topic for examples on how to integrate the FixedValueCalculator with the xamDataChart control in order to calculate error bars with a fixed length for Series objects.

== Related Topics

* link:ig-math-calculators-api-overview.html[API Overview]
* link:datachart-series-error-bars.html[Series Error Bars]