////

|metadata|
{
    "name": "ig-calculators-using-math-calculators",
    "controlName": ["IG Math Calculators"],
    "tags": ["Calculations"],
    "guid": "81486cd6-2d80-4c68-ae1c-1c23048f08b5",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:53.7760413Z"
}
|metadata|
////

= Using Math Calculators

This topic is your gateway to important conceptual and task-based information that will help you to use the various mathematical and statistical calculators provided by the link:{ApiPlatform}math.calculators.v{ProductVersion}~infragistics.math.calculators_namespace.html[Infragistics Math Calculators]™ library.

* link:ig-calculators-correlation-calculator.html[Correlation Calculator]
* link:ig-calculators-data-calculator.html[Data Calculator]
* link:ig-calculators-fixed-value-calculator.html[Fixed Value Calculator]
* link:ig-calculators-mean-calculator.html[Mean Calculator]
* link:ig-calculators-median-calculator.html[Median Calculator]
* link:ig-calculators-percentage-calculator.html[Percentage Calculator]
* link:ig-calculators-standard-deviation-calculator.html[Standard Deviation Calculator]
* link:ig-calculators-standard-error-calculator.html[Standard Error Calculator]
* link:ig-calculators-variance-calculator.html[Variance Calculator]