////

|metadata|
{
    "name": "ig-math-vectors",
    "controlName": ["IG Math Library"],
    "tags": ["Calculations"],
    "guid": "8abbae9b-15ca-46db-8038-9235d13ada66",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:53.8480846Z"
}
|metadata|
////

= Vectors

The Infragistics Math Library™ provides functionality for working with vectors.

== About Vectors

Vectors are one-dimensional data classes for storing collections of objects. link:{ApiPlatform}math{ApiVersion}~infragistics.math.vector.html[Vector] can be a link:http://en.wikipedia.org/wiki/Row_vector[Row Vector] or a link:http://en.wikipedia.org/wiki/Column_vector[Column Vector].

== Using Vectors

Infragistics Math Library supports the following vector classes:

* link:{ApiPlatform}math{ApiVersion}~infragistics.math.vector.html[Vector] – stores a collection of real numbers
* link:{ApiPlatform}math{ApiVersion}~infragistics.math.booleanvector.html[BooleanVector] – stores a collection of boolean values
* link:{ApiPlatform}math{ApiVersion}~infragistics.math.complexvector.html[ComplexVector] – stores a collection of complex numbers

These classes are all derived from the link:{ApiPlatform}math{ApiVersion}~infragistics.math.matrixbase.html[MatrixBase] class. They differ in the data types they store.

The following topics will guide you how to use vectors in the Infragistics Math Library:

* link:ig-math-creating-vectors.html[Creating Vectors]
* link:ig-math-working-with-vectors.html[Working With Vectors]

== Related Topics

link:ig-math-complex-numbers.html[Complex Numbers]

link:ig-math-matrices.html[Matrices]

link:ig-math-mathematical-functions.html[Mathematical Functions]