////

|metadata|
{
    "name": "ig-math-matrices",
    "controlName": ["IG Math Library"],
    "tags": ["Calculations"],
    "guid": "3e6a39d0-e3c0-42af-afd8-517332954f08",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:53.8400513Z"
}
|metadata|
////

= Matrices

The Infragistics Math Library™ provides functionality for working with matrices.

== About Matrices

Matrices are multi-dimensional data classes for storing collections of objects. For more conceptual information refer to the link:http://en.wikipedia.org/wiki/Matrix_(mathematics)[Matrix] website.

== Using Matrices

Infragistics Math Library supports the following matrix classes:

* link:{ApiPlatform}math{ApiVersion}~infragistics.math.matrix.html[Matrix] – stores a collection of real numbers
* link:{ApiPlatform}math{ApiVersion}~infragistics.math.booleanmatrix.html[BooleanMatrix] – stores a collection of boolean values
* link:{ApiPlatform}math{ApiVersion}~infragistics.math.complexmatrix.html[ComplexMatrix]– stores a collection of complex numbers

These classes are all derived from the link:{ApiPlatform}math{ApiVersion}~infragistics.math.matrixbase.html[MatrixBase] class. They differ in the data types they store.

The following topic will guide you how to use matrices in the Infragistics Math Library:

* link:ig-math-creating-matrices.html[Creating Matrices]
* link:ig-math-working-with-matrices.html[Working With Matrices]

== Related Topics

link:ig-math-complex-numbers.html[Complex Numbers]

link:ig-math-vectors.html[Vectors]

link:ig-math-mathematical-functions.html[Mathematical Functions]