////

|metadata|
{
    "name": "ig-spe-create-textdocument",
    "controlName": ["IG Syntax Parsing Engine"],
    "tags": ["Editing","How Do I"],
    "guid": "a6703ac8-4093-47bf-82e3-9a3c9f8b3e9d",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:54.1241002Z"
}
|metadata|
////

= Create a TextDocument (Syntax Parsing Engine)

== Topic Overview

=== Purpose

This topic introduces the TextDocument and explains how to set a language on the TextDocument.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:ig-spe-overview.html[Syntax Parsing Engine Overview]
|This topic provides an overview of the Syntax Parsing Engine.

| link:ig-spe-grammar-overview.html[Grammar Overview]
|This topic provides an overview of the Syntax Parsing Engine’s Grammar.

| link:ig-spe-create-custom-language.html[Create Custom Language]
|This topic explains the process of creating a custom language.

|====

== TextDocument Introduction

=== Overview

The link:{ApiPlatform}documents.textdocument.v{ProductVersion}~infragistics.documents.textdocument.html[TextDocument] is a class in the link:{ApiPlatform}documents.textdocument.v{ProductVersion}~infragistics.documents_namespace.html[Infragistics.Documents] namespace which provides all the functionality for parsing and modifying a document. To set custom languages (or link:xamsyntaxeditor-supported-languages.html[one of the predefined languages]) use the link:{ApiPlatform}documents.textdocument.v{ProductVersion}~infragistics.documents.textdocument~language.html[Language] property of the `TextDocument` class.

For example, here is how to set a C# language to the `TextDocument`:

*In C#:*

[source,csharp]
----
var document = new TextDocument();
document.Language = CSharpLanguage.Instance;
----

To load content in the document you can use the link:{ApiPlatform}documents.textdocument.v{ProductVersion}~infragistics.documents.textdocument~initializetext.html[InitializeText] method or one of the link:{ApiPlatform}documents.textdocument.v{ProductVersion}~infragistics.documents.textdocument~load.html[Load] methods. As changes are made to the document, almost all tokens are reused so that the lexical analyzer only needs to analyze the parts of the document which have changed.

== Related Content

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:ig-spe-create-custom-language.html[Create Custom Language]
|This topic explains the process of creating a custom language.

| link:ig-spe-customize-error-messages.html[Customize Error Messages]
|This topic explains how to customize the error messages produced by the Syntax Parsing Engine.

| link:ig-spe-working-with-the-syntax-tree.html[Working with the Syntax Tree]
|The topics in this group explain in detail how to work with the Syntax Tree.

| link:textdocument-overview.html[TextDocument Overview]
|This topic contains links to conceptual information and code snippets related to the TextDocument class.

| link:textdocumentsnapshot-overview.html[TextDocumentSnapshot Overview]
|This topic provides an overview of the TextDocumentSnapshot object’s properties and methods.

| link:textdocumentsnapshotscanner-overview.html[TextDocumentSnapshotScanner Overview]
|This topic provides an overview of the TextDocumentSnapshotScanner object’s properties and methods.

|====