////

|metadata|
{
    "name": "igexcelengine-freeze-rows-and-columns",
    "controlName": ["IG Excel Engine"],
    "tags": ["Editing","Exporting","Formatting","How Do I"],
    "guid": "{1E83B4BD-023D-414B-9A57-D6155BB5CFFA}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:51.7627057Z"
}
|metadata|
////

= Freezing and Splitting Panes (Infragistics Excel Engine)

== Topic Overview

=== Purpose

This topic explains how to freeze columns and/or rows and how to split the worksheet in several panes.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:igexcelengine-about-infragistics-excel-engine.html[About Infragistics Excel Engine]
|In this section you will find information that will help you to better understand the object model and the functionalities of the _Infragistics Excel Engine_ .

|====

=== In this topic

This topic contains the following sections:

* <<_Ref394589174, Freezing and Splitting Configuration Summary >>
* <<_Ref394589199, Freezing Panes >>
* <<_Ref394589200, Splitting Panes >>
* <<_Ref394589223, Related Content >>

[[_Ref394589174]]
== Freezing and Splitting Configuration Summary

=== Freezing and splitting configuration summary chart

The following table explains briefly the configurable aspects of the freezing and splitting features. Further details are available after the table.

[options="header", cols="a,a,a"]
|====
|Configurable aspect|Details|Properties

|<<_Ref394589199,Freezing Panes>>
|This feature allows you to freeze rows and/or columns and make them visible at all time when the user is scrolling.
| link:{ApiPlatform}documents.excel.v{ProductVersion}~infragistics.documents.excel.displayoptions~frozenpanesettings.html[FrozenPaneSettings]

|<<_Ref394589200,Splitting Panes>>
|This feature allows you to split the worksheet into two or four scrollable panes.
| link:{ApiPlatform}documents.excel.v{ProductVersion}~infragistics.documents.excel.displayoptions~unfrozenpanesettings.html[UnfrozenPaneSettings]

|====

.Note
[NOTE]
====
You can also conveniently freeze and/or split panes using commands. For more information see the  _xamSpreadsheet’s_   link:spreadsheet-work-commands.html[Working with Commands (xamSpreadsheet)] topic.
====

[[_Ref394589199]]
== Freezing Panes

[[_Hlk368069110]]

=== Overview

You can freeze row(s) at top or column(s) at left of a worksheet using the freezing panes features. Frozen row(s) and/or column(s) remain visible at all time while the user is scrolling. The frozen row(s) and/or column(s) are separate from the rest of the worksheet by a single solid line, which cannot be moved.

.Note
[NOTE]
====
If you freeze rows and columns at the same time the horizontal scrollbar will still be able to scroll part of the frozen rows and the vertical scrollbar will still be able to scroll part of the frozen columns.
====

=== Property settings

The following table maps the desired configuration to the `FrozenPaneSettings` object’s properties that manage it.

[options="header", cols="a,a,a"]
|====
|In order to:|Use this property:|And set it to:

|Enable panes freezing
| link:{ApiPlatform}documents.excel.v{ProductVersion}~infragistics.documents.excel.displayoptions~panesarefrozen.html[PanesAreFrozen]
|`true`

|Specify rows to freeze
| link:{ApiPlatform}documents.excel.v{ProductVersion}~infragistics.documents.excel.frozenpanesettings~frozenrows.html[FrozenRows]
|A number of rows of your choice

|Specify columns to freeze
| link:{ApiPlatform}documents.excel.v{ProductVersion}~infragistics.documents.excel.frozenpanesettings~frozencolumns.html[FrozenColumns]
|A number of columns of your choice

|Specify first row in the bottom pane
| link:{ApiPlatform}documents.excel.v{ProductVersion}~infragistics.documents.excel.panesettingsbase~firstrowinbottompane.html[FirstRowInBottomPane]
|The first row (0-based index) number to be displayed in the bottom pane

|Specify first column in the right pane
| link:{ApiPlatform}documents.excel.v{ProductVersion}~infragistics.documents.excel.panesettingsbase~firstcolumninrightpane.html[FirstColumnInRightPane]
|The first column (0-based index) number to be displayed in the right pane

|====

[[_Hlk337817761]]

=== Example

The following example code demonstrates how to freeze rows and columns. The example code assumes you have a reference to a worksheet object named worksheet1:

*In Visual Basic:*

[source,vb]
----
worksheet1.DisplayOptions.PanesAreFrozen = True
' Freeze first row in worksheet
worksheet1.DisplayOptions.FrozenPaneSettings.FrozenRows = 1
' Freeze first 2 columns in worksheet
worksheet1.DisplayOptions.FrozenPaneSettings.FrozenColumns = 2
' The 4th column is displayed first after the frozen columns
worksheet1.DisplayOptions.FrozenPaneSettings.FirstColumnInRightPane = 4
' The 3rd row is displayed first after the frozen row
worksheet1.DisplayOptions.FrozenPaneSettings.FirstRowInBottomPane = 2
----

*In C#:*

[source,csharp]
----
worksheet1.DisplayOptions.PanesAreFrozen = true;
// Freeze first row in worksheet
worksheet1.DisplayOptions.FrozenPaneSettings.FrozenRows = 1;
// Freeze first 2 columns in worksheet
worksheet1.DisplayOptions.FrozenPaneSettings.FrozenColumns = 2;
// The 4th column is displayed first after the frozen columns
worksheet1.DisplayOptions.FrozenPaneSettings.FirstColumnInRightPane = 4;
// The 3rd row is displayed first after the frozen row
worksheet1.DisplayOptions.FrozenPaneSettings.FirstRowInBottomPane = 2;
----

[[_Ref394589200]]
== Splitting Panes

=== Overview

You can use the splitting panes feature to split the worksheet into two (either horizontal or vertical) panes or four panes. Each pane supports scrolling, however panes on one column will share the same horizontal scrollbar and panes on one row will share the same vertical scrollbar. The split panes are separated by a double border which supports resizing.

=== Property settings

The following table maps the desired configuration to the `UnfrozenPaneSettings` object’s properties that manage it.

[options="header", cols="a,a,a"]
|====
|In order to:|Use this property:|And set it to:

|Specify the first column in the left pane(s)
| link:{ApiPlatform}documents.excel.v{ProductVersion}~infragistics.documents.excel.unfrozenpanesettings~firstcolumninleftpane.html[FirstColumnInLeftPane]
|A column index of your choice (0-based)

|Specify the first column in the right pane(s)
| link:{ApiPlatform}documents.excel.v{ProductVersion}~infragistics.documents.excel.panesettingsbase~firstcolumninrightpane.html[FirstColumnInRightPane]
|A column index of your choice (0-based)

|Specify the first row in the top pane(s)
| link:{ApiPlatform}documents.excel.v{ProductVersion}~infragistics.documents.excel.unfrozenpanesettings~firstrowintoppane.html[FirstRowInTopPane]
|A row index of your choice (0-based)

|Specify the first row in the bottom pane(s)
| link:{ApiPlatform}documents.excel.v{ProductVersion}~infragistics.documents.excel.panesettingsbase~firstrowinbottompane.html[FirstRowInBottomPane]
|A row index of your choice (0-based)

|Specify the left pane width 

.Note 

[NOTE] 

==== 

This will divide the worksheet vertically 

====
| link:{ApiPlatform}documents.excel.v{ProductVersion}~infragistics.documents.excel.unfrozenpanesettings~leftpanewidth.html[LeftPaneWidth]
|A value of type `int` in twips (1/20th of a point)

|Specify the top pane height 

.Note 

[NOTE] 

==== 

This will divide the worksheet horizontally 

====
| link:{ApiPlatform}documents.excel.v{ProductVersion}~infragistics.documents.excel.unfrozenpanesettings~toppaneheight.html[TopPaneHeight]
|A value of type `int` in twips (1/20th of a point)

|====

=== Example

The following example code demonstrates how to split rows and columns. The example code assumes you have a reference to a worksheet object named worksheet1:

*In Visual Basic:*

[source,vb]
----
worksheet1.DisplayOptions.UnfrozenPaneSettings.FirstColumnInLeftPane = 0
worksheet1.DisplayOptions.UnfrozenPaneSettings.FirstColumnInRightPane = 5
worksheet1.DisplayOptions.UnfrozenPaneSettings.FirstRowInTopPane = 0
worksheet1.DisplayOptions.UnfrozenPaneSettings.FirstRowInBottomPane = 3
' left pane will be 150 points width
worksheet1.DisplayOptions.UnfrozenPaneSettings.LeftPaneWidth = 150 * 20
' top pane will be 100 points height
worksheet1.DisplayOptions.UnfrozenPaneSettings.TopPaneHeight = 100 * 20
----

*In C#:*

[source,csharp]
----
worksheet1.DisplayOptions.UnfrozenPaneSettings.FirstColumnInLeftPane = 0;
worksheet1.DisplayOptions.UnfrozenPaneSettings.FirstColumnInRightPane = 5;
worksheet1.DisplayOptions.UnfrozenPaneSettings.FirstRowInTopPane = 0;
worksheet1.DisplayOptions.UnfrozenPaneSettings.FirstRowInBottomPane = 3;
// left pane will be 150 points width
worksheet1.DisplayOptions.UnfrozenPaneSettings.LeftPaneWidth = 150 * 20;
// top pane will be 100 points height
worksheet1.DisplayOptions.UnfrozenPaneSettings.TopPaneHeight = 100 * 20;
----

[[_Ref394589223]]
== Related Content

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:igexcelengine-configuringgridlines.html[Configuring the Gridlines (Infragistics Excel Engine)]
|This topic explains how to show or hide the gridlines and set their color.

| link:igexcelengine-configuringheaders.html[Configuring the Headers (Infragistics Excel Engine)]
|This topic explains how to show or hide the column and row headers.

| link:igexcelengine-disable-editing-of-a-worksheet.html[Disabling Editing of a Worksheet (Infragistics Excel Engine)]
|This topic explains how to prevent the user from editing the cell values in a worksheet.

| link:igexcelengine-zoomlevel.html[Setting the Worksheet Zoom Level (Infragistics Excel Engine)]
|This topic explains how to programmatically set the zoom level in a worksheet.

|====