////
|metadata|
{
    "name": "igexcelengine-set-excel-document-properties",
    "controlName": ["IG Excel Engine"],
    "tags": ["Exporting","How Do I"],
    "guid": "{8F0D4F9E-95E1-44E1-9E89-D578CF6169A9}",
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:51.7737079Z"
}
|metadata|
////

= Setting Workbook Properties (Infragistics Excel Engine)

Microsoft® Excel® document properties provide information to help organize and keep track of your documents. You can use the Infragistics Excel Engine to set these properties using the link:{ApiPlatform}documents.excel.v{ProductVersion}~infragistics.documents.excel.workbook.html[Workbook] object’s link:{ApiPlatform}documents.excel.v{ProductVersion}~infragistics.documents.excel.workbook~documentproperties.html[DocumentProperties] property. The available properties are:

* Author
* Title
* Subject
* Keywords
* Category
* Status
* Comments
* Company
* Manager

The following code demonstrates how to create a workbook and set its Title and Status document properties.

*In Visual Basic:*
[source, vb]
----
Imports Infragistics.Documents.Excel
...
Dim workbook As New Workbook()
workbook.DocumentProperties.Title = "Expense Report"
workbook.DocumentProperties.Status = "Complete"
----

*In C#:*
[source, csharp]
----
using Infragistics.Documents.Excel;
...
Workbook workbook = new Workbook();
workbook.DocumentProperties.Title = "Expense Report";
workbook.DocumentProperties.Status = "Complete";
----

== Related Topics

link:igexcelengine-about-infragistics-excel-engine.html[About Infragistics Excel Engine]

link:igexcelengine-creating-a-workbook.html[Creating a Workbook (Infragistics Excel Engine)]

link:igexcelengine-load-an-excel-file.html[Loading an Excel File (Infragistics Excel Engine)]

link:igexcelengine-save-a-workbook.html[Saving a Workbook (Infragistics Excel Engine)]

link:igexcelengine-format-a-cell.html[Formatting a Cell (Infragistics Excel Engine)]

link:igexcelengine-copy-a-cells-format.html[Copying a Cell's Format (Infragistics Excel Engine)]

link:igexcelengine-reference-cells-and-regions.html[Referencing Cells and Regions (Infragistics Excel Engine)]

link:igexcelengine-merge-cells.html[Merging Cells (Infragistics Excel Engine)]

link:igexcelengine-add-a-formula-to-a-cell.html[Adding a Formula to a Cell (Infragistics Excel Engine)]

link:igexcelengine-add-a-comment-to-a-cell.html[Adding a Comment to a Cell (Infragistics Excel Engine)]

link:igexcelengine-disable-editing-of-a-worksheet.html[Disabling Editing of a Worksheet]

link:igexcelengine-freeze-rows-and-columns.html[Freezing and Splitting Panes (Infragistics Excel Engine)]
