////

|metadata|
{
    "name": "knownissues-netadvantage-for-wpf-data-visualization",
    "controlName": [],
    "tags": [],
    "guid": "3a2c44a7-70e0-4e2f-838e-ff4ad0d08509",  
    "buildFlags": [],
    "createdOn": "2012-01-31T21:13:20.8023228Z"
}
|metadata|
////

= Infragistics WPF Data Visualization

When using the {ProductName} products, be sure to take note of the known issues and breaking changes.

The following links take you to the list for known issues and different versions of the {ProductName} product that first introduced the breaking changes.

* link:breaking-changes-2011-volume-2.html[2011 Volume 2]
* link:breaking-changes-2011-volume-1.html[2011 Volume 1]
* link:breaking-changes-2010-volume-3-sr-1.html[2010 Volume 3 November Service Release]
* link:breaking-changes-2010-volume-3.html[2010 Volume 3]
* link:breaking-changes-2010-volume-2-sr-1.html[2010 Volume 2 August Service Release]
* link:breaking-changes-2010-volume-2.html[2010 Volume 2]
* link:breaking-changes-2009-volume-2.html[2009 Volume 2]