////

|metadata|
{
    "name": "knownissues-netadvantage-for-wpf-line-of-business",
    "controlName": [],
    "tags": [],
    "guid": "513ea4db-96bb-4a21-885f-f6e1163cf63c",  
    "buildFlags": [],
    "createdOn": "2012-01-31T21:13:47.1549578Z"
}
|metadata|
////

= Infragistics WPF Line of Business

Before you upgrade your WPF projects to a newer version of the {ProductName} product, you should be aware of breaking changes that were made that could potentially impact the behavior or building of your application.

The following links take you to the list for known issues and different versions of that first introduced the breaking changes.

* link:wpf-breaking-changes-in-2011-volume-2.html[2011 Volume 2]
* link:wpf-breaking-changes-in-2011-volume-1.html[2011 Volume 1]
* link:wpf-breaking-changes-in-2010-volume-3.html[2010 Volume 3]
* link:wpf-breaking-changes-in-2010-volume-2.html[2010 Volume 2]
* link:wpf-2009-volume-2.html[2009 Volume 2]
* link:wpf-2008-volume-1.html[2008 Volume 1]
* link:wpf-2007-volume-2.html[2007 Volume 2]
* link:wpf-2007-volume-1.html[2007 Volume 1]