////

|metadata|
{
    "name": "methods-and-properties-reference",
    "controlName": ["IG Undo Redo Framework"],
    "tags": ["Getting Started"],
    "guid": "1e7c1eb2-658f-4ec4-ac5c-6c5c3ad7dcdb",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:54.2040649Z"
}
|metadata|
////

= Undo/Redo Framework Methods and Properties Reference

=== Introduction

This section contains reference information about the Infragistics Undo\Redo Framework™ key methods and properties. The topics included cover the reference information about the major framework classes and reference information based on the task you want to achieve with the Undo\Redo API.

=== Topics

Detailed information regarding Infragistics Undo\Redo Framework key methods and properties is covered in the following topics:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:undo-redo-framework-methods-and-properties-reference-by-class.html[Undo/Redo Framework Methods and Properties Reference by Class]
|This section contains reference information about the key classes methods and properties in the Infragistics Undo\Redo Framework.

| link:undo-redo-framework-methods-and-properties-reference-by-task.html[Undo/Redo Framework Methods and Properties Reference by Task]
|This section contains reference information about the key methods and properties in the Infragistics Undo\Redo Framework that you may find useful for implementing specific undo\redo functionality.

|====