////

|metadata|
{
    "name": "persistence-api-overview",
    "controlName": ["IG Control Persistence Framework"],
    "tags": ["API","Persistence"],
    "guid": "{FCFB276D-CAC8-42EF-A4B9-472F103180EC}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:53.5890442Z"
}
|metadata|
////

= API Overview

This section lists each namespace that is relevant to the link:{ApiPlatform}persistence.v{ProductVersion}~infragistics.persistence_namespace.html[Infragistics Persistence Framework]™ library. There are also several key classes listed that you will be using while programming with this control. The namespaces and classes on this page link directly into our API documentation.

[options="header", cols="a,a"]
|====
|Namespace:|Key Classes:

| link:{ApiPlatform}persistence.v{ProductVersion}~infragistics.persistence_namespace.html[Infragistics.Persistence]
|
* link:{ApiPlatform}persistence.v{ProductVersion}~infragistics.persistence.persistencemanager.html[PersistenceManager] 

* link:{ApiPlatform}persistence.v{ProductVersion}~infragistics.persistence.persistencesettings.html[PersistenceSettings] 

* link:{ApiPlatform}persistence.v{ProductVersion}~infragistics.persistence.persistencegroup.html[PersistenceGroup] 

* link:{ApiPlatform}persistence.v{ProductVersion}~infragistics.persistence.persistenceevents.html[PersistenceEvents] 

|====