////

|metadata|
{
    "name": "persistence-persisting-specific-control-properties",
    "controlName": ["IG Control Persistence Framework"],
    "tags": ["How Do I","Persistence"],
    "guid": "{6D93C146-9826-4218-B621-6C972BFE1D06}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:53.5630358Z"
}
|metadata|
////

= Persisting Specific Control Properties

The following code demonstrates how you can selectively choose to persist only the Background property of the TextBox control.

*In XAML:*

----
<TextBox x:Name="txtAccount" Background="#FFCCFAEA">
    <ig:PersistenceManager.Settings>
        <ig:PersistenceSettings SavePersistenceOptions="OnlySpecified" >
            <ig:PersistenceSettings.PropertySettings>
                <ig:PropertyNamePersistenceInfo PropertyName="Background" Options="PropertyPath" />
            </ig:PersistenceSettings.PropertySettings>
        </ig:PersistenceSettings>
    </ig:PersistenceManager.Settings>
</TextBox>
----

Set the link:{ApiPlatform}persistence.v{ProductVersion}~infragistics.persistence.persistencesettings.html[PersistenceSettings] object’s link:{ApiPlatform}persistence.v{ProductVersion}~infragistics.persistence.persistencesettings~savepersistenceoptions.html[SavePersistenceOptions] property to OnlySpecified.

Use the link:{ApiPlatform}persistence.v{ProductVersion}~infragistics.persistence.propertynamepersistenceinfo.html[PropertyNamePersistenceInfo] object’s link:{ApiPlatform}persistence.v{ProductVersion}~infragistics.persistence.propertynamepersistenceinfo~propertyname.html[PropertyName] property to specify that you will persist the Background property of the TextBox.

The same functionality can be implemented in the code-behind.

*In Visual Basic:*

----
' create a new PersistenceSettings object
Dim settings As New PersistenceSettings()
' set save persistence option - OnlySpecified
settings.SavePersistenceOptions = Infragistics.Persistence.Primitives.PersistenceOption.OnlySpecified
' we will identify the specific property by its name
Dim pnpi As New PropertyNamePersistenceInfo()
pnpi.PropertyName = "Background"
' add the property in the PropertySettings collection
settings.PropertySettings.Add(pnpi)
Dim memoryStream As MemoryStream = PersistenceManager.Save(txtAccount, settings)
----

*In C#:*

----
// create a new PersistenceSettings object
PersistenceSettings settings = new PersistenceSettings();
// set save persistence option - OnlySpecified
settings.SavePersistenceOptions = Infragistics.Persistence.Primitives.PersistenceOption.OnlySpecified;
// we will identify the specific property by its name
PropertyNamePersistenceInfo pnpi = new PropertyNamePersistenceInfo();
pnpi.PropertyName = "Background";
// add the property in the PropertySettings collection
settings.PropertySettings.Add(pnpi);
MemoryStream memoryStream = PersistenceManager.Save(txtAccount, settings);
----

*Related Topics*

link:persistence-persistence-settings.html[Persistence Settings]

link:persistence-exclude-specific-control-properties.html[Exclude Specific Control Properties]

ifdef::sl,win-rt,win-phone[]
link:3ff664bc-2a4b-459d-8184-4ddca70ed809[Identifier]
endif::sl,win-rt,win-phone[]

link:persistence-persistence-groups.html[Persistence Groups]

ifdef::win-phone[]
link:persistence-using-propertynamepersistenceinfo-typeconverter-property.html[Using PropertyNamePersistenceInfo TypeConverter Property]
endif::win-phone[]

ifdef::sl,wpf,win-rt[]
link:persistence-using-typeconverte.html[Using PropertyNamePersistenceInfo TypeConverter Property]
endif::sl,wpf,win-rt[]

link:persistence-handle-persistencesaved-and-persistenceloaded-events.html[Handle PersistenceSaved and PersistenceLoaded Events]

link:persistence-handle-savepropertypersistence-and-loadpropertypersistence-events.html[Handle SavePropertyPersistence and LoadPropertyPersistence Events]