////
|metadata|
{
    "name": "persistence-using-ig-control-persistence-framework",
    "controlName": ["IG Control Persistence Framework"],
    "tags": ["Getting Started","How Do I","Persistence"],
    "guid": "{05DBDDDC-77AE-4151-9474-B96D0A20BD3D}",
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:53.5530369Z"
}
|metadata|
////

= Using Infragistics Control Persistence Framework

This section is your gateway to important conceptual and task-based information that will help you to use the various features and functionalities provided by the link:{ApiPlatform}persistence.v{ProductVersion}~infragistics.persistence_namespace.html[Infragistics Persistence Framework]™ library.

== link:persistence-persistence-settings.html[Persistence Settings]

This topic describes the management of the control properties’ persistence process via a PersistenceSettings object.

== link:persistence-exclude-specific-control-properties.html[Exclude Specific Control Properties]

This topic describes how a specific control property is excluded from the saving process performed by the Infragistics Control Persistence Framework.

== link:persistence-persistence-groups.html[Persistence Groups]

This topic describes how you can create and use a PersistenceGroup object to consolidate multiple controls' settings into a group that will be persisted by the Infragistics Control Persistence Framework.

== link:persistence-persisting-specific-control-properties.html[Persisting Specific Control Properties]

This topic describes how you can choose a specific control's property to be persisted.

== link:persistence-using-typeconverte.html[Using PropertyNamePersistenceInfo TypeConverter property]

This topic describes in which specific cases the PropertyNamePersistenceInfo object’s TypeConverter property should be used. The topic includes example code to illustrate the property usage.

== link:persistence-handle-persistencesaved-and-persistenceloaded-events.html[Handle PersistenceSaved and PersistenceLoaded Events]

This topic describes how you can manage the persistence process via the PersistenceSaved and PersistenceLoaded events.

== link:persistence-handle-savepropertypersistence-and-loadpropertypersistence-events.html[Handle SavePropertyPersistence and LoadPropertyPersistence Events]

This topic describes how you can manage the persistence process via the SavePropertyPersistence and LoadPropertyPersistence events.