////

|metadata|
{
    "name": "reswash",
    "controlName": ["Resource Washer"],
    "tags": ["How Do I","Styling","Templating"],
    "guid": "50ddd0e7-f045-4077-99c1-4af302edf508",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:22:00.244403Z"
}
|metadata|
////

= Infragistics Resource Washer

This section contains information about the ResourceWasher™ component , ranging from what the component does and step-by-step procedures on using it in your application.

Click the links below to access important information about Resource Washer.

== link:reswash-about.html[About Resource Washer]

In this section you'll find information that will help you to better understand the functionalities of Resource Washer.

== link:reswash-adding.html[Adding Resource Washer to Your Page]

In order to get you up and running as quickly as possible with Resource Washer, we've provided you with information on how to get started using the control.

== link:reswash-using.html[Using Resource Washer]

This section contains information on the key features and functionalities provided by Resource Washer.

== link:reswash-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with Resource Washer. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.