////
|metadata|
{
    "name": "sharing-color-tuning-configuration",
    "controlName": ["Infragistics Color Tuner"],
    "tags": ["Exporting","Getting Started","How Do I","Styling","Theming"],
    "guid": "1da5a519-44c6-4dde-8aec-9afc29df54ad",
    "buildFlags": [],
    "createdOn": "2016-05-25T18:22:00.2974057Z"
}
|metadata|
////

= Sharing Color Tuning Configuration

== Topic Overview

=== Purpose

This topic is a walkthrough for sharing color tuning configurations.

=== Required background

The following table lists the topics required as a prerequisite to understanding this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:using-infragistics-color-tuner.html[Using Infragistics Color Tuner]
|This topic introduces you to Infragistics Color Tuner™, an extension to Microsoft Visual Studio® 2010. The topic gives information on how to apply and color tune XAML themes of the pick:[sl="Silverlight"] pick:[wpf="WPF"] controls using convenient UI.

| link:creating-and-applying-color-tuning-configurations.html[Creating And Applying Color Tuning Configurations]
|This topic is a walkthrough for creating and applying custom color tuned themes using Infragistics Color Tuner.

|====

=== In this topic

This topic contains the following sections:

* <<_Sharing_Color_Tuning_Configurations,Sharing Color Tuning Configurations>>
* <<_Related_Content,Related Content>>

[[_Sharing_Color_Tuning_Configurations]]
== Sharing Color Tuning Configurations

=== Introduction

You can share color tuning configurations for Infragistics Color Tuner.

=== Preview

Infragistics Color Tuner color tuning configurations are saved at `CommonApplicationData\Infragistics\Tools\ColorTuner\_version_\SavedThemes.xml`. The `CommonApplicationData` is the directory that serves as a common repository for application-specific data that is used by all users.

For example, on Windows 7 machine and typical settings of Infragistics controls installer, version 12.1, this location is:

C:\ProgramData\Infragistics\Tools\ColorTuner\12.1\SavedThemes.xml

=== Requirements

The new machine, where you want to use saved color tuning configurations must have Infragistics Color Tuner already installed.

=== Steps

The following steps demonstrate how to share color tuning configurations.

=== Copy the configuration file

Copy the existing  _SavedThemes.xml_   file on your machine.

=== Paste the configuration file

You must place the copied file,  _SaveThemes.xml_   at the proper location on the new machine: `Environment.SpecialFolder.CommonApplicationData\Infragistics\Tools\ColorTuner\_version_\`

.Note
[NOTE]
====
Copied file will override the existing one. When you are copying the  _SavedThemes.xml_   file, it will replace the existing file with same name on the new machine. 
====

[[_Related_Content]]
== Related Content

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:creating-and-applying-color-tuning-configurations.html[Creating And Applying Color Tuning Configurations]
|This topic is a walkthrough for creating and applying custom color tuned themes using Infragistics Color Tuner.

| link:using-infragistics-color-tuner.html[Using Infragistics Color Tuner]
|This topic introduces you to Infragistics Color Tuner, an extension to Visual Studio 2010. It allows you to apply and color tune XAML themes of the pick:[sl="Silverlight"] pick:[wpf="WPF"] controls using convenient UI.

| link:reswash-using.html[Using Resource Washer]
|This topic introduces you to the ResourceWasher component where you can learn to change the overall color schemes of your application.

|====