////
|metadata|
{
    "name": "themes-theming-quickstart",
    "controlName": [],
    "tags": [],
    "guid": "075f40d1-e8a6-4da7-b2ec-3b4eba8dfb51",
    "buildFlags": ["wpf"],
    "createdOn": "2012-01-31T15:02:19.7917347Z"
}
|metadata|
////

= Theming QuickStart

Controls derived from link:infragisticswpf4.datapresenter{ApiVersion}~infragistics.windows.datapresenter.datapresenterbase.html[DataPresenterBase] (i.e., xamDataGrid™, xamDataPresenter™, and xamDataCarousel™) have a link:infragisticswpf4.datapresenter{ApiVersion}~infragistics.windows.datapresenter.datapresenterbase~theme.html[Theme] property that can be set to one of several predefined themes to get started quickly.

*In XAML:*

----
<igDP:XamDataPresenter Theme="Royale"/>
----

== Default Themes

The following is a list of the default themes available:

* Aero (Microsoft® Windows® Vista™)
* Generic (default)
* IG Theme
* LunaNormal (Windows XP Blue)
* LunaOlive (Windows XP Olive)
* LunaSilver (Windows XP Silver)
* Metro
* Metro Dark
* Office2007Blue
* Office2007Black
* Office2007Silver
* Office2010Blue
* Office2013
* Onyx
* Royal Dark
* Royale (Windows Media Center)
* RoyaleStrong (Windows Media Center-inspired)
* Scenic (MS Paint / MS Wordpad like)