////

|metadata|
{
    "name": "undo-redo-framework",
    "controlName": ["IG Undo Redo Framework"],
    "tags": ["Getting Started"],
    "guid": "3961de75-bd40-45b1-a3c7-e8fcda072341",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:54.1981018Z"
}
|metadata|
////

= Infragistics Undo/Redo Framework

=== Introduction

The Infragistics Undo/Redo Framework™ provides support for undo\redo functionality available in most applications.

The framework maintains operations history, executes undo\redo operations, and may group several operations into one single history item. Commands are provided to invoke an undo/redo operation from within your UI.

The framework is cross-platform and can be used either in WPF or Silverlight applications.

=== Topics

Detailed information regarding Infragistics Undo/Redo Framework is covered in the following topics:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:implementing-undo-redo-crud-operations-in-xamgrid-control.html[Implementing Undo/Redo CRUD Operations in xamGrid Control]
|This topic demonstrates how the Infragistics Undo\Redo Framework™ can be used with the xamGrid™ control. End-user operations as adding of a new row, editing cells and rows deletion can be reverted using the functionality provided by the framework.

| link:methods-and-properties-reference.html[Undo/Redo Framework Methods and Properties Reference]
|This section contains reference information about the Infragistics Undo\Redo Framework™ key methods and properties. The topics included cover the reference information for the major framework classes and reference information based on the tasks you want to achieve with the Undo\Redo API.

|====