////

|metadata|
{
    "name": "word-library",
    "controlName": ["IG Word Library"],
    "tags": ["Getting Started"],
    "guid": "edaa3759-9e1a-4e0f-8819-b7aa4d47d868",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:54.3251104Z"
}
|metadata|
////

= Infragistics Word Library

If you're looking for an area that houses all of the overview/task-based information related to the Word Library, you've come to the right place. This section contains valuable information about Word Library, ranging from what the Word Library does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task.

Click the links below to access important information about the Word Library.

== link:word-about-ig-word-library.html[About Infragistics Word Library]

In this section you'll find any information that will help you to better understand the functionalities of the Word Library, as well as why you would want to use it to as part of building your applications.

== link:word-using-the-ig-word-library.html[Using the Infragistics Word Library]

In this section, you'll find short, useful topics with sample code snippets that demonstrate how to perform specific tasks with the Word Library.

== link:word-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the Word Library. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.