////

|metadata|
{
    "name": "wpf-specific-controls-landing-page",
    "controlName": [],
    "tags": ["Getting Started"],
    "guid": "8fb909ba-1671-4316-8410-a97938553543",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:46:20.6049227Z"
}
|metadata|
////

= WPF Specific

Most of the {ProductName} controls are crossplatform which means that the WPF and Silverlight versions of each control are Object Model and API compatible. Any code you write (in C#/VB.NET code behind or XAML) to create and manipulate the controls can be shared across WPF and Silverlight versions of your application. All you need to do is change the references in your project to reference the platform specific version of the control assembly.

However, there are some controls that are specific to the {ProductName} product. Below is a list of these controls.

* link:wpfspecific-charts.html[Charts]
* link:wpf-the-data-presenter-family.html[The Data Presenter Family]
* link:editors.html[Editors]
* link:wpfspecific-frameworks.html[Frameworks]
* link:wpfspecific-grids.html[Grids]
* link:wpfspecific-interactions.html[Interactions]
* link:wpfspecific-layouts.html[Layouts]
* link:wpfspecific-menus.html[Menus]
* link:wpfspecific-schedules.html[Schedules]