////

|metadata|
{
    "name": "wpf-2007-volume-2",
    "controlName": [],
    "tags": ["Getting Started","How Do I"],
    "guid": "{075ACAAD-168E-4DEC-B6E5-19B9965F46AC}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:51.6666865Z"
}
|metadata|
////

= 2007 Volume 2

* Composite elements, such as the link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.labelpresenter.html[LabelPresenter] and link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.cellvaluepresenter.html[CellValuePresenter], will not appear in Microsoft® Expression® Blend's Asset Library. In order to edit the styles of these elements, use the Editing Control Styles and Templates with Expression Blend provided to you as part of the {ProductName} installation.
* The parameter-less OnRegisterResourceSets method of the AssemblyResourceSetLoader class has been been modified and now takes a string parameter. This method may either be called with a specified grouping name (e.g. DataPresenter, Editors or Primitives) or with null. When a specific grouping name is specified, it is recommended that you only register the resource sets for that grouping. When null is specified, all resource sets should be registered. As with the previous release, derived classes would use the protected static RegisterResourceSet method to register your custom ResourceSet instance.