////
|metadata|
{
    "name": "wpf-infragistics-excel-engine",
    "controlName": ["xamDataPresenter"],
    "tags": [],
    "guid": "{E6FB9EA1-5649-4078-A890-3FBEA1549CDA}","buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.0339599Z"
}
|metadata|
////

= Infragistics Excel Engine

This section contains information about the Infragistics Excel Engine, ranging from what the engine does and step-by-step procedures on using it in your application.

Click the links below to access important information about the Infragistics Excel Engine.

== link:igexcelengine-about-infragistics-excel-engine.html[About Infragistics Excel Engine]

In this section you'll find information that will help you to better understand the object model and the functionalities of the Infragistics Excel Engine.

== link:igexcelengine-creating-a-workbook.html[Creating a Workbook (Infragistics Excel Engine)]

In order to get you up and running as quickly as possible with the Infragistics Excel Engine, we've provided you with information on how to get started using the Infragistics Excel Engine (e.g., creating a workbook).

== link:igexcelengine-using-the-infragistics-excel-engine.html[Using the Infragistics Excel Engine]

This section contains information on the key features and functionalities provided by the Infragistics Excel Engine.

== link:igexcelengine-api-overview.html[API Overview (Infragistics Excel Engine)]

This topic lists the namespaces and classes that you will be working with while programming with the Infragistics Excel Engine. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.