////

|metadata|
{
    "name": "wpf-creating-a-themepack",
    "controlName": [],
    "tags": ["Styling","Theming"],
    "guid": "{DA9EB3A6-3905-4582-977B-D2D55F43EDD7}",  
    "buildFlags": ["wpf"],
    "createdOn": "2012-01-30T20:33:32.0530392Z"
}
|metadata|
////

= Creating a ThemePack

The {ProductName} product offers several ThemePacks that you can use to provide uniform styling of the controls across your application or to style a specific page. The architecture used to create these ThemePacks is available inside the {ProductName} assemblies; therefore, you can create your own ThemePack to use with the {ProductName} controls.

The following topics walk you, from start to finish, through the process of creating your own ThemePack.

* link:wpf-creating-and-setting-up-a-themepack-project.html[Creating and Setting Up a ThemePack Project]
* link:wpf-creating-a-style-groups-class.html[Creating a Style Group's Class]
* link:wpf-creating-a-style-groups-resourcedictionary-files.html[Creating a Style Group's ResourceDictionary Files]
* link:wpf-creating-the-assemblyresourcesetloader-class.html[Creating the AssemblyResourceSetLoader Class]
* link:wpf-modifying-the-assemblyinfo-file.html[Modifying the AssemblyInfo File]
* link:wpf-referencing-your-themepack.html[Referencing Your ThemePack]