////

|metadata|
{
    "name": "wpf-2008-volume-1",
    "controlName": [],
    "tags": ["Getting Started","How Do I"],
    "guid": "{1FA58C40-11BD-4FF2-80D3-46E0FA067BBB}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:51.6686869Z"
}
|metadata|
////

= 2008 Volume 1

* *DataContext handling in xamRibbon™* - The xamRibbon control uses WPF functionality (e.g. ItemsSource, DataTemplate) within its templates that sets the DataContext property. The xamRibbon control has been changed to maintain, when possible, the DataContext property set on it or one of its ancestors. In order to accommodate this change, the ApplicationMenuPresenter template and the DataTemplate for the RibbonGroupCollection have been modified.
* *The Theme property of xamChart™* - The Theme property of the xamChart control has been changed from an enumeration to a string. This was done to be consistent with the other {ProductName} controls as well as to allow for custom themes to be registered for and used by the xamChart control.
* *The GetThemeGroupings method of xamScreenTip* - The protected virtual GetThemeGroupings method has been removed from the XamScreenTip control. Instead, derived classes should use the ThemeManager.RegisterGroupings method to register the groupings for an element that exposes a Theme property.
* *ICommandHost interface changed* - The CanExecute and Execute methods of the ICommandHost interface have been changed. CanExecute now takes a single ExecuteCommandInfo object as a parameter instead of a RoutedCommand object and a CommandParameter object. Execute also takes a ExecuteCommandInfo object instead of an ExecuteRoutedEventArgs object and returns a Boolean value indicating whether the command execution has been processed.