////
|metadata|
{
    "name": "wpf-reporting",
    "controlName": ["IG WPF Reporting"],
    "tags": [],
    "guid": "{DA79954E-5EC6-4FBB-BD19-7CB624ADFFAC}","buildFlags": [],
    "createdOn": "2012-01-30T19:39:51.8977327Z"
}
|metadata|
////

= WPF Reporting

This section contains information about the WPF Reporting engine, ranging from what the engine does and step-by-step procedures on using it in your application.

Click the links below to access important information about the WPF Reporting engine.

== link:wpf-reporting-understanding-wpf-reporting.html[About WPF Reporting]

In this section you'll find information that will help you to better understand the functionalities of the WPF Reporting engine.

== link:wpf-reporting-getting-started-with-wpf-reporting.html[Adding WPF Reporting to Your Page]

In order to get you up and running as quickly as possible with the WPF Reporting engine, we've provided you with information on how to get started using the WPF Reporting engine (e.g., creating a report).

== link:wpf-reporting-using-wpf-reporting.html[Using WPF Reporting]

This section contains information on the key features and functionalities provided by the WPF Reporting engine.

== link:wpf-reporting-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WPF Reporting engine. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.

[[seealsobookmark]]