////

|metadata|
{
    "name": "wpf-breaking-changes-in-2010-volume-3",
    "controlName": [],
    "tags": ["API","Known Issues"],
    "guid": "7a91714c-b028-4c66-902b-7d884d789e40",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:51.7106953Z"
}
|metadata|
////

= 2010 Volume 3

== xamSchedule

== Known Issues

[start=1]
. When a recurring activity is created in the past, reminders for all the occurrences that it generates in the past are invoked. This issue will be fixed in a future release.
[start=2]
. When a recurring activity is created with a start time that does not coincide with the start time of the first occurrence generated by the associated recurrence rules, the recurring activity will not generate an occurrence for its start time, which it should. Note that when the recurring activity is created via the built in appointment dialog, the start time of the root activity is forced to be the start time of the first occurrence as generated by the recurrence rules, and thus this issue is not applicable in that case. This issue will be fixed in a future release.
[start=3]
. When using one of the WcfListConnectorService-derived services, if the activity data items supplied in the item sources are the normal view objects (derived from ActivityBase), property mappings cannot be specified for the Reminder or Recurrence properties or there will be errors. This issue will be fixed in a future release.
[start=4]
. When dragging activities in an Xbap application the cursor does not change to a "move" or "copy" cursor. This issue will be fixed in a future release.

== Limitations

[start=1]
. When deriving a class from ScheduleDialogFactoryBase and implementing any of the ‘Create…’ methods to return an element that represents the contents of your custom dialog, you should not return an instance of *Infragistics.Controls.Interactions.XamDialogWindow* or *System.Windows.Controls.ChildWindow* when compiling for Silverlight. Doing so may produce unpredictable results. This limitation will be removed in a future release.
[start=2]
. When defining property mappings on a WCF server using one of the WcfListConnectorService-derived services, the metadata property mappings will be ignored and that data will not be sent to the client. The metadata will also not be returned back from the client to the server when items are added or updated through the client’s UI. This limitation will be removed in a future release.