////

|metadata|
{
    "name": "wpf-the-data-presenter-family",
    "controlName": ["xamDataPresenter"],
    "tags": [],
    "guid": "{A6B43C3E-28F6-40E7-8E31-073DFB0C108E}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:51.5376607Z"
}
|metadata|
////

= Data Presenter Family

The Data Presenter Family is the grouping for the {ProductName} data-driven controls (xamDataCarousel™, xamDataGrid™,xamDataCards™, and xamDataPresenter™). These controls are in this family because the base functionality for these controls is the same.

To learn about the {ProductName} Data Presenter Family, click the links below:

* link:wpf-about-the-data-presenter-family.html[About the Data Presenter Family] -- Explains in more detail the reason for this section, and what to expect from the topics in this section.
* link:xamdata-theoryofoperation.html[Theory of Operation] -- Explains how controls derived from DataPresenterBase work, and the flexibility of the architecture.
* link:wpf-terms-and-concepts.html[Terms and Concepts] -- Defines the major elements that comprise xamDataPresenter.