////

|metadata|
{
    "name": "wpf-whats-new-in-the-2007-volume-1-hotfix-build-7-1-20071-1320",
    "controlName": [],
    "tags": [],
    "guid": "{5F24A75B-11BE-43B5-B4A1-D25F2DA60DFC}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:51.7036939Z"
}
|metadata|
////

= What's New in 2007 Volume 1 Hotfix (Build 7.1.20071.1320)

The {ProductName} 2007 Volume 1 hotfix includes a number of important changes and improvements to allow you use the {ProductName} toolset even more effectively.

== Performance Improvements

In the 2007 Volume 1 hotfix (build 7.1.20071.1320), we have made several performance improvements. These improvements include the following:

* When xamDataPresenter's™ GridView or xamDataGrid™ uses separate headers, the LabelPresenters elements are now being virtualized. This optimization improves initial form load speed; you can notice the performance boost when more fields are present in the data source. However, this does not improve scrolling performance, unless the scrolling reveals child bands for which headers need to be created.
* We have made many minor improvements that increase the speed of page scrolling and page loading in xamDataPresenter's GridView or xamDataGrid.
* The speed of grouping and sorting operations has been significantly improved.