////

|metadata|
{
    "name": "xamcarouselpanel",
    "controlName": ["xamCarouselPanel"],
    "tags": [],
    "guid": "{0C71AEB5-1D6C-4BFF-BA3B-78D7C17D5839}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:52.0627657Z"
}
|metadata|
////

= xamCarouselPanel

If you're looking for an area that houses all of the overview/task-based information related to the xamCarouselPanel™ control, you've come to the right place. This section contains valuable information about xamCarouselPanel, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the xamCarouselPanel control.

== link:xamcarouselpanel-understanding-xamcarouselpanel.html[About xamCarouselPanel]

In this section you'll find any information that will help you to better understand the functionalities of the xamCarouselPanel control, as well as why you would want to use it to as part of building your applications.

== link:xamcarouselpanel-getting-started-with-xamcarouselpanel.html[Adding xamCarouselPanel to Your Page]

In order to get you up and running as quickly as possible with the xamCarouselPanel control, we've provided you with information on how to get started using the control (e.g., adding xamCarouselPanel to your form).

== link:xamcarouselpanel-using-xamcarouselpanel.html[Using xamCarouselPanel]

This section contains information on the key features and functionalities provided by the xamCarouselPanel control.

== link:xamcarouselpanel-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamCarouselPanel control. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.