////

|metadata|
{
    "name": "xamcarousellistbox-accessing-data",
    "controlName": ["xamCarouselListBox"],
    "tags": ["Data Presentation"],
    "guid": "{F78B9162-CE5A-47A6-BDEB-CA51D4B3356F}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:52.0247581Z"
}
|metadata|
////

= Accessing Data

Data bound applications are everywhere. Without data, your end users wouldn't be able to save settings, access customer orders, or even check their e-mail. Being able to access an application's underlying data quickly and efficiently is a high priority for every developer.

Whether you use a Microsoft® Access™ database, SQL Server, your own custom object, or an XML site map, we can guide you through connecting each one to the xamCarouselListBox™ control without the headaches and frustration inherent in data bound applications. This section will provide you with all the knowledge you need to bind xamCarouselListBox to any data source.

Click the following links to view topics written specifically to help you access data using the xamCarouselListBox control.

* link:xamcarousellistbox-data-binding-overview.html[Data Binding Overview]