////

|metadata|
{
    "name": "xamcurrencyeditor",
    "controlName": ["xamCurrencyEditor"],
    "tags": [],
    "guid": "{322B1244-1DD5-4DD1-8CF0-FCDEAAB2D775}",  
    "buildFlags": [],
    "createdOn": "2012-09-05T19:05:30.1199781Z"
}
|metadata|
////

= xamCurrencyEditor

If you're looking for an area that houses all of the overview/task-based information related to the xamCurrencyEditor™ control, you've come to the right place. This section contains valuable information about xamCurrencyEditor, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the xamCurrencyEditor control.

* link:xamcurrencyeditor-about-xamcurrencyeditor.html[About xamCurrencyEditor]
* link:xameditors-overview-of-the-valueeditor-class.html[Overview of the ValueEditor Class]
* link:xameditors-masks.html[Masks]
* link:xamcurrencyeditor-using-xamcurrencyeditor-as-a-field-in-xamdatagrid.html[Using xamCurrencyEditor as a Field in xamDataGrid]
* link:xameditors-enabling-right-to-left-support.html[Enabling Right to Left Support]
* link:xameditors-working-with-the-isalwaysineditmode-property-and-the-editors.html[Working with the IsAlwaysInEditMode Property and the Editors]
* link:xamcurrencyeditor-api-overview.html[API Overview]