////

|metadata|
{
    "name": "xamcarouselpanel-designing-the-look-and-feel",
    "controlName": ["xamCarouselPanel"],
    "tags": [],
    "guid": "{11AE0E3C-2034-4DF4-9CF3-51070D6FD2DE}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:52.0697671Z"
}
|metadata|
////

= Designing the Look and Feel

The look and feel of a control isn't simply a style; it's an attitude. The "look" implies how a control visually appears, but the "feel" implies how a control acts; thus, you receive an appealing visual style coupled with specific functionality.

The look and feel of xamCarouselPanel™ might consist of the color scheme of a particular operating system, or possibly the functionality of a popular word-processing application. This section will help you turn on/off these look and feels and manipulate them to meet your application's personal attitude.

Click the following links to view topics written specifically to help you design the look and feel of the xamCarouselPanel control.

* link:xamcarousel-overview-of-path-effects.html[Overview of Path Effects]
* link:xamcarousel-changing-the-location-of-carousel-navigator-element.html[Changing the Location of the Carousel Navigation Element]
* link:xamcarousel-creating-a-named-path-on-the-artboard.html[Creating a Named Path on the Artboard]
* link:xamcarouselpanel-editing-the-carouselpanelitem-template.html[Editing the CarouselPanelItem Template]
* link:xamcarousel-disabling-reflection-for-an-item-along-a-path.html[Disabling Reflection for an Item Along a Path]
* link:xamcarouselpanel-modifying-the-opacity-effect-of-items-on-xamcarouselpanels-path.html[Modifying the Opacity Effect of Items on xamCarouselPanel's Path]
* link:xamcarouselpanel-modifying-the-scale-of-elements-on-xamcarouselpanels-path.html[Modifying the Scale of Elements on xamCarouselPanel's Path]
* link:xamcarouselpanel-modifying-the-skew-effect-of-items-on-xamcarouselpanels-path.html[Modifying the Skew Effect of Items on xamCarouselPanel's Path]
* link:xamcarouselpanel-setting-a-path-for-xamcarouselpanel-to-use.html[Setting a Path for xamCarouselPanel to Use]