////

|metadata|
{
    "name": "xamcarousellistbox-designing-the-look-and-feel",
    "controlName": ["xamCarouselListBox"],
    "tags": ["Data Presentation","Styling"],
    "guid": "{191CDFF4-767C-40A8-8AD7-5E81DE175FF4}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:52.0337599Z"
}
|metadata|
////

= Designing the Look and Feel

The look and feel of a control isn't simply a style; it's an attitude. The "look" implies how a control visually appears, but the "feel" implies how a control acts; thus, you receive an appealing visual style coupled with specific functionality.

The look and feel of xamCarouselListBox™ might consist of the color scheme of a particular operating system, or possibly the functionality of a popular word-processing application. This section will help you turn on/off these look and feels and manipulate them to meet your application's personal attitude.

Click the following links to view topics written specifically to help you design the look and feel of the xamCarouselListBox control.

* link:xamcarousel-overview-of-path-effects.html[Overview of Path Effects]
* link:xamcarousel-changing-the-location-of-carousel-navigator-element.html[Changing the Location of the Carousel Navigation Element]
* link:xamcarousel-creating-a-named-path-on-the-artboard.html[Creating a Named Path on the Artboard]
* link:xamcarousel-disabling-reflection-for-an-item-along-a-path.html[Disabling Reflection for an Item Along a Path]
* link:xamcarousellistbox-editing-the-carousellistboxitem-template.html[Editing the CarouselListBoxItem Template]
* link:xamcarousellistbox-modifying-the-opacity-effect-of-items-on-xamcarousellistboxs-path.html[Modifying the Opacity Effect of Items on xamCarouselListBox's Path]
* link:xamcarousellistbox-modifying-the-scale-of-elements-on-xamcarouselistboxs-path.html[Modifying the Scale of Elements on xamCarouselListBox's Path]
* link:xamcarousellistbox-modifying-the-skew-effect-of-items-on-xamcarousellistboxs-path.html[Modifying the Skew Effect of Items on xamCarouselListBox's Path]
* link:xamcarousellistbox-setting-a-path-for-xamcarousellistbox-to-use.html[Setting a Path for xamCarouselListBox to Use]