////
|metadata|
{
    "name": "xamcomboeditor-autocomplete",
    "controlName": ["xamComboEditor"],
    "tags": ["Getting Started"],
    "guid": "{F5152570-742C-46B1-97E6-13BCCA02843A}",
    "buildFlags": ["WPF"],
    "createdOn": "2016-05-25T18:21:54.7131325Z"
}
|metadata|
////

= Configuring Autocomplete (xamComboEditor)

The xamComboEditor™ control provides link:{ApiPlatform}controls.editors.xamcomboeditor.v{ProductVersion}~infragistics.controls.editors.xamcomboeditor~autocomplete.html[AutoComplete] feature in editable mode.

When you start typing, the control filters the data and displays the rest of the suggested text by highlighting it. By default this property is disabled. The filtering that is performed when auto-complete is executed uses StartsWith criteria.

You can use the Enter and Tab keys to accept the suggested text. You can also use the Space key if the text does not contain spaces.

You can traverse the other options in the drop-down list using the Up and Down arrow keys.

The following code will show you an example for the AutoComplete property usage.

*In XAML:*

----
<ig:XamComboEditor 
    x:Name="autoCompleteCombo"
    IsEditable="True" 
    AllowFiltering="True"
    AutoComplete="True"
    AutoCompleteDelay="1000" .../>
----

Other useful properties associated with the AutoComplete feature are:

* link:{ApiPlatform}controls.editors.xamcomboeditor.v{ProductVersion}~infragistics.controls.editors.comboeditorbase`2~autocompletedelay.html[AutoCompleteDelay]: this property controls the delay between going to the items source and filtering while you type. This delay is estimated in milliseconds.
* link:{ApiPlatform}controls.editors.xamcomboeditor.v{ProductVersion}~infragistics.controls.editors.xamcomboeditor~opendropdownontyping.html[OpenDropDownOnTyping]: if you set this property to False, the xamComboEditor drop-down list will not open.

== Related Topics

link:xamcomboeditor-using-customvalueenteredaction.html[Configuring the Behavior on User Input (xamComboEditor)]

link:xamcomboeditor-dropdown-resizing.html[Configuring the Drop-Down Size (xamComboEditor)]

link:xamcomboeditor-custom-filtering.html[Configuring Item Filtering (xamComboEditor)]

link:xamcomboeditor-working-with-itemtemplate.html[Configuring Item Template (xamComboEditor)]

link:xamcomboeditor-selection.html[Selection (xamComboEditor)]