////

|metadata|
{
    "name": "xamcontextmenu",
    "controlName": ["xamContextMenu"],
    "tags": ["Getting Started"],
    "guid": "{43AEEEA6-96CC-4E00-B816-5DAF1805C825}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:54.776106Z"
}
|metadata|
////

= xamContextMenu

This section gives you an overview of the use of xamContextMenu™. This section contains valuable information about xamContextMenu, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish common tasks using the control. Click the links below to access important information about the xamContextMenu control.

== link:xamcontextmenu-about-xamcontextmenu.html[About xamContextMenu]

In this section you’ll find any information that will help you to better understand the functionalities of the xamContextMenu control, as well as why you would want to use it as part of building your applications.

== link:xamcontextmenu-getting-started-with-xamcontextmenu.html[Adding xamContextMenu to Your Page]

In order to get you up and running as quickly as possible with the xamContextMenu control, we've provided you with information on how to get started using the control.

== link:xamcontextmenu-using-xamcontextmenu.html[Using xamContextMenu]

This section contains information on the key features and functionalities provided by the xamContextMenu control.

== link:xamcontextmenu-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamContextMenu control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the {ProductName} help.