////

|metadata|
{
    "name": "xamcomboeditor-editing-data",
    "controlName": ["xamComboEditor"],
    "tags": [],
    "guid": "{24F80C13-5CC7-4CA7-A767-3221E3CD0194}",  
    "buildFlags": [],
    "createdOn": "2012-09-05T19:05:30.0959781Z"
}
|metadata|
////

= Editing Data

Occasionally, you might use a database purely for informational purposes, never modifying the data. However, when this is not the case, you need a dependable and easy way for the end user to modify data. These modifications might include adding, updating, or deleting data, all of which are tasks that the xamComboEditor™ control performs by default.

The xamComboEditor control displays several views of the underlying data source. The xamComboEditor control can also manipulate the data source through several convenient methods, allowing you to give your end users the ease of use they've become accustomed to.

Click the following links to view topics written specifically to help you edit data using the xamComboEditor control.

* link:xamcomboeditor-enabling-right-to-left-support.html[Enabling Right to Left Support (xamComboEditor)]
* link:xamcomboeditor-setting-the-xamcomboeditor-as-an-editor-of-a-field-programmatically.html[Setting the xamComboEditor as an Editor of a Field Programmatically]
* link:xamcomboeditor-using-xamcomboeditor-to-edit-a-field-in-xamdatagrid.html[Using xamComboEditor to Edit a Field in xamDataGrid]
* link:xamcomboeditor-working-with-the-isalwaysineditmode-property-and-the-editors.html[Working with the IsAlwaysInEditMode Property and the Editors (xamComboEditor)]