////

|metadata|
{
    "name": "xamcalendar",
    "controlName": ["xamCalendar"],
    "tags": ["How Do I"],
    "guid": "a5f99c24-d7ae-4d25-b8ab-c2f0c282c403",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:54.6181259Z"
}
|metadata|
////

= xamCalendar

This section contains information about xamCalendar™ control.

== link:xamcalendar-about.html[About xamCalendar]

Click the link above to access important information about xamCalendar.

== link:xamcalendar-using.html[Using xamCalendar]

In order to get you up and running as quickly as possible with xamCalendar, we've provided you with information on how to get started using the control.

== link:xamcalendar-restricting-date-selection.html[Implementing Date Selection Restrictions]

In this topic you'll find information that will help you to better understand the functionalities of xamCalendar.

== link:xamcalendar-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamCalendar control. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.