////

|metadata|
{
    "name": "xamcomboeditor",
    "controlName": ["xamComboEditor"],
    "tags": ["Getting Started"],
    "guid": "{D256DCE8-E0AF-4A76-B4E1-56D37BAF45DA}",  
    "buildFlags": [],
    "createdOn": "2012-09-05T19:05:30.0639781Z"
}
|metadata|
////

= xamComboEditor (Input)

If you're looking for an area that houses all of the overview/task-based information related to the xamComboEditor™ control, you've come to the right place. This section contains valuable information about xamComboEditor, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the xamComboEditor control.

== link:wpf-xamcomboeditor-about-xamcomboeditor.html[About xamComboEditor]

In this section you'll find any information that will help you to better understand the functionalities of the xamComboEditor control, as well as why you would want to use it to as part of building your applications.

== link:wpf-xamcomboeditor-using-xamcomboeditor.html[Using xamComboEditor]

This section contains information on the key features and functionalities provided by the xamComboEditor control.

== link:wpf-xamcomboeditor-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamComboEditor control. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.