////

|metadata|
{
    "name": "xamcomboeditor-accessing-data",
    "controlName": ["xamComboEditor"],
    "tags": ["Data Binding","Getting Started"],
    "guid": "{955AEB48-DD99-412F-96D0-70CFEA0B152A}",  
    "buildFlags": [],
    "createdOn": "2012-09-05T19:05:30.0729781Z"
}
|metadata|
////

= Accessing Data

Data bound applications are everywhere. Without data, your end users wouldn't be able to save settings, access customer orders, or even check their e-mail. Being able to access an application's underlying data quickly and efficiently is a high priority for every developer.

Whether you use a Microsoft® Access™ database, SQL Server, your own custom object, or an XML file, we can guide you through connecting each one to the xamComboEditor™ control without the headaches and frustration inherent in data bound applications. This section will provide you with all the knowledge you need to bind xamComboEditor to any data source.

Click the following links to view topics written specifically to help you access data using the xamComboEditor control.

* link:xamcomboeditor-bind-xamcomboeditor-to-a-collection.html[Bind xamComboEditor to a Collection]
* link:xamcomboeditor-bind-xamcomboeditor-to-a-dataset.html[Bind xamComboEditor to a DataSet]
* link:xamcomboeditor-bind-xamcomboeditor-to-an-xmldataprovider.html[Bind xamComboEditor to an XmlDataProvider]
* link:xamcomboeditor-manually-add-items-to-xamcomboeditor.html[Manually Add Items to xamComboEditor]
* link:xamcomboeditor-handling-enums.html[Handling Enum Data Type (xamComboEditor)]