////

|metadata|
{
    "name": "xamcarousel-enabling-right-to-left-support",
    "controlName": ["xamCarousel"],
    "tags": ["How Do I"],
    "guid": "{DDDA00DC-9BB3-4C5B-89F0-B26A3BCC41CA}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:52.0087549Z"
}
|metadata|
////

= Enabling Right to Left Support

All {ProductName} controls support right-to-left functionality. By setting the link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.xamdatagrid.html[FlowDirection] property to RightToLeft, the content will flow from the right side of the control to the left. (i.e., Hebrew and Arabic use RightToLeft). By default, the FlowDirection is set to LeftToRight. The {ProductName} controls inherit this property from System.Windows.FrameworkElement.

This property is also available off some of the sub-controls used by the {ProductName} controls. For example, link:{RootAssembly}{ApiVersion}~infragistics.windows.virtualization.recyclingitemspanel.html[RecyclingItemsPanel] and several more sub-controls expose this property. Setting the FlowDirection at this level allows more control over the flow direction of the main control that uses these sub-controls.