////

|metadata|
{
    "name": "xamcarousellistbox-defining-layouts",
    "controlName": ["xamCarouselListBox"],
    "tags": ["Data Presentation","Layouts"],
    "guid": "{0F249959-002D-4F58-B1D5-A15A5F77BB59}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:52.0317595Z"
}
|metadata|
////

= Defining Layouts

You've gone through the steps to bind your data to xamCarouselListBox™, and now you're ready to present your data. However, the data won't jump out of the screen by itself; you need to create patterns and organize the data in a meaningful format. Defining layouts is a key feature of the xamCarouselListBox control.

Whether you have a flat or hierarchical data source, there are several layouts that will fit your needs. This section will provide you with all the knowledge you need to define layouts for xamCarouselListBox in order to present your data in the most usable format.

Click the following links to view topics written specifically to help you define layouts using the xamCarouselListBox control.

* link:xamcarousel-enabling-right-to-left-support.html[Enabling Right to Left Support]
* link:xamcarousellistbox-limiting-the-number-of-items-on-xamcarousellistboxs-path.html[Limiting the Number of Items on xamCarouselListBox's Path]
* link:xamcarousellistbox-making-the-xamcarousellistboxs-path-continuous.html[Making the xamCarouselListBox's Path Continuous]
* link:xamcarousellistbox-setting-padding-on-xamcarousellistboxs-path.html[Setting Padding on xamCarouselListBox's Path]
* link:xamcarousellistbox-working-with-the-itemtemplate.html[Working with the ItemTemplate]