////

|metadata|
{
    "name": "xamcarousellistbox-data-binding-overview",
    "controlName": ["xamCarouselListBox"],
    "tags": ["Data Binding","Data Presentation"],
    "guid": "{878A653E-432C-4FA0-BE68-2B0FADFE3CD8}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:52.0287589Z"
}
|metadata|
////

= Data Binding Overview

The xamCarouselListBox™ supports data binding like xamDataGrid™, xamDataCarousel™, and xamDataPresenter™ do, but the way it functions is different then the data controls. The data controls will actually interrogate their data source and based on it, generate the necessary fields and layouts. The xamCarouselListBox will not interrogate its data source and generate a layout. You must provide one for the xamCarouselListBox to follow. For more information, see link:xamcarousellistbox-working-with-the-itemtemplate.html[Working with the ItemTemplate].

== Related Topics

link:creating-a-flat-dataset.html[Creating a Flat DataSet]

link:creating-an-objectdataprovider.html[Creating an ObjectDataProvider]

link:creating-an-xmldataprovider.html[Creating an XmlDataProvider]

link:using-the-data-context-for-data-binding.html[Using the Data Context for Data Binding]