////

|metadata|
{
    "name": "xamcontextmenu-using-xamcontextmenu",
    "controlName": ["xamContextMenu"],
    "tags": ["Getting Started"],
    "guid": "{8381511A-0090-4D80-9AB8-E7CAFD5C69CE}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:54.7940975Z"
}
|metadata|
////

= Using xamContextMenu

This section is your gateway to important task-based information that will help you to effectively use the various features and functionalities provided by xamContextMenu™

link:xamcontextmenu-opening-and-showing-xamcontextmenu.html[Opening and Showing xamContextMenu]

This topic describes how you can configure the xamContextMenu control’s opening behavior.

link:xamcontextmenu-set-xamcontextmenus-location.html[Set xamContextMenu's Location]

This topic describes how you can configure the xamContextMenu control's placement via Placement, PlacementTarget, PlacementRectangle, HorizontalOffset and VerticalOffset properties.

link:xammenu-binding-to-data.html[Binding to Data]

This topic describes how you can bind the xamMenu or the xamContextMenu to hierarchical data.

link:xammenu-adding-and-removing-items.html[Adding and Removing Items]

This topic describes how you can add or remove xamMenuItems.

link:xammenu-adding-separators-between-xammenuitems.html[Adding Separators between XamMenuItems]

This topic describes how you can add separator lines to distinguish the xamMenu items.

link:xammenu-adding-icons-to-xammenuitems.html[Adding Icons to XamMenuItems]

This topic describes how you can add icons for items in the xamMenu control.

link:xammenu-adding-check-boxes-to-xammenuitems.html[Adding Check Boxes to XamMenuItems]

This topic describes how you can display check boxes for each of xamMenu's items.