////

|metadata|
{
    "name": "xamcarouselpanel-making-the-xamcarouselpanels-path-continuous",
    "controlName": ["xamCarouselPanel"],
    "tags": ["How Do I"],
    "guid": "{A2660B40-F0F6-4F44-B087-C7BCB15F9065}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:52.0787689Z"
}
|metadata|
////

= Making the xamCarouselPanel's Path Continuous

By default, xamCarouselPanel™ allows you to navigate right or left through the list of items until only the last item available visible. Set the link:{ApiPlatform}v{ProductVersion}~infragistics.windows.controls.carouselviewsettings~islistcontinuous.html[IsListContinuous] property to True to have xamCarouselListBox's list of items cycle through continually.

For a continuous list, the example code below goes inside the opening XamCarouselPanel tag in link:xamcarouselpanel-getting-started-with-xamcarouselpanel.html[Adding xamCarouselPanel to Your Page].

*In XAML:*

----
<igWindows:XamCarouselPanel.ViewSettings>
        <igWindows:CarouselViewSettings IsListContinuous="True" />
</igWindows:XamCarouselPanel.ViewSettings>
----