////

|metadata|
{
    "name": "xamcarouselpanel-defining-layouts",
    "controlName": ["xamCarouselPanel"],
    "tags": [],
    "guid": "{C8AC7E25-5D8F-44EC-86D5-B8FE513AEA7A}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:52.0677667Z"
}
|metadata|
////

= Defining Layouts

You've gone through the steps to bind your data to xamCarouselPanel™, and now you're ready to present your data. However, the data won't jump out of the screen by itself; you need to create patterns and organize the data in a meaningful format. Defining layouts is a key feature of the xamCarouselPanel control.

Whether you have a flat or hierarchical data source, there are several layouts that will fit your needs. This section will provide you with all the knowledge you need to define layouts for xamCarouselPanel in order to present your data in the most usable format.

Click the following links to view topics written specifically to help you define layouts using the xamCarouselPanel control.

* link:xamcarousel-enabling-right-to-left-support.html[Enabling Right to Left Support]
* link:xamcarouselpanel-limiting-the-number-of-items-viewed-on-xamcarouselpanels-path.html[Limiting the Number of Items Viewed on xamCarouselPanel's Path]
* link:xamcarouselpanel-making-the-xamcarouselpanels-path-continuous.html[Making the xamCarouselPanel's Path Continuous]
* link:xamcarouselpanel-setting-padding-on-xamcarouselpanels-path.html[Setting Padding on xamCarouselPanel's Path]