////

|metadata|
{
    "name": "xamcarousellistbox-making-the-xamcarousellistboxs-path-continuous",
    "controlName": ["xamCarouselListBox"],
    "tags": ["Data Presentation","Editing"],
    "guid": "{B864E9BA-D563-45D2-96CA-0560671D5D1E}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:52.0427617Z"
}
|metadata|
////

= Making the xamCarouselListBox's Path Continuous

By default, xamCarouselListBox™ allows you to navigate right or left through the list of items until only the last item available visible. Set the link:{RootAssembly}{ApiVersion}~infragistics.windows.controls.carouselviewsettings~islistcontinuous.html[IsListContinuous] property to True to have xamCarouselListBox's list of items cycle through continually.

For a continuous list, place the following example code inside the opening XamCarouselListBox tag in the link:xamcarousellistbox-getting-started-with-xamcarousellistbox.html[Adding xamCarouselListBox to Your Application].

*In XAML:*

----
<igWindows:XamCarouselListBox.ViewSettings>
        <igWindows:CarouselViewSettings IsListContinuous="True" />
</igWindows:XamCarouselListBox.ViewSettings>
----