////
|metadata|
{
    "name": "xamcalculationmanager-using-xamcalculationmanager",
    "controlName": ["xamCalculationManager"],
    "tags": ["Calculations"],
    "guid": "11eaf089-88bf-414b-b905-759a56a9f17c",
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:54.5601243Z"
}
|metadata|
////

= Using xamCalculationManager

This section is your gateway to important task-based information that will help you to effectively use the various features and functionalities provided by xamCalculationManager™ control.

link:xamcalculationmanager-create-xamcalculationmanager-custom-functions.html[Create xamCalculationManager Custom Functions]

link:xamcalculationmanager-overview-of-item-calculator.html[Overview of Item Calculator]

link:xamcalculationmanager-overview-of-list-calculator.html[Overview of List Calculator]

link:xamcalculationmanager-overview-of-named-references.html[Overview of Named References]

link:xamcalculationmanager-using-xamcalculationmanager-with-xamdatagrid.html[Using xamCalculationManager with xamDataGrid]