////

|metadata|
{
    "name": "xamcarousellistbox",
    "controlName": ["xamCarouselListBox"],
    "tags": [],
    "guid": "{0844DD26-F29D-4858-9D21-DB090D63F78F}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:52.0227577Z"
}
|metadata|
////

= xamCarouselListBox

If you're looking for an area that houses all of the overview/task-based information related to the xamCarouselListBox™ control, you've come to the right place. This section contains valuable information about xamCarouselListBox, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the xamCarouselListBox control.

== link:xamcarousellistbox-understanding-xamcarousellistbox.html[About xamCarouselListBox]

In this section you'll find any information that will help you to better understand the functionalities of the xamCarouselListBox control, as well as why you would want to use it to as part of building your applications.

== link:xamcarousellistbox-getting-started-with-xamcarousellistbox.html[Adding xamCarouselListBox to Your Application]

In order to get you up and running as quickly as possible with the xamCarouselListBox control, we've provided you with information on how to get started using the control (e.g., adding xamCarouselListBox to your form).

== link:xamcarousellistbox-using-xamcarousellistbox.html[Using xamCarouselListBox]

This section contains information on the key features and functionalities provided by the xamCarouselListBox control.

== link:xamcarousellistbox-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamCarouselListBox control. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.