////

|metadata|
{
    "name": "xamdatapresenter-designing-the-look-and-feel",
    "controlName": ["xamDataPresenter"],
    "tags": ["Styling"],
    "guid": "{0EFBA92D-3862-492C-A01A-1889ADA6E818}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.1409813Z"
}
|metadata|
////

= Styling xamDataPresenter

The look and feel of a control isn't simply a style; it's an attitude. The "look" implies how a control visually appears, but the "feel" implies how a control acts; thus, you receive an appealing visual style coupled with specific functionality.

The look and feel of xamDataPresenter™ might consist of the color scheme of a particular operating system, or possibly the functionality of a popular word-processing application. This section will help you turn on/off these look and feels and manipulate them to meet your application's personal attitude.

Click the following links to view topics written specifically to help you design the look and feel of the xamDataPresenter control.

* link:xamdatapresenter-changing-the-column-headers-style.html[Changing the Column Headers Style]
* link:xamdata-changing-the-record-hover-color.html[Changing the Record Hover Color]
* link:xamdatapresenter-enabling-alternating-row-colors.html[Enabling Alternating Row Colors]
* link:xamdata-referencing-a-themepack-in-xaml.html[Referencing a ThemePack in XAML]
* link:xamdatapresenter-designing-the-look-and-feel-carousel-view.html[Styling Carousel View]
* link:xamdatapresenter-styling-treeview.html[Styling Tree View]
* link:xamdata-using-built-in-themes.html[Using Built-In Themes]