////

|metadata|
{
    "name": "xamdiagram-connections-configuration-overview",
    "tags": ["Charting","Getting Started","How Do I","Summaries"],
    "controlName": ["xamDiagram"],
    "guid": "94f08487-69b8-4ae9-8ef6-4287334185c8",  
    "buildFlags": [],
    "createdOn": "2014-06-16T09:32:50.2834696Z"
}
|metadata|
////

= Diagram Connections Configuration Overview (xamDiagram)

[[_Ref391537902]]
== _xamDiagram_   Connections Configuration Overview

=== Purpose

This topic provides an overview of the configurable aspects of the connections of the  _xamDiagram_™ control.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamdiagram-general-overview.html[ _xamDiagram_ General Overview]
|This topic provides a general overview of the _xamDiagram_ control.

|====

[[_Ref391538037]]
== Connections Configuration Overview

[[_Ref391538045]]

=== xamDiagram connections configuration summary chart

include::xamdiagram-connections-configuration-summary-chart.adoc[]

[[_Ref391538049]]

=== Start and end

There are two possible methods for configuring the start and end points of diagram connections in the  _xamDiagram_   control:

*  *Relative*  – by specifying the nodes to connect to – the start and the end node, respectively.

This approach requires associating the connection with a start and end node; in this case, the start and end points of the connection are controlled by these nodes (When the node is relocated, the connection adjusts automatically.).
*  *Absolute*  – by specifying the coordinates of the connection’s start and end points on the diagram space.

A mixed approach, i.e. specifying a node at one of the ends of the connection and coordinates for the other end, is allowed, too.

==== Related Topics:

* link:xamdiagram-configuring-the-start-and-end-of-diagram-connections.html[Configuring the Start and End of Diagram Connections ( _xamDiagram_ )]

[[_Ref391538053]]

=== Connection caps

The caps of a diagram connection are the shapes that indicate its start and end. By default the start of a connection has no cap and its end is a filled arrow cap.

The  _xamDiagram_   provides a number of pre-defined shapes for the caps. (See the link:xamdiagram-visual-elements-overview.html[Visual Elements Overview ( _xamDiagram_ )] topic for details.) A pre-defined cap is selected through the link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramconnection~startcaptype.html[StartCapType]/ link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramconnection~endcaptype.html[EndCapType] properties. These properties accept as a value the respective cap shapes available as a link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramconnectioncaptype.html[DiagramConnectionCapType] enumeration. When using one of the pre-defined cap types, you can additionally specify the cap size through the link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramconnection~startcapsize.html[StartCapSize]/ link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramconnection~endcapsize.html[EndCapSize] properties.

If you need entirely custom caps, a custom `Style` with target type of link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramconnectioncappresenter_members.html[DiagramConnectionCapPresenter] can be set to the link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramconnection~startcapstyle.html[StartCapStyle]/ link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramconnection~endcapstyle.html[EndCapStyle] properties. In this, style any custom `ControlTemplate` can be specified for achieving the desired look.

==== Related Topics:

* link:xamdiagram-configuring-the-caps-of-diagram-connections.html[Configuring the Caps of the Diagram Connections ( _xamDiagram_ )]