////

|metadata|
{
    "name": "xamdatapresenter-clipboard-operations",
    "controlName": ["xamDataPresenter"],
    "tags": ["Editing"],
    "guid": "{F8AB05CA-FEF1-424A-99EE-C36D9021D554}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.1159763Z"
}
|metadata|
////

= Clipboard Operations (xamDataPresenter)

The DataPresenter controls allow your end users to perform cut, copy, paste, and clear cell content operations when they select cells, data records, or fields. Your end users can copy data from a DataPresenter control and paste it into a Microsoft® Excel® spreadsheet or vice-versa. They can also copy data between DataPresenter controls or within a single instance of a DataPresenter control. In fact, if your end users paste data into an add-new record, the DataPresenter control will automatically create new records for them.

Click on the topics below to find information on clipboard operations.

* link:xamdatapresenter-enable-clipboard-operations.html[Enable Clipboard Operations]
* link:xamdatapresenter-perform-clipboard-operations.html[Perform Clipboard Operations]
* link:xamdatapresenter-handle-clipboard-operation-errors.html[Handle Clipboard Operation Errors]
* link:xamdatapresenter-prevent-clipboard-operations-from-modifying-a-field.html[Prevent Clipboard Operations From Modifying a Field]
* link:xamdatapresenter-prevent-the-addition-of-specific-formats-to-the-clipboard.html[Prevent the Addition of Specific Formats to the Clipboard]