////

|metadata|
{
    "name": "xamdatapresenter-about-data-items-and-data-records",
    "controlName": ["xamDataPresenter"],
    "tags": ["Data Binding"],
    "guid": "{89488927-A4C8-42A0-91AC-00D9C2557DDE}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.0409613Z"
}
|metadata|
////

= About Data Items and Data Records

The link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datarecord.html[DataRecord] object's link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datarecord~dataitem.html[DataItem] property is a reference to the data item that the record represents. It should be an easy task to retrieve a reference to your data item if you already have a reference to a DataRecord object.

On the other hand, if you have a reference to your data item, finding the corresponding DataRecord object could be a complex recursive procedure. Fortunately, the DataPresenter family of controls exposes a link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datapresenterbase~getrecordfromdataitem.html[GetRecordFromDataItem] method that can return a DataRecord object that corresponds to your data item. You should keep in mind that this method starts searching for the record at the root level working its way down to the descendants until it finds a match. Therefore, calling the GetRecordFromDataItem method may be an expensive procedure if you have a deeply nested data source.

The following example code demonstrates the usage of the GetRecordFromDataItem method.

*In Visual Basic:*

----
Imports Infragistics.Windows.DataPresenter
...
'TODO: Replace 'YOUR_DATA_ITEM' with an actual reference to your data item.
Dim record As DataRecord = Me.xamDataPresenter1.GetRecordFromDataItem(YOUR_DATA_ITEM, True)
If record IsNot Nothing Then
    'TODO: Add logic for the record here
End If
----

*In C#:*

----
using Infragistics.Windows.DataPresenter;
...
//TODO: Replace 'YOUR_DATA_ITEM' with an actual reference to your data item.
DataRecord record = this.xamDataPresenter1.GetRecordFromDataItem(YOUR_DATA_ITEM, true);
if(record != null)
{
    //TODO: Add logic for the record here
}
----

== Related Topics

link:xamdatapresenter-add-items-manually-to-a-datapresenter-control.html[Add Items Manually to a DataPresenter Control]

link:xamdatapresenter-iterate-through-the-records-collection.html[Iterate through the Records Collection]