////

|metadata|
{
    "name": "xamdatetimeeditor",
    "controlName": ["xamDateTimeEditor"],
    "tags": ["Getting Started"],
    "guid": "{F5413562-08BE-4C09-9C30-0AFFC6DA0A5F}",  
    "buildFlags": [],
    "createdOn": "2012-09-05T19:05:30.1389781Z"
}
|metadata|
////

= xamDateTimeEditor

If you're looking for an area that houses all of the overview/task-based information related to the xamDateTimeEditor™ control, you've come to the right place. This section contains valuable information about xamDateTimeEditor, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the xamDateTimeEditor control.

* link:xamdatetimeeditor-about-xamdatetimeeditor.html[About xamDateTimeEditor]
* link:xameditors-overview-of-the-valueeditor-class.html[Overview of the ValueEditor Class]
* link:xameditors-masks.html[Masks]
* link:xamdatetimeeditor-using-xamdatetimeeditor-as-a-field-in-xamdatagrid.html[Using xamDateTimeEditor as a Field in xamDataGrid]
* link:xameditors-working-with-the-isalwaysineditmode-property-and-the-editors.html[Working with the IsAlwaysInEditMode Property and the Editors]
* link:xameditors-enabling-right-to-left-support.html[Enabling Right to Left Support]
* link:xamdatetimeeditor-api-overview.html[API Overview]