////

|metadata|
{
    "name": "xamdatapresenter-sorting",
    "controlName": ["xamDataPresenter"],
    "tags": ["Getting Started","Grouping","Sorting"],
    "guid": "{2C7672F3-EAF4-4698-8B23-84EDD59EDE83}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.3370205Z"
}
|metadata|
////

= Record Sorting (xamDataPresenter)

Most of you can remember creating a bubble sort algorithm while studying programming. Coding a bubble sort may or may not be second nature to you now, but the importance of sorting is paramount. Sorting gives your end user a way to find the data they need, for example, alphabetically or numerically.

Understanding how sorting and grouping function is not enough, you need to know how and when to use them.

Click the following links to view topics written specifically to help you sort your data using the xamDataPresenter control.

* link:xamdatapresenter-about-sorting.html[About Sorting]
* link:xamdatapresenter-disable-sorting.html[Disable Sorting]
* link:xamdatapresenter-sorting-and-grouping-fields-programmatically.html[Sorting and Grouping Fields Programmatically]