////

|metadata|
{
    "name": "xamdatacards",
    "controlName": ["xamDataCards"],
    "tags": [],
    "guid": "{5173A275-E859-49A6-9826-EBF628A78F9B}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:52.5878707Z"
}
|metadata|
////

= xamDataCards

This section contains information about xamDataCards™, ranging from what the control does and step-by-step procedures on using it in your application.

Click the links below to access important information about the xamDataCards control.

== link:xamdatacards-about-xamdatacards.html[About xamDataCards]

In this section you'll find information that will help you to better understand the functionalities of the xamDataCards control.

== link:xamdatacards-adding-xamdatacards-to-your-application.html[Adding xamDataCards to Your Application]

In order to get you up and running as quickly as possible with the xamDataCards control, we've provided you with information on how to get started using the control (e.g., adding xamDataCards to your Application).

== link:xamdatacards-using-xamdatacards.html[Using xamDataCards]

This section contains information on the key features and functionalities provided by the xamDataCards control.

== link:xamdatacards-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamDataCards/xamDataPresenter control. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.