////

|metadata|
{
    "name": "xamdatatree-about-xamdatatree",
    "controlName": ["xamDataTree"],
    "tags": ["Getting Started","How Do I"],
    "guid": "ecda680c-c651-4ce0-8bd9-8769468dac7a",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:54.8371101Z"
}
|metadata|
////

= About xamDataTree

The xamDataTree™ control is a tree control designed for high performance which focuses on data-bound tree scenarios. This control simplifies the process of creating a tree that is bound to an N-level-deep data structure. It also automates the process of creating node hierarchies while preserving the flexibility in node display that is provided by XAML.

The following is a list of key features of the xamDataTree control:

*High Performance* – The xamDataTree is extremely lightweight and extremely fast when handling large amounts of data.

*Fully Templatable* – You can customize every aspect of your tree node.

*Keyboard Navigable* - Your end users can easily move around the xamDataTree control using only a few familiar key presses.

*Drag and Drop* – Your end users can drag and drop nodes around on the xamDataTree control.

*Related Topics*

link:xamdatatree-adding-xamdatatree-to-your-page.html[Adding xamDataTree to Your Page]

link:xamdatatree-xamdatatree-data-binding.html[Binding xamDataTree to Data]

link:xamdatatree-using-xamdatatree.html[Configuring xamDataTree]