////

|metadata|
{
    "name": "xamdiagram-optimizing-for-handling-large-data",
    "tags": [],
    "controlName": ["xamDiagram"],
    "guid": "5ebf7a8d-b551-4259-83e3-6ebfc9e30c96",  
    "buildFlags": [],
    "createdOn": "2014-06-16T09:44:37.0993974Z"
}
|metadata|
////

= Optimizing xamDiagram for Handling Large Data

== Optimizing xamDiagram for Handing Large Data

=== Introduction

This topic provides guidance about tuning the  _xamDiagram_™ control for large data handling.

The  _xamDiagram_  is capable of handling large amounts of data; however, performance issues may still arise. If you are experiencing performance issues, consider trying some of the following suggestions in order to improve performance.

.Note:
[NOTE]
====
This is not normally necessary and applying too many of the suggestions listed below could diminish the overall usability of the diagram. Therefore, these are to be carefully considered and practically tested first in order to find out which combination produces the best results.
====

=== xamDiagram performance optimization suggestions reference chart

include::xamdiagram-performance-optimization-reference-chart.adoc[]