////

|metadata|
{
    "name": "xamdockmanager",
    "controlName": ["xamDockManager"],
    "tags": [],
    "guid": "{E24E8F78-0D6A-47D6-AA6E-FB055AC7AF50}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.4770485Z"
}
|metadata|
////

= xamDockManager

If you're looking for an area that houses all of the overview/task-based information related to the xamDockManager™ control, you've come to the right place. This section contains valuable information about xamDockManager, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the xamDockManager control.

== link:xamdockmanager-understanding-xamdockmanager.html[About xamDockManager]

In this section you'll find any information that will help you to better understand the functionalities of the xamDockManager control, as well as why you would want to use it to as part of building your applications.

== link:xamdockmanager-getting-started-with-xamdockmanager.html[Adding xamDockManager to Your Application]

In order to get you up and running as quickly as possible with the xamDockManager control, we've provided you with information on how to get started using the control (e.g., adding xamDockManager to your Window).

== link:xamdockmanager-using-xamdockmanager.html[Using xamDockManager]

This section contains information on the key features and functionalities provided by the xamDockManager control.

== link:xamdockmanager-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamDockManager control. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.