////

|metadata|
{
    "name": "xamdatapresenter-defining-layouts-carousel-view",
    "controlName": ["xamDataPresenter"],
    "tags": [],
    "guid": "{95379DEF-4BB1-455B-A453-2D4303F6F1F4}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.1369805Z"
}
|metadata|
////

= Carousel View

Click the following links to view topics written specifically to help you define layouts using the xamDataPresenter's™ Carousel View.

link:xamdatapresenter-changing-the-location-of-the-carouselbreadcrumb.html[Changing the Location of the CarouselBreadcrumb]

See how you can change the location of the Carousel View's Breadcrumb

link:xamdatapresenter-limiting-the-number-of-items-viewed-on-xamdatapresenters-path.html[Limiting the Number of Items Viewed on xamDataPresenter's Path]

See how to change the number of items shown along xamDataPresenter's path.

link:xamdatapresenter-making-the-path-continuous.html[Making the Path Continuous]

See how to make the path continuous i.e. to continuously navigate through the collection of items.

link:xamdatapresenter-setting-padding-on-xamdatapresenters-path.html[Setting Padding on xamDataPresenter's Path]

See how to add and modify the size of the buffer/padding before the first and after the last card in the collection.

link:xamdatapresenter-showing-more-than-three-fields-in-xamdatapresenter.html[Showing More Than Three Fields in xamDataPresenter]

See how to show more fields in Carousel View.