////

|metadata|
{
    "name": "xamdialogwindow-using-xamdialogwindow",
    "controlName": ["xamDialogWindow"],
    "tags": [],
    "guid": "{D945D272-BE03-447F-8062-D9F7F12A1EBD}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:54.9521229Z"
}
|metadata|
////

= Using xamDialogWindow

This section is your gateway to important conceptual and task-based information that will help you to use the various features and functionalities provided by the xamDialogWindow™ control.

link:xamdialogwindow-custom-cursors.html[Custom Cursors]

This topic describes how you can customize the xamDialogWindow control’s resizing cursors via DataTemplates.

link:xamdialogwindow-customize-modal-dialog-window-background.html[Customize Modal Dialog Window Background]

This topic describes how you can apply effects to the modal xamDialogWindow control’s background.

link:xamdialogwindow-customize-the-window-header-icon.html[Customize the Window Header Icon]

This topic describes how you can change the control’s header icon.

link:xamdialogwindow-handle-moving-events.html[Handle Moving Events]

This topic describes the control’s Moving and Moved events.

link:xamdialogwindow-handle-window-state-changing-events.html[Handle Window State Changing Events]

This topic describes the events associated with the xamDialogWindow state change. The window can switch between normal, minimized, maximized and hidden state.

link:xamdialogwindow-keyboard-settings.html[Keyboard Settings]

This topic describes how you can enable and tune the keyboard navigation on the xamDialogWindow control in order to move it with the arrows keys.

link:xamdialogwindow-modal-and-modeless-dialog-windows.html[Modal and Modeless Dialog Windows]

This topic describes how you can create a modal xamDialogWindow.

link:xamdialogwindow-position-minimized-dialog-window.html[Position Minimized Dialog Window]

This topic describes how you can minimize the xamDialogWindow control and place it in a panel.

link:xamdialogwindow-set-the-dialog-windows-height-and-width-when-minimized.html[Set the Dialog Window's Height and Width When Minimized]

This topic describes the usage of the xamDialogWindow control’s MinimizedWidth and MinimizedHeight properties.

link:xamdialogwindow-start-up-position-of-xamdialogwindow.html[Start Up Position of xamDialogWindow]

This topic describes how you can set up the xamDialogWindow control’s initial position.

link:xamdialogwindow-the-xamdialogwindow-controls-behavior.html[The xamDialogWindow Control's Behavior]

This topic describes the behavior of the xamDialogWindow when nested in different containers.

link:xamdialogwindow-window-header-controls.html[Window Header Controls]

This topic describes the usage of the xamDialogWindow control’s CloseButtonVisibility, MaximizeButtonVisibility and MinimizeButtonVisibility properties.