////

|metadata|
{
    "name": "xamdialogwindow",
    "controlName": ["xamDialogWindow"],
    "tags": ["Getting Started"],
    "guid": "3ab6a1ea-8cb4-47e7-ab42-58ec44bafd4a",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:54.9471229Z"
}
|metadata|
////

= xamDialogWindow

This section gives you an overview of the use of xamDialogWindow™. This section contains valuable information about xamDialogWindow, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish common tasks using the control. Click the links below to access important information about the xamDialogWindow control.

== link:xamdialogwindow-about-xamdialogwindow.html[About xamDialogWindow]

In this section you’ll find any information that will help you to better understand the functionalities of the xamDialogWindow control, as well as why you would want to use it as part of building your applications.

== link:xamdialogwindow-adding-xamdialogwindow-to-your-page.html[Adding xamDialogWindow to Your Application]

In order to get you up and running as quickly as possible with the xamDialogWindow control, we've provided you with information on how to get started using the control.

== link:xamdialogwindow-using-xamdialogwindow.html[Using xamDialogWindow]

This section contains information on the key features and functionalities provided by the xamDialogWindow control.

== link:xamdialogwindow-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamDialogWindow control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the {ProductName} help.