////

|metadata|
{
    "name": "xamdata-hierarchical-heterogenous-and-free-form-data-structures",
    "controlName": ["xamDataPresenter"],
    "tags": ["Data Binding","How Do I"],
    "guid": "{88EE3350-CE09-4BE2-A083-4DC8E76CECE6}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:52.5178567Z"
}
|metadata|
////

= Hierarchical, Heterogenous and Free-Form Data Structures

The DataPresenter architecture supports the consumption and display of hierarchical data, heterogeneous data, and free-form data structures (trees). Heterogeneous data describes a data source that contains records of different types. This is supported based on xamDataPresenter's™ ability to assign a different link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fieldlayout.html[FieldLayout] to each link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datarecord.html[DataRecord].

.Note
[NOTE]
====
There is currently a limitation with regard to multiple FieldLayout support in the controls -- the link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datapresenterbase~groupbyarea.html[GroupByArea] can show only fields from a single FieldLayout: the link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datapresenterbase~defaultfieldlayout.html[DefaultFieldLayout]. Therefore, grouping is supported only for the DefaultFieldLayout.
====

Hierarchical data is automatically supported unless the link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datapresenterbase~isnesteddatadisplayenabled.html[IsNestedDataDisplayEnabled] property is set to False. By default, any field that has a link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.field~datatype.html[DataType] that implements the System.Collections.IEnumerable interface, other than string is marked as "expandable". You can explicitly change this by setting the Field's link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.field~isexpandable.html[IsExpandable] property.

When a Field is marked as expandable, link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.cellvaluepresenter.html[CellValuePresenters] are not created to represent the field in the UI. Instead, an link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.expandablefieldrecord.html[ExpandableFieldRecord] is created and added to each DataRecord's link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datarecord~childrecords.html[ChildRecords] collection. An ExpandableFieldRecord, like a DataRecord, is not a UIElement™ but rather a lightweight object. It is represented in the UI by a corresponding link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.expandablefieldrecordpresenter.html[ExpandableFieldRecordPresenter] (for more information, see link:xamdata-performance-optimizations-overview.html[Performance Optimizations Overview]).

If the associated Field's DataType implements the IEnumerable interface, a link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.expandablefieldrecord~childrecordmanager.html[ChildRecordManager] is initialized to create and manage the child DataRecords. In this case, when the ExpandableFieldRecord is expanded, the ExpandableFieldRecordPresenter's link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.recordpresenter~nestedcontent.html[NestedContent] will contain a link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.recordlistcontrol.html[RecordListControl] containing the child DataRecordPresenters. Otherwise, the NestedContent will contain an link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.expandedcellpresenter.html[ExpandedCellPresenter] with the actual cell value.

.Note
[NOTE]
====
The link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datapresenterbase~fieldsettings.html[FieldSettings] object exposes two additional properties that determine the behavior of the ExpandableFieldRecordPresenters: link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fieldsettings~expandablefieldrecordexpansionmode.html[ExpandableFieldRecordExpansionMode] and link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fieldsettings~expandablefieldrecordheaderdisplaymode.html[ExpandableFieldRecordHeaderDisplayMode]. These two properties are applicable only in link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.gridview.html[Grid view].
====

Different link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.xamdatapresenter~view.html[Views] support hierarchical data differently. Therefore, the link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.recordpresenter.html[RecordPresenter]-derived classes ( link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datarecordpresenter.html[DataRecordPresenter], link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.groupbyrecordpresenter.html[GroupByRecordPresenter], and ExpandableFieldRecordPresenter) expose a link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.recordpresenter~templategridview.html[TemplateGridView] and a link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.recordpresenter~templatecardview.html[TemplateCardView] property to vary their visual trees based on the view. For example, in the Grid view, a RecordPresenter will normally show an expansion indicator in the UI that is used to toggle its link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.record~isexpanded.html[IsExpanded] state, and will show its nested child records directly beneath its record content. However, in a Card view, this is not the case. Normally, Card views, like the Carousel view, are limited to showing only sibling records at any one time. Therefore, the Carousel view supports hierarchical data through a drill-down metaphor that makes use of breadcrumbs to visualize and navigate the drill-down path.