////

|metadata|
{
    "name": "xamdatapresenter-making-the-path-continuous",
    "controlName": ["xamDataPresenter"],
    "tags": ["How Do I","Layouts","Tips and Tricks"],
    "guid": "{FAAAA587-C609-4A3E-A3B8-D6F7058E939B}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.2490029Z"
}
|metadata|
////

= Making the Path Continuous

You can navigate right or left in xamDataPresenter's™ Records collection till the last Record available in the list is still visible. You can also navigate continuously through the collection by setting the link:{ApiPlatform}v{ProductVersion}~infragistics.windows.controls.carouselviewsettings~islistcontinuous.html[IsListContinuous] property to True.

For a continuous list, use the following code.

*In XAML:*

----
<igDP:XamDataPresenter.View>
        <igDP:CarouselView>
                <igDP:CarouselView.ViewSettings>
                        <igWindows:CarouselViewSettings IsListContinuous="True" />
                </igDP:CarouselView.ViewSettings>
        </igDP:CarouselView>
</igDP:XamDataPresenter.View>
----

Replace the code inside the XamDataPresenter tag in link:xamdatapresenter-getting-started-with-xamdatapresenter.html[Adding xamDataPresenter to Your Application], with the above code to view this functionality.