////

|metadata|
{
    "name": "xamdatetimeinput",
    "controlName": ["xamInputs"],
    "tags": ["Editing"],
    "guid": "76796c4f-37a0-4a79-9840-e3c6cafc8141",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:56.9942288Z"
}
|metadata|
////

= xamDateTimeInput

This section contains valuable information about the xamDateTimeInput™ control, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish common tasks using the control.

The information you need about the xamDateTimeInput control is covered in the following topics:

* link:xamdatetimeinput-about.html[About xamDateTimeInput]
* link:xamdatetimeinput-using.html[Using xamDateTimeInput]
* link:xamdatetimeinput-api-overview.html[API Overview]

== Related Topics

Following are some other topics you may find useful.

* link:xaminputs-masks.html[Masks]
* link:xaminputs-overview-of-the-valueinput-class.html[Overview of the ValueInput Class]

ifdef::sl,wpf,win-rt[]
* link:xaminputs-using-xaminput-controls-in-xamgrid-cells-for-data-editing.html[Using xamInput Controls in xamGrid Cells for Data Editing]

endif::sl,wpf,win-rt[]