////

|metadata|
{
    "name": "xamdockmanager-load-an-end-users-docking-layout",
    "controlName": ["xamDockManager"],
    "tags": ["How Do I"],
    "guid": "{41F7BF85-24FA-4E61-9879-F8F5015B0986}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.5110553Z"
}
|metadata|
////

= Load an End User's Docking Layout

The link:{ApiPlatform}dockmanager{ApiVersion}~infragistics.windows.dockmanager.xamdockmanager.html[ _xamDockManager_  ]™ control allows your end users to modify the layout of your application. Your end users will expect you to save and load these settings so that they do not have to modify the layout when they restart your application. The xamDockManager control exposes an overloaded link:{ApiPlatform}dockmanager{ApiVersion}~infragistics.windows.dockmanager.xamdockmanager~loadlayout.html[LoadLayout] method that you can use to load a previously saved docking layout.

.Note
[NOTE]
====
The  _xamDockManager_   does not create and add content panes automatically based on the layout file information. The content panes need to exist prior the invoking of the `LoadLayout` method. If  _xamDockManager_   discovers a content pane in the layout file that is not found among the content panes of the current layout, the link:{ApiPlatform}dockmanager{ApiVersion}~infragistics.windows.dockmanager.xamdockmanager~initializepanecontent_ev.html[InitializePaneContent] event will be fired and you can provide content for the missing content pane. To distinguish content panes and figure out what content you need to provide you can use the link:{ApiPlatform}dockmanager{ApiVersion}~infragistics.windows.dockmanager.contentpane~serializationid.html[SerializationId] property. If you do not provide content during this event,  _xamDockManager_   will not add the missing content pane to its layout.
====

The example code below demonstrates how to load a previously saved docking layout.

*In Visual Basic:*

----
Imports System.IO
...
' Load the layout from a stream
Using fs As New FileStream("layout.xml", FileMode.Open, FileAccess.Read) 
    Me.xamDockManager1.LoadLayout(fs)                                                        
End Using 
...
' Handle the InitializePaneContent event to add content to missing panes
Private Sub xamDockManager1_InitializePaneContent(ByVal sender As Object,
    ByVal e As InitializePaneContentEventArgs) 
    ' TODO: Add content to the missing content pane using the e.NewPane object 
End Sub
...
----

*In C#:*

----
using System.IO;
...
// Load the layout from a stream
using (FileStream fs = new FileStream("layout.xml", FileMode.Open, FileAccess.Read))
{
    this.xamDockManager1.LoadLayout(fs);
}
....
// Handle the InitializePaneContent event to add content to missing panes
private void xamDockManager1_InitializePaneContent(object sender,
    InitializePaneContentEventArgs e)
{
    // TODO: Add content to the missing content pane using the e.NewPane object
}
...
----

== Related Topics

link:xamdockmanager-about-saving-and-loading-layouts.html[About Saving and Loading Layouts]

link:xamdockmanager-save-an-end-users-docking-layout.html[Save an End User's Docking Layout]

link:xamdockmanager-using-xamdockmanager.html[Using xamDockManager]