////

|metadata|
{
    "name": "xamdatatree-xamdatatree-data-binding",
    "controlName": ["xamDataTree"],
    "tags": ["Data Binding","How Do I"],
    "guid": "5ed97f1e-65aa-41dd-8960-1547d1518f0e",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:54.8931115Z"
}
|metadata|
////

= Binding xamDataTree to Data

The xamDataTree™ control is a bound tree control; therefore you cannot add nodes directly to it.

Binding the xamDataTree to data requires you to set the xamDataTree control’s link:{ApiPlatform}controls.menus.xamdatatree.v{ProductVersion}~infragistics.controls.menus.xamdatatree~itemssource.html[ItemsSource] property.

The following code shows you how to bind to data in xamDataTree. It uses the link:resources-datautil.html[DataUtil class] provided for you.

*In XAML:*

----
<UserControl.Resources>
    <local:DataUtil x:Key="DataUtil" />
</UserControl.Resources>
<Grid x:Name="LayoutRoot" Background="White">
   <ig:XamDataTree x:Name="MyTree" ItemsSource="{Binding Source={StaticResource DataUtil}, Path=CategoriesAndProducts}">
   </ig:XamDataTree>
</Grid>
----

*In Visual Basic:*

----
MyTree.ItemsSource = DataUtil.CategoriesAndProducts
----

*In C#:*

----
MyTree.ItemsSource = DataUtil.CategoriesAndProducts;
----

*Data Representation*

The xamDataTree control uses a link:{ApiPlatform}controls.menus.xamdatatree.v{ProductVersion}~infragistics.controls.menus.nodelayout.html[NodeLayout] object to represent a group/ type of node. This allows for common styling based on the type or data level. For more information, see the link:xamdatatree-xamdatatree-node-layouts.html[xamDataTree Node Layouts] topic.

*Related Topics*

link:xamdatatree-about-xamdatatree.html[About xamDataTree]

link:xamdatatree-adding-xamdatatree-to-your-page.html[Adding xamDataTree to Your Page]

link:xamdatatree-using-xamdatatree.html[Configuring xamDataTree]