////

|metadata|
{
    "name": "xamdata-about-xamdatapresenter-and-xameditors",
    "controlName": ["xamDataPresenter"],
    "tags": ["Data Presentation","Editing"],
    "guid": "{2B24A175-7951-47D6-BC92-8F3E5FFA3040}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:52.4838499Z"
}
|metadata|
////

= About xamDataPresenter and xamEditors

The xamEditor controls are automatically registered to edit a specific data type in a xamDataPresenter™ control's link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.field.html[Field]. For example, xamCheckEditor™ is registered to edit a Field with a Boolean data type while xamCurrencyEditor™ is registered to edit a Field with a decimal data type. Using this information, you can easily embed a xamEditor control in an unbound field by setting the `UnboundField` object's link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.field~datatype.html[DataType] property. For example, if you want to add a field of xamCheckEditor controls to xamDataPresenter, xamDataCarousel™, or xamDataGrid™, you can add an UnboundField object to a field layout and set the field's DataType property to Boolean.

If you want to change the default registration of a xamEditor and a data type, you can manually register a xamEditor control for a specific data type by calling the static RegisterDefaultEditorForType method of the ValueEditor class. Calling this method before or during xamDataPresenter's link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datapresenterbase~fieldlayoutinitialized_ev.html[FieldLayoutInitialized] event will change the xamEditor control that xamDataPresenter uses to edit a specific data type. For a list of xamEditors and their registered data types, see link:xamdata-default-editor-types-for-different-data-types.html[Default Editor Types for Different Data Types].

If you use the RegisterDefaultEditorForType method to change the xamEditor control registered to a specific data type, all fields with that data type will use the same xamEditor control. However, you also have granular control over the xamEditor control for individual fields in a field layout. The link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fieldsettings.html[FieldSettings] object exposes the link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fieldsettings~editortype.html[EditorType] property so that you can change the xamEditor control that a field uses to edit data. If you need to set properties of the xamEditor control, you have to create a Style that targets that particular xamEditor.

== Related Topics

link:xamdatapresenter-embedding-a-xameditor-in-a-field.html[Embedding a xamEditor in a Field]