////

|metadata|
{
    "name": "xamdatapresenter-field-sizing",
    "controlName": ["xamDataPresenter"],
    "tags": [],
    "guid": "{3B8B40A1-ECE0-47AC-8748-D08A00A7E076}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.2039939Z"
}
|metadata|
////

= Field Sizing

A DataPresenter control gives your end users the ability to automatically resize a field by double clicking a field's resizing indicator. This behavior replicates the column-sizing functionality found in Microsoft® Excel®. Furthermore, just like Excel, your end users can synchronize field sizing by selecting multiple fields and dragging or double clicking a resizing indicator. However, if you enable field selection by setting a link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fieldsettings.html[FieldSettings] object's link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fieldsettings~labelclickaction.html[LabelClickAction] property to SelectField, your end users will not be able to click a field's header to sort the field.

In addition to your end users auto sizing a field, the DataPresenter controls can automatically resize all fields within a field layout to fit within the bounds of the control. To complement this feature, the DataPresenter controls also allow you to set a field's width as a percentage using the same star-sizing syntax found in the Grid panel.

Click on the topics below to find information on field sizing.

link:xamdatapresenter-set-a-fields-width.html[Set a Field's Width]

Learn how to manually set field size using different units and methods.

link:xamdatapresenter-automatically-fit-fields.html[Automatically Fit Fields]

Learn about the different the modes of the "auto-fit" feature that can be set on the fields.

link:xamdatapresenter-modify-field-sizing-behaviors.html[Modify Field-Sizing Behaviors]

Learn about the different factors that have influence over the field resizing indicator.

link:xamdatapresenter-perform-an-auto-sizing-operation.html[Perform an Auto-Sizing Operation]

Learn when and how to force execution of the "auto-sizing" feature from the programming code.