////

|metadata|
{
    "name": "xamdatapresenter-creating-custom-views",
    "controlName": ["xamDataPresenter"],
    "tags": ["Extending","How Do I"],
    "guid": "{1D729C73-771C-4752-A7FB-A8D6269A75FA}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.1249781Z"
}
|metadata|
////

= Creating Custom Views

The xamDataPresenter™ is a layout-type control which allows the visualizing of data in several different views including custom ones. It is useful when you need to change the data presentation view dynamically. The xamDataPresenter controlcombines a robust data binding and UIElement-generation foundation with a pluggable view architecture to offer developers a flexible platform for data display.

The {ProductName} product providestwo Views: GridView and CarouselView. Each of these built-in Views is derived from the ViewBase base class and builds on the very sameservices that you can use to create your own Custom Pluggable View.

When you create a Custom View, you are leveraging a tremendous amount of functionality provided by xamDataPresenter. The code in your view can focus on providing its unique presentation and rely on xamDataPresenter to provide the basics like data binding, selection, keyboard navigation, grouping, sorting, etc.

Click the following links to learn more about how to create a Custom View:

* link:xamdatapresenter-how-to-create-a-basic-custom-view.html[How to Create a Basic Custom View]
* link:xamdatapresenter-services-provided-by-the-xamdatapresenter.html[Services Provided by the XamDataPresenter]
* link:xamdatapresenter-creating-the-custom-view-class-and-layout-panel.html[Creating the Custom View Class and Layout Panel]
* link:xamdatapresenter-how-to-use-your-custom-view-with-xamdatapresenter.html[How to Use Your Custom View with xamDataPresenter]