////

|metadata|
{
    "name": "xamdockmanager-pin-and-unpin-a-pane",
    "controlName": ["xamDockManager"],
    "tags": ["How Do I"],
    "guid": "{CDC05C09-461F-458C-8BA5-20291C5DE951}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.5140559Z"
}
|metadata|
////

= Pin and Unpin a Pane

Using the xamDockManager™ control, you can hide a pinned content pane by unpinning it. Likewise, you can pin a hidden pane when it flies out so that it is always visible. A content pane can be pinned and unpinned in code or by the end user at run time.

The following example code demonstrates how to unpin a content pane.

*In XAML:*

----
...
<igDock:XamDockManager Name="xamDockManager1"> 
    <igDock:XamDockManager.Panes>
        <igDock:SplitPane>
            <igDock:ContentPane 
                Name="contentPane1" 
                Header="Pane 1" 
                IsPinned=">
                <!--TODO: Add content here-->
            </igDock:ContentPane>
        </igDock:SplitPane>
    </igDock:XamDockManager.Panes>
</igDock:XamDockManager>
...
----

*In Visual Basic:*

----
Me.contentPane1.IsPinned = False
----

*In C#:*

----
this.contentPane1.IsPinned = false;
----

== Related Topics

link:xamdockmanager-about-opening-and-closing-panes.html[About Opening and Closing Panes]

link:xamdockmanager-add-content-to-a-contentpane.html[Add Content to a ContentPane]

link:xamdockmanager-add-panes-to-the-documentcontenthost-object.html[Add Panes to the DocumentContentHost Object]

link:xamdockmanager-add-panes-to-xamdockmanager.html[Add Panes to xamDockManager]

link:xamdockmanager-creating-a-tabbed-mdi-application.html[Creating a Tabbed MDI Application]

link:xamdockmanager-prevent-end-users-from-resizing-floating-panes.html[Prevent End Users From Resizing Floating Panes]

link:xamdockmanager-set-the-location-of-a-floating-pane.html[Set the Location of a Floating Pane]

link:xamdockmanager-set-the-initial-location-of-a-pane.html[Set the Initial Location of a Pane]

link:xamdockmanager-set-the-size-of-a-floating-pane.html[Set the Size of a Floating Pane]

link:xamdockmanager-show-the-pane-navigator-programmatically.html[Show the Pane Navigator Programmatically]

link:xamdockmanager-end-user-settings.html[End User Settings]

link:xamdockmanager-styling-xamdockmanager.html[Styling xamDockManager]