////

|metadata|
{
    "name": "xamdatacarousel",
    "controlName": ["xamDataPresenter"],
    "tags": [],
    "guid": "{0D7DF756-B06A-49C2-B796-FAEFAB858101}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:52.6298791Z"
}
|metadata|
////

= xamDataCarousel

If you're looking for an area that houses all of the overview/task-based information related to the xamDataCarousel™ control, you've come to the right place. This section contains valuable information about xamDataCarousel, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the xamDataCarousel control.

== link:xamdatacarousel-understanding-xamdatacarousel.html[About xamDataCarousel]

In this section you'll find any information that will help you to better understand the functionalities of the xamDataCarousel control, as well as why you would want to use it to as part of building your applications.

== link:xamdatacarousel-getting-started-with-xamdatacarousel.html[Adding xamDataCarousel to Your Page]

In order to get you up and running as quickly as possible with the xamDataCarousel control, we've provided you with information on how to get started using the control (e.g., adding xamDataCarousel to your form).

== link:xamdatacarousel-using-xamdatacarousel.html[Using xamDataCarousel]

This section contains information on the key features and functionalities provided by the xamDataCarousel control.

== link:xamdatacarousel-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamDataCarousel control. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.