////

|metadata|
{
    "name": "xamdata-default-editor-types-for-different-data-types",
    "controlName": ["xamDataPresenter"],
    "tags": ["Editing"],
    "guid": "{5CFAB3B1-CDE6-48D2-BE62-9D915FEE30C2}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:52.5018535Z"
}
|metadata|
////

= Default Editor Types for Different Data Types

The xamDataGrid™, xamDataCarousel™, and xamDataPresenter™ controls have default editors registered with them for particular data types. The following table shows the data type and the editor that is registered to edit it by default.

[options="header", cols="a,a"]
|====
|Data Type|Editor

|string
|xamTextEditor™

|bool
|xamCheckEditor™

|DateTime
|xamDateTimeEditor™

|decimal
|xamCurrencyEditor™

|double
|xamNumericEditor™

|float
|xamNumericEditor

|byte
|xamNumericEditor

|sbyte
|xamNumericEditor

|short
|xamNumericEditor

|ushort
|xamNumericEditor

|int
|xamNumericEditor

|uint
|xamNumericEditor

|long
|xamNumericEditor

|ulong
|xamNumericEditor

|====

