////

|metadata|
{
    "name": "xamdatapresenter-understanding-xamdatapresenter",
    "controlName": ["xamDataPresenter"],
    "tags": ["Getting Started"],
    "guid": "{E0826A54-27A4-44EC-B44E-10DBA41A4D96}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.3410213Z"
}
|metadata|
////

= About xamDataPresenter

The xamDataPresenter™ is a layout-type control which allows the visualizing of data in several different views including custom ones. It is useful when you need to change the data presentation view dynamically. The {ProductName} product provides three different views for you: link:xamdatapresenter-about-gridview.html[GridView], link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.cardview.html[CardsView], and link:xamdatapresenter-about-carouselview.html[CarouselView]; these views allow you to easily present your data in a tabular grid format or in a stylish carousel format, respectively. You can also create your own link:xamdatapresenter-creating-custom-views.html[custom view] to display your data as you see fit.

In addition to the different views, xamDataPresenter supports a wide range of features such as:

* link:xamdatapresenter-defining-layouts.html[Customizable Field Arrangement] – You can customize the layout of the link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.field.html[Fields] in GridView.
* link:xamdatapresenter-editing-data.html[Editing Data] - You can use the {ProductName} editors such as xamMaskedEditor™, xamNumericEditor™, etc in a Field for data entry.
* Heterogeneous Data - The xamDataPresenter control creates a link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fieldlayout.html[FieldLayout] for each unique Type in your data source. The resulting FieldLayouts are assigned on a link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datarecord.html[DataRecord] by DataRecord basis. This allows you to display heterogeneous data within a single "band".
* link:xamdatapresenter-sorting.html[Record Grouping] – Users can group Records based on a value in a Field, just like Microsoft® Outlook.
* Sorting – Users can sort data in any Field simply by clicking the Field's label. This feature is only available in GridView since the CarouselView does not display Field labels; however, you can still sort a Field using procedural code.
* User-resizable Fields and Records – Users can click and drag the edges of Fields and Records in GridView to resize them.

== Related Topics

link:wpf-terms-and-concepts.html[Terms and Concepts]

link:xamdata-theoryofoperation.html[Theory of Operation]

link:xamdatapresenter-about-carouselview.html[About CarouselView]

link:xamdatapresenter-about-gridview.html[About GridView]

link:xamdatapresenter-xamdatapresenters-carousel-view-composition-diagram.html[xamDataPresenter's Carousel View Composition Diagram]

link:xamdatapresenter-xamdatapresenters-grid-view-composition-diagram.html[xamDataPresenter's Grid View Composition Diagram]