////

|metadata|
{
    "name": "xamdata-deleting-records",
    "controlName": ["xamDataPresenter"],
    "tags": ["How Do I"],
    "guid": "{AC0DDC96-FAB7-4A9A-A262-99FE69E78DAA}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:52.5038539Z"
}
|metadata|
////

= Deleting Records

By default, record deletion through the UI is enabled. To disable record deletion through the UI, set the link:{ApiPlatform}datapresenter.v{ProductVersion}~infragistics.windows.datapresenter.fieldlayoutsettings.html[FieldLayoutSettings]' link:{ApiPlatform}datapresenter.v{ProductVersion}~infragistics.windows.datapresenter.fieldlayoutsettings~allowdelete.html[AllowDelete] property to False, as shown in the following example:

----
<igDP:XamDataGrid> 
        <igDP:XamDataGrid.FieldLayoutSettings> 
                <igDP:FieldLayoutSettings 
                  AllowDelete="False"/> 
        </igDP:XamDataGrid.FieldLayoutSettings> 
</igDP:XamDataGrid>
----

Support for record deletion in the UI applies to the currently selected records (see link:{ApiPlatform}datapresenter.v{ProductVersion}~infragistics.windows.datapresenter.datapresenterbase~selecteditems.html[SelectedItems]). Normally, the end user selects the records and then presses the DELETE key. By default, a confirmation message box is displayed before the records are deleted. However, this behavior can be modified by handling the link:{ApiPlatform}datapresenter.v{ProductVersion}~infragistics.windows.datapresenter.datapresenterbase~recordsdeleting_ev.html[RecordsDeleting] event.

.Note
[NOTE]
====
Record deletion is not supported by all data sources.
====