////

|metadata|
{
    "name": "xamdatapresenter-defining-layouts-grid-view",
    "controlName": ["xamDataPresenter"],
    "tags": [],
    "guid": "{93E4D6C1-54AD-4845-9360-0972E00A049D}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.1389809Z"
}
|metadata|
////

= Grid View

Click the following links to view topics written specifically to help you define layouts using the xamDataPresenter's™ Grid View.

link:xamdatagrid-about-field-moving.html[About Field Moving]

Learn about the field moving in xamDataGrid, when it is possible and how to disable it.

link:xamdatagrid-about-fixed-non-scrolling-fields.html[About Fixed (Non-Scrolling) Fields]

Learn more about the fixed fields and the flow direction influence on them.

link:xamdatagrid-changing-the-default-column-and-row-definitions.html[Changing the Default Column and Row Definitions]

Learn how to change the layout of a record by modifying the ColumnSpan and RowSpan of the fields.

link:xamdatagrid-changing-the-record-orientation.html[Changing the Record Orientation]

See how to change the records orientation and how the visual representation is changing.

link:xamdatagrid-enable-fixed-fields.html[Enable Fixed Fields]

Learn the different levels on which you can allow the end user to fix fields.

link:xamdatagrid-fix-fields.html[Fix Fields]

See how to set the location for the fixed fields.

link:xamdatapresenter-manually-assigning-a-field-layout-to-xamdatapresenter.html[Manually Assigning a Field Layout to xamDataPresenter]

A sample showing how to dynamically change the layout of xamDataPresenter while showing one and the same data.