////

|metadata|
{
    "name": "xamdiagram-user-interactions-configuration-overview",
    "tags": ["Charting","Getting Started","How Do I","Summaries"],
    "controlName": ["xamDiagram"],
    "guid": "ab1aeda3-3f6e-4277-a445-f7301aececa6",  
    "buildFlags": [],
    "createdOn": "2014-06-16T09:37:15.6243875Z"
}
|metadata|
////

= User Interactions Configuration Overview (xamDiagram)

[[_Ref391537902]]
== _xamDiagram_   User Interactions Configuration Overview

=== Purpose

This topic provides a summary of all user interaction tasks in the  _xamDiagram_™ control.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamdiagram-general-overview.html[General Overview ( _xamDiagram_ )]
|This topic provides a general overview of the _xamDiagram_ control.

|====

[[_Ref391538059]]
== User Interactions Configuration Overview

[[_Ref391538063]]

=== xamDiagram user interactions configuration summary chart

include::xamdiagram-user-interactions-configuration-summary-chart.adoc[]

[[_Ref391538068]]

=== Commands

The  _xamDiagram_   control supports a set of commands which can represent an action performed on diagram items or an interaction with the UI of the control or have some impact on its undo/redo operations history. The commands can be invoked using keyboard shortcuts, interactions with other controls, etc..

Most of the commands are associated to keyboard keys and key combinations according to the existing computing interface standards (like using Ctrl+C for copy, etc.). You can however change the keyboard shortcuts (or key combinations) by overriding them programmatically. (For details, see link:xamdiagram-configuring-keyboard-shortcuts.html[Configuring Keyboards Shortcuts]).

==== Related Topics:

* link:xamdiagram-configuring-ui-elements-with-commands.html[Configuring UI Elements with  _xamDiagram_  Commands]

[[_Ref391538072]]

=== Context menu

The diagram items of the  _xamDiagram_   control can be configured using the context menu functionality of the control. It is represented by an options pane which is opened upon diagram item’s (or items’) selection through a mouse click on the gear-like icon which then appears. By default, the context menu is disabled on the diagram.

==== Related Topics:

* link:xamdiagram-configuring-the-context-menu.html[Configuring the Context Menu ( _xamDiagram_ )]

[[_Ref391538076]]

=== Mouse interaction and tool

The  _xamDiagram_   provides a number of ways to interact with the xamDiagram using the mouse. These are configured by two properties – link:{ApiPlatform}controls.charts.xamdiagram{ApiVersion}~infragistics.controls.charts.xamdiagram~tool.html[Tool] and link:{ApiPlatform}controls.charts.xamdiagram{ApiVersion}~infragistics.controls.charts.xamdiagram~defaultdraginteraction.html[DefaultDragInteraction]. The link:{ApiPlatform}controls.charts.xamdiagram{ApiVersion}~infragistics.controls.charts.xamdiagram~tool.html[Tool] setting determines what happens when performing a click and drag in the  _xamDiagram_   surface. The following tools are available:

* Pointer
* Connector

The default is Pointer. It allows a number of interactions controlled by the link:{ApiPlatform}controls.charts.xamdiagram{ApiVersion}~infragistics.controls.charts.xamdiagram~defaultdraginteraction.html[DefaultDragInteraction] setting. The supported interactions are:

* None
* Zoom
* Pan
* Select  _(default)_  

The Connector tool allows drawing a connection by dragging over the diagram surface.

==== Related Topics:

* link:xamdiagram-configuring-the-mouse-tool-and-default-interaction.html[Configuring the Mouse Tool and Default Interaction ( _xamDiagram_ )]

[[_Ref391538082]]

=== Navigation pane

The  _xamDiagram_   control has the capability to display a reduced-size overview of its full content in a separate pane positioned inside the diagram space, by default at its bottom-right corner.

==== Related Topics:

* link:xamdiagram-configuring-the-navigation-pane.html[Configuring the Navigation Pane ( _xamDiagram_ )]

[[_Ref391538088]]

=== Selection

The  _xamDiagram_   control provides functionality enabling the both programmatic and user-interaction selection of diagram items located on its space. There are several types of selection functionality available - single, multiple, and none, which all can be configured through a property setting. By default, multiple diagram items selection is enabled.

==== Related Topics:

* link:xamdiagram-configuring-selection.html[Configuring Selection ( _xamDiagram_ )]

[[_Ref391538095]]

=== Keyboard shortcuts

The  _xamDiagram_   exposes a set of keyboard shortcuts associated with its commands. For a listing of all shortcuts refer to link:xamdiagram-general-overview.html[General Overview]. The predefined shortcuts can be changed or removed and new ones can be defined.

==== Related Topics:

* link:xamdiagram-configuring-keyboard-shortcuts.html[Configuring Keyboard Shortcuts ( _xamDiagram_ )]

[[_Ref391538100]]

=== Toolbox

The  _xamDiagram_   control provides functionality, which allows for drag-drop diagram items from a predefined set of shapes, directly on the diagram surface. This functionality is represented by the  _xamDiagramToolbox_™ control. By default, it has two preconfigured shape categories:  _Basic Shapes_   and  _Connections_   which contain all currently supported diagram node types, including a node representing a label, and the two types of diagram connections.

==== Related Topics:

* link:xamdiagram-configuring-the-toolbox.html[Configuring the Toolbox ( _xamDiagram_ )]

[[_Ref391538104]]

=== Undo/redo

The  _xamDiagram_   control provides support for undo/redo functionality by maintaining operation’s history and executing undo/redo operations.

The Infragistics Undo/Redo Framework provides the undo/redo functionality in {ProductName}.

==== Related Topics:

* link:xamdiagram-configuring-undo-redo-operations.html[Configuring Undo/Redo Operations ( _xamDiagram_ )]