////

|metadata|
{
    "name": "xamdatapresenter-optimizing-performance",
    "controlName": ["xamDataPresenter"],
    "tags": ["Performance","Tips and Tricks"],
    "guid": "{E68B2C77-15BB-486D-8204-9FAFA970990B}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.2760083Z"
}
|metadata|
////

= Optimizing xamDataPresenter's Performance

There are several tips and tricks that you can perform, giving xamDataPresenter™ the competitive edge necessary to shield your end users from unnecessary downtime.

Click the following links to view topics written specifically to help you optimize xamDataPresenter's performance.

* link:xamdata-performance-optimizations-overview.html[Performance Optimizations Overview]
* link:xamdatapresenter-hierarchical-records-and-performance.html[Hierarchical Records and Performance]
* link:xamdata-impact-styles-have-on-performance-of-controls.html[Impact Style Have on Performance of Controls]
* link:xamdatapresenter-optimizing-performance-grid-view.html[Grid View]