////

|metadata|
{
    "name": "xamdatagrid-about-fixed-non-scrolling-fields",
    "controlName": ["xamDataGrid"],
    "tags": ["How Do I"],
    "guid": "{EFCB797F-5162-4C16-A093-9B19723586A0}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:52.9729477Z"
}
|metadata|
////

= About Fixed (Non-Scrolling) Fields

The xamDataPresenter™ control and the xamDataGrid™ control allow your end users to fix fields so they are not scrolled out of view.

The fixed field feature is a robust feature that allows your end users to fix fields to the edges of xamDataPresenter or xamDataGrid with respect to the record orientation and flow direction of the control. Since the position of a fixed field is based on the record orientation and flow direction of the control, the terms "near" and "far" are used instead of left, right, top, or bottom. For example, if you have a xamDataPresenter control with a vertical record orientation, "near" refers to the left side and "far" refers to the right side of the control. If you set the record orientation to horizontal, "near" will refer to the top edge and "far" will refer to the bottom edge of the control. Finally, if you set the link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.xamdatagrid.html[FlowDirection] property of the control to RightToLeft, the previously mentioned fixed field locations will be reversed.

In order to work effectively with fixed fields, you will need to understand the following properties:

* link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fieldsettings~allowfixing.html[AllowFixing]
* link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fieldlayoutsettings~fixedfielduitype.html[FixedFieldUIType]
* link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fielditem~fixedlocation.html[FixedLocation]

== Related Topic

link:xamdatagrid-enable-fixed-fields.html[Enable Fixed Fields]

link:xamdatagrid-fix-fields.html[Fix Fields]