////

|metadata|
{
    "name": "xamdatapresenter-limit-the-number-of-fixed-records",
    "controlName": ["xamDataPresenter"],
    "tags": ["Editing","Layouts"],
    "guid": "{A4E2681D-DD9F-413C-88F1-A21459111150}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.2390009Z"
}
|metadata|
////

= Limit the Number of Fixed Records

If you allow your end users to fix records, they will be able to fix all records that are in view. However, doing so will fill the entire viewable area with fixed records, preventing unfixed records from scrolling into view. In order to prevent this scenario, you can set the link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fieldlayoutsettings.html[FieldLayoutSettings] object's link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fieldlayoutsettings~fixedrecordlimit.html[FixedRecordLimit] property to limit the number of records that your end users can fix.

The FixedRecordLimit property is not a limit on the sum of fixed records on the top and bottom of a DataPresenter control; instead, it is a limit per location. Once a location has reached the maximum number of fixed records, any subsequent records that your end users fix to that location will replace the earliest fixed record in that location (FIFO - first in, first out).

The following example code demonstrates how to limit the number of fixed records.

*In XAML:*

----
<igDP:XamDataPresenter Name="xamDataPresenter1" BindToSampleData="True">
    <igDP:XamDataPresenter.FieldLayoutSettings>
        <igDP:FieldLayoutSettings AllowRecordFixing="Top" FixedRecordLimit="3" />
    </igDP:XamDataPresenter.FieldLayoutSettings>    
</igDP:XamDataPresenter>
----

*In Visual Basic:*

----
Me.xamDataPresenter1.FieldLayoutSettings.FixedRecordLimit = 3
----

*In C#:*

----
this.xamDataPresenter1.FieldLayoutSettings.FixedRecordLimit = 3;
----

== Related Topics

link:xamdatapresenter-about-fixed-non-scrolling-records.html[About Fixed (Non-Scrolling) Records]

link:xamdatapresenter-about-fixed-records-and-sorting.html[About Fixed Records and Sorting]

link:xamdatapresenter-enable-fixed-records.html[Enable Fixed Records]

link:xamdatapresenter-fix-records.html[Fix Records]