////

|metadata|
{
    "name": "xamdatetimeeditor-about-xamdatetimeeditor",
    "controlName": ["xamDateTimeEditor"],
    "tags": ["Getting Started"],
    "guid": "{0A350874-93D1-4735-AF7B-D07F48E85A2F}",  
    "buildFlags": [],
    "createdOn": "2012-09-05T19:05:30.1439781Z"
}
|metadata|
////

= About xamDateTimeEditor

The xamDateTimeEditor™ control is a simple text box control that uses a mask to assist end users in entering dates and/or time values in the correct format. Using this mask, you can restrict the end user's input to valid date and time formats that you decide beforehand. Use the xamDateTimeEditor control either as a stand-alone editor or in a Field of the xamDataGrid™ control. As a Field in xamDataGrid, xamDateTimeEditor assists end users in data input while still keeping the proper format of a specific grid column.

link:{ApiPlatform}editors.v{ProductVersion}~infragistics.windows.editors.xammaskededitor~mask.html[Mask] property of the xamDateTimeEditor can be used to specify whether only date, only time or both the date and time are displayed and edited by the editor.