////

|metadata|
{
    "name": "xamdatapresenter-grouping",
    "controlName": ["xamDataPresenter"],
    "tags": [],
    "guid": "cb88a61a-6a89-4719-a2a2-7197736be08e",  
    "buildFlags": [],
    "createdOn": "2012-07-18T14:45:51.6443788Z"
}
|metadata|
////

= Grouping (xamDataPresenter)

Grouping is an important feature of the xamDataPresenter™ control because it can narrow the field-of-view, allowing the user to focus on the data that's important to them.

Click the following links to view topics written specifically to help you group your data using the xamDataPresenter control.

* link:xamdatapresenter-about-grouping.html[About Grouping]
* link:xamdatapresenter-change-the-location-of-the-groupbyarea.html[Change the Location of the GroupByArea]
* link:xamdatapresenter-create-an-external-group-by-area.html[Create an External Group-By Area]
* link:xamdatapresenter-disable-groupby.html[Disable GroupBy]
* link:xamdatapresenter-modify-the-group-by-area.html[Modify the Group-By Area]
* link:xamdatapresenter-sorting-and-grouping-fields-programmatically.html[Sorting and Grouping Fields Programmatically]