////

|metadata|
{
    "name": "xamdatapresenter-defining-layouts-card-view",
    "controlName": ["xamDataPresenter"],
    "tags": [],
    "guid": "{95B73374-C55E-448A-80C5-4BCD55B0EA2F}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.1339799Z"
}
|metadata|
////

= Card View

Click the following links to view topics written to help you modify CardView settings.

link:xamdatapresenter-about-card-settings.html[About Card Settings]

Learn how to modify the layout and behavior of the card view.

link:xamdatapresenter-about-card-sizing.html[About Card Sizing]

Learn how to modify the cards size or how to stretch them to take up all the available space.

link:xamdatapresenter-about-repositioning-animations.html[About Repositioning Animations]

Learn how to modify cards animation timing.

link:xamdatapresenter-collapse-a-card.html[Collapse a Card]

Learn about the different ways to collapse a card.

link:xamdatapresenter-collapse-an-empty-cell.html[Collapse an Empty Cell]

Learn about the different ways to hide an empty cell.

link:xamdatapresenter-set-the-maximum-number-of-viewable-cards.html[Set the Maximum Number of Viewable Cards]

See how to limit the maximum number of columns and rows the cards can occupy.

link:xamdatapresenter-set-the-space-between-cards.html[Set the Space Between Cards]

Describe how to change the horizontal and vertical gap between the cards.

link:xamdatapresenter-working-with-card-headers.html[Working with Card Headers]

Learn how to change the value shown in the cards header.