////

|metadata|
{
    "name": "xamdockmanager-save-an-end-users-docking-layout",
    "controlName": ["xamDockManager"],
    "tags": ["How Do I","Layouts"],
    "guid": "{B416571F-DE15-4C3F-B373-963403C98BB7}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.5230577Z"
}
|metadata|
////

= Save an End User's Docking Layout

The xamDockManager™ control allows your end users to modify the layout of your application. Your end users will expect you to save these settings so that they do not have to modify the layout when they restart your application. The xamDockManager control exposes an overloaded link:{ApiPlatform}dockmanager.v{ProductVersion}~infragistics.windows.dockmanager.xamdockmanager~savelayout.html[SaveLayout] method that you can use to save a docking layout.

You can call the SaveLayout method without a parameter to retrieve the docking layout as an XML string. This functionality is useful if you want to implement functionality that restores your application's default layout. Instead of writing your application's default layout to a Stream object, you can store the default layout as a string when your application starts up. If your end user wants to restore the default layout, you can pass the XML string to the link:{ApiPlatform}dockmanager.v{ProductVersion}~infragistics.windows.dockmanager.xamdockmanager~loadlayout.html[LoadLayout] method instead of a Stream object.

The following example code demonstrates how to save a layout.

*In Visual Basic:*

----
Imports System.IO
...
Using fs As New FileStream("layout.xml", FileMode.Create, FileAccess.Write) 
    Me.xamDockManager1.SaveLayout(fs) 
End Using
...
----

*In C#:*

----
using System.IO;
...
using (FileStream fs = new FileStream("layout.xml", FileMode.Create, FileAccess.Write))
{
    this.xamDockManager1.SaveLayout(fs);
}
...
----

== Related Topics

link:xamdockmanager-about-saving-and-loading-layouts.html[About Saving and Loading Layouts]

link:xamdockmanager-load-an-end-users-docking-layout.html[Load an End User's Docking Layout]

link:xamdockmanager-using-xamdockmanager.html[Using xamDockManager]