////

|metadata|
{
    "name": "xamdialogwindow-start-up-position-of-xamdialogwindow",
    "controlName": ["xamDialogWindow"],
    "tags": ["How Do I","Layouts"],
    "guid": "{1D869E90-BEDA-4B93-9EE9-3769AA35D2ED}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.016118Z"
}
|metadata|
////

= Start Up Position of xamDialogWindow

You can set the initial position of the xamDialogWindow control by setting the link:{ApiPlatform}controls.interactions.xamdialogwindow{ApiVersion}~infragistics.controls.interactions.xamdialogwindow~startupposition.html[StartupPosition] property to one of the following link:{ApiPlatform}controls.interactions.xamdialogwindow{ApiVersion}~infragistics.controls.interactions.startupposition.html[StartupPosition] enumeration values:

* Center – the dialog window will appear in the center of the application or container.
* Manual – manually set values for the Top and Left properties.

When the dialog window is restored to normal state, it will be restored to the last position it was at.

The following code demonstrates up to specify a start up position for the dialog window by setting the Top and Left properties.

*In XAML:*

----
<Grid x:Name="LayoutRoot" Width="600" Height="400">
   <ig:XamDialogWindow x:Name="DialogWindow" Width="200" 
       Height="200" IsModal="True" 
       StartupPosition="Manual" Top="250" Left="350">
   </ig:XamDialogWindow>
</Grid>
----

*In Visual Basic:*

----
Imports Infragistics.Controls.Interactions
…
DialogWindow.StartupPosition = StartupPosition.Manual
DialogWindow.Top = 250
DialogWindow.Left = 350
----

*In C#:*

----
using Infragistics.Controls.Interactions;
…
DialogWindow.StartupPosition = StartupPosition.Manual;
DialogWindow.Top = 250;
DialogWindow.Left = 350;
----

== Related Topics

link:xamdialogwindow-custom-cursors.html[Custom Cursors]

link:xamdialogwindow-customize-modal-dialog-window-background.html[Customize Modal Dialog Window Background]

link:xamdialogwindow-customize-the-window-header-icon.html[Customize the Window Header Icon]

link:xamdialogwindow-handle-moving-events.html[Handle Moving Events]

link:xamdialogwindow-handle-window-state-changing-events.html[Handle Window State Changing Events]

link:xamdialogwindow-keyboard-settings.html[Keyboard Settings]

link:xamdialogwindow-modal-and-modeless-dialog-windows.html[Modal and Modeless Dialog Windows]

link:xamdialogwindow-position-minimized-dialog-window.html[Position Minimized Dialog Window]

link:xamdialogwindow-set-the-dialog-windows-height-and-width-when-minimized.html[Set the Dialog Window's Height and Width When Minimized]

link:xamdialogwindow-the-xamdialogwindow-controls-behavior.html[The xamDialogWindow Control's Behavior]

link:xamdialogwindow-window-header-controls.html[Window Header Controls]