////

|metadata|
{
    "name": "xamdiagram-configuration-overview",
    "tags": ["Charting","Getting Started","How Do I","Summaries"],
    "controlName": ["xamDiagram"],
    "guid": "9d2269be-be68-4b5c-a279-502ff9d36c64",  
    "buildFlags": [],
    "createdOn": "2014-06-16T09:21:11.8798023Z"
}
|metadata|
////

= xamDiagram Configuration Overview

== Topic Overview

=== Purpose

This topic provides an overview of the configurable aspects of the  _xamDiagram_™ control.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamdiagram-general-overview.html[ _xamDiagram_ General Overview]
|This topic provides a general overview of the _xamDiagram_ control.

|====

=== In this topic

This topic contains the following sections:

* <<_Ref391537902,  _xamDiagram_  Configuration Overview >>

** <<_Ref391537908, _xamDiagram_   configuration summary>>
** <<_Ref391537913, _xamDiagram_   configuration summary chart>>
** <<_Ref391537923,Layout>>
** <<_Ref391537950,Visible portion>>

* <<_Ref391537956,  _xamDiagram_  Items Configuration Overview >>

** <<_Ref391537987, _xamDiagram_   items configuration summary chart>>
** <<_Ref391537992,Look-and-feel>>
** <<_Ref391537997,Template>>

* <<_Ref391538003,  _xamDiagram_  Nodes Configuration Overview >>

** <<_Ref391538008, _xamDiagram_   nodes configuration summary chart>>
** <<_Ref391538016,Position and size>>
** <<_Ref391538021,Shape>>
** <<_Ref391538026,Connection points>>

* <<_Ref391538037,  _xamDiagram_  Connections Configuration Overview >>

** <<_Ref391538045, _xamDiagram_   connections configuration summary chart>>
** <<_Ref391538049,Start and end>>
** <<_Ref391538053,Connection caps>>

* <<_Ref391538059,  _xamDiagram_  User Interactions Configuration Overview >>

** <<_Ref391538063, _xamDiagram user interactions configuration summary chart_  >>
** <<_Ref391538068,Commands>>
** <<_Ref391538072,Context menu>>
** <<_Ref391538076,Mouse interaction and tool>>
** <<_Ref391538082,Navigation pane>>
** <<_Ref391538088,Selection>>
** <<_Ref391538095,Keyboard shortcuts>>
** <<_Ref391538100,Toolbox>>
** <<_Ref391538104,Undo/redo>>

* <<_Ref388439099, Related Content >>

** <<_Ref386478106,Topics>>
** <<_Ref386478113,Samples>>

[[_Ref391537902]]
== _xamDiagram_   Configuration Overview

[[_Ref391537908]]

=== xamDiagram configuration summary

include::xamdiagram-configuration-summary.adoc[]

[[_Ref391537913]]

=== xamDiagram configuration summary chart

include::xamdiagram-configuration-summary-chart.adoc[]

[[_Ref391537923]]

=== Layout

If the position is not specified individually for each of the nodes a global layout algorithm can be used to layout the nodes. You can either use one of the provided layouts (force directed graph layout, tree layout, grid layout) or implement your own.

==== Related Topics:

* link:xamdiagram-configuring-the-layout.html[Configuring the Layout ( _xamDiagram_ )]

[[_Ref391537950]]

=== Visible portion

The  _xamDiagram_   control exposes a set of properties for obtaining which is the currently visible part. The  _xamDiagram_   uses a concept of three rectangles whose position and size determine the currently visible part. The link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.xamdiagram_members.html[XamDiagram] class exposes each of these rectangles as a property.

The link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.xamdiagram~viewportrect.html[ViewportRect] denotes the currently available space in the control. Margins, paddings of the control set aside, and the link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.xamdiagram~viewportrect.html[ViewportRect] have exactly the same size as the  _xamDiagram_  .

The link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.xamdiagram~worldrect.html[WorldRect] denotes the area in which there are diagram nodes and connections, that is the rectangle representing the union of all the bounds rectangles of the diagram items.

The link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.xamdiagram~windowrect.html[WindowRect] determines what part of the link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.xamdiagram~worldrect.html[WorldRect] to display in the link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.xamdiagram~viewportrect.html[ViewportRect].

==== Related Topics:

* link:xamdiagram-configuring-the-visible-portion.html[Configuring the visible portion of the Diagram ( _xamDiagram_ )]

[[_Configuring_a_Custom]]
[[_Ref388439055]]
[[_Ref386478097]]
[[_Ref391537956]]
== _xamDiagram_   Items Configuration Overview

[[_Ref391537987]]

=== xamDiagram items configuration summary chart

include::xamdiagram-items-configuration-summary-chart.adoc[]

[[_Ref391537992]]

=== Look-and-feel

The  _xamDiagram_   items expose a number of properties enabling customization of their look-and-feel.

==== Related Topics:

* link:xamdiagram-configuring-the-look-and-feel-of-diagram-items.html[Configuring the Look-and-Feel of the Diagram Items ( _xamDiagram_ )]

[[_Ref391537997]]

=== Template

Diagram items have two templates that can be applied to their content – display template and edit template. The display template defines the presentation of the content and the edit template is the template applied when editing the item’s content.

==== Related Topics:

* link:xamdiagram-configuring-the-diagram-items-content-visualization.html[Configuring the Visualization of the Content of the Diagram Items ( _xamDiagram_ )]

[[_Ref391538003]]
== _xamDiagram_   Nodes Configuration Overview

[[_Ref391538008]]

=== xamDiagram nodes configuration summary chart

include::xamdiagram-nodes-configuration-summary-chart.adoc[]

[[_Ref391538016]]

=== Position and size

The nodes of  _xamDiagram_   can be positioned either individually at any location on the diagram’s surface or by applying a layout algorithm (setting available through the link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.xamdiagram~layout.html[Layout] property. (For information about the latter approach, refer to the link:xamdiagram-configuring-the-layout.html[Configuring the Layout] topic.)

By default, if no explicit overriding has been applied, a newly created node is displayed at the point of origin of the coordinate system (0, 0).

The size of a diagram node can be controlled explicitly by setting its width and height. There is a default size which depends on its shape. (For reference on default sizes, see link:xamdiagram-visual-elements-overview.html#_Ref389665128[Nodes Default Sizes].)

==== Related Topics:

* link:xamdiagram-configuring-the-position-and-size-of-diagram-nodes.html[Configuring the Position and Size of Diagram Nodes ( _xamDiagram_ )]

[[_Ref391538021]]

=== Shape

The  _xamDiagram_   provides a number of pre-defined shapes for the nodes. (See the link:xamdiagram-general-overview.html[General Overview] topic for details.) A pre-defined shape is selected through the link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramnode~shapetype.html[ShapeType] property. This property accepts as a value the respective node shapes available as `ShapeType` enumeration. If the desired shape is not available as a pre-defined shape, a custom shape can be set to the link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramnode~geometry.html[Geometry] property.

==== Related Topics:

* link:xamdiagram-configuring-the-shape-of-diagram-nodes-overview.html[Configuring the Shape of the Diagram Nodes ( _xamDiagram_ )]

[[_Ref391538026]]

=== Connection points

Connection points are the points on a node where diagram connections can start/end. A connection point for a node is specified by a name and coordinates.

*  *Name*  – used for explicitly specifying a connection point for connection through the connection’s link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramconnection~startnodeconnectionpointname.html[DiagramConnection.StartNodeConnectionPointName]/ link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramconnection~endnodeconnectionpointname.html[DiagramConnection.EndNodeConnectionPointName] properties; therefore, all names of connection points for a node must be unique.
*  *Coordinates*  – relative to the node’s rectangle. The coordinates are in the range 0,0 (top-left) to 1,1 (bottom-right).

Each connection point is represented by a link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramconnectionpoint_members.html[DiagramConnectionPoint] object exposing link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramconnectionpoint~name.html[Name] and link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramconnectionpoint~position.html[Position] properties.

When using one of the predefined shape types set through the link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramnode~shapetype.html[DiagramNode.ShapeType] property, the node’s link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramnode~connectionpoints.html[ConnectionPoints] collection is pre-populated with a few points according to the node type. For custom node shapes, no connection points are added by default.

==== Related Topics:

* link:xamdiagram-configuring-the-connection-points-of-diagram-nodes.html[Configuring the Connection Points of Diagram Nodes ( _xamDiagram_ )]

[[_Ref391538037]]
== _xamDiagram_   Connections Configuration Overview

[[_Ref391538045]]

=== xamDiagram connections configuration summary chart

include::xamdiagram-connections-configuration-summary-chart.adoc[]

[[_Ref391538049]]

=== Start and end

There are two possible methods for configuring the start and end points of diagram connections in the  _xamDiagram_   control:

*  *Relative*  – by specifying the nodes to connect to – the start and the end node, respectively. This approach requires associating the connection with a start and end node; in this case, the start and end points of the connection are controlled by these nodes (When the node is relocated, the connection adjusts automatically.).
*  *Absolute*  – by specifying the coordinates of the connection’s start and end points on the diagram space.

A mixed approach, i.e. specifying a node at one of the ends of the connection and coordinates for the other end, is allowed, too.

==== Related Topics:

* link:xamdiagram-configuring-the-start-and-end-of-diagram-connections.html[Configuring the Start and End of Diagram Connections ( _xamDiagram_ )]

[[_Ref391538053]]

=== Connection caps

The caps of a diagram connection are the shapes that indicate its start and end. By default the start of a connection has no cap and its end is a filled arrow cap.

The  _xamDiagram_   provides a number of pre-defined shapes for the caps. (See the link:xamdiagram-visual-elements-overview.html[Visual Elements Overview ( _xamDiagram_ )] topic for details.) A pre-defined cap is selected through the link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramconnection~startcaptype.html[StartCapType]/ link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramconnection~endcaptype.html[EndCapType] properties. These properties accept as a value the respective cap shapes available as a link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramconnectioncaptype.html[DiagramConnectionCapType] enumeration. When using one of the pre-defined cap types, you can additionally specify the cap size through the link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramconnection~startcapsize.html[StartCapSize]/ link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramconnection~endcapsize.html[EndCapSize] properties.

If you need entirely custom caps, a custom `Style` with target type of link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramconnectioncappresenter_members.html[DiagramConnectionCapPresenter] can be set to the link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramconnection~startcapstyle.html[StartCapStyle]/ link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.diagramconnection~endcapstyle.html[EndCapStyle] properties. In this, style any custom `ControlTemplate` can be specified for achieving the desired look.

==== Related Topics:

* link:xamdiagram-configuring-the-caps-of-diagram-connections.html[Configuring the Caps of the Diagram Connections ( _xamDiagram_ )]

[[_Ref391538059]]
== _xamDiagram_   User Interactions Configuration Overview

[[_Ref391538063]]

=== xamDiagram user interactions configuration summary chart

include::xamdiagram-user-interactions-configuration-summary-chart.adoc[]

[[_Ref391538068]]

=== Commands

The  _xamDiagram_   control supports a set of commands which can represent an action performed on diagram items or an interaction with the UI of the control or have some impact on its undo/redo operations history. The commands can be invoked using keyboard shortcuts, interactions with other controls, etc..

Most of the commands are associated to keyboard keys and key combinations according to the existing computing interface standards (like using Ctrl+C for copy, etc.). You can however change the keyboard shortcuts (or key combinations) by overriding them programmatically. (For details, see link:xamdiagram-configuring-keyboard-shortcuts.html[Configuring Keyboards Shortcuts]).

==== Related Topics:

* link:xamdiagram-configuring-ui-elements-with-commands.html[Configuring UI Elements with  _xamDiagram_  Commands]

[[_Ref391538072]]

=== Context menu

The diagram items of the  _xamDiagram_   control can be configured using the context menu functionality of the control. It is represented by an options pane which is opened upon diagram item’s (or items’) selection through a mouse click on the gear-like icon which then appears. By default, the context menu is disabled on the diagram.

==== Related Topics:

* link:xamdiagram-configuring-the-context-menu.html[Configuring the Context Menu ( _xamDiagram_ )]

[[_Ref391538076]]

=== Mouse interaction and tool

The  _xamDiagram_   provides a number of ways to interact with the xamDiagram using the mouse. These are configured by two properties – link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.xamdiagram~tool.html[Tool] and link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.xamdiagram~defaultdraginteraction.html[DefaultDragInteraction]. The link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.xamdiagram~tool.html[Tool] setting determines what happens when performing a click and drag in the  _xamDiagram_   surface. The following tools are available:

* Pointer
* Connector

The default is Pointer. It allows a number of interactions controlled by the link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.xamdiagram~defaultdraginteraction.html[DefaultDragInteraction] setting. The supported interactions are:

* None
* Zoom
* Pan
* Select  _(default)_  

The Connector tool allows drawing a connection by dragging over the diagram surface.

==== Related Topics:

* link:xamdiagram-configuring-the-mouse-tool-and-default-interaction.html[Configuring the Mouse Tool and Default Interaction ( _xamDiagram_ )]

[[_Ref391538082]]

=== Navigation pane

The  _xamDiagram_   control has the capability to display a reduced-size overview of its full content in a separate pane positioned inside the diagram space, by default at its bottom-right corner.

==== Related Topics:

* link:xamdiagram-configuring-the-navigation-pane.html[Configuring the Navigation Pane ( _xamDiagram_ )]

[[_Ref391538088]]

=== Selection

The  _xamDiagram_   control provides functionality enabling the programmatic select of diagram items located on its space. There are several types of selection functionality available - single, multiple, and none, which all can be configured through a property setting. By default, multiple diagram items selection is enabled.

==== Related Topics:

* link:xamdiagram-configuring-selection.html[Configuring Selection ( _xamDiagram_ )]

[[_Ref391538095]]

=== Keyboard shortcuts

The  _xamDiagram_   exposes a set of keyboard shortcuts associated with its commands. For a listing of all shortcuts refer to link:xamdiagram-general-overview.html[General Overview]. The predefined shortcuts can be changed or removed and new ones can be defined.

==== Related Topics:

* link:xamdiagram-configuring-keyboard-shortcuts.html[Configuring Keyboard Shortcuts ( _xamDiagram_ )]

[[_Ref391538100]]

=== Toolbox

The  _xamDiagram_   control provides functionality, which allows for drag-drop diagram items from a predefined set of shapes, directly on the diagram surface. This functionality is represented by the  _xamDiagramToolbox_™ control. By default, it has two preconfigured shape categories:  _Basic Shapes_   and  _Connections_   which contain all currently supported diagram node types, including a node representing a label, and the two types of diagram connections.

==== Related Topics:

* link:xamdiagram-configuring-the-toolbox.html[Configuring the Toolbox ( _xamDiagram_ )]

[[_Ref391538104]]

=== Undo/redo

The  _xamDiagram_   control provides support for undo/redo functionality by maintaining operation’s history and executing undo/redo operations.

The Infragistics Undo/Redo Framework provides the undo/redo functionality in {ProductName}.

==== Related Topics:

* link:xamdiagram-configuring-undo-redo-operations.html[Configuring Undo/Redo Operations ( _xamDiagram_ )]

[[_Ref388439099]]
== Related Content

[[_Ref386478106]]

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamdiagram-configuring-nodes.html[Configuring _xamDiagram_ Nodes]
|The topics in this group explain the various configurations applicable to _xamDiagram_ nodes.

| link:xamdiagram-configuring-diagram-connections.html[Configuring _xamDiagram_ Connections]
|The topics in this group explain the various configurations applicable to _xamDiagram_ connections.

| link:xamdiagram-configuring-user-interactions.html[Configuring User Interactions ( _xamDiagram_ )]
|The topics in this group explain the various configurations applicable to user interactions in the _xamDiagram_ .

|====

[[_Ref386478113]]

=== Samples

The following sample provides additional information related to this topic.

[options="header", cols="a,a"]
|====
|Sample|Purpose

| link:{SamplesURL}/diagram/basic-configuration[Basic Configuration]
|This sample demonstrates how to create a simple flow diagram using the _xamDiagram_ .

|====