////

|metadata|
{
    "name": "xamdockmanager-about-opening-and-closing-panes",
    "controlName": ["xamDockManager"],
    "tags": ["Getting Started"],
    "guid": "{E867A904-69D6-4EB6-91CD-989515D4808F}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.4790489Z"
}
|metadata|
////

= About Opening and Closing Panes

The xamDockManager™ control allows your end user to close a pane and hide it from view. However, unlike pinning and unpinning panes, there is no way for your end user to display a closed pane unless you implement functionality to open a closed pane.

When your end user closes a pane, it is hidden by default. For the default case, you need to set the content pane's link:{ApiPlatform}dockmanager{ApiVersion}~infragistics.windows.dockmanager.contentpane.html[Visibility] property to Visible to open the closed pane. However, if you explicitly set a content pane's link:{ApiPlatform}dockmanager{ApiVersion}~infragistics.windows.dockmanager.contentpane~closeaction.html[CloseAction] property to RemovePane, xamDockManager removes the content pane from the docking layout. In order to open a removed pane, you have to re-add it to the proper split pane's link:{ApiPlatform}dockmanager{ApiVersion}~infragistics.windows.dockmanager.splitpane~panes.html[Panes collection] or tab group pane's link:{ApiPlatform}dockmanager{ApiVersion}~infragistics.windows.dockmanager.tabgrouppane.html[Items collection].

== Related Topics

link:xamdockmanager-add-content-to-a-contentpane.html[Add Content to a ContentPane]

link:xamdockmanager-add-panes-to-the-documentcontenthost-object.html[Add Panes to the DocumentContentHost Object]

link:xamdockmanager-add-panes-to-xamdockmanager.html[Add Panes to xamDockManager]

link:xamdockmanager-creating-a-tabbed-mdi-application.html[Creating a Tabbed MDI Application]

link:xamdockmanager-pin-and-unpin-a-pane.html[Pin and Unpin a Pane]

link:xamdockmanager-prevent-end-users-from-resizing-floating-panes.html[Prevent End Users From Resizing Floating Panes]

link:xamdockmanager-set-the-location-of-a-floating-pane.html[Set the Location of a Floating Pane]

link:xamdockmanager-set-the-initial-location-of-a-pane.html[Set the Initial Location of a Pane]

link:xamdockmanager-set-the-size-of-a-floating-pane.html[Set the Size of a Floating Pane]

link:xamdockmanager-show-the-pane-navigator-programmatically.html[Show the Pane Navigator Programmatically]

link:xamdockmanager-end-user-settings.html[End User Settings]

link:xamdockmanager-styling-xamdockmanager.html[Styling xamDockManager]