////

|metadata|
{
    "name": "xamdiagram-configuring- undo-redo-operations",
    "tags": ["Charting","Commands","How Do I"],
    "controlName": ["xamDiagram"],
    "guid": "7367ae03-d272-459c-89c4-2f681ac328d7",  
    "buildFlags": [],
    "createdOn": "2014-06-16T09:41:18.056078Z"
}
|metadata|
////

= Configuring Undo/Redo Operations (xamDiagram)

== Topic Overview

=== Purpose

This topic explains how to configure the Undo/Redo operations in the  _xamDiagram_™ control. The topic covers configuring an Undo/Redo Manager that is exclusive for  _xamDiagram_ . If you prefer to configure a manager that is shared across the controls in your application, refer to link:undo-redo-framework.html[Infragistics® Undo/Redo Framework].

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamdiagram-general-overview.html[General Overview ( _xamDiagram_ )]
|This topic provides a conceptual overview of the _xamDiagram_ control and its main features and capabilities.

| link:xamdiagram-adding-to-a-page.html[Adding _xamDiagram_ to a Page]
|This topic explains how to add the _xamDiagram_ control to a WPF application.

| link:undo-redo-framework.html[Infragistics Undo/Redo Framework]
|This topic provides an overview of the _Infragistics Undo/Redo Framework_™ and provides links to some more detailed topics about the undo/redo functionality.

|====

=== In this topic

This topic contains the following sections:

* <<_Ref389574920, Introduction >>
* <<_Ref386642731, Enabling/Disabling the Undo/Redo Functionality >>

** <<_Ref385408417,Overview>>
** <<_Ref385408421,Property settings>>

* <<_Ref386630199, Clearing the Undo/Redo History >>

** <<_Ref385408401,Overview>>
** <<_PropertySettings,Property settings>>

* <<_Ref386642762, Related Content >>

** <<_Ref385408435,Topics>>
** <<_Ref385408439,Samples>>

[[_Ref389574920]]
[[_Ref385408414]]
== Introduction

[[_Ref386630190]]

=== xamDiagram Undo/Redo functionality summary

The  _xamDiagram_   control provides support for undo/redo functionality by maintaining operations history and executing undo/redo operations.

The undo/redo functionality in {ProductName} is provided via the link:undo-redo-framework.html[Infragistics Undo/Redo Framework]. It is a cross-platform framework and allows for commands-controlled invoking of the undo/redo operations from the UI.

The diagram uses its own instance of the link:{ApiPlatform}undo.v{ProductVersion}~infragistics.undo.undomanager_members.html[UndoManager] class (part of the  _Infragistics Undo/Redo Framework_  ) which allows for independent undo/redo history processing. This is the use case covered in detail in this help topic. The alternative approach is to use an external instance of the `UndoManager` in order to support shared history across the application.

By default, undo/redo operations are enabled on  _xamDiagram_   and can be triggered by user key combinations (Ctrl+Z for undo and Ctrl+Y for redo) or by explicit commands invoking. By default, there is no limit to the number of operations stored in the undo/redo stack, but this number can be controlled via property setting of the link:{ApiPlatform}undo.v{ProductVersion}~infragistics.undo.undomanager_members.html[UndoManager] class.

[[_Ref386642731]]
== Enabling/Disabling the Undo/Redo Functionality

[[_Ref385408417]]

=== Overview

To enable or disable undo/redo operations in the  _xamDiagram_   control, use its link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.xamdiagram~isundoenabled.html[IsUndoEnabled] property. Setting the value of the property to  _“False”_   also clears the current history.

[[_Ref385408421]]

=== Property settings

The following table maps the desired behavior to the property settings that manage it.

[options="header", cols="a,a,a"]
|====
|In order to:|Use this property:|And set it to:

|Enable undo/redo operations on the diagram
| link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.xamdiagram~isundoenabled.html[IsUndoEnabled]
|_“True”_

|Disable undo/redo operations on the diagram
| link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.xamdiagram~isundoenabled.html[IsUndoEnabled]
| _“False”_ 

|====

[[_Ref386630199]]
[[_Ref385408430]]
== Clearing the Undo/Redo History

[[_Ref385408401]]

=== Overview

To clear the current operations history of the  _xamDiagram_   control, call its link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.xamdiagram~clearundoredohistory.html[ClearUndoRedoHistory()] method. Invoking the method results in clearing the current undo/redo history for the diagram only. (If an external instance of link:{ApiPlatform}undo.v{ProductVersion}~infragistics.undo.undomanager_members.html[UndoManager] has been created, the history for the other controls managed by it will not be affected.)

[[_PropertySettings]]

=== Property settings

The following table maps the desired behavior to the property settings that manage it.

[options="header", cols="a,a"]
|====
|In order to:|Use this method:

|Clear the undo/redo history of the diagram
| link:{ApiPlatform}controls.charts.xamdiagram.v{ProductVersion}~infragistics.controls.charts.xamdiagram~clearundoredohistory.html[XamDiagram.ClearUndoRedoHistory()]

|====

[[_Ref386642762]]
== Related Content

[[_Ref385408435]]

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamdiagram-user-interactions-configuration-overview.html[User Interactions Configuration Overview ( _xamDiagram_ )]
|This topic provides a summary of all user interaction tasks in the _xamDiagram_ control.

| link:xamdiagram-commands-overview.html[Commands Overview ( _xamDiagram_ )]
|This topic explains the operational logic of the commands available in the _xamDiagram_ control.

| link:xamdiagram-configuring-ui-elements-with-commands.html[Configuring UI Elements with _xamDiagram_ Commands]
|This topic explains how to use the commands provided by _xamDiagram_ in UI element controls such as menus and buttons.

| link:xamdiagram-configuring-keyboard-shortcuts.html[Configuring Keyboard Shortcuts ( _xamDiagram_ )]
|This topic explains how to change the keyboard shortcuts associated with _xamDiagram_ commands.

| link:undo-redo-framework-methods-and-properties-reference-by-task.html[Undo/Redo Framework Methods and Properties Reference]
|This is a group of topics containing reference information about the Infragistics Undo\Redo Framework key methods and properties. The topics included cover the reference information about the major framework classes and reference information based on the task you want to achieve with the Undo\Redo API.

|====

[[_Ref385408439]]

=== Samples

The following samples provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Sample|Purpose

| link:{SamplesURL}/diagram/diagram-commands[Diagram Commands]
|This sample demonstrates the commands available in the _xamDiagram_ control.

|====