////

|metadata|
{
    "name": "xamdatapresenter-editing-data",
    "controlName": ["xamDataPresenter"],
    "tags": ["Editing"],
    "guid": "{3D046855-54E7-403B-A11A-B1208AFE0263}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.1599851Z"
}
|metadata|
////

= Editing Data (xamDataPresenter)

Occasionally, you might use a database purely for informational purposes, never modifying the data. However, when this is not the case, you need a dependable and easy way for the end user to modify data. These modifications might include adding, updating, or deleting data, all of which are tasks that the xamDataPresenter™ control performs by default.

The xamDataPresenter control displays several views of the underlying data source. The xamDataPresenter control can also manipulate the data source through several convenient methods, allowing you to give your end users the ease of use they've become accustomed to.

Click the following links to view topics written specifically to help you edit data using the xamDataPresenter control.

link:xamdata-about-xamdatapresenter-and-xameditors.html[About xamDataPresenter and xamEditors]

Learn about the default editors used by the xamDataPresenter and how you can register your own editors.

link:xamdatapresenter-conf-editing.html[Configuring Editing Behavior (xamDataPresenter)]

This topic explains how to customize the control's editing behavior.

link:xamdatapresenter-about-the-datavaluechanged-event.html[About the DataValueChanged Event]

Learn when the DataValueChanged event is raised and how you can interact with the date it provides.

link:xamdatapresenter-enable-data-value-change-tracking.html[Enable Data-Value Change Tracking]

Discover how to receive data value changed events from fields in the view and not in the view.

link:xamdatapresenter-reset-a-cells-value-history.html[Reset a Cell's Value History]

Learn how to operate with the value history of a cell or reset it.

link:xamdatapresenter-accessing-cell-values-in-the-active-record.html[Accessing Cell Values in the Active Record]

Learn how to bind the value of a cell from the active record to a TextBox control.

link:xamdatapresenter-accessing-cell-values-in-the-recordactivated-event.html[Accessing Cell Values in the RecordActivated Event]

An example showing how to access cell data when a RecordActivated event is fired.

link:xamdatapresenter-configuring-readonly-fields-disabling-cells.html[Configuring Read-only Fields and Disabling Field’s Cells]

This topic describes how to disable a particular field’s cells and how to set a field to be read-only in the xamDataPresenter controls.

link:xamdata-changing-field-record-cell-selection-behavior.html[Changing Field, Record, or Cell Selection Behavior]

Learn about the different selection types used in xamDataPresenter.

link:xamdata-default-editor-types-for-different-data-types.html[Default Editor Types for Different Data Types]

List of the default editors used for different data types.

link:xamdatapresenter-embedding-a-custom-control-in-a-field.html[Embedding a Custom Control in a Field]

A sample showing how to modify the CellValuePresenter object's template to show cell value in a custom control.

link:xamdatapresenter-embedding-a-xameditor-in-a-field.html[Embedding a xamEditor in a Field]

A sample showing how to change the default editor on a cell.

link:xamdatapresenter-validating-data.html[Data Validation Overview]

Learn about data validation and how to display error notifications to the end user.

link:xamdatapresenter-acessing-data-carousel-view.html[Carousel View]

Learn specific information about data editing in the Carousel View control.

link:xamdatapresenter-accessing-data-grid-view.html[Grid View]

Learn specific information about data editing in the Grid View control.