////

|metadata|
{
    "name": "xamdatapresenter-navigating-and-selecting",
    "controlName": ["xamDataPresenter"],
    "tags": ["Navigation","Selection"],
    "guid": "{2A36B111-672C-4CC3-90DC-CAE453F98B2E}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.2710073Z"
}
|metadata|
////

= Navigating and Selecting (xamDataPresenter)

The keyboard and mouse are standard peripherals of personal computers everywhere. Using these peripherals quickly is the key to every end user's computing experience. You can take advantage of that experience by allowing end users to navigate through data in a grid, nodes in a tree, or items in a list with specific keys on the keyboard. You can even control which items are selected when the user clicks a mouse button or scrolls the mouse wheel.

The xamDataPresenter™ control's object model contains the necessary tools to allow your end users to navigate completely by keyboard if they want to. Mouse event handling is also a standard feature of xamDataPresenter, giving your end users the familiar point-and-click experience.

Click the following links to view topics written specifically to help you implement navigation and selection in your application using the xamDataPresenter control.

* link:xamdata-selection-overview.html[Selection Overview]
* link:xamdata-accessing-records-through-the-recordmanager.html[Accessing Records Through the RecordManager]
* link:xamdata-changing-field-record-cell-selection-behavior.html[Changing Field, Records, or Cell Selection Behavior]
* link:xamdatapresenter-keyboard-navigation-in-xamdatapresenter.html[Keyboard Navigation in xamDataPresenter]
* link:xamdatapresenter-configuring-custom-tab-navigation.html[Configuring Custom Tab Navigation]
* link:xamdata-using-data-presenter-family-commands.html[Using Data Presenter Family Commands]
* link:xamdatapresenter-selected-data-items.html[Working with Selected Data Items]