////

|metadata|
{
    "name": "xamdatagrid-conf-editing",
    "tags": ["Editing"],
    "controlName": ["xamDataGrid"],
    "guid": "bc232cd5-62e6-441a-9a6f-ac35912a0813",  
    "buildFlags": [],
    "createdOn": "2015-11-19T10:53:44.4939568Z"
}
|metadata|
////

= Configuring Editing Behavior (xamDataGrid)

== Topic Overview

=== Purpose

This topic explains how to customize the control’s editing behavior.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamdatagrid-understanding-xamdatagrid.html[About xamDataGrid]
|This is a group of topics providing an overview of the xamDataGrid control.

|====

== Editing Configuration Summary

=== Editing configuration summary

The data presenter family of controls allows you to configure some aspects of the editing behavior such as:

* allowing the user to edit cell values
* allowing the user to enter cell’s editing mode by start typing when a cell is active

=== Editing configuration summary chart

The following table explains briefly the configurable aspects of the  _xamDataPresenter’s_   editing feature and maps them to the properties that configure them. These properties are available at the link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datapresenterbase~fieldsettings.html[FieldSettings] object of the control.

[options="header", cols="a,a,a"]
|====
|Configurable Aspect|Details|Properties

|[[_Hlk356484826]] 

Enable / disable cell’s editing
|By default the editing mode is enabled, but you can disable it by setting this property to `false`. 

.Note 

[NOTE] 

==== 

Editing will not be possible if the control is bound to a data source which does not support editing. 

====
| link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fieldsettings~allowedit.html[AllowEdit]

|Enter cell's editing mode on keypress
|You can allow the user to enter editing mode automatically when a cell is activated and the user enters text or presses the space or backspace keys.
| link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.fieldsettings~isautoeditmodeenabled.html[IsAutoEditModeEnabled]

|====

== Related Content

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamdatagrid-editing-data.html[Editing Data (xamDataGrid)]
|This is a group of topics explaining how to define and customize field editors in the xamDataGrid.

|====

=== Samples

The following samples provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Sample|Purpose

| link:{SamplesURL}/data-grid/editing[Editing]
|This sample demonstrates how you can customize the editing behavior of the control.

|====