////

|metadata|
{
    "name": "xamdatatree",
    "controlName": ["xamDataTree"],
    "tags": [],
    "guid": "d1974f1d-3a76-4d3e-88ec-6ac879b55c1d",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:54.8311002Z"
}
|metadata|
////

= xamDataTree

This section gives you an overview of the use of xamDataTree™. This section contains valuable information about xamDataTree, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish common tasks using the control. Click the links below to access important information about the xamDataTree control.

== link:xamdatatree-about-xamdatatree.html[About xamDataTree]

In this section you’ll find any information that will help you to better understand the functionalities of the xamDataTree control, as well as why you would want to use it as part of building your applications.

== link:xamdatatree-adding-xamdatatree-to-your-page.html[Adding xamDataTree to Your Page]

In order to get you up and running as quickly as possible with the xamDataTree control, we've provided you with information on how to get started using the control.

== link:xamdatatree-xamdatatree-data-binding.html[Binding xamDataTree to Data]

In order to get you up and running as quickly as possible with the xamDataTree control, we've provided you with information on how to bind the control to data.

== link:xamdatatree-using-xamdatatree.html[Configuring xamDataTree]

This section contains information on the key features and functionalities provided by the xamDataTree control.

== link:xamdatatree-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamDataTree control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the {ProductName} help.