////

|metadata|
{
    "name": "xamdialogwindow-keyboard-settings",
    "controlName": ["xamDialogWindow"],
    "tags": ["How Do I","Navigation"],
    "guid": "{5C83D298-BE50-487C-97D0-56BAFE037FDA}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:54.9921483Z"
}
|metadata|
////

= Keyboard Settings

You can enable keyboard navigation on the xamDialogWindow™ control. This allows your end users to move the dialog window using the arrows keys.

You can set how many pixels the dialog window will move by setting the link:{ApiPlatform}controls.interactions.xamdialogwindow.v{ProductVersion}~infragistics.controls.interactions.keyboardsettings.html[KeyboardSettings] object’s link:{ApiPlatform}controls.interactions.xamdialogwindow.v{ProductVersion}~infragistics.controls.interactions.keyboardsettings~horizontalstep.html[HorizontalStep] and link:{ApiPlatform}controls.interactions.xamdialogwindow.v{ProductVersion}~infragistics.controls.interactions.keyboardsettings~verticalstep.html[VerticalStep] properties, as demonstrated in the following code snippet.

*In XAML:*

----
<Grid x:Name="LayoutRoot" Background="White">
   <ig:XamDialogWindow x:Name="DialogWindow" Width="200" 
                   Height="200" IsModal="True">
      <ig:XamDialogWindow.KeyboardSettings>
         <ig:KeyboardSettings AllowKeyboardNavigation="True" 
                                VerticalStep="25" HorizontalStep="25">
         </ig:KeyboardSettings>
      </ig:XamDialogWindow.KeyboardSettings>
   </ig:XamDialogWindow>
</Grid>
----

*In Visual Basic:*

----
Imports Infragistics.Controls.Interactions
...
DialogWindow.KeyboardSettings.AllowKeyboardNavigation = True
DialogWindow.KeyboardSettings.VerticalStep = 25
DialogWindow.KeyboardSettings.HorizontalStep = 25
----

*In C#:*

----
using Infragistics.Controls.Interactions;
...
DialogWindow.KeyboardSettings.AllowKeyboardNavigation = true;
DialogWindow.KeyboardSettings.VerticalStep = 25;
DialogWindow.KeyboardSettings.HorizontalStep = 25;
----

== Related Topics

link:xamdialogwindow-custom-cursors.html[Custom Cursors]

link:xamdialogwindow-customize-modal-dialog-window-background.html[Customize Modal Dialog Window Background]

link:xamdialogwindow-customize-the-window-header-icon.html[Customize the Window Header Icon]

link:xamdialogwindow-handle-moving-events.html[Handle Moving Events]

link:xamdialogwindow-handle-window-state-changing-events.html[Handle Window State Changing Events]

link:xamdialogwindow-modal-and-modeless-dialog-windows.html[Modal and Modeless Dialog Windows]

link:xamdialogwindow-position-minimized-dialog-window.html[Position Minimized Dialog Window]

link:xamdialogwindow-set-the-dialog-windows-height-and-width-when-minimized.html[Set the Dialog Window's Height and Width When Minimized]

link:xamdialogwindow-start-up-position-of-xamdialogwindow.html[Start Up Position of xamDialogWindow]

link:xamdialogwindow-the-xamdialogwindow-controls-behavior.html[The xamDialogWindow Control's Behavior]

link:xamdialogwindow-window-header-controls.html[Window Header Controls]