////

|metadata|
{
    "name": "xamdatapresenter-selected-data-items",
    "tags": ["Editing","How Do I","Selection"],
    "controlName": ["xamDataPresenter"],
    "guid": "1e15e9af-6f5c-437a-ab98-9ab80d47c3cd",  
    "buildFlags": [],
    "createdOn": "2014-03-25T14:10:05.056959Z"
}
|metadata|
////

= Working with Selected Data Items (xamDataPresenter)

== Topic Overview

=== Purpose

This topic explains how to access the  _xamDataPresenter’s_   selected items.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamdatapresenter-understanding-xamdatapresenter.html[About xamDataPresenter]
|This topic introduces the _xamDataPresenter_ control and various elements, on which control is composed.

| link:xamdata-selection-overview.html[Selection Overview]
|This topic provides overview information about the selection of the data presenter’s cells, rows and fields.

|====

=== In this topic

This topic contains the following sections:

* <<_Ref380068372,Introduction>>
* <<_Ref380068382,Selection Scope Configuration Summary>>
* <<_Ref380068388,Related Content>>

[[_Ref380068372]]

== Introduction

=== Selected data items summary

The link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datapresenterbase~selecteddataitems.html[SelectedDataItems] property of the  _xamDataPresenter_   allows you to set or obtain an array of the currently selected items. You can bind to this property and operate with  _xamDataPresenter_   selection while creating MVVM design pattern applications.

.Note
[NOTE]
====
The items in the `SelectedDataItems` array are the actual data items from the underlying data source.
====

This property is exposed so that applications can “two-way” bind to it (which is its default binding mode) to select the associated `DataRecords` and/or be notified when the user selects cells and/or records. This behavior is determined by the link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datapresenterbase~selecteddataitemsscope.html[SelectedDataItemsScope] property which is explained below.

[[_Ref380068382]]
== Selection Scope Configuration Summary

=== Selection configuration summary chart

[options="header", cols="a,a"]
|====
|*Task*|* Value*

|The user selection not to have any impact on the `SelectedDataItems` property.
| link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datapresenterbase~selecteddataitemsscope.html[None] (default)

|The user record selection only to be included in the `SelectedDataItems` property.
| link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datapresenterbase~selecteddataitemsscope.html[RecordsOnly]

|The user record or cell selection to be included in the `SelectedDataItems` property. 

.Note 

[NOTE] 

==== 

Each time the user switches between record selection and cell selection this will clear the previous selected items and begin new selection. 

====
| link:{ApiPlatform}datapresenter{ApiVersion}~infragistics.windows.datapresenter.datapresenterbase~selecteddataitemsscope.html[RecordsOrCells]

|====

.Note
[NOTE]
====
If the `SelectedDataItemsScope` property is changed from its default value of `None` then every time the user changes selection the `SelectedDataItems` property will be set to a new array of data items based on the behavior described in the above table.
====

[[_Ref380068388]]
== Related Content

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamdatapresenter-define-a-field-layout.html[Define a Field Layout]
|This topic explains how to define and configure field’s presentation in the control.

|====

=== Samples

The following samples provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Sample|Purpose

| link:{SamplesURL}/data-grid/selecteddataitems[SelectedDataItems]
|This sample demonstrates the `SelectedDataItems` property of the _xamDataGrid_ which allows the user to get or set the selected items of the grid.

|====