////

|metadata|
{
    "name": "xamdialogwindow-set-the-dialog-windows-height-and-width-when-minimized",
    "controlName": ["xamDialogWindow"],
    "tags": ["Editing","How Do I"],
    "guid": "{9FDC7E26-0245-43B9-AAA6-5B0170C1CEFC}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.0101185Z"
}
|metadata|
////

= Set the Dialog Window's Height and Width When Minimized

When your end users minimize the dialog window the following happens:

* the header’s width decreases
* the content pane disappears

However, you can customize this by setting the xamDialogWindow control’s link:{ApiPlatform}controls.interactions.xamdialogwindow.v{ProductVersion}~infragistics.controls.interactions.xamdialogwindow~minimizedwidth.html[MinimizedWidth] and link:{ApiPlatform}controls.interactions.xamdialogwindow.v{ProductVersion}~infragistics.controls.interactions.xamdialogwindow~minimizedheight.html[MinimizedHeight] properties.

The following code demonstrates how to set the minimized dialog window's height and width.

*In XAML:*

----
<Grid x:Name="LayoutRoot" Background="White">
   <ig:XamDialogWindow Content="Dialog Window" 
                 x:Name="DialogWindow" Width="200" 
                 Height="200" MinimizedHeight="30"
                 MinimizedWidth="30"/>
</Grid>
----

*In Visual Basic:*

----
DialogWindow.MinimizedHeight = 30
DialogWindow.MinimizedWidth = 30
----

*In C#:*

----
DialogWindow.MinimizedHeight = 30;
DialogWindow.MinimizedWidth = 30;
----

== Related Topics

link:xamdialogwindow-custom-cursors.html[Custom Cursors]

link:xamdialogwindow-customize-modal-dialog-window-background.html[Customize Modal Dialog Window Background]

link:xamdialogwindow-customize-the-window-header-icon.html[Customize the Window Header Icon]

link:xamdialogwindow-handle-moving-events.html[Handle Moving Events]

link:xamdialogwindow-handle-window-state-changing-events.html[Handle Window State Changing Events]

link:xamdialogwindow-keyboard-settings.html[Keyboard Settings]

link:xamdialogwindow-modal-and-modeless-dialog-windows.html[Modal and Modeless Dialog Windows]

link:xamdialogwindow-position-minimized-dialog-window.html[Position Minimized Dialog Window]

link:xamdialogwindow-start-up-position-of-xamdialogwindow.html[Start Up Position of xamDialogWindow]

link:xamdialogwindow-the-xamdialogwindow-controls-behavior.html[The xamDialogWindow Control's Behavior]

link:xamdialogwindow-window-header-controls.html[Window Header Controls]