////

|metadata|
{
    "name": "xamdatapresenter-how-to-use-your-custom-view-with-xamdatapresenter",
    "controlName": ["xamDataPresenter"],
    "tags": ["How Do I","Layouts"],
    "guid": "{D5FD45E5-367F-4D4F-8707-83341DF33829}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.2309993Z"
}
|metadata|
////

= How to Use Your Custom View with xamDataPresenter

To use your Custom View with xamDataPresenter™, simply set the XamDataPresenter.View property to an instance of your View. It's that simple.

If the developer is editing a project in Microsoft® Expression® Blend that contains a xamDataPresenter, and the project also contains a reference to the assembly that contains your Custom View, when the developer clicks New in the Blend Properties Panel (within the entry for the XamDataPresenter.View property), a dialog box will open, asking what kind of View needs to be created. In addition to the built-in GridView and CarouselView, the list will also contain an entry for your Custom View.

== Related Topics

link:xamdatapresenter-how-to-create-a-basic-custom-view.html[How to Create a Basic Custom View]

link:xamdatapresenter-services-provided-by-the-xamdatapresenter.html[Services Provided by the XamDataPresenter]

link:xamdatapresenter-creating-the-custom-view-class-and-layout-panel.html[Creating the Custom View Class and Layout Panel]