////

|metadata|
{
    "name": "xameditors-working-with-the-isalwaysineditmode-property-and-the-editors",
    "controlName": [],
    "tags": ["Editing"],
    "guid": "{9AD315AE-C6C3-4EBF-984B-5A1BBC79BA3B}",  
    "buildFlags": [],
    "createdOn": "2012-09-05T19:05:30.1869781Z"
}
|metadata|
////

= Working with the IsAlwaysInEditMode Property and the Editors

The {ProductName} editor's link:{ApiPlatform}editors{ApiVersion}~infragistics.windows.editors.valueeditor~isalwaysineditmode.html[IsAlwaysInEditMode] property defaults to True; however, the IsAlwaysInEditMode property is ignored when the editor is embedded in another control (i.e., ValuePresenter for a xamDataGrid™, xamDataCarousel™, xamDataPresenter™). Therefore, when the control is loaded, the editor enters edit mode and remains in edit mode even when it loses focus.

When the IsAlwaysInEditMode property is set to False, or the editor is hosted inside another control, it enters edit mode when it receives focus and exits edit mode when it loses focus. The exception to this rule is when an editor contains an invalid value and the link:{ApiPlatform}editors{ApiVersion}~infragistics.windows.editors.valueeditor~invalidvaluebehavior.html[InvalidValueBehavior] property is set to RetainValue. In this case, the editor remains in edit mode since the editor can not have an invalid value while not in edit mode. In addition, when the IsAlwaysInEditMode is set to False, the following four events are raised:

* link:{ApiPlatform}editors{ApiVersion}~infragistics.windows.editors.valueeditor~editmodestarting_ev.html[EditModeStarting]
* link:{ApiPlatform}editors{ApiVersion}~infragistics.windows.editors.valueeditor~editmodestarted_ev.html[EditModeStarted]
* link:{ApiPlatform}editors{ApiVersion}~infragistics.windows.editors.valueeditor~editmodeending_ev.html[EditModeEnding]
* link:{ApiPlatform}editors{ApiVersion}~infragistics.windows.editors.valueeditor~editmodeended_ev.html[EditModeEnded]