////

|metadata|
{
    "name": "xamformulaeditor",
    "controlName": ["xamFormulaEditor"],
    "tags": ["Calculations"],
    "guid": "b1f7e499-5707-4da9-a6cd-c50662e26327",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.0721514Z"
}
|metadata|
////

= xamFormulaEditor

This section provides links to content on the xamFormulaEditor™ control. Content ranges from explaining what the control does, why you would want to use it in your application to step-by-step procedures on how to accomplish common tasks using the control.

The information you need about the xamFormulaEditor control is covered in the following topics:

* link:xamformulaeditor-about.html[About xamFormulaEditor]
* link:xamformulaeditor-contextualhelp.html[Contextual Help]
* link:xamformulaeditor-using.html[Using xamFormulaEditor and FormulaEditorDialog with xamCalculationManager]
* link:xamformulaeditor-api-overview.html[API Overview]

== Related Topics

Following are some other topics you may find useful. 

* link:xamcalculationmanager.html[Getting Started with xamCalculationManager]
* link:xamcalculationmanager-using-xamcalculationmanager.html[Using xamCalculationManager]