////

|metadata|
{
    "name": "xamgrid-define-column-layout",
    "controlName": ["xamGrid"],
    "tags": ["Data Presentation","Grids","Layouts"],
    "guid": "{E0C05436-BCA5-4D56-8CF2-B5AF4A572A49}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.8771978Z"
}
|metadata|
////

= Define Column Layout

The xamGrid™ uses a concept called Column Layouts to determine what columns are shown, and how those columns are positioned. You can define one or more link:{ApiPlatform}controls.grids.xamgrid.v{ProductVersion}~infragistics.controls.grids.columnlayout.html[ColumnLayout] objects within the grid, allowing you to display hierarchical data structures. Each column layout is generally independent from any other defined in xamGrid.

*Related Topics*

link:xamgrid-auto-generate-columns.html[Auto Generate Columns]

link:xamgrid-defining-a-self-related-hierarchical-structure.html[Defining a Self Related Hierarchical Structure]

link:xamgrid-defining-hierarchical-layouts.html[Defining Hierarchical Layouts]

link:xamgrid-defining-unstructured-column-layout-collections.html[Defining Unstructured Column Layout Collections]

link:xamgrid-manually-defining-a-basic-column-structure.html[Manually Defining a Basic Column Structure]

link:xamgrid-targettypename-resolution.html[TargetTypeName Resolution]