////

|metadata|
{
    "name": "xamgantt-project-related-features",
    "controlName": ["xamGantt"],
    "tags": ["Data Presentation","How Do I","Scheduling"],
    "guid": "0ee85394-e8f0-4335-9522-0e28ceb16842",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.3981315Z"
}
|metadata|
////

= Project-Related Features

== Topic Overview

=== Purpose

This topic gives an overview of the major project-related features available using the  _xamGantt™_   control.

=== In this topic

This topic contains the following sections:

* <<_Ref335179586, Main Features Summary >>
* <<_Ref335758963, Project Calculation >>
* <<_Ref335759017, Project Critical Path Calculation >>
* <<_Ref335759372, Project Scheduling From Start or Finish Date >>
* <<_Ref335401312, Related Content >>

[[_Ref335179586]]
== Main Features Summary

=== Main features summary chart

The following table summarizes the  _xamGantt_   control’s main project-related features. Additional details follow later in this topic.

[options="header", cols="a,a"]
|====
|Feature|Description

|<<_Ref335758963,Project Calculation>>
|The _xamGantt_ control provides either automatic or manual re-calculation of the project when changes occur.

|<<_Ref335759017,Project Critical Path Calculation>>
|The _xamGantt_ control provides functionality for project critical path calculation.

|<<_Ref335759372,Project Scheduling From Start or Finish Date>>
|The _xamGantt_ control provides functionality for scheduling the project from its start or finish date.

|====

[[_Ref335758963]]
== Project Calculation

=== Project calculation

As in the Microsoft Project, the  _xamGantt_   control provides functionality for calculating the project after each edit and keeping the project and task data up-to-date.

The  _xamGantt_   control’s built-in scheduling engine provides much of the same scheduling functionality found in the Microsoft Project.

The engine performs:

* intra-task updates – updating the related properties within a task when modifying a task property
* inter-task updates – updating the related predecessor/successors tasks as well as ancestors and descendants.

By default, the scheduling engine performs the project re-calculation after each edit, but this is a configurable feature and can be set to trigger project calculations explicitly.

==== Related Topics:

* link:xamgantt-calculating-explicitly-a-project.html[Calculating Explicitly a Project]

[[_Ref335759017]]
== Project Critical Path Calculation

=== Project critical path calculation

As in the Microsoft Project, the  _xamGantt_   control provides functionality for project critical path calculations.

The project critical path consists of tasks that are critical for the calculated project’s start or finish date. By definition, a task is critical if delaying it results in violating a deadline or constraint or increasing the project’s duration.

Using the  _xamGantt_   control:

* you can highlight either single or multiple critical paths
* configure the tasks’ critical slack limit

==== Related Topics:

* link:xamgantt-configuring-critical-slack-limit.html[Configuring Critical Slack Limit]

[[_Ref335759372]]
== Project Scheduling From Start or Finish Date

=== Project scheduling from start or finish date

As in the Microsoft Project, the  _xamGantt_   control provides project scheduling functionality from a project’s start or finish date.

This means that updates to the project tasks’ start and finish dates occur according to the project’s start or finish date.

* For a project scheduled from its start date, the scheduling engine uses the start date as a starting point to calculate the project finish date.
* For a project scheduled from its finish date, the scheduling engine uses the finish date as a starting point to calculate the project start date.

==== Related Topics:

* link:xamgantt-scheduling-project-from-start-or-finish-date.html[Scheduling a Project from Start or Finish Date]

[[_Ref335401312]]
== Related Content

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamgantt-task-related-features.html[Task-Related Features]
|This topic gives an overview of the major task-related features available using the _xamGantt_ control.

| link:xamgantt-other-features.html[Other xamGantt Features]
|This topic gives an overview of some of the major features available using the _xamGantt_ control.

|====