////

|metadata|
{
    "name": "xamgrid-fixed-column-events",
    "controlName": ["xamGrid"],
    "tags": ["Events","Grids","How Do I","Layouts"],
    "guid": "{BCBCC614-B405-4704-A46F-465B71E4BF60}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.7811924Z"
}
|metadata|
////

= Fixed Column Events

There are two events associated with fixed columns in xamGrid™. These events have the suffix “ing” or “ed” appended to them, reflecting the order in which they occur. The fixed column events allow you to perform some custom business logic before or after a column’s fixed state is changed.

* link:{ApiPlatform}controls.grids.xamgrid.v{ProductVersion}~infragistics.controls.grids.xamgrid~columnfixedstatechanging_ev.html[ColumnFixedStateChanging] Event – The moment right before a column’s fixed state is changed, the ColumnFixedStateChanging event fires.
* link:{ApiPlatform}controls.grids.xamgrid.v{ProductVersion}~infragistics.controls.grids.xamgrid~columnfixedstatechanged_ev.html[ColumnFixedStateChanged] Event – This event fires after the column’s fixed state is changed.

These events allow you to control how your end users interact with the fixed columns feature of the xamGrid control. You can cancel the ColumnFixedStateChanging event which would not allow your end user to fixed that column. The ColumnFixedStateChanged event allows you to see which column that your end user fixed in place.

== Related Topics

link:xamgrid-fixed-columns.html[Fixed Columns]

link:xamgrid-setting-the-drop-area-location.html[Setting the Drop Area Location]

link:xamgrid-setting-fixed-columns-programmatically.html[Setting Fixed Columns Programmatically]