////

|metadata|
{
    "name": "xamgantt-setting-and-retrieving-the-active-element",
    "controlName": ["xamGantt"],
    "tags": ["Editing","Events","How Do I"],
    "guid": "59241f9e-bca7-468b-b614-67b122015c04",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.2781247Z"
}
|metadata|
////

= Setting and Retrieving the Active Element

== Topic Overview

=== Purpose

This topic describes the properties and events used to set or retrieve the currently active cell, column or row in the  _xamGantt™_   control.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamgantt-adding-xamgantt-to-a-page.html[Adding xamGantt to a Page]
|This topic describes how to add the _xamGantt_ control to a page.

|====

=== In this topic

This topic contains the following sections:

* <<_Ref334390331, Properties Configuration Summary >>
* <<_Ref334390337, Events Summary >>
* <<_Ref334390343, Code Example: Identifying Active Task >>
* <<_Ref334390352, Related Content >>

** <<_Ref334390359,Topics>>
** <<_Ref334390364,Samples>>

[[_Ref334390331]]
== Properties Configuration Summary

=== Properties configuration summary chart

The following table lists the configurable aspects and corresponding properties for setting and retrieving the active element in the  _xamGantt_   control.

[options="header", cols="a,a,a"]
|====
|Configurable aspect|Details|Property

|Getting or setting the currently active cell
|Identify or modify the currently active cell via the _xamGantt_ `ActiveCell` property. 

The property exposes information about the active cell link:{ApiPlatform}controls.schedules.xamgantt.v{ProductVersion}~infragistics.controls.schedules.ganttgridcell~row.html[Row] and link:{ApiPlatform}controls.schedules.xamgantt.v{ProductVersion}~infragistics.controls.schedules.ganttgridcell~column.html[Column].
| link:{ApiPlatform}controls.schedules.xamgantt.v{ProductVersion}~infragistics.controls.schedules.xamgantt~activecell.html[ActiveCell]

|Getting or setting the currently active column
|Identify or modify the currently active column via the _xamGantt_ `ActiveColumn` property. 

The property exposes information about the active column link:{ApiPlatform}controls.schedules.xamgantt.v{ProductVersion}~infragistics.controls.schedules.ganttgridcolumn~key.html[Key].
| link:{ApiPlatform}controls.schedules.xamgantt.v{ProductVersion}~infragistics.controls.schedules.xamgantt~activecolumn.html[ActiveColumn]

|Getting or setting the currently active row
|Identify or modify the currently active row via the _xamGantt_ `ActiveRow` property. 

The property exposes information about the active link:{ApiPlatform}controls.schedules.xamgantt.v{ProductVersion}~infragistics.controls.schedules.ganttgridrow~task.html[Task].
| link:{ApiPlatform}controls.schedules.xamgantt.v{ProductVersion}~infragistics.controls.schedules.xamgantt~activerow.html[ActiveRow]

|====

[[_Ref334390337]]
== Events Summary

=== Events summary chart

The following table identifies the event to set and retrieve the active element in the  _xamGantt_   control.

[options="header", cols="a,a"]
|====
|In order to:|Use this event:

|Handle the change of the _xamGantt_ active cell
| link:{ApiPlatform}controls.schedules.xamgantt.v{ProductVersion}~infragistics.controls.schedules.xamgantt~activecellchanged_ev.html[ActiveCellChanged]

|====

[[_Ref334390343]]
== Code Example: Identifying Active Task

=== Description

The code snippet demonstrates how to use the  _xamGantt_   `ActiveCellChanged` event to identify the currently active task and its name. Every time you select or click in a  _xamGantt_   cell, you automatically trigger the ActiveCellChanged event.

[[_Ref334390352]]

=== Code

*In XAML:*

[source,xaml]
----
<ig:XamGantt x:Name="gantt" 
             Project="{Binding Project}"
             ActiveCellChanged="gantt_ActiveCellChanged"/>
----

*In C#:*

[source,csharp]
----
private void gantt_ActiveCellChanged(object sender, System.EventArgs e)
{
    if (this.gantt.ActiveRow.HasValue)
    {
        string msg = string.Format("The current active task is {0}.",this.gantt.ActiveRow.Value.Task.TaskName);
        System.Diagnostics.Debug.WriteLine(msg);
    }
}
----

*In Visual Basic:*

[source,vb]
----
Private Sub gantt_ActiveCellChanged(sender As System.Object, e As System.EventArgs)
    If Me.gantt.ActiveRow.HasValue Then
        Dim msg As String = String.Format("The current active task is {0}.", Me.gantt.ActiveRow.Value.Task.TaskName)
        System.Diagnostics.Debug.WriteLine(msg)
    End If
End Sub
----

== Related Content

[[_Ref334390359]]

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamgantt-retrieving-selected-elements.html[Retrieving Selected Elements]
|This topic describes the events and their arguments used to retrieve information about the currently selected cells, columns or rows in the _xamGantt_ control.

| link:xamgantt-other-events-and-events-arguments.html[Other Events and Event Arguments]
|This topic describes some of the available events triggered by common user interactions in the _xamGantt_ control.

|====

[[_Ref334390364]]

=== Samples

The following samples provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Sample|Purpose

| pick:[sl=" link:{SamplesURL}/gantt/#/activation[Activation]"] pick:[wpf=" link:{SamplesURL}/gantt/activation[Activation]"] 
|This sample demonstrates how you can use the ActiveCellChanged event and the ActiveCell, ActiveColumn and ActiveRow properties to extract information about the currently active _xamGantt_ element.

|====