////

|metadata|
{
    "name": "xamgrid-using-xamgrid",
    "controlName": ["xamGrid"],
    "tags": ["Grids"],
    "guid": "{527947C0-55C1-494D-A0DC-1D234E823431}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.6391826Z"
}
|metadata|
////

= Using xamGrid

This section is your gateway to important conceptual and task-based information that will help you to use the various features and functionalities provided by the xamGrid™ control.

link:xamgrid-activation.html[Activation]

This section describes the activation feature and demonstrates how to implement tasks such as how to enable activation on the xamGrid control.

link:xamgrid-active-item.html[Active Item]

This section describes the active item feature.

link:xamgrid-change-child-bands-visibility.html[Change Child Bands Visibility]

This walkthrough demonstrates how to change the visibility of the xamGrid control's ChildBand header rows at runtime.

link:xamgrid-columns.html[Columns]

This section describes all the different Columns available within the xamGrid control and demonstrates how to interact with the Columns.

link:xamgrid-column-chooser.html[Column Chooser]

This section describes the column chooser feature and demonstrates how to implement tasks such as how to enable the column chooser on the xamGrid control.

link:xamgrid-column-moving.html[Column Moving]

This section describes the column moving feature of xamGrid and demonstrates how to implement tasks such as how to enable column moving on the xamGrid control.

link:xamgrid-column-resizing.html[Column Resizing]

This section describes the column resizing feature of xamGrid and demonstrates how to implement tasks such as how to enable column resizing on the xamGrid control.

link:xamgrid-conditional-formatting.html[Conditional Formatting]

The section describes how to build conditional rules based on column values within the xamGrid control.

link:xamgrid-copy-paste-support.html[Copy-Paste Support]

This section describes how copy and paste is supported within xamGrid.

link:xamgrid-data-annotations.html[Data Annotations]

This topics explains how data annotations is implemented with the xamGrid control.

link:xamgrid-data-binding.html[Data Binding]

This topic explains how data binding is implemented within the xamGrid control.

link:xamgrid-deferred-scrolling.html[Deferred Scrolling]

This section describes the deferred scrolling feature of xamGrid and demonstrates how to use it to improve performance.

link:xamgrid-editing-data.html[Editing Data]

This section demonstrates how to edit data within the xamGrid control.

link:xamgrid-filtering.html[Filtering]

This section describes the filtering feature and demonstrates how to implement tasks such as how to enable filtering on the xamGrid control.

link:xamgrid-fixed-columns.html[Fixed Columns]

This section describes the fixed columns feature of xamGrid and gives examples on how to implement the feature in xamGrid.

link:xamgrid-groupby.html[GroupBy]

This section demonstrates how to enable GroupBy on xamGrid and also how to customize the GroupBy feature.

link:xamgrid-merged-cells.html[Merged Cells]

This section demonstrates how to enable Cell Merging and also how to customize the feature.

link:xamgrid-paging.html[Paging]

This section describes the Paging feature and also gives examples on how to implement it in xamGrid.

link:xamgrid-right-to-left-bidirectional-language-support.html[Right to Left Bidirectional Language Support]

This topic demonstrates how to implement right to left bidirectional language support within xamGrid.

link:xamgrid-row-selectors.html[Row Selectors]

This section describes the row selector feature and demonstrates how to implement the feature in xamGrid.

link:xamgrid-rows.html[Rows]

This section describes different ways in which you can interact with the rows in xamGrid.

link:xamgrid-selection.html[Selection]

This section describes the selection feature of xamGrid. It also gives examples demonstrating how to implement the feature.

link:xamgrid-sorting.html[Sorting]

This section contains information on the sorting feature and how to perform tasks such as enable sorting on the xamGrid control.

link:xamgrid-summaries.html[Summaries]

The section describes the summaries feature and also contains information on how to perform tasks such as enable summaries on xamGrid.

link:xamgrid-implicitdatatemplates.html[Applying Different User Interface Depending on the Cell Data Type]

This topic demonstrates how implicit data templates can be used to apply different visual representation of data types in cells in a TemplateColumn in the xamGrid™ control.

link:xamgrid-support-for-string-indexers.html[Support for String Indexers]

This topic explains how string indexers are supported within xamGrid.

link:xamgrid-tooltips.html[ToolTips]

This topic describes how to implement ToolTips within xamGrid.

link:xamgrid-virtualization.html[Virtualization]

This section explains how to improve the performance of xamGrid using Virtualization.