////

|metadata|
{
    "name": "xamgrid-rows",
    "controlName": ["xamGrid"],
    "tags": ["Grids","How Do I","Layouts"],
    "guid": "{A12DFFB4-7884-4ACE-AF03-0FF14F773658}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:56.0941711Z"
}
|metadata|
////

= Rows

This section provides you with useful information about task-based procedures on working with the Rows object of the xamGrid™ control.

link:xamgrid-add-new-row.html[Add New Row]

This topic demonstrates how to add a new row the xamGrid control.

link:xamgrid-add-row-commands.html[Add Row Commands]

This topics demonstrates how to add commands to rows in the xamGrid control.

link:xamgrid-auto-expand-data-rows-and-child-bands.html[Auto Expand Data Rows and Child Bands]

This topic demonstrates how to expand the data rows and the child bands automatically using the IsExpanded property and RowExpansionChanged event.

link:xamgrid-change-row-hover-type.html[Change Row Hover Type]

This topic demonstrates how to change the row hover type default value.

link:xamgrid-remove-alternative-row-styling.html[Remove Alternative Row Styling]

This topic demonstrates how to remove the default styling that is applied to alternative rows.

link:xamgrid-row-deletion.html[Row Deletion]

This topic demonstrates how to remove a row from the xamGrid control.

link:xamgrid-requireemptyconstructor-exception.html[RequireEmptyConstructor Exception]

This topic demonstrates how to avoid getting the RequireEmptyConstructor exception.