////

|metadata|
{
    "name": "xamgauge",
    "controlName": ["xamGauge","xamSegmentedDisplay"],
    "tags": ["Getting Started","How Do I"],
    "guid": "{F852A6AF-4B87-47AA-89D6-DAC4C21A37A9}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:58.9843322Z"
}
|metadata|
////

= xamSegmentedDisplay

This section gives you an overview of the use of the xamSegmentedDisplay™. This section contains valuable information about this control, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish common tasks using the control.

In order to get you up and running as quickly as possible with the xamSegmentedDisplay control, we've provided you with information on how to get started using the control:

* link:xamgauge-adding-a-digital-gauge-to-your-page.html[Getting Started with xamSegmentedDisplay]

== link:xamgauge-using-xamgauge.html[Using xamGauge]

This section contains information on the key features and functionalities provided by the xamSegmentedDisplay control.

== link:xamgauge-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamSegmentedDisplay control. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.