////

|metadata|
{
    "name": "xamgrid-sorting-events",
    "controlName": ["xamGrid"],
    "tags": ["Events","Grids","How Do I","Sorting"],
    "guid": "{F1F19607-C912-437D-AEF9-2B14DDF68C46}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.693148Z"
}
|metadata|
////

= Sorting Events

There are two events associated with sorting in xamGrid™. These events have the suffix “ing” or “ed” appended to them, reflecting the order in which they occur. The sorting events allow you to perform some custom business logic before or after a column is sorted.

link:{ApiPlatform}controls.grids.xamgrid{ApiVersion}~infragistics.controls.grids.xamgrid~columnsorting_ev.html[ColumnSorting] Event – The moment right before a column is sorted, the ColumnSorting event fires. This event can be cancelled if your certain conditions are not met.

link:{ApiPlatform}controls.grids.xamgrid{ApiVersion}~infragistics.controls.grids.xamgrid~columnsorted_ev.html[ColumnSorted] Event – This event fires after the column is sorted.

These events allow you to control how your end users interact with the sorting columns feature of the xamGrid control. You can cancel the ColumnSorting event which would not allow your end user to sort on that column. The ColumnSorted event allows you to see which column your end user sorted.

== *Related Topics*

link:xamgrid-sorting.html[Sorting]

link:xamgrid-multi-column-sorting.html[Multi-Column Sorting]

link:xamgrid-remove-sort-indicator.html[Remove Sort Indicator]

link:xamgrid-disable-sorting-on-certain-columns.html[Disable Sorting on Certain Columns]

link:xamgrid-custom-sort.html[Custom Sort]

pick:[win-rt=" link:bb45cdbe-7149-49bc-a63a-1a77676c6986[Touch Support]"]