////

|metadata|
{
    "name": "xamgrid-activation-events",
    "controlName": ["xamGrid"],
    "tags": ["Events","Grids","How Do I"],
    "guid": "{6A1BDB9B-9ED8-4B9D-B716-DB90543C346E}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.6631463Z"
}
|metadata|
////

= Activation Events

There are two events associated with activation in xamGrid™. These events have the suffix “ing” or “ed” appended to them, reflecting the order in which they occur. The activation events allow you to perform some custom business logic before or after a cell becomes activate on the xamGrid control.

link:{ApiPlatform}controls.grids.xamgrid.v{ProductVersion}~infragistics.controls.grids.xamgrid~activecellchanging_ev.html[ActiveCellChanging] - The moment right before a cell becomes active, the ActiveCellChanging event fires. This event can be cancelled if your certain conditions are not met.

link:{ApiPlatform}controls.grids.xamgrid.v{ProductVersion}~infragistics.controls.grids.xamgrid~activecellchanged_ev.html[ActiveCellChanged] - This event is fired after the active cell is changed.

You can use these events to control which cells on the xamGrid control can be activated, and they also allow you to interact with your end user based on which cells they activate.

== *Related Topic*
link:xamgrid-activation.html[Activation]