////

|metadata|
{
    "name": "xamgrid-selection-events",
    "controlName": ["xamGrid"],
    "tags": ["Events","Grids","How Do I","Selection"],
    "guid": "{C7793810-330C-45BC-AB25-8798656C1206}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.7571914Z"
}
|metadata|
////

= Selection Events

There are three events associated with selection in xamGrid™. These events are fired when an object has been added or removed from the objects collection. The selection events allow you to perform some custom business logic when a cell, row or column is added to or removed from their collections. link:{ApiPlatform}controls.grids.xamgrid.v{ProductVersion}~infragistics.controls.grids.xamgrid~selectedcellscollectionchanged_ev.html[SelectedCellsCollectionChanged] – This event is fired when a cell has been added to or removed from the SelectedCells collection. link:{ApiPlatform}controls.grids.xamgrid.v{ProductVersion}~infragistics.controls.grids.xamgrid~selectedrowscollectionchanged_ev.html[SelectedRowsCollectionChanged] – This event is fired when a row has been added to or removed from the SelectedRows collection. link:{ApiPlatform}controls.grids.xamgrid.v{ProductVersion}~infragistics.controls.grids.xamgrid~selectedcolumnscollectionchanged_ev.html[SelectedColumnsCollectionChanged] – This event is fired when a column has been added to or removed from the SelectedColumns collection. 

You can use these events which items of the xamGrid control your end user has selected.

== *Related Topics*

link:xamgrid-selection.html[Selection]

link:xamgrid-setting-selection-programmatically.html[Setting Selection Programmatically]