////
|metadata|
{
    "name": "xamgantt-calendars-configuration-overview",
    "controlName": ["xamGantt"],
    "tags": ["Data Binding","Data Presentation","Formatting","Grids","Scheduling"],
    "guid": "f02315e7-8a55-4615-8cf8-f8160f17c33b",
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.4751771Z"
}
|metadata|
////

= Calendars Configuration Overview (xamGantt)

== Topic Overview

=== Purpose

This topic gives an overview of the main features of  _xamGantt_™ Calendars. xamGantt makes time calculations using calendars.

=== In this topic

This topic contains the following sections:

* <<_Calendars_Overview, Calendars Overview >>

** <<_xamGantt_Calendars,xamGantt calendars>>

** <<_Project_Calendar,Project Calendar>>

** <<_Custom_Calendar,Custom Calendar>>

* <<_Related_Content, Related Content >>

[[_Calendars_Overview]]
== Calendars Overview

[[_xamGantt_Calendars]]

=== xamGantt calendars

Calendars are used by xamGantt for making time calculations, such as adding the task duration to its Start value. Time calculations are based on task, project and resource settings. You can use link:{ApiPlatform}controls.schedules.xamgantt.v{ProductVersion}~infragistics.controls.schedules.projectcalendar_members.html[ProjectCalendar] class for setting calendars or you can create a custom calendar class.

Using `ProjectCalendar` you can specify working time information for the days of the week using link:{ApiPlatform}controls.schedules.xamgantt.v{ProductVersion}~infragistics.controls.schedules.projectcalendar~daysofweek.html[DaysOfWeek] and link:{ApiPlatform}controls.schedules.xamgantt.v{ProductVersion}~infragistics.controls.schedules.projectcalendar~workweeks.html[WorkWeeks] properties.

The following table summarizes the main points when using calendars with xamGantt.

[options="header", cols="a,a"]
|====
|Feature|Description

|ProjectCalendar
|You can use `ProjectCalendar` class for representing working time information in a link:{ApiPlatform}controls.schedules.xamgantt.v{ProductVersion}~infragistics.controls.schedules.project_members.html[Project].

|Custom calendar
|You can create a custom class and use it as calendar.

|Determine the used calendar
|To perform a time calculation, xamGantt needs a calendar. Calendar is set for a project and all time calculations are based on this calendar.

|====

[[_Project_Calendar]]

=== Project Calendar

You can set working time information for the days of the week by setting `DaysOfWeek` property, get adjustments in working times on a specific recurrence pattern by using link:{ApiPlatform}controls.schedules.xamgantt.v{ProductVersion}~infragistics.controls.schedules.projectcalendar~exceptions.html[Exceptions] property, specify the name of the user calendar with the link:{ApiPlatform}controls.schedules.xamgantt.v{ProductVersion}~infragistics.controls.schedules.projectcalendar~displayname.html[DisplayName] property, get a collection of working times for days of the week for specific ranges of dates using `WorkWeeks` property.

*Related Topic*

link:xamgantt-configuring-the-xamgantt-project-calendar.html[Configuring the xamGantt ProjectCalendar]

[[_Custom_Calendar]]

=== Custom Calendar

You can create a custom calendar and use it with xamGantt.

*Related Topic*

link:xamgantt-configuring-custom-calendars-for-xamgantt.html[Configuring the xamGantt Custom calendar]

[[_Related_Content]]
== Related Content

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamgantt-configuring-the-xamgantt-calendars.html[Configuring the xamGantt Calendars]
|The topics in this group contains information about _xamGantt_ Calendars.

|====

=== Samples

The following samples provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Sample|Purpose

| link:{SamplesURL}/gantt/project-calendar[Project Calendars]
|This sample demonstrates how you can customize project calendar and set a non-working day.

| link:{SamplesURL}/gantt/calendar-working-times[Calendar Working Times]
|This sample demonstrates how you can create a fully customized project calendar.

|====