////

|metadata|
{
    "name": "xamgrid-column-resizing-events",
    "controlName": ["xamGrid"],
    "tags": ["Events","Grids","How Do I","Layouts"],
    "guid": "{A0F8091D-75EC-4D07-ABED-6998031D3957}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.8291643Z"
}
|metadata|
////

= Column Resizing Events

There are two events associated with column resizing in xamGrid™. These events have the suffix “ing” or “ed” appended to them, reflecting the order in which they occur. The column resizing events allow you to perform custom business logic before or after your end user resizes a column. link:{ApiPlatform}controls.grids.xamgrid{ApiVersion}~infragistics.controls.grids.xamgrid~columnresizing_ev.html[ColumnResizing] – The moment right before a column is resized, the ColumnResizing event fires. You can cancel this event if your application's state does not meet certain conditions. link:{ApiPlatform}controls.grids.xamgrid{ApiVersion}~infragistics.controls.grids.xamgrid~columnresized_ev.html[ColumnResized] – This event fires after the column is resized. 

These events allow you to restrict which columns your end user can resize by cancelling the ColumnResizing event. You can also determine which Column your end user resized using the ColumnResized event.

== *Related Topics*

link:xamgrid-column-resizing.html[Column Resizing]

link:xamgrid-multi-column-resizing.html[Multi-Column Resizing]

link:xamgrid-resize-in-the-cell-area.html[Resize Cells in the Cell Area]

link:xamgrid-auto-size-columns-using-mouse-clicks.html[Auto Size Columns Using Mouse Clicks]

link:xamgrid-set-columns-maximum-and-minimum-widths.html[Set Column's Maximum and Minimum Widths]

link:xamgrid-disable-resizing-of-certain-columns.html[Disable Resizing of Certain Columns]