////

|metadata|
{
    "name": "xamgantt-showing-hiding-summary-tasks",
    "controlName": ["xamGantt"],
    "tags": ["Data Presentation","How Do I","Scheduling"],
    "guid": "71d203bb-62d8-4ce5-b924-e350831bb9d3",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.3571671Z"
}
|metadata|
////

= Showing/Hiding Summary Tasks

== Topic Overview

=== Purpose

This topic explains how to configure summary task visibility using the  _xamGantt™_   control.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamgantt-adding-xamgantt-to-a-page.html[Adding xamGantt to a Page]
|This topic describes how to add the _xamGantt_ control to a page.

|====

=== In this topic

This topic contains the following sections:

* <<_Ref334910790, Showing/Hiding Summary Tasks >>

** <<_Ref335272110,Overview>>
** <<_Ref335272117,Property settings>>
** <<_Ref335272123,Example>>

* <<_Ref334910796, Related Content >>

** <<_Ref334910801,Topics>>
** <<_Ref334910806,Samples>>

[[_Ref334910790]]
== Showing/Hiding Summary Tasks

[[_Ref335272110]]

=== Overview

By default, summary tasks are visible in the  _xamGantt_   control.

Configure summary task visibility via the link:{ApiPlatform}controls.schedules.xamgantt.v{ProductVersion}~infragistics.controls.schedules.projectviewsettings_members.html[ProjectViewSettings] link:{ApiPlatform}controls.schedules.xamgantt.v{ProductVersion}~infragistics.controls.schedules.projectviewsettings~aresummarytasksvisible.html[AreSummaryTasksVisible] property.

[[_Ref335272117]]

=== Property settings

The following table maps the desired configuration to property settings.

[options="header", cols="a,a,a"]
|====
|In order to:|Use this property:|And set it to:

|Show or hide summary tasks
| link:{ApiPlatform}controls.schedules.xamgantt.v{ProductVersion}~infragistics.controls.schedules.projectviewsettings~aresummarytasksvisible.html[AreSummaryTasksVisible]
|`bool`

|====

[[_Ref335272123]]

=== Example

The example below demonstrates how to hide the summary tasks:

*In XAML:*

[source,xaml]
----
<ig:XamGantt x:Name="gantt" 
             Project="{Binding Project}">
    <ig:XamGantt.ViewSettings>
        <ig:ProjectViewSettings AreSummaryTasksVisible=" />
    </ig:XamGantt.ViewSettings>
</ig:XamGantt>
----

[[_Ref334910796]]
== Related Content

[[_Ref334910801]]

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamgantt-project-view-settings-configuration-overview.html[Project View Settings Configuration Overview]
|This topic gives an overview of the _xamGantt_ ProjectViewSettings class and its configurable aspects.

|====

[[_Ref334910806]]

=== Samples

The following samples provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Sample|Purpose

| pick:[sl=" link:{SamplesURL}/gantt/#/milestone-and-summary-tasks[Milestone and Summary Tasks]"] pick:[wpf=" link:{SamplesURL}/gantt/milestone-and-summary-tasks[Milestone and Summary Tasks]"] 
|This sample demonstrates how you can add milestones and summary tasks. You can also toggle the visibility of the root project summary task and other summary tasks.

|====