////

|metadata|
{
    "name": "xamgantt-calculating-explicitly-a-project",
    "controlName": ["xamGantt"],
    "tags": ["Calculations","How Do I","Scheduling"],
    "guid": "e6eb8825-adcf-4ec4-84d3-547e4e761fbd",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.3071261Z"
}
|metadata|
////

= Calculating Explicitly a Project

== Topic Overview

=== Purpose

This topic explains how to calculate a project explicitly using the  _xamGantt™_   control.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamgantt-binding-arbitrary-tasks-collection-listbackedproject.html[Binding to Arbitrary Tasks Collection Using ListBackedProject]
|This topic describes how the _xamGantt_ control is bound to an arbitrary tasks collection via ListBackedProject.

|====

=== In this topic

This topic contains the following sections:

* <<_Ref334822139, Explicitly Calculating a Project >>
* <<_Ref334818619, Related Content >>

** <<_Ref334818626,Topics>>
** <<_Ref334818631,Samples>>

[[_Ref334818613]]
[[_Ref334822139]]
== Explicitly Calculating a Project

=== Overview

By default, automatic project calculations in the  _xamGantt_   control occur with every edit.

This behavior is configurable, and you may explicitly calculate the project as needed.

=== Property settings

The following table maps the explicit project’s calculation configuration to property settings.

[options="header", cols="a,a,a"]
|====
|In order to:|Use:|And set it to:

|Disables automatic project calculation
| link:{ApiPlatform}controls.schedules.xamgantt{ApiVersion}~infragistics.controls.schedules.projectsettings~shouldcalculateaftereachedit.html[ShouldCalculateAfterEachEdit]
|`False`

|Explicitly calculate the project
| link:{ApiPlatform}controls.schedules.xamgantt{ApiVersion}~infragistics.controls.schedules.project_members.html[Project] link:{ApiPlatform}controls.schedules.xamgantt{ApiVersion}~infragistics.controls.schedules.project~calculate.html[Calculate] method
|-

|====

=== Example

The example below demonstrates how you explicitly calculate a project; triggered by clicking the ‘Calculate’ Button:

*In XAML:*

[source,xaml]
----
<ig:ListBackedProject x:Name="dataProvider" 
                      TaskItemsSource="{Binding Tasks}"                                 
<!-- Add ProjectTask Property Mappings Here -->
    <ig:ListBackedProject.Settings>
        <ig:ProjectSettings ShouldCalculateAfterEachEdit=" />
    </ig:ListBackedProject.Settings>
</ig:ListBackedProject>
<ig:XamGantt x:Name="gantt" 
             Project="{Binding ElementName=dataProvider}"/>
…
<Button x:Name="Btn_Calculate" Content="Calculate" 
        Click="Btn_Calculate_Click" />
----

*In C#:*

[source,csharp]
----
private void Btn_Calculate_Click(object sender, RoutedEventArgs e)
{
    this.dataProvider.Calculate();
}
----

*In Visual Basic:*

[source,vb]
----
Private Sub Btn_Calculate_Click(sender As Object, e As RoutedEventArgs)
    Me.dataProvider.Calculate()
End Sub
----

[[_Ref334818619]]
== Related Content

[[_Ref334818626]]

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamgantt-project-configuration-overview.html[Project Configuration Overview]
|This topic gives an overview of the _xamGantt_ Project class and its configurable aspects.

| link:xamgantt-scheduling-project-from-start-or-finish-date.html[Scheduling a Project From a Start or Finish Date]
|This topic explains how to calculate project and tasks dates according to the project start or finish date in the _xamGantt_ control.

|====

[[_Ref334818631]]

=== Samples

The following samples provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Sample|Purpose

| pick:[sl=" link:{SamplesURL}/gantt/#/using-commands[Using Commands]"] pick:[wpf=" link:{SamplesURL}/gantt/using-commands[Using Commands]"] 
|This sample mimics the Microsoft Project 2010 ribbon menu and demonstrates some of the _xamGantt_ commands such as explicit calculation of the project.

|====