////

|metadata|
{
    "name": "xamgrid-paging-events",
    "controlName": ["xamGrid"],
    "tags": ["Events","Grids","How Do I","Paging"],
    "guid": "{9564190B-E18C-4F01-A3CB-4D2DEC2C9E1B}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.7101864Z"
}
|metadata|
////

= Paging Events

There are two events associated with paging in xamGrid™. These events have the suffix “ing” or “ed” appended to them, reflecting the order in which they occur. The paging events allow you to perform some custom business logic before or after the page is changed.

link:{ApiPlatform}controls.grids.xamgrid{ApiVersion}~infragistics.controls.grids.xamgrid~pageindexchanging_ev.html[PageIndexChanging] -- The moment right before the page index is changed, the PageIndexChanging event fires. This event can be cancelled if your certain conditions are not met.

link:{ApiPlatform}controls.grids.xamgrid{ApiVersion}~infragistics.controls.grids.xamgrid~pageindexchanged_ev.html[PageIndexChanged] -- This event fires after the page index changes.

You can access very useful information using these events. For example when the PageIndexChanging event is fired, you can determine the ColumnLayout that the event was triggered for or you can determine the collection of rows that the ColumnLayout will represent.

== *Related Topics*

link:xamgrid-paging.html[Paging]

link:xamgrid-customize-the-pager.html[Customize the Pager]