////

|metadata|
{
    "name": "xamgrid-filtering-events",
    "controlName": ["xamGrid"],
    "tags": ["Events","Filtering","Grids"],
    "guid": "{793D9FE1-44B7-4498-B313-B489F4BFA4DA}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:56.0042053Z"
}
|metadata|
////

= Filtering Events

There are two events associated with filtering in the xamGrid™ control. These events have the suffix “ing” or “ed” appended to them, reflecting the order in which they occur. The filtering events allow you to perform custom business logic before or after your end user filters the grid. link:{ApiPlatform}controls.grids.xamgrid.v{ProductVersion}~infragistics.controls.grids.xamgrid~filtering_ev.html[Filtering]– The moment right before the grid is filtered, the Filtering event fires. You can cancel this event if your application’s state does not meet certain conditions. link:{ApiPlatform}controls.grids.xamgrid.v{ProductVersion}~infragistics.controls.grids.xamgrid~filtered_ev.html[Filtered] – this event fires after the grid is filtered. 

These events allow you to control what actions your end users can perform on the xamGrid control. For example you can disable the filtering on the grid by cancelling the Filtering event.

== *Related Topics*

link:xamgrid-filtering.html[Filtering]

link:xamgrid-programmatically-create-a-filter.html[Programmatically Create a Filter]

link:xamgrid-create-a-custom-filter.html[Create a Custom Filter]

link:xamgrid-filter-operands.html[Filter Operands]