////

|metadata|
{
    "name": "xamgrid-setting-the-drop-area-location",
    "controlName": ["xamGrid"],
    "tags": ["Grids","How Do I","Layouts","Selection"],
    "guid": "{D8065F68-E7B6-488F-AD96-633132779636}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.7751708Z"
}
|metadata|
////

= Setting the Drop Area Location

You can configure an area on the xamGrid™ control where your end users can drag a column into and it will automatically become fixed. Also when your end users drag a fixed column from this area, it will automatically return to its original unpinned position.

Setting the link:{ApiPlatform}controls.grids.xamgrid{ApiVersion}~infragistics.controls.grids.fixedcolumnsettings.html[FixedColumnSettings] object’s link:{ApiPlatform}controls.grids.xamgrid{ApiVersion}~infragistics.controls.grids.fixedcolumnsettings.html[FixedDropAreaLocation] property to left, right or both will determine the location of the drop area.

*In XAML:*

----
<ig:XamGrid.FixedColumnSettings>
   <ig:FixedColumnSettings AllowFixedColumns="DropArea"            
      FixedDropAreaLocation="Left"/>
</ig:XamGrid.FixedColumnSettings>
----

*In Visual Basic:*

----
Imports Infragistics.Controls.Grids
...
Me.MyGrid.FixedColumnSettings.AllowFixedColumns = FixedColumnType.DropArea
Me.MyGrid.FixedColumnSettings.FixedDropAreaLocation = FixedDropAreaLocation.Left
----

*In C#:*

----
using Infragistics.Controls.Grids;
...
this.MyGrid.FixedColumnSettings.AllowFixedColumns = FixedColumnType.DropArea;
this.MyGrid.FixedColumnSettings.FixedDropAreaLocation = FixedDropAreaLocation.Left;
----

== *Related Topics*

link:xamgrid-fixed-columns.html[Enable Fixed Columns]

link:xamgrid-fixed-column-events.html[Fixed Column Events]

link:xamgrid-setting-fixed-columns-programmatically.html[Setting Fixed Columns Programmatically]

pick:[win-rt=" link:bb45cdbe-7149-49bc-a63a-1a77676c6986[Touch Support]"]