////

|metadata|
{
    "name": "xamgantt-configuring-sections",
    "tags": ["Layouts","Templating"],
    "controlName": ["xamGantt"],
    "guid": "72996820-e56a-4f33-9f4a-89df23a09f64",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.6201836Z"
}
|metadata|
////

= Configuring Sections (xamGantt)

== Topic Overview

=== Purpose

This topic explains how to configure the width of the grid and the chart sections of the  _xamGantt™_  control.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamgantt-xamgantt-visual-elements-overview.html[xamGantt Visual Elements Overview]
|This topic illustrates the main visual elements in the _xamGantt_ control.

|====

=== In this topic

This topic contains the following sections:

* <<_Ref400551188, XamGantt Sections Configuration Summary >>
* <<_Ref400551196, Related Content >>

[[_Ref400551188]]
== XamGantt Sections Configuration Summary

=== Sections summary

The two main sections of the link:{ApiPlatform}controls.schedules.xamgantt{ApiVersion}~infragistics.controls.schedules.xamgantt.html[ _xamGantt_  ] controls (grid sections and chart section) have properties for controlling their width. You can set independently both their width using the `GridLength` type. This type supports width specified in pixels, size determined by the content and size expressed as a weighted proportions of the available space.

=== Sections summary chart

The following table explains briefly the configurable aspects of the  _xamGantt’s_   sections and maps them to the properties that configure them.

[options="header", cols="a,a,a"]
|====
|Configurable aspect|Details|Properties

|[[_Hlk356484826]] 

Grid Section Width
|Set the width of the grid section with a value of type `GridLength`.
| link:{ApiPlatform}controls.schedules.xamgantt{ApiVersion}~infragistics.controls.schedules.xamgantt~gridwidth.html[GridWidth]

|Chart Section Width
|Set the width of the chart section with a value of type `GridLength`.
| link:{ApiPlatform}controls.schedules.xamgantt{ApiVersion}~infragistics.controls.schedules.xamgantt~chartwidth.html[ChartWidth]

|====

.Note
[NOTE]
====
The control doesn't use these properties directly. Instead it is expected that the properties are bound to in the control template so if you create a custom `ControlTemplate` for the  _xamGantt_   then you should bind to these properties as it is done in the default template.
====

[[_Ref400551196]]
== Related Content

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamgantt-configuring-project.html[Configuring Project (xamGantt)]
|The topics in this group explain the xamGantt Project class, its configurable aspects and the main features it provides.

| link:xamgantt-configuring-project-view-settings.html[Configuring Project View Settings]
|The topics in this group explain the xamGantt ProjectViewSettings class, its configurable aspects as well as the main features that provides.

| link:xamgantt-configuring-the-xamgantt-timescale.html[Configuring the xamGantt Timescale]
|The topics in this group contains information about xamGantt Timescale.

|====