////

|metadata|
{
    "name": "xamgrid-retrieve-the-result-of-a-summary",
    "controlName": ["xamGrid"],
    "tags": ["Grids","How Do I","Summaries"],
    "guid": "{04250E61-6E48-41B4-833E-24B00CFEF2B3}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:56.0222044Z"
}
|metadata|
////

= Retrieve the Result of a Summary

You can retrieve a  pick:[sl,win-rt=" link:{RootAssembly}{ApiVersion}~infragistics.summaryresult.html[SummaryResult]"]  pick:[wpf=" link:{ApiPlatform}datamanager{ApiVersion}~infragistics.summaryresult.html[SummaryResult]"]  object by indexing into a  pick:[sl,win-rt=" link:{RootAssembly}{ApiVersion}~infragistics.summaryresultcollection.html[SummaryResultCollection]"]  pick:[wpf=" link:{ApiPlatform}datamanager{ApiVersion}~infragistics.summaryresultcollection.html[SummaryResultCollection]"]  off the link:{ApiPlatform}controls.grids.xamgrid{ApiVersion}~infragistics.controls.grids.summaryrowsettings.html[SummaryRowSettings] object in xamGrid.

There are different SummaryResultCollection collections available, for example the column layout or the child band collections. The one that is used depends on the value of the SummaryRowSettings/SummaryRowSettingsOverride object’s link:{ApiPlatform}controls.grids.xamgrid{ApiVersion}~infragistics.controls.grids.summaryrowsettings~summaryscope.html[SummaryScope] property.

For more information on column layouts, see the link:xamgrid-define-column-layout.html[Define Column Layout] topic.

The  pick:[sl,win-rt=" link:{RootAssembly}{ApiVersion}~infragistics.summaryresult~value.html[Value]"]  pick:[wpf=" link:{ApiPlatform}datamanager{ApiVersion}~infragistics.summaryresult~value.html[Value]"]  property of the SummaryResult object returns the result of the summary. You may need to cast the Value property to the correct data type before using it in your application logic.

The built-in summary calculators will return the following data types:

[options="header", cols="a,a"]
|====
|*Summary Calculator*|* Data Type*

|Sum
|Decimal

|Average
|Decimal

|Count
|Integer

|Minimum
|Data Type of the Column

|Maximum
|Data Type of the Column

|====

The  pick:[sl,win-rt=" link:{RootAssembly}{ApiVersion}~infragistics.summarydefinition.html[SummaryDefinition]"]  pick:[wpf=" link:{ApiPlatform}datamanager{ApiVersion}~infragistics.summarydefinition.html[SummaryDefinition]"]  of the SummaryResult object returns the Column which the summary is executed on, and the SummaryOperand of the summary.

The following example code demonstrates how to retrieve values from the SummaryResult object.

*In Visual Basic:*

----
Dim SumResult As Object = Me.MyDataGrid.SummaryRowSettings.SummaryResultCollection(0).Value
Dim SumDefinition As SummaryDefinition = Me.MyDataGrid.SummaryRowSettings.SummaryResultCollection(0).SummaryDefinition
Dim MySummary As SummaryOperandBase = SumDefinition.SummaryOperand
Dim MyColumn As String = SumDefinition.ColumnKey
----

*In C#:*

----
object SumResult = this.MyDataGrid.SummaryRowSettings.SummaryResultCollection[0].Value;
SummaryDefinition SumDefinition = this.MyDataGrid.SummaryRowSettings.SummaryResultCollection[0].SummaryDefinition;
SummaryOperandBase MySummary = SumDefinition.SummaryOperand;
String MyColumn = SumDefinition.ColumnKey;
----

== *Related Topics*

link:xamgrid-programmatically-add-summaries.html[Programmatically Add Summaries]

link:xamgrid-summaries.html[Summaries]

link:xamgrid-create-a-custom-summary.html[Create a Custom Summary]

link:xamgrid-formatting-row-summaries.html[Formatting Row Summaries]

pick:[win-rt=" link:bb45cdbe-7149-49bc-a63a-1a77676c6986[Touch Support]"]