////

|metadata|
{
    "name": "xamgrid-tooltips",
    "controlName": ["xamGrid"],
    "tags": ["Grids","How Do I","Selection","Tips and Tricks"],
    "guid": "4cbc6d44-6718-4054-a21b-09daa00e7824",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:56.1692123Z"
}
|metadata|
////

= ToolTips

You can enable ToolTips on certain Columns so that when the end user hovers the mouse over a cell, that particular cell’s information is displayed. You can prevent ToolTips from appearing anywhere on the xamGrid control, customize them to appear only when the cell content overflows, or display them in all cases.

By default ToolTips do not appear.

You can enable ToolTips by setting the Column’s link:{ApiPlatform}controls.grids.xamgrid{ApiVersion}~infragistics.controls.grids.column~allowtooltips.html[AllowToolTips] property to one of the following values of the AllowToolTips enumeration:

* link:{ApiPlatform}controls.grids.xamgrid{ApiVersion}~infragistics.controls.grids.allowtooltips.html[Always]: Display the ToolTips whenever the end user hovers over the cell.
* link:{ApiPlatform}controls.grids.xamgrid{ApiVersion}~infragistics.controls.grids.allowtooltips.html[Never]: Never display the ToolTips.
* link:{ApiPlatform}controls.grids.xamgrid{ApiVersion}~infragistics.controls.grids.allowtooltips.html[Overflow]: Only display the ToolTips when the cell content overflows.

*In XAML:*

----
<ig:XamGrid x:Name="MyDataGrid" ItemsSource="{Binding Source={StaticResource DataUtil}, Path=Products}" AutoGenerateColumns=">
   <ig:XamGrid.Columns>
      <ig:TextColumn AllowToolTips="Always" Key="ProductID"/>
      <ig:TextColumn AllowToolTips="Overflow" Key="ProductName"/>
      <ig:TextColumn AllowToolTips="Never" Key="QuantityPerUnit"/>
      <ig:TextColumn Key="UnitPrice"/>
   </ig:XamGrid.Columns>
</ig:XamGrid>
----

*In Visual Basic:*

----
MyDataGrid.Columns.DataColumns("ProductID").AllowToolTips = AllowTooltips.Always
MyDataGrid.Columns.DataColumns("ProductName").AllowToolTips = AllowTooltips.Overflow
MyDataGrid.Columns.DataColumns("QuantityPerUnit").AllowToolTips = AllowTooltips.Never
----

*In C#:*

----
MyDataGrid.Columns.DataColumns["ProductID"].AllowToolTips = AllowTooltips.Always;
MyDataGrid.Columns.DataColumns["ProductName"].AllowToolTips = AllowTooltips.Overflow;
MyDataGrid.Columns.DataColumns["QuantityPerUnit"].AllowToolTips = AllowTooltips.Never;
----

You can style the ToolTip by setting the link:{ApiPlatform}controls.grids.xamgrid{ApiVersion}~infragistics.controls.grids.column~tooltipstyle.html[ToolTipStyle] property that targets the ToolTip control.

You can specify the content of the ToolTip by setting the link:{ApiPlatform}controls.grids.xamgrid{ApiVersion}~infragistics.controls.grids.column~tooltipcontenttemplate.html[ToolTipContentTemplate] property to an instance of a data template. The DataContext of this property is the Row’s data.

The following code demonstrates how set these properties to customize the ToolTip.

*In XAML:*

----
<ig:XamGrid x:Name="MyDataGrid" ItemsSource="{Binding Source={StaticResource 
                   DataUtil}, Path=Products}" AutoGenerateColumns=">
   <ig:XamGrid.Columns>
      <ig:TextColumn AllowToolTips="Always" Key="ProductID">
         <!-- Set the ToolTipStyle property -->
         <ig:TextColumn.ToolTipStyle>
            <Style TargetType="ToolTip">
               <Setter Property="Foreground" Value="Red"/>
            </Style>
         </ig:TextColumn.ToolTipStyle>
      </ig:TextColumn>
      <ig:TextColumn AllowToolTips="Overflow" Key="ProductName">
         <!-- Set the ToolTipContentTemplate property -->
         <ig:TextColumn.ToolTipContentTemplate>
            <DataTemplate>
               <TextBlock Text="{Binding ProductID}"/>
            </DataTemplate>
         </ig:TextColumn.ToolTipContentTemplate>
      </ig:TextColumn>
      <ig:TextColumn AllowToolTips="Never" Key="QuantityPerUnit"/>
      <ig:TextColumn Key="UnitPrice"/>
   </ig:XamGrid.Columns>
</ig:XamGrid>
----