////

|metadata|
{
    "name": "xamgantt-showing-the-project-summary-task",
    "controlName": ["xamGantt"],
    "tags": ["Data Presentation","How Do I"],
    "guid": "c39d9514-9fb6-45d7-8750-2139d24d6130",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.3311343Z"
}
|metadata|
////

= Showing the Project Summary Task

== Topic Overview

=== Purpose

This topic explains how to display the project’s summary task using the  _xamGantt™_   control.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamgantt-binding-arbitrary-tasks-collection-listbackedproject.html[Binding to Arbitrary Tasks Collection Using ListBackedProject]
|This topic describes how the _xamGantt_ control is bound to an arbitrary tasks collection via ListBackedProject.

|====

=== In this topic

This topic contains the following sections:

* <<_Ref334897358, Showing the Project Summary Task >>

** <<_Ref335264179,Overview>>
** <<_Ref335264195,Property settings>>
** <<_Ref335264202,Example>>

* <<_Ref334897365, Related Content >>

** <<_Ref334897370,Topics>>
** <<_Ref334897375,Samples>>

[[_Ref334897358]]
== Showing the Project Summary Task

[[_Ref335264179]]

=== Overview

By default, the project summary task is not displayed in the  _xamGantt_   control’s user interface. You can configure whether or not the project summary task is visible.

When the project summary task is visible, it appears in both the  _xamGantt_   control’s grid and chart sections.

[[_Ref335264195]]

=== Property settings

The following table maps the desired configuration to its corresponding property settings.

[options="header", cols="a,a,a"]
|====
|In order to:|Use this property:|And set it to:

|Show the project summary task
| link:{ApiPlatform}controls.schedules.xamgantt{ApiVersion}~infragistics.controls.schedules.projectsettings~isroottaskvisible.html[IsRootTaskVisible]
|`True`

|====

[[_Ref335264202]]

=== Example

The example below demonstrates how to display the project summary task:

*In XAML:*

[source,xaml]
----
<ig:ListBackedProject x:Name="dataProvider" 
                      TaskItemsSource="{Binding Tasks}">
    <!-- Add ProjectTask Property Mappings Here -->
    <!-- Specify Project Settings Here -->    
    <ig:ListBackedProject.Settings>
        <ig:ProjectSettings IsRootTaskVisible="True" />
    </ig:ListBackedProject.Settings>
</ig:ListBackedProject>
<ig:XamGantt x:Name="gantt" 
             Project="{Binding ElementName=dataProvider}"/>
----

[[_Ref334897365]]
== Related Content

[[_Ref334897370]]

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamgantt-project-settings-configuration-overview.html[Project Settings Configuration Overview]
|This topic gives an overview of the _xamGantt_ ProjectSettings class and its configurable aspects.

|====

[[_Ref334897375]]

=== Samples

The following samples provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Sample|Purpose

| pick:[sl=" link:{SamplesURL}/gantt/#/milestone-and-summary-tasks[Milestone and Summary Tasks]"] pick:[wpf=" link:{SamplesURL}/gantt/milestone-and-summary-tasks[Milestone and Summary Tasks]"] 
|This sample demonstrates how you can add milestones, summary tasks and show/hide project root task.

|====