////

|metadata|
{
    "name": "xamgrid",
    "controlName": ["xamGrid"],
    "tags": ["Grids"],
    "guid": "31512944-9402-487e-8cf5-8cb7bcd620ad",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:55.6331823Z"
}
|metadata|
////

= xamGrid

This section gives you an overview of the use of the xamGrid™ control. It contains valuable information about xamGrid, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish common tasks using the control.

Click the links below to access important information about the xamGrid control.

== link:xamgrid-about-xamgrid.html[About xamGrid]

In this section you’ll find any information that will help you to better understand the functionalities of the xamGrid control, as well as why you would want to use it as part of building your applications.

== link:xamgrid-adding-xamgrid-to-your-page.html[Adding xamGrid to Your Page]

In order to get you up and running as quickly as possible with the xamGrid control, we've provided you with information on how to get started using the control.

== link:xamgrid-using-xamgrid.html[Using xamGrid]

This section contains information on the key features and functionalities provided by the xamGrid control.

== link:xamgrid-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamGrid control. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the help.