////

|metadata|
{
    "name": "xaminputs",
    "controlName": ["xamInputs"],
    "tags": ["Editing"],
    "guid": "96a3ea80-b6f9-4294-be1b-4e2608b0ca74",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:56.8802159Z"
}
|metadata|
////

= xamInputs

== Introduction

This grouping serves as a starting point for the four input controls: link:xammaskedinput.html[xamMaskedInput]™, link:xamcurrencyinput.html[xamCurrencyInput]™ pick:[sl,wpf,win-rt=", link:xamdatetimeinput.html[xamDateTimeInput]"]  and link:xamnumericinput.html[xamNumericInput]™.

== Topics

The following topics feature information that applies to all input controls. If you want to learn about the specifics of a particular control, please refer to its own group in the table of contents.

* link:xaminputs-about.html[About xamInputs]
* link:xaminputs-masks.html[Masks]
* link:xaminputs-overview-of-the-valueinput-class.html[Overview of the ValueInput Class]

== Related Topics

Following are some other topics you may find useful.

* link:xamcurrencyinput.html[xamCurrencyInput]
* link:xamnumericinput.html[xamNumericInput]

ifdef::sl,wpf,win-rt[]
* link:xamdatetimeinput.html[xamDateTimeInput]

endif::sl,wpf,win-rt[]

* link:xammaskedinput.html[xamMaskedInput]