////

|metadata|
{
    "name": "xaml-xamcomboeditor",
    "controlName": ["xamComboEditor"],
    "tags": ["Getting Started"],
    "guid": "{925F4CFB-F561-4BCD-9F3C-10B1B5A4A0C5}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:54.696093Z"
}
|metadata|
////

= xamComboEditor

This section gives you an overview of the use of xamComboEditor™. This section contains valuable information about xamComboEditor, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish common tasks using the control. Click the links below to access important information about the xamComboEditor control.

== link:xamcomboeditor-about-xamcomboeditor.html[About xamComboEditor]

In this section you’ll find any information that will help you to better understand the functionalities of the xamComboEditor control, as well as why you would want to use it as part of building your applications.

== link:xamcomboeditor-adding-xamcomboeditor-to-your-page.html[Adding xamComboEditor to Your Page]

In order to get you up and running as quickly as possible with the xamComboEditor control, we've provided you with information on how to get started using the control.

== link:xamcomboeditor-using-xamcomboeditor.html[Configuring xamComboEditor]

This section contains information on the key features and functionalities provided by the xamComboEditor control.

== link:xamcomboeditor-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamComboEditor control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the {ProductName} help.