////

|metadata|
{
    "name": "xammaskededitor-understanding-xammaskededitor",
    "controlName": ["xamMaskedEditor"],
    "tags": ["Getting Started"],
    "guid": "{B770698D-46F1-4888-80B6-B2312E938E99}",  
    "buildFlags": [],
    "createdOn": "2012-09-05T19:05:30.2069781Z"
}
|metadata|
////

= About xamMaskedEditor

The xamMaskedEditor™ control is a simple text box control that uses a mask to assist end users in data input. Using this mask, you can restrict the end user's input to valid text formats that you decide beforehand. Use the xamMaskedEditor control either as a stand-alone editor or in a Field of the xamDataGrid™ control. As a Field in xamDataGrid, xamMaskedEditor assists end users in data input while still keeping the proper format of a specific grid column.

For more information you can check the base class of xamMaskEditor - link:xameditors-overview-of-the-valueeditor-class.html[ValueEditor] class and also introduce yourself with the list of availabe link:xameditors-masks.html[Masks] that can be used.