////

|metadata|
{
    "name": "xammaskededitor",
    "controlName": ["xamMaskedEditor"],
    "tags": [],
    "guid": "{3DC13BF7-BE2C-4885-9FAA-90BCC85312D9}",  
    "buildFlags": [],
    "createdOn": "2012-09-05T19:05:30.1919781Z"
}
|metadata|
////

= xamMaskedEditor

If you're looking for an area that houses all of the overview/task-based information related to the xamMaskedEditor™ control, you've come to the right place. This section contains valuable information about xamMaskedEditor, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the xamMaskedEditor control.

== link:xammaskededitor-understanding-xammaskededitor.html[Understanding xamMaskedEditor]

In this section you'll find any information that will help you to better understand the functionalities of the xamMaskedEditor control, as well as why you would want to use it to as part of building your applications.

== link:xammaskededitors-using-xammaskededitor.html[Using xamMaskedEditor]

This section contains information on the key features and functionalities provided by the xamMaskedEditor control.

== link:xammaskededitor-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamMaskedEditor control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the {ProductName} help.