////

|metadata|
{
    "name": "xammap-map-window-animation",
    "controlName": ["xamMap"],
    "tags": ["Data Presentation","How Do I"],
    "guid": "9d4f91d6-b9c6-4431-a7be-b4f28920e72d",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:57.3052385Z"
}
|metadata|
////

= Using Map Window Animation

The Map Window Animation feature provides functionality for changing how the xamMap™ control’s window is animated when panning or zooming operations occur. You can change mode and duration of the map window animation using control’s link:{ApiPlatform}controls.maps.xammap.v{ProductVersion}~infragistics.controls.maps.xammap~windowanimationmode.html[WindowAnimationMode] and link:{ApiPlatform}controls.maps.xammap.v{ProductVersion}~infragistics.controls.maps.xammap~windowanimationduration.html[WindowAnimationDuration] properties respectively.

There are three scenarios that you need to consider while using map window animation:

* If the map is composed of map layer(s) and map tile source provider then animation for zooming and panning respects WindowAnimationMode and WindowAnimationDuration values;
* If the map contains only map layer(s) then animation is done according to WindowAnimationMode and WindowAnimationDuration values;
* If the map contains only map tile source provider then the animation is done according to the algorithm in the link:{ApiPlatform}controls.maps.xammap.v{ProductVersion}~infragistics.controls.maps.mapviewport~multiscaleimage.html[MultiScaleImage] property’s type object.

The following table lists all supported animation modes and their description.

[options="header", cols="a,a"]
|====
|WindowAnimationMode|Description

| link:{ApiPlatform}controls.maps.xammap.v{ProductVersion}~infragistics.controls.maps.mapwindowanimationmode.html[None]
|Map window steps from one position to another and the WindowAnimationDuration is ignored.

| link:{ApiPlatform}controls.maps.xammap.v{ProductVersion}~infragistics.controls.maps.mapwindowanimationmode.html[Linear]
|Map window moves at constant speed from one position to another using the WindowAnimationDuration

| link:{ApiPlatform}controls.maps.xammap.v{ProductVersion}~infragistics.controls.maps.mapwindowanimationmode.html[Logarithmic]
|Map window moves smoothly from one position to another using the WindowAnimationDuration

| link:{ApiPlatform}controls.maps.xammap.v{ProductVersion}~infragistics.controls.maps.mapwindowanimationmode.html[Trigonometric]
|Map window accelerates and decelerates from one position to another using the WindowAnimationDuration

|====

The following snippet shows how to add logarithmic map window animation with 2-seconds duration in the link:{ApiPlatform}controls.maps.xammap.v{ProductVersion}~infragistics.controls.maps.xammap.html[xamMap] control.

*In XAML:*

----
<ig:XamMap x:Name="igMap" 
           WindowAnimationMode="Logarithmic"
           WindowAnimationDuration="0:0:2" >
</ig:XamMap>
----

*In Visual Basic:*

----
Me.igMap.WindowAnimationMode = MapWindowAnimationMode.Logarithmic
Me.igMap.WindowAnimationDuration = TimeSpan.FromMilliseconds(2000)
----

*In C#:*

----
this.igMap.WindowAnimationMode = MapWindowAnimationMode.Logarithmic;
this.igMap.WindowAnimationDuration = TimeSpan.FromMilliseconds(2000);
----

== Related Topics

* link:xamwebmap-map-elements.html[Display Map Elements]
* link:xamwebmap-map-panes.html[Display Map Panes]
* link:xamwebmap-using-multiple-layers.html[Using Multiple Layers]