////

|metadata|
{
    "name": "xammap",
    "controlName": ["xamMap"],
    "tags": ["Getting Started"],
    "guid": "{D6B680C7-BC02-4317-A2BE-B4D73CA1976C}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:57.3112388Z"
}
|metadata|
////

= xamMap

This section gives you an overview of the use of the link:{ApiPlatform}controls.maps.xammap{ApiVersion}~infragistics.controls.maps.xammap.html[xamMap]™ control, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish common tasks using the control.

The xamMap control displays data in the form of maps. The map shape depends on the Shapefile—a geospatial vector data format that describes points, polylines, and polygons. Points may describe cities, polylines may describe roads, and polygons may describe states.

The xamMap control uses map projections to visualize map shapes. The SphericalMercator projection is the default map projection. This control can read Shapefiles with various coordinate systems as well as display a map with a selection of map projections. In addition, the xamMap can display geo-imagery data from external sources.

In addition to displaying shape data, xamMap provides an arsenal of features that makes viewing and interacting with maps captivating and productive. These features include:

* *Map Layers* – Multiple maps can be used allowing for a complex layering of map elements; e.g. states, cities, and roads.
* *Geo-Imagery* – Geo-Imagery maps can be used allowing for even more complex map elements; e.g. terrain types, road types/names, building types, and much more.
* *Interactive Map Elements* – The representation of the shapes in a map can respond to user actions enhancing the user experience.
* *Comprehensive Color Model* – The presentation of maps are enhanced with rich but simple ways to color the map elements.
* *Data Binding* – In addition to data from Shapefiles and Geo-Imagery, xamMap can associate other data sources with map elements using the data binding and data mapping features.
* *Helper Panes and Child Controls* – Additional controls are available in the xamMap control library to further enhance the user experience, such as navigational, color swatch, thumbnail and scale panes.

Click the links below to access important information about the xamMap control.

== link:xamwebmap-understanding-xamwebmap.html[Understanding xamMap]

In this section you’ll find any information that will help you to better understand the functionalities of the xamMap control, as well as why you would want to use it as part of building your applications.

== link:xamwebmap-getting-started-with-xamwebmap.html[Getting Started with xamMap]

In order to get you up and running as quickly as possible with the xamMap control, we've provided you with information on how to get started using the control.

== link:xamwebmap-using-xamwebmap.html[Using xamMap]

This section contains information on the key features and functionalities provided by the xamMap control.

== link:xamwebmap-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamMap control. The namespaces and classes listed in this topic link conveniently into the link:xamwebmap-api-overview.html[API Reference Guide] section of the {ProductName} help.