////

|metadata|
{
    "name": "xammenu",
    "controlName": ["xamMenu"],
    "tags": ["Getting Started"],
    "guid": "c75165cb-a35a-4476-a443-9933ae04adf3",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:57.3242394Z"
}
|metadata|
////

= xamMenu

This section gives you an overview of the use of xamMenu™. This section contains valuable information about xamMenu, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish common tasks using the control. Click the links below to access important information about the xamMenu control.

== link:xammenu-understanding-xammenu.html[About xamMenu]

In this section you’ll find any information that will help you to better understand the functionalities of the xamMenu control, as well as why you would want to use it as part of building your applications.

== link:xammenu-getting-started-with-xammenu.html[Adding xamMenu to Your Page]

In order to get you up and running as quickly as possible with the xamMenu control, we've provided you with information on how to get started using the control.

== link:xammenu-using-xammenu.html[Using xamMenu]

This section contains information on the key features and functionalities provided by the xamMenu control.

== link:xammenu-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamMenu control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the {ProductName} help.