////

|metadata|
{
    "name": "xammulticolumncomboeditor",
    "controlName": ["xamMultiColumnComboEditor"],
    "tags": ["Getting Started"],
    "guid": "e0dfd655-2cdc-4fc0-b8c8-97af554625b5",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:57.5372503Z"
}
|metadata|
////

= xamMultiColumnComboEditor

This section contains information about xamMultiColumnComboEditor™ control, ranging from what the control does and step-by-step procedures on using it in your application.

Click the links below to access important information about xamMultiColumnComboEditor.

== link:xammulticce-about.html[About xamMultiColumnComboEditor]

In this section you'll find information that will help you to better understand the functionalities of xamMultiColumnComboEditor.

== link:xammulticce-adding.html[Adding xamMultiColumnComboEditor to Your Page]

In order to get you up and running as quickly as possible with xamMultiColumnComboEditor, we've provided you with information on how to get started using the control.

== link:xammulticce-configuring-xammulticolumncomboeditor.html[Using xamMultiColumnComboEditor]

This section contains information on the key features and functionalities provided by xamMultiColumnComboEditor.

== link:xammulticce-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with xamMultiColumnComboEditor. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.