////

|metadata|
{
    "name": "xammenu-using-xammenu",
    "controlName": ["xamMenu"],
    "tags": ["Getting Started"],
    "guid": "{0381C6B0-A160-442C-B9EF-38D39C91CA83}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:57.3462542Z"
}
|metadata|
////

= Using xamMenu

This section is your gateway to important conceptual and task-based information that will help you to use the various features and functionalities provided by the xamMenu™ control.

link:xammenu-binding-to-data.html[Binding to Data]

This topic describes how you can bind the xamMenu and the xamContextMenu to hierarchical data.

link:xammenu-layout-settings.html[Layout Settings]

This topic describes how you can configure different xamMenu control's layout properties - MenuOrientation, SubmenuPreferredLocation, ExpandOnHover and etc.

link:xammenu-navigating-pages-using-xammenu.html[Navigating Pages Using xamMenu]

This topic describes how you can use the xamMenu control along with the Navigation Framework to navigate to a new XAML page.

link:xammenu-adding-and-removing-items.html[Adding and Removing Items]

This topic describes how you can add or remove xamMenuItems.

link:xammenu-adding-separators-between-xammenuitems.html[Adding Separators between XamMenuItems]

This topic describes how you can add separator lines to distinguish the xamMenu items.

link:xammenu-adding-icons-to-xammenuitems.html[Adding Icons to XamMenuItems]

This topic describes how you can add icons for items in the xamMenu control.

link:xammenu-adding-check-boxes-to-xammenuitems.html[Adding Check Boxes to XamMenuItems]

This topic describes how you can display check boxes for each of xamMenu's items.