////

|metadata|
{
    "name": "xammonthcalendar",
    "controlName": ["xamMonthCalendar"],
    "tags": [],
    "guid": "{C86A37FA-C7C7-4EC4-80E5-444E831DD568}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:53.9751481Z"
}
|metadata|
////

= xamMonthCalendar

This section contains information about xamMonthCalendar™, ranging from what the control does and step-by-step procedures on using it in your application.

Click the links below to access important information about the xamMonthCalendar control.

== link:xammonthcalendar-about-xammonthcalendar.html[About xamMonthCalendar]

In this section you'll find information that will help you to better understand the functionalities of the xamMonthCalendar control.

== link:xammonthcalendar-getting-started-with-xammonthcalendar.html[Adding xamMonthCalendar to Your Page]

In order to get you up and running as quickly as possible with the xamMonthCalendar control, we've provided you with information on how to get started using the control (e.g., adding xamMonthCalendar to your Window).

== link:xammonthcalendar-using-xammonthcalendar.html[Using xamMonthCalendar]

This section contains information on the key features and functionalities provided by the xamMonthCalendar control.

== link:xammonthcalendar-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamMonthCalendar control. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.