////

|metadata|
{
    "name": "xamnetworknode-api-overview",
    "controlName": ["xamNetworkNode"],
    "tags": ["API"],
    "guid": "81b43e60-4731-48c1-95e7-88b5a8ff6d11",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:57.4282454Z"
}
|metadata|
////

= API Overview

This section lists each namespace that is relevant to the link:{ApiPlatform}controls.maps.xamnetworknode{ApiVersion}~infragistics.controls.maps.xamnetworknode.html[xamNetworkNode]™ control. We also give you several key classes that you will be using while programming with this control. The namespaces and classes on this page link directly into our API documentation.

=== XamNetworkNode Namespace:

link:{ApiPlatform}controls.maps.xamnetworknode{ApiVersion}~infragistics.controls.maps_namespace.html[Infragistics.Controls.Maps]

=== KeyClasses:

* link:{ApiPlatform}controls.maps.xamnetworknode{ApiVersion}~infragistics.controls.maps.xamnetworknode.html[XamNetworkNode]
* link:{ApiPlatform}controls.maps.xamnetworknode{ApiVersion}~infragistics.controls.maps.networknodenodelayout.html[NetworkNodeNodeLayout]