////

|metadata|
{
    "name": "xamnumericeditor",
    "controlName": ["xamNumericEditor"],
    "tags": [],
    "guid": "{05236760-8A94-47B5-B34E-C5A0E47A21A0}",  
    "buildFlags": [],
    "createdOn": "2012-09-05T19:05:30.2229781Z"
}
|metadata|
////

= xamNumericEditor

If you're looking for an area that houses all of the overview/task-based information related to the xamNumericEditor™ control, you've come to the right place. This section contains valuable information about xamNumericEditor, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the xamNumericEditor control.

* link:xamnumericeditor-about-xamnumericeditor.html[About xamNumericEditor]
* link:xameditors-overview-of-the-valueeditor-class.html[Overview of the ValueEditor Class]
* link:xameditors-masks.html[Masks]
* link:xamnumericeditor-using-xamnumericeditor-as-a-field-in-xamdatagrid.html[Using xamNumericEditor as a Field in xamDataGrid]
* link:xameditors-enabling-right-to-left-support.html[Enabling Right to Left Support]
* link:xameditors-working-with-the-isalwaysineditmode-property-and-the-editors.html[Working with the IsAlwaysInEditMode Property and the Editors]
* link:xamnumericeditor-api-overview.html[API Overview]