////

|metadata|
{
    "name": "xamoutlookbar",
    "controlName": ["xamOutlookBar"],
    "tags": [],
    "guid": "{D2ECEDBC-F529-4CC0-B626-F5AC37886299}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:54.0251581Z"
}
|metadata|
////

= xamOutlookBar

This section contains information about xamOutlookBar™, ranging from what the control does and step-by-step procedures on using it in your application.

Click the links below to access important information about the xamOutlookBar control.

== link:xamoutlookbar-about-xamoutlookbar.html[About xamOutlookBar]

In this section you'll find information that will help you to better understand the functionalities of the xamOutlookBar control.

== link:xamoutlookbar-adding-xamoutlookbar-to-your-page.html[Adding xamOutlookBar to Your Application]

In order to get you up and running as quickly as possible with the xamOutlookBar control, we've provided you with information on how to get started using the control.

== link:xamoutlookbar-using-xamoutlookbar.html[Using xamOutlookBar]

This section contains information on the key features and functionalities provided by the xamOutlookBar control.

== link:xamoutlookbar-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamOutlookBar control. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.