////

|metadata|
{
    "name": "xamoutlookbar-using-xamoutlookbar",
    "controlName": ["xamOutlookBar"],
    "tags": [],
    "guid": "{E7CC8ADB-DEB3-404D-8B12-30A7F5172C85}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:54.0511633Z"
}
|metadata|
////

= Using xamOutlookBar

This section is your gateway to important task-based information that will help you to effectively use the various features and functionalities provided by xamOutlookBar™.

link:xamoutlookbar-about-styling-xamoutlookbar.html[About Styling xamOutlookBar]

This topic describes some styling points that can help you to customize the xamOutlookBar control's look.

link:xamoutlookbar-add-groups-to-xamoutlookbar.html[Add Groups to xamOutlookBar]

This topic describes how you can add groups to display content to the xamOutlookBar control.

link:xamoutlookbar-add-content-to-a-group.html[Add Content to a Group]

This topic describes how you can add content to the group's items in the xamOutlookBar control.

link:xamoutlookbar-collapse-xamoutlookbar.html[Collapse xamOutlookBar]

This topic describes how you can collapse the xamOutlookBar control using IsMinimized property.

link:xamoutlookbar-select-a-group.html[Select a Group]

This topic describes how you can define the initially selected group.