////

|metadata|
{
    "name": "xampivotgrid-integration-with-other-controls",
    "controlName": ["xamPivotGrid"],
    "tags": ["Charting","Getting Started","Grids"],
    "guid": "55b8ff97-1253-476d-98ad-9e7ebcee4c05",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:58.142291Z"
}
|metadata|
////

= Integration with Other Controls (xamPivotGrid)

=== Introduction

The link:{ApiPlatform}controls.grids.xampivotgrid.v{ProductVersion}~infragistics.controls.grids.xampivotgrid_members.html[xamPivotGrid™], the link:{ApiPlatform}controls.grids.xampivotgrid.v{ProductVersion}~infragistics.controls.grids.xampivotdataselector_members.html[xamPivotDataSelector™] and the data source ViewModels ( link:{ApiPlatform}olap.flatdata.v{ProductVersion}~infragistics.olap.flatdata.flatdatasource_members.html[FlatDataSource], link:{ApiPlatform}olap.xmla.v{ProductVersion}~infragistics.olap.xmla.xmladatasource_members.html[XmlaDataSource], etc.) can be used together with other Infragistics® controls.

=== Topics

Detailed information regarding integration of the pivot grid and its related components is covered in the following topics:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xampivotgrid-integration-with-chart.html[Integration with Data Chart]
|The topic demonstrates how to build interaction between the xamPivotGrid™ and the link:{ApiPlatform}controls.charts.xamdatachart.v{ProductVersion}~infragistics.controls.charts.xamdatachart_members.html[xamDataChart™] controls.

|====

== Related Content

=== Samples

The following samples provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Sample|Purpose

|
ifdef::sl[] 

link:{SamplesURL}/pivot-grid/#/integration-with-datachart[Integration with DataChart] 

endif::sl[] 

ifdef::wpf[] 

link:{SamplesURL}/pivot-grid/integration-with-datachart[Integration with DataChart] 

endif::wpf[] 

|This sample demonstrates the XamPivotGrid integration with XamDataChart. A new axis has been added to XamDataChart called OLAPAxis, which can be bound to the same data source as the pivot grid to display the Rows or Columns of pivot grid data on the DataChart.

|
ifdef::sl[] 

link:{SamplesURL}/pivot-grid/#/dataselector-with-no-grid[DataSelector with no grid] 

endif::sl[] 

ifdef::wpf[] 

link:{SamplesURL}/pivot-grid/dataselector-with-no-grid[DataSelector with no grid] 

endif::wpf[] 

|This sample shows that you can work with raw data only, without using the xamPivotGrid to visualize the result.

|====