////

|metadata|
{
    "name": "xampropertygrid-commands",
    "tags": ["Commands","How Do I"],
    "controlName": ["xamPropertyGrid"],
    "guid": "1e847edb-ef6f-4949-bf44-82d3273a7ea4",  
    "buildFlags": [],
    "createdOn": "2014-08-28T11:08:01.036596Z"
}
|metadata|
////

= Working with Commands (xamPropertyGrid)

== Topic Overview

=== Purpose

This topic explains how to perform different operations with the control using commands.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xampropertygrid-features-overview.html[Features Overview (xamPropertyGrid)]
|This topic explains the features supported by the control from developer perspective.

| link:xampropertygrid-visual-elements.html[Visual Elements (xamPropertyGrid)]
|This topic provides an overview of the visual elements of the control.

|====

=== In this topic

This topic contains the following sections:

* <<_Ref394931540, Commands Introduction >>
* <<_Ref394931554, Code Example: Invoking a Command in XAML >>
* <<_Ref394931560, Code Example: Invoking a Command in XAML with Parameter >>
* <<_Ref394931561, Code Example: Invoking a Command in Code >>
* <<_Ref394931565, Related Content >>

[[_Ref394931540]]
== Commands Introduction

=== Commands summary

The link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.xampropertygrid_members.html[ _xamPropertyGrid_  ] control provides a lot of commands for activating different features. You can find the full list of commands in the link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.propertygridcommandtype.html[PropertyGridCommandType] enumeration.

You can invoke commands by instantiating the link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.primitives.propertygridcommandsource_members.html[PropertyGridCommandSource] type. The following commands however require a link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.propertygridpropertyitem_members.html[PropertyGridPropertyItem] parameter to be supplied and they are invoked by instantiating the link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.primitives.propertygridpropertyitemcommandsource_members.html[PropertyGridPropertyItemCommandSource] type:

* `AddListEntry`
* `RemoveListEntry`
* `ResetPropertyValue`
* `CreateExpandableObject`
* `ShowOptionsMenu`

[[_Ref394931554]]
== Code Example: Invoking a Command in XAML

=== Description

The following code snippet shows how to invoke a command in XAML on the  _xamPropertyGrid_   control using a button. The code snippet assumes you have a reference to a  _xamPropertyGrid_   instance named "xamPropertyGrid1".

=== Code

*In XAML:*

[source,xaml]
----
<Page
  …
  xmlns:ig="http://schemas.infragistics.com/xaml"
  xmlns:igPrim="http://schemas.infragistics.com/xaml/primitives"
  …>
<Button
  Content="Sort By Category"
  ig:Commanding.CommandTarget="{Binding ElementName=xamPropertyGrid1}">
  <ig:Commanding.Command>
    <igPrim:PropertyGridCommandSource
      EventName="Click"
      CommandType="SortByCategory" />
  </ig:Commanding.Command>
</Button>
----

[[_Ref394931560]]
== Code Example: Invoking a Command in XAML with Parameter

=== Description

The following code snippet shows how to invoke a command with parameter in XAML on the  _xamPropertyGrid_   control using a button. The code snippet assumes you have a reference to a  _xamPropertyGrid_   instance named "xamPropertyGrid1".

=== Code

*In XAML:*

[source,xaml]
----
<Page
  …
  xmlns:ig="http://schemas.infragistics.com/xaml"
  xmlns:igPrim="http://schemas.infragistics.com/xaml/primitives"
  …>
<Button
  Content="Reset Current Property Value"
  ig:Commanding.CommandTarget="{Binding ElementName=xamPropertyGrid1}">
  <ig:Commanding.Command>
    <igPrim:PropertyGridPropertyItemCommandSource
      EventName="Click"
      CommandType="ResetPropertyValue"
      ParameterBinding="{Binding ElementName=xamPropertyGrid1, Path=SelectedItem}" />
  </ig:Commanding.Command>
</Button>
----

[[_Ref394931561]]
== Code Example: Invoking a Command in Code

=== Description

The following code snippet shows how to invoke a command in code on the  _xamPropertyGrid_   control. The code snippet assumes you have a reference to a  _xamPropertyGrid_   instance named "xamPropertyGrid1".

=== Code

Following is the code that implements this example.

*In C#:*

[source,csharp]
----
using Infragistics.Controls.Editors;
using Infragistics.Controls.Editors.Primitives;
...
PropertyGridCommand cmd = new PropertyGridCommand(PropertyGridCommandType.SortByCategory);
cmd.Execute(this.xamPropertyGrid1);
----

*In Visual Basic:*

[source,vb]
----
Import Infragistics.Controls.Editors
Import Infragistics.Controls.Editors.Primitives
...     
Dim cmd As New PropertyGridCommand(PropertyGridCommandType.SortByCategory)
cmd.Execute(Me.xamPropertyGrid1)
----

[[_Ref394931565]]
== Related Content

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xampropertygrid-work-expandable-properties.html[Expandable Properties Support (xamPropertyGrid)]
|This topic explains how the control identifies and displays expandable properties.

| link:xampropertygrid-property-item-generators.html[Property Item Generators (xamPropertyGrid)]
|This topic explains how the control discovers properties on the selected object(s), generates the list of property items and how the process can be configured and customized.

| link:xampropertygrid-resetting-property-value.html[Resetting Property Value (xamPropertyGrid)]
|This topic explains how to define default property value and how to customize the options menu.

|====