////
|metadata|
{
    "name": "xampivotgrid-saving-and-loading-grid-customizations",
    "controlName": ["xamPivotGrid"],
    "tags": ["Grids","How Do I","Persistence"],
    "guid": "4f8c17c2-ed78-4591-bdd8-c8bd46bb7075",
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:58.2823314Z"
}
|metadata|
////

= Saving and Loading User Customizations (xamPivotGrid)

== Topic Overview

=== Purpose

This topic explains how to save and load the user customizations made to the way the data is presented in the  _xamPivotGrid_™ control.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xampivotgrid-binding-data-to-the-xampivotgrid.html[Binding Data to the xamPivotGrid]
|This topic serves as an overview of the data sources supported by the _xamPivotGrid_ control.

| link:xampivotgrid-interaction-with-xampivotgrid.html[Interaction with xamPivotGrid]
|This is a group of topics explaining the main interactions with the _xamPivotGrid_ control that can be performed either through the UI or in code.

|====

=== In this topic

This topic contains the following sections:

* <<_Ref347827418,Saving and Loading Data Source Customizations – Overview>>

** <<_Ref347827428,User-customizable aspects of the grid View>>
** <<_Ref347827436,Saving and Loading Data Source Customizations summary>>
** <<_Ref347827457,Requirements>>
** <<_Ref347827459,Properties Saved Upon Customization>>

* <<_Ref347827476,Saving a Data Source Customization – Code Example>>

** <<_Ref347827481,Description>>
** <<_Ref347765476,Code>>

* <<_Ref347827509,Loading Data Source Customizations – Procedure>>

** <<_Ref347827521,Introduction>>
** <<_Ref347827524,Prerequisites>>
** <<_Ref347827527,Overview>>
** <<_Ref347827529,Steps>>

* <<_Ref347827534,Related Content>>

** <<_Ref347827539,Samples>>

[[_Ref347827418]]
== Saving and Loading Data Source Customizations – Overview

[[_Ref347827428]]

=== User-customizable aspects of the grid View

In  _xamPivotGrid_, users can customize the View presenting the data slide in the following aspects:

* Selected database
* Selected cube
* Selected measure group
* Current hierarchies used in rows, columns, filters
* Current measures
* Location of the measure list view model (if applicable)
* Expansion states of filter members
* Selection states of filter members
* Expansion states of members (for rows and columns)
* Currently applied sort orders (for both values and member names within a level)
* Applied Excel®-style filters (Advanced filters)
* Deferred layout update state

The information about these customization aspects is stored in the data source controls ( _FlatDataSource_™ and  _XmlaDataSource_™) used by the  _xamPivotGrid_   control and and in the  _OlapXAxis_™ component of the  _xamDataChart_™ control and can be saved and consequently loaded.

[[_Ref347827436]]

=== Saving and Loading Data Source Customizations summary

[[_Saving_customizations]]
[[_Ref347827438]]
==== Saving customizations

In order to save the current view of  _xamPivotGrid_  , you need to save the current values of the properties that define that view. All relevant information is available in the data source instance set as the value of the link:{ApiPlatform}controls.grids.xampivotgrid.v{ProductVersion}~infragistics.controls.grids.xampivotgrid~datasource.html[DataSource] property of the  _xamPivotGrid_  . The link:{ApiPlatform}olap.v{ProductVersion}~infragistics.olap.datasourcebase_members.html[DataSourceBase] class (from which all other multi-dimensional (OLAP) data sources inherit) exposes extension methods for saving and loading the current state of the data source. The customizations can be written to either a string or in a stream.

The actual saving is done by the link:{ApiPlatform}olap.v{ProductVersion}~infragistics.olap.datasourcebaseextension~savecustomizations.html[SaveCustomizations] method. There are two overloads for this method. One returns a string containing the saved customizations, and the other expects a stream into which the customizations are written. You invoke one of them depending on your preferences.

[[_Ref347827441]]
==== Loading customizations

The link:{ApiPlatform}olap.v{ProductVersion}~infragistics.olap.datasourcebaseextension~loadcustomizations.html[LoadCustomizations] methods load previously <<_Saving_customizations,>><<_Ref347827438,saved customizations>>. Saved customizations can be loaded from a string or stream. In addition to this, in both cases, an Action can be specified to be executed when the load has completed. Therefore there are four overloads of the `LoadCustomizations` method, one for each parameter combination.

In practice, the implementation of the loading usually goes together with configuring of some post-load action. For example, because the process of loading the customizations may take some time, you may want to execute some custom code when it is finished, or be notified for its completion. To do this, call one of the `LoadCustomizations` overloads that accept an action parameter. When the load process finishes, the action is executed. The action accepts a string parameter which will contain descriptions of the errors that occurred during the load process if such errors have occurred.

[[_Ref347827457]]

=== Requirements

Following are the general requirements for saving and loading customizations:

* Data requirements

In order for a set of customizations to load, the source and destination data sources must have the same database (metadata) structure. Otherwise the load process will either fail or be incomplete.

* References
** Defining the link:{ApiPlatform}olap.v{ProductVersion}~infragistics.olap.datasourcebaseextension~savecustomizations.html[SaveCustomizations] and link:{ApiPlatform}olap.v{ProductVersion}~infragistics.olap.datasourcebaseextension~loadcustomizations.html[LoadCustomizations] extension methods for the `DataSourceBase` class in the `Infragistics.Olap` namespace
** `using`/`Imports` directive to the `Infragistics.Olap` namespace

[[_Ref347827459]]

=== Properties Saved Upon Customization

The following table maps the configurable aspects that are saved by the link:{ApiPlatform}olap.v{ProductVersion}~infragistics.olap.datasourcebaseextension~savecustomizations.html[SaveCustomizations] methods to the values of the respective properties and the data source type to which they apply.

[options="header", cols="a,a,a"]
|====
|Configurable aspect|Data Source Property|Applicable to:

|Selected Database
|`XmlaDataSource.Database`
| _XmlaDataSource_ 

|Selected cube
|`XmlaDataSource.Cube`
| _XmlaDataSource_ 

|Selected Measure group
|`XmlaDataSource.MeasureGroup`
| _XmlaDataSource_ 

|Used hierarchies for rows, columns, filters
|`DataSourceBase.Rows` 

`DataSourceBase.Columns` 

`DataSourceBase.Filters`
|All data sources

|Used measures
|`DataSourceBase.Measures`
|All data sources

|Location of the measure list View model (if applicable)
|`DataSourceBase.MeasureListLocation`
|All data sources

|Expansion states of filter members
|`IFilterMember.IsExpanded` for the filter members in all `IFilterViewModels` used in the rows, columns, and filters
|All data sources

|Selection states of filter members
|`IFilterMember.IsSelected` for the filter members in all `IFilterViewModels` used in the rows, columns, and filters
|All data sources

|Expansion states of members (for rows and columns)
|The result of the call for `TupleResolver.IsMemberExpanded`, for each member in the row and column tuples.
|All data sources

|Applied sort orders (for both values and member names within a level)
|`DataSourceBase.LevelSortDirections` 

`DataSourceBase.SortDescriptors`
|All data sources

|Applied Excel-style filters (advanced filters)
|`ISupportFilters.FilterExpressions`
| _XmlaDataSource_ 

|Deferred layout update state
|`DataSourceBase.DeferredLayoutUpdate`
|All data sources

|====

[[_Ref347827476]]
== Saving a Data Source Customization – Code Example

[[_Ref347827481]]

=== Description

The following procedure demonstrates the process of saving the customizations for a data source. To save the user customizations, one of the link:{ApiPlatform}olap.v{ProductVersion}~infragistics.olap.datasourcebaseextension~savecustomizations.html[SaveCustomizations] methods is called. The example <<_Ref347765476,Code>> assumes that a variable of type link:{ApiPlatform}olap.v{ProductVersion}~infragistics.olap.datasourcebase_members.html[DataSourceBase] (or a class inherited from it) named `dataSource` holds a reference to a data source object.

[[_Ref347765476]]

=== Code

[[_Ref347827490]]
==== Saving a customization to a string

*In C#:*

[source,csharp]
----
String customizations = dataSource.SaveCustomizations();
----

*In Visual Basic:*

[source,vb]
----
Dim customizations = dataSource.SaveCustomizations()
----

[[_Ref347827492]]
==== Saving a customization to a stream

*In C#:*

[source,csharp]
----
using (Stream stream = [initialize the stream here])
{
    dataSource.SaveCustomizations(stream);
}
----

*In Visual Basic:*

[source,vb]
----
Using stream As [initialize the stream here]
   dataSource.SaveCustomizations(stream)
End Using
----

[[_Ref347827509]]
== Loading Data Source Customizations – Procedure

[[_Ref347827521]]

=== Introduction

The following procedure loads a previously saved customization of a multi-dimensional (OLAP) data source.

The procedure contains an optional step of configuring a post-load action which, in this case, is displaying load errors in a message box. To that purpose, a sample method (`LoadCompletedAction`) is defined.

[[_Ref347827524]]

=== Prerequisites

To complete the procedure, you need the following:

* A variable of type link:{ApiPlatform}olap.v{ProductVersion}~infragistics.olap.datasourcebase_members.html[DataSourceBase] (or a class inherited from it) named `dataSource` holding a reference to a data source object

[[_Ref347827527]]

=== Overview

Following is a conceptual overview of the process:

*1.  _(Optional)_  Defining a post-load action*

*2. Calling the `LoadCustomizations` method*

[[_Ref347827529]]

=== Steps

The following demonstrate how to load a customization.
[start=1]
. (Optional) Define a post-load action.

The following code snippet defines a sample method which displays the load errors in a message box:

*In C#:*

[source,csharp]
----
public void LoadCompletedAction(string loadErrors)
{
   if(!string.IsNullOrWhiteSpace(loadErrors))
   {
     MessageBox.Show(loadErrors);
   }
}
----

*In Visual Basic:*

[source,vb]
----
Public Sub LoadCompletedAction(loadErrors As String)
      If Not String.IsNullOrWhiteSpace(loadErrors) Then
            MessageBox.Show(loadErrors)
      End If
End Sub
----

[start=2]
. Call the LoadCustomizations method.

To load customizations that have been earlier saved to a string or a stream, call one of the `LoadCustomization` methods passing the `String` or `Stream` argument.

The following code snippet demonstrates how to load a customization from a string when passing an action argument.

*In C#:*

[source,csharp]
----
dataSource.LoadCustomizations(customizations, LoadCompletedAction);
// or
using(Stream customizations = [initialize stream here])
{
   dataSource.LoadCustomizations(customizations, LoadCompletedAction);
}
----

*In Visual Basic:*

[source,vb]
----
dataSource.LoadCustomizations(customizations, LoadCompletedAction)
‘ or
Using stream As [initialize the stream here]
   dataSource.LoadCustomizations(customizations, LoadCompletedAction)
End Using
----

If you prefer not to specify the action parameter (`LoadCompletedAction`), use the overloads of the `LoadCustomizations` methods that accept only one argument.

[[_Ref347827534]]
== Related Content

[[_Ref347827539]]

=== Samples

The following samples provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Sample|Purpose

|
ifdef::sl[] 

link:{SamplesURL}/pivot-grid/#/save-and-load-data-source-customizations[Save and Load Data Source Customizations ( _xamPivotGrid_ )] 

endif::sl[] 

ifdef::wpf[] 

link:{SamplesURL}/pivot-grid/save-and-load-data-source-customizations[Save and Load Data Source Customizations ( _xamPivotGrid_ )] 

endif::wpf[] 

|This sample demonstrates saving and loading the user customizations made to the _xamPivotGrid_ .

|====