////

|metadata|
{
    "name": "xampivotgrid-enabling-advanced-filtering",
    "controlName": ["xamPivotGrid"],
    "tags": ["Drilldown","Filtering","Grids","How Do I"],
    "guid": "6d27b2ae-5fe0-4ac9-a3e0-37ce2b6250ee",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:58.2703315Z"
}
|metadata|
////

= Enabling Excel-Style Filtering (xamPivotGrid, xamPivotDataSelector)

== Topic Overview

=== Purpose

This topic explains how to enable the Microsoft® Excel®-Style Filtering feature of the  _xamPivotGrid_™/ _xamPivotDataSelector_™ controls.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xampivotgrid-understanding-xampivotgrid.html[xamPivotGrid Overview]
|This topic introduces the _xamPivotGrid_ control and its key features and functionalities. _xamPivotGridxamPivotGrid_

| link:xampivotgrid-getting-started-with-xampivotgrid.html[Getting Started with xamPivotGrid]
|This topic demonstrates how to get started with the _xamPivotGrid_ control by providing step-by-step procedure for adding this control to a Silverlight® application.

| link:xampivotgrid-dataselector.html[DataSelector]
|This topic is an introduction to the _xamPivotDataSelector_ control.

| link:xampivotgrid-excel-style-filtering-overview-and-user-functionality.html[Excel-Style Filtering Overview and User Functionality (xamPivotGrid, xamPivotDataSelector)]
|This topic explains the Excel-Style Filtering feature of the _xamPivotGrid_ and its user functionality and interactions.

|====

=== In this topic

This topic contains the following sections:

* <<_Ref332040821,Introduction>>
* <<_Ref333607318,Enabling Excel-Style Filtering>>

** <<_Ref332040869,Property settings>>
** <<_Ref333607340,Considerations>><<_Ref332040872,>>

* <<_Ref332040900,Related Content>>

** <<_Ref332040893,Samples>>

[[_Ref332040821]]
== Introduction

=== Enabling Excel-style filtering summary

When Excel-Style Filtering in the  _xamPivotGrid_   control and the data selector is enabled, users can add custom filter conditions for the measure values and for the captions of members from the row and column hierarchies.

By default, Excel-Style Filtering in the  _xamPivotGrid_   is not enabled, so you need to explicitly enable it by setting the link:{ApiPlatform}controls.grids.xampivotgrid.v{ProductVersion}~infragistics.controls.grids.xampivotdataselector~enableadvancedfiltering.html[EnableAdvancedFiltering] property to  _True._   This property is available for both the  _xamPivotGrid_   and the link:{ApiPlatform}controls.grids.xampivotgrid.v{ProductVersion}~infragistics.controls.grids.xampivotdataselector_members.html[XamPivotDataSelector].

[[_Ref332040841]]
[[_Ref333607318]]
== Enabling Excel-Style Filtering

[[_Ref332040869]]

=== Property settings

The following table maps the desired configuration to property settings.

[options="header", cols="a,a,a"]
|====
|In order to:|Use this property:|And set it to:

|Enable the Excel-Style Filtering UI in the pivot grid.
| link:{ApiPlatform}controls.grids.xampivotgrid.v{ProductVersion}~infragistics.controls.grids.xampivotgrid~enableadvancedfiltering.html[XamPivotGrid.EnableAdvancedFiltering]
|`True`

|Enable the Excel-Style Filtering UI in the data selector.
| link:{ApiPlatform}controls.grids.xampivotgrid.v{ProductVersion}~infragistics.controls.grids.xampivotdataselector~enableadvancedfiltering.html[XamPivotDataSelector.EnableAdvancedFiltering]
|`True`

|====

[[_Ref333607340]]

=== Considerations

When using Excel-Style Filtering there are a few things you should keep in mind:

* In order to enable Excel-Style Filtering, the data source set as the link:{ApiPlatform}controls.grids.xampivotgrid.v{ProductVersion}~infragistics.controls.grids.xampivotgrid~datasource.html[DataSource] property of the pivot grid/data selector must implement the link:{ApiPlatform}olap.v{ProductVersion}~infragistics.olap.data.isupportfilters_members.html[ISupportFilters] interface. Currently this interface is implemented in the link:{ApiPlatform}olap.xmla.v{ProductVersion}~infragistics.olap.xmla.xmladatasource_members.html[XmlaDataSource].
* The default value of link:{ApiPlatform}controls.grids.xampivotgrid.v{ProductVersion}~infragistics.controls.grids.xampivotdataselector~enableadvancedfiltering.html[EnableAdvancedFiltering] is `False`.
* The `EnableAdvancedFiltering` property should be set before any items are added to the columns, rows, filters or measures of the pivot grid or the data selector. This means that if you want to set the property in code (rather than XAML) and there are initial items in columns, rows etc., you should set it before the pivot grid is initialized. For example, a suitable place to set the property in code is the constructor of the Page/UserControl, where the pivot grid or data selector is used. Setting the property should be after `InitializeComponent``(``)` has been called.
* Changing the value of the `EnableAdvancedFiltering` property at run-time does not change the existing UI filtering controls in the grid or data selector. However, all hierarchies that are added to the rows, columns, filters, or measures after that will support Excel-Style Filtering or not based on the value that was set to `EnableAdvancedFiltering`.

[[_Ref332040900]]
== Related Content

[[_Ref332040893]]

=== Samples

The following samples provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Sample|Purpose

|pick:[sl=" link:{SamplesURL}/pivot-grid/#/excel-style-filtering[Excel-Style Filtering]"] 

pick:[wpf=" link:{SamplesURL}/pivot-grid/excel-style-filtering[Excel-Style Filtering]"]
|The Excel-Style filtering feature allows filtering the pivot grid values and labels by applying custom filter conditions e.g. top / bottom items, equals, less / greater than etc.

|====