////
|metadata|
{
    "name": "xampropertygrid-conf-templateselector",
    "tags": ["Editing","How Do I","Templating"],
    "controlName": ["xamPropertyGrid"],
    "guid": "dfca43ec-6d9b-4873-a2c1-16c694912895",
    "buildFlags": [],
    "createdOn": "2016-06-22T06:25:00.8638134Z"
}
|metadata|
////

= Configuring Data Template Selector for Editor Definitions (xamPropertyGrid)

== Purpose

This topic explains how create custom logic for assigning editing template on an editor definition.

== Required Background

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xampropertygrid-features-overview.html[Features Overview (xamPropertyGrid)]
|This topic explains the features supported by the control from developer perspective.

| link:xampropertygrid-visual-elements.html[Visual Elements (xamPropertyGrid)]
|This topic provides an overview of the visual elements of the control.

| link:xampropertygrid-conf-editors.html[Configuring Editors Definitions (xamPropertyGrid)]
|This topic explains how to customize the editors used for editing the properties’ values.

|====

== In This Topic

This topic contains the following sections:

* <<_RefLink01, Introduction >>
* <<_RefLink02, Providing Template Selector >>
* <<_RefLink03, Template Selector Example >>
* <<_RefLink04, Re-evaluate the Template Selector Programmatically >>
* <<_RefLink05, Related Content >>

[[_RefLink01]]
== Introduction

In some cases it may not be enough to specify a custom editor depending on its type, category or name. As an alternative approach you may use the editor definition's link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.propertygrideditordefinition~templateselector.html[TemplateSelector] property and provide an object which extends from the link:https://msdn.microsoft.com/en-us/library/system.windows.controls.datatemplateselector(v=vs.110).aspx[DataTemplateSelector] class. When a template selector is provided to an editor definition the link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.propertygrideditordefinition~edittemplate.html[EditTemplate] property and the link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.propertygrideditordefinition~readonlytemplate.html[ReadOnlyTemplate] property are ignored and the resolved template will be the one returned by the template selector's link:https://msdn.microsoft.com/en-us/library/system.windows.controls.datatemplateselector.selecttemplate(v=vs.110).aspx[SelectTemplate] method. In addition, the template selector has access to the edit template and the read-only template and can either return one of them or return any other data template based on its internal logic.

[[_RefLink02]]
== Providing Template Selector

Your custom template selector must extend from the `DataTemplateSelector` class and implements the `SelectTemplate` method. This method has the following arguments:

* `item` - this is an object of type link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.propertygridtemplateselectorcontext.html[PropertyGridTemplateSelectorContext] which gives you access to the
** link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.propertygridtemplateselectorcontext~edittemplate.html[EditTemplate] (if such is specified)
** link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.propertygridtemplateselectorcontext~readonlytemplate.html[ReadOnlyTemplate] (if such is specified)
** link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.propertygridtemplateselectorcontext~propertyitem.html[PropertyItem]

* `container` - this is a reference to the link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.xampropertygrid.html[_xamPropertyGrid_] control

Having access to the `xamPropertyGrid` control and the property item for which the control is requesting a template should be sufficient for you to provide an adequate template. In addition you have access to the editing and read-only templates specified on the editor definition. Your implementation can either return any of them or a data template based on your custom logic.

If the template selector returns `null` the `xamPropertyGrid` will use the default built-in editor for the property.

[[_RefLink03]]
== Template Selector Example

The following example shows how to create two data templates. The first data template (with key "SpinIntEditor") will be used for all properties of type Int32. The second data template (with key "SliderIntEditor") will be used by the Template Selector and will be returned and set only on the property with name "Level".

*In XAML:*
[source,xaml]
----
<Page
  …
  xmlns:ig="http://schemas.infragistics.com/xaml"
  …>
  <Page.Resources>
    <ResourceDictionary>
      <DataTemplate x:Key="SpinIntEditor">
        <igEditors:XamNumericEditor Value="{Binding Path=Value}" ValueType="{x:Type sys:Int32}"
          SpinButtonDisplayMode="Always" Theme="IGTheme" />
      </DataTemplate>
      <DataTemplate x:Key="SliderIntEditor">
        <Grid>
          <Grid.ColumnDefinitions>
            <ColumnDefinition Width="Auto" />
            <ColumnDefinition Width="*" />
          </Grid.ColumnDefinitions>
          <TextBlock Grid.Column="0" MinWidth="20" Margin="2"
            Text="{Binding Path=Value, Converter={StaticResource IntDoubleConv}, Mode=OneWay}" />
          <Slider Grid.Column="1" Minimum="0" Maximum="5" TickFrequency="1" IsSnapToTickEnabled="True"
            Value="{Binding Path=Value, Converter={StaticResource IntDoubleConv}}" />
        </Grid>
      </DataTemplate>
      <local:CustomDataTemplateSelector x:Key="CustomSelector" />
    </ResourceDictionary>
  </Page.Resources>
  <Grid>
    <ig:XamPropertyGrid>
      <ig:XamPropertyGrid.EditorDefinitions>
        <ig:PropertyGridEditorDefinition
          TargetType="{x:Type sys:Int32}"
          EditTemplate="{StaticResource SpinIntEditor}"
          TemplateSelector="{StaticResource CustomSelector}">
        </ig:PropertyGridEditorDefinition>
      </ig:XamPropertyGrid.EditorDefinitions>
    </ig:XamPropertyGrid>
  </Grid>
</Page>
----

The following code example shows the implementation of the Template Selector which assigns certain data template based on a property name. This functionality will override the template which will be set by the control based on a property type.

*In Visual Basic:*

[source,vb]
----
Public Class CustomDataTemplateSelector
  Inherits DataTemplateSelector
  Public Overrides Function SelectTemplate(item As Object, container _
 As DependencyObject) As DataTemplate
    Dim context As PropertyGridTemplateSelectorContext = _
      TryCast(item, PropertyGridTemplateSelectorContext)
    If context.PropertyItem.PropertyName.Equals("Level") Then
      Dim propertyGrid As XamPropertyGrid = TryCast(container, XamPropertyGrid)
      Dim resource = propertyGrid.TryFindResource("SliderIntEditor")
      Return DirectCast(resource, DataTemplate)
    End If
    Return context.EditTemplate
  End Function
End Class
----

*In C#:*

[source,csharp]
----
public class CustomDataTemplateSelector : DataTemplateSelector
{
  public override DataTemplate SelectTemplate(object item, DependencyObject container)
  {
    PropertyGridTemplateSelectorContext context = item as PropertyGridTemplateSelectorContext;
    if (context.PropertyItem.PropertyName.Equals("Level"))
    {
      XamPropertyGrid propertyGrid = container as XamPropertyGrid;
      var resource = propertyGrid.TryFindResource("SliderIntEditor");
      return (DataTemplate)resource;
    }
    return context.EditTemplate;
  }
}
----

[[_RefLink04]]
== Re-evaluate the Template Selector Programmatically

There are cases when you may need to re-evaluate the template selector's value programmatically. For example if your template selector's code is returning different data templates based on the value of another property you can initiate re-evaluation by invoking the link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.propertygridpropertyitem.html[PropertyGridPropertyItem]'s link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.propertygridpropertyitem~requeryeditordefinition.html[RequeryEditorDefinition] method.

.Note
[NOTE]
====
You can be notified when a property’s value has changed by attaching an event handler to the `xamPropertyGrid's` link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.xampropertygrid~propertyitemvaluechanged_ev.html[PropertyItemValueChanged] event and to find the `PropertyGridPropertyItem` associated with a specific property you can call the existing `xamPropertyGrid's` link:{ApiPlatform}controls.editors.xampropertygrid{ApiVersion}~infragistics.controls.editors.xampropertygrid~findpropertyitem.html[FindPropertyItem] method.
====

[[_RefLink05]]
== Related Content

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xampropertygrid-conf-visuals.html[Configuring Visual Appearance (xamPropertyGrid)]
|This topic explains how to configure some general control options.

| link:xampropertygrid-conf-properties-filtering.html[Properties List Filtering (xamPropertyGrid)]
|This topic explains how to configure the filtering of the control’s properties list.

| link:xampropertygrid-conf-properties-sorting.html[Properties List Sorting (xamPropertyGrid)]
|This topic explains how to provide logic for custom sorting of the properties list.

|====

[options="header", cols="a,a"]
|====
|Sample|Purpose

| link:{SamplesURL}/data-grid/editing-template-selector[Editing Template Selector]
|This sample demonstrates how to define a Template Selector which is used to provide read-only and editing templates based on custom logic.

|====