////

|metadata|
{
    "name": "xampivotgrid",
    "controlName": ["xamPivotGrid"],
    "tags": ["Getting Started"],
    "guid": "{E357E246-DE9D-48EB-8AD2-21B26F3DF4C3}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:58.2523286Z"
}
|metadata|
////

= xamPivotGrid

This section gives you an overview of the use of the link:{ApiPlatform}controls.grids.xampivotgrid.v{ProductVersion}~infragistics.controls.grids.xampivotgrid.html[xamPivotGrid]™ control. It contains valuable information about xamPivotGrid, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish common tasks using the control.

Click the links below to access important information about the xamPivotGrid control.

== link:xampivotgrid-understanding-xampivotgrid.html[Understanding xamPivotGrid]

In this section you’ll find any information that will help you to better understand the functionalities of the xamPivotGrid control, as well as why you would want to use it as part of building your applications.

== link:xampivotgrid-getting-started-with-xampivotgrid.html[Getting Started with xamPivotGrid]

In order to get you up and running as quickly as possible with the xamPivotGrid control, we've provided you with information on how to get started using the control.

== link:xampivotgrid-using-xampivotgrid.html[Using XamPivotGrid]

This section contains information on the key features and functionalities provided by the xamPivotGrid control.

== link:xampivotgrid-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamPivotGrid control. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.