////

|metadata|
{
    "name": "xamribbon-screen-tips",
    "controlName": ["xamRibbon"],
    "tags": ["Data Presentation"],
    "guid": "{2D60C813-0251-48FA-B67A-10BC695ABFE1}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:54.2071945Z"
}
|metadata|
////

= Screen Tips

You can think of a Screen Tip as an enhanced ToolTip. The Screen Tip, as with the ToolTip, displays over a specific element when the end user hovers the mouse pointer over the element for a certain amount of time. The difference between a standard ToolTip and a Screen Tip is that the Screen Tip includes a header, body, and footer. You can also add separators (thin horizontal lines) between the header and body and between the body and footer. The link:{RootAssembly}{ApiVersion}~infragistics.windows.controls.xamscreentip.html[XamScreenTip] class itself is located in the Infragistics.Windows assembly; however, we have an even better Screen Tip in store for you.

The xamRibbon™ Screen Tip is a beefed-up version of the standard Screen Tip. Deriving from the XamScreenTip class itself, the link:{ApiPlatform}ribbon{ApiVersion}~infragistics.windows.ribbon.xamribbonscreentip.html[XamRibbonScreenTip] adds additional support for Microsoft® Office® 2007 guidelines, as well as support for an image. When setting the link:{ApiPlatform}ribbon{ApiVersion}~infragistics.windows.ribbon.xamribbonscreentip~contentimage.html[ContentImage] property, the xamRibbon Screen Tip restricts its own width to 318 pixels, and 210 pixels when no image is specified.

If we've piqued your interest, you can read the following topics to learn much more about xamRibbon's Screen Tips.

* link:xamribbon-about-xamribbonscreentip.html[About xamRibbonScreenTip]
* link:xamribbon-add-a-xamribbonscreentip-to-a-ribbon-tool.html[Add a xamRibbonScreenTip to a Ribbon Tool]
* link:xamribbon-add-a-simple-tooltip-to-a-ribbon-tool.html[Add a Simple ToolTip to a Ribbon Tool]