////

|metadata|
{
    "name": "xamribbon-applicationmenu2010",
    "controlName": ["xamRibbon"],
    "tags": [],
    "guid": "53a42839-5c20-4d18-aea8-377391dc074d",  
    "buildFlags": [],
    "createdOn": "2013-03-04T07:10:46.6554069Z"
}
|metadata|
////

= Application Menu 2010 (xamRibbon)

== In This Group of Topics

=== Introduction

The topics in this group explain how to create and configure the link:{ApiPlatform}ribbon{ApiVersion}~infragistics.windows.ribbon.xamribbon.html[xamRibbon™] control’s Application Menu 2010.

=== Topics

This section contains topics covering the  _xamRibbon_   control’s Application menu 2010.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamribbon-applicationmenu2010-overview.html[Application Menu 2010 Overview]
|This topic explains the Application Menu 2010 and its behaviors in general.

| link:xamribbon-defininganapplicationmenu2010.html[Defining an Application Menu 2010]
|This topic provides step-by-step instructions on how to define an Application Menu 2010.

| link:xamribbon-applicationmenu2010keytips.html[Application Menu 2010 KeyTips]
|This topic explains the Application Menu 2010’s KeyTips feature.

|====