////

|metadata|
{
    "name": "xamribbon",
    "controlName": ["xamRibbon"],
    "tags": [],
    "guid": "{AEBD085A-8285-4EA2-82DD-5D4B42B84703}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:54.0781687Z"
}
|metadata|
////

= xamRibbon

If you're looking for an area that houses all of the overview/task-based information related to the xamRibbon™ control, you've come to the right place. This section contains valuable information about xamRibbon, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the xamRibbon control.

== link:xamribbon-about-xamribbon.html[About xamRibbon]

In this section you'll find any information that will help you to better understand the functionalities of the xamRibbon control, as well as why you would want to use it to as part of building your applications.

== link:xamribbon-adding-xamribbon-to-your-application-.html[Adding xamRibbon to Your Application]

In order to get you up and running as quickly as possible with the xamRibbon control, we've provided you with information on how to get started using the control.

== link:xamribbon-using-xamribbon.html[Using xamRibbon]

This section contains information on the key features and functionalities provided by the xamRibbon control.

== link:xamribbon-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamRibbon control. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.