////

|metadata|
{
    "name": "xamribbon-tools",
    "controlName": ["xamRibbon"],
    "tags": ["Events","Getting Started","How Do I","Navigation"],
    "guid": "{A5AECD96-2545-4658-B77C-2D2577E03530}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:54.2231977Z"
}
|metadata|
////

= Tools

Ribbon link:xamribbon-ribbon-tabs.html[Tabs] and link:xamribbon-ribbon-groups.html[Groups] help you organize your user interface; Tabs are clickable, as are link:{ApiPlatform}ribbon.v{ProductVersion}~infragistics.windows.ribbon.ribbongroup~dialogboxlaunchertool.html[DialogBoxLauncher] buttons on a Group's header. However, your end user isn't going to get far if all they're doing is navigating and not acting. Tools give action to xamRibbon™ -- place a tool inside a Ribbon Group and your end user can perform whatever action you link to that tool. Ribbon Groups aren't the only area you can place tools; you can also place tools in the link:xamribbon-application-menu.html[Application Menu] and the link:xamribbon-quick-access-toolbar.html[Quick Access Toolbar (QAT)].

Tools come in all shapes and sizes, from the standard link:xamribbon-button.html[Button], to the impressive Gallery tool. Most tools derive from their WPF parent, so you'll get all the basic functionality a standard Button, ToggleButton, or RadioButton control would provide. {ProductName} tools, however, give you added functionality by implementing the IRibbonTool interface. When a tool implements the `IRibbonTool` interface, they gain specific xamRibbon functionality that allows them to be placed and managed on the QAT. This interface is extremely important, especially if you have high aspirations to *create your own custom xamRibbon tool* .

If we've piqued your interest, you can read the following topics to learn much more about xamRibbon's Tools.

* link:xamribbon-about-ribbon-tool-commands.html[About Ribbon Tool Commands]
* link:xamribbon-access-a-tool-by-its-id.html[Access a Tool by Its ID]
* link:xamribbon-add-tools-to-a-ribbon-group.html[Add Tools to a Ribbon Group]
* link:xamribbon-button.html[Button]
* link:xamribbon-check-box.html[Check Box]
* link:xamribbon-combo-editor.html[Combo Editor]
* link:xamribbon-gallery.html[Gallery]
* link:xamribbon-label.html[Label]
* link:xamribbon-masked-editor.html[Masked Editor]
* link:xamribbon-menu.html[Menu]
* link:xamribbon-radio-button.html[Radio Button]
* link:xamribbon-resize-a-tool.html[Resize a Tool]
* link:xamribbon-ribbon-tool-events.html[Ribbon Tool Events]
* link:xamribbon-separator.html[Separator]
* link:xamribbon-text-editor.html[Text Editor]
* link:xamribbon-toggle-button.html[Toggle Button]