////

|metadata|
{
    "name": "xamribbon-toggle-button",
    "controlName": ["xamRibbon"],
    "tags": ["Getting Started","How Do I"],
    "guid": "{F85A0B61-19CF-4FB1-9949-F729F15238D9}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:54.2211973Z"
}
|metadata|
////

= Toggle Button



The Toggle Button tool is synonymous with font styles in a word-processing application, such as Bold, Italics, Underline, etc. Clicking the button will toggle the associated action, usually a Boolean property that you can set to two values: True or False. In a word-processing application, you might highlight some text and click the Bold button. The button remains in a selected state as long as the selected text is bold, very similar to a check box-type control -- and just like a check box control, the end user can place the Toggle Button tool in a checked, unchecked, or indeterminate state.

The Toggle Button tool derives from Microsoft® Windows® Presentation Foundation's System.Windows.Controls ToggleButton class; therefore, you get all the same functionality as a standard Windows Presentation Foundation toggle button. The Toggle Button tool also implements the `IRibbonTool` interface, which adds cloning and binding functionality to facilitate advanced xamRibbon™ features. If you aren't creating your own custom xamRibbon tool, you don't need to worry about the IRibbonTool interface.

The link:{ApiPlatform}ribbon.v{ProductVersion}~infragistics.windows.ribbon.togglebuttontool.html[ToggleButtonTool] class exposes several extra properties that go a long way towards easily managing a button on xamRibbon. ToggleButtonTool exposes several 'Has' and 'Is' properties to help confirm if a property has been set or if the toggle button is in a certain state. A few of the standard properties that help set up a Toggle Button tool (or any tool) on xamRibbon include:

* link:{ApiPlatform}ribbon.v{ProductVersion}~infragistics.windows.ribbon.togglebuttontool~caption.html[Caption] - If a tool's size is set to where the tool's caption is visible, you'll see this text next to the tool.
* link:{ApiPlatform}ribbon.v{ProductVersion}~infragistics.windows.ribbon.togglebuttontool~id.html[Id] - An identification string that xamRibbon uses to associate tools when they're located in different locations (i.e. a Ribbon Group and the Quick Access Toolbar simultaneously). The Id isn't required, but it can help you link:xamribbon-access-a-tool-by-its-id.html[access a tool] at run time.
* link:{ApiPlatform}ribbon.v{ProductVersion}~infragistics.windows.ribbon.togglebuttontool~keytip.html[KeyTip] - Each tool has a link:xamribbon-key-tips.html[Key Tip] (similar to main menu mnemonics) associated with it. If you don't provide one explicitly, xamRibbon will internally choose one for you.
* link:{ApiPlatform}ribbon.v{ProductVersion}~infragistics.windows.ribbon.togglebuttontool~largeimage.html[LargeImage] - Usually a 32 x 32 pixel image. You'll see this image when a tool's SizingMode is set to ImageAndTextLarge.
* link:{ApiPlatform}ribbon.v{ProductVersion}~infragistics.windows.ribbon.togglebuttontool~sizingmode.html[SizingMode] - This property is read-only and returns how the tool is currently sized on its associated Ribbon group. If you want to link:xamribbon-resize-a-tool.html[set the size of a tool], you can set the RibbonGroup's link:{ApiPlatform}ribbon.v{ProductVersion}~infragistics.windows.ribbon.ribbongroup~minimumsizeproperty.html[MinimumSize] and/or link:{ApiPlatform}ribbon.v{ProductVersion}~infragistics.windows.ribbon.ribbongroup~maximumsizeproperty.html[MaximumSize] attached properties. Also, if you link:xamribbon-add-tools-to-a-buttongroup.html[place a tool in a Button Group], the tools will automatically be sized to ImageOnly.
* link:{ApiPlatform}ribbon.v{ProductVersion}~infragistics.windows.ribbon.togglebuttontool~smallimage.html[SmallImage] - Usually a 16 x 16 pixel image. You'll see this image when a tool's SizingMode is set to ImageAndTextNormal.

Since xamRibbon tools all derive from and implement the same objects, the functionality for each of them is very similar. The following topics apply to all xamRibbon tools.

== Related Topics

link:xamribbon-access-a-tool-by-its-id.html[Access a Tool by Its ID]

link:xamribbon-add-tools-to-a-buttongroup.html[Add Tools to a ButtonGroup]

link:xamribbon-add-tools-to-a-ribbon-group.html[Add Tools to a Ribbon Group]

link:xamribbon-resize-a-tool.html[Resize a Tool]