////

|metadata|
{
    "name": "xamribbon-label",
    "controlName": ["xamRibbon"],
    "tags": ["Getting Started","How Do I"],
    "guid": "{6CB5D090-4564-4F75-809D-AE06F17D99E4}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:54.1771885Z"
}
|metadata|
////

= Label



If you need a simple text label, then the Label tool is the right tool for you. The Label tool does not support user interaction. In fact, the Label tool will not display a KeyTip even if you set the KeyTip property since the Label tool's functionality is for display purposes only.

The Label tool also implements the IRibbonTool interface, which adds cloning and binding functionality to facilitate advanced xamRibbon™ features. If you aren't creating your own custom xamRibbon tool, you don't need to worry about the `IRibbonTool` interface.

The link:{ApiPlatform}ribbon.v{ProductVersion}~infragistics.windows.ribbon.labeltool.html[LabelTool] class exposes several properties that go a long way towards easily managing a label on xamRibbon. LabelTool exposes several 'Has' and 'Is' properties to help confirm if a property has been set or if the label is in a certain state. A few of the standard properties that help set up a Label tool on xamRibbon include:

* link:{ApiPlatform}ribbon.v{ProductVersion}~infragistics.windows.ribbon.labeltool~caption.html[Caption] - This text will always be visible next to the Label tool regardless of its resolved SizingMode property.
* link:{ApiPlatform}ribbon.v{ProductVersion}~infragistics.windows.ribbon.labeltool~id.html[Id] - The Id isn't required, but it can help you link:xamribbon-access-a-tool-by-its-id.html[access a tool] at run time.
* link:{ApiPlatform}ribbon.v{ProductVersion}~infragistics.windows.ribbon.labeltool~largeimage.html[LargeImage] - Usually a 32 x 32 pixel image. You'll see this image when a tool's SizingMode is set to ImageAndTextLarge.
* link:{ApiPlatform}ribbon.v{ProductVersion}~infragistics.windows.ribbon.labeltool~sizingmode.html[SizingMode] - This property is read-only and returns how the tool is currently sized on its associated Ribbon group. If you want to link:xamribbon-resize-a-tool.html[set the size of a tool], you can set the RibbonGroup's link:{ApiPlatform}ribbon.v{ProductVersion}~infragistics.windows.ribbon.ribbongroup~minimumsizeproperty.html[MinimumSize] and/or link:{ApiPlatform}ribbon.v{ProductVersion}~infragistics.windows.ribbon.ribbongroup~maximumsizeproperty.html[MaximumSize] attached properties.
* link:{ApiPlatform}ribbon.v{ProductVersion}~infragistics.windows.ribbon.labeltool~smallimage.html[SmallImage] - Usually a 16 x 16 pixel image. You'll see this image when a tool's SizingMode is set to ImageAndTextNormal.

Since xamRibbon tools all derive from and implement the same objects, the functionality for each of them is very similar. The following topics apply to all xamRibbon tools.

== Related Topics

link:xamribbon-access-a-tool-by-its-id.html[Access a Tool by Its ID]

link:xamribbon-add-tools-to-a-buttongroup.html[Add Tools to a ButtonGroup]

link:xamribbon-add-tools-to-a-ribbon-group.html[Add Tools to a Ribbon Group]

link:xamribbon-resize-a-tool.html[Resize a Tool]