////

|metadata|
{
    "name": "xamribbon-about-xamribbon",
    "controlName": ["xamRibbon"],
    "tags": ["Getting Started"],
    "guid": "{C4741F6B-F571-4E6C-93CB-FCA92E63FCD3}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:54.0891709Z"
}
|metadata|
////

= About xamRibbon

The xamRibbon™ control is the perfect navigation paradigm for user interfaces that require a great deal of user interaction. However, xamRibbon isn't simply a control...it encompasses the entire user interface with help from the xamRibbon window. Though xamRibbon may look familiar to users of Microsoft® Office®, add a dose of Infragistics ingenuity, and you'll get the only user interface you'll ever need. With xamRibbon's unique Tab and Group structure, you'll never run out of spots to place a tool, especially with contextual tabs which only display when needed.

== Tabs and Groups

Tabs and Groups are the main client area in xamRibbon. The Tabs will allow your end users to easily navigate and find tools appropriate for the task at hand. Within each Tab, Groups will have tools that execute your application logic.

== Application Menu

Tired of the boring main menu bar at the top of your application? The xamRibbon control's application menu shrinks the main menu into one neatly organized, visually appealing drop-down menu which displays when you click the attractive application menu button.

== Quick Access Toolbar

Let's not forget the Quick Access Toolbar (QAT); the completely customizable toolbar floating above or below xamRibbon. The QAT's sole purpose for existing is to allow you or your end user to add frequently used tools (or entire Ribbon groups) to it for easy access later. You can even collapse the entire xamRibbon control and just use all your favorite tools on the QAT.

== Related Topics

link:xamribbon-adding-xamribbon-to-your-application-.html[Adding xamRibbon to Your Application]

link:xamribbon-using-xamribbon.html[Using xamRibbon]