////

|metadata|
{
    "name": "xamribbon-ribbon-groups",
    "controlName": ["xamRibbon"],
    "tags": ["Grouping"],
    "guid": "{9F34DBFF-C7B7-4800-A463-ECB25486B693}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:54.1971925Z"
}
|metadata|
////

= Ribbon Groups

Ribbon Groups help define your tool structure on a more narrow level. link:xamribbon-ribbon-tabs.html[Ribbon Tabs] give your end user an idea of what task they want to perform, but the Group takes their idea one level deeper. You may be using xamRibbon™ for a word-processing application, and you may have a Formatting Tab. Inside the Formatting Tab, you could have several Groups of tools relating to the format of your end user's document. You might have a Fonts Group or a Paragraph Group. You can add an entire Group to the link:xamribbon-quick-access-toolbar.html[Quick Access Toolbar (QAT)] by setting a link:{ApiPlatform}ribbon{ApiVersion}~infragistics.windows.ribbon.qatplaceholdertool.html[QatPlaceholderTool's] link:{ApiPlatform}ribbon{ApiVersion}~infragistics.windows.ribbon.qatplaceholdertool~targetid.html[TargetID] to the Group's ID. You can also add a special button to the right side of the Group's header which can launch a dialog box of your choosing.

If we've piqued your interest, you can read the following topics to learn much more about xamRibbon's Groups.

* link:xamribbon-about-group-resizing.html[About Ribbon Group Resizing]
* link:xamribbon-add-a-ribbon-group-to-a-ribbon-tab.html[Add a Ribbon Group to a Ribbon Tab]
* link:xamribbon-using-the-dialog-box-launcher-to-display-a-dialog-box.html[Using the Dialog Box Launcher to Display a Dialog Box]