////

|metadata|
{
    "name": "xamribbon-add-a-tab-to-xamribbon",
    "controlName": ["xamRibbon"],
    "tags": ["Data Presentation","Grouping","How Do I","Layouts","Navigation","Selection"],
    "guid": "{44A839D9-96B3-4206-836A-6FBD16ED1D41}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:54.1151761Z"
}
|metadata|
////

= Add a Tab to xamRibbon



Tabs organize your application by presenting your end users with a high-level overview of your application's tasks. You can add RibbonGroups to a Tab to further organize the tasks into smaller tool based groups.

The following example code demonstrates how to add two Tabs to a xamRibbon™ control and set their headers.

*In XAML:*

----
...
<igRibbon:XamRibbon Name="xamRibbon1">
    <igRibbon:XamRibbon.Tabs>
        <igRibbon:RibbonTabItem Header="Home" />
        <igRibbon:RibbonTabItem Header="Insert" />
    </igRibbon:XamRibbon.Tabs>
</igRibbon:XamRibbon>
...
----

*In Visual Basic:*

----
Imports Infragistics.Windows.Ribbon
...
Dim tab As RibbonTabItem
tab = New RibbonTabItem()
tab.Header = "Home"
Me.xamRibbon1.Tabs.Add(tab)
tab = New RibbonTabItem()
tab.Header = "Insert"
Me.xamRibbon1.Tabs.Add(tab)
...
----

*In C#:*

----
using Infragistics.Windows.Ribbon;
...
RibbonTabItem tab;
tab = new RibbonTabItem();
tab.Header = "Home";
this.xamRibbon1.Tabs.Add(tab);
tab = new RibbonTabItem();
tab.Header = "Insert";
this.xamRibbon1.Tabs.Add(tab);
...
----

== Related Topics

link:xamribbon-adding-xamribbon-to-your-application-.html[Adding xamRibbon to Your Application]

link:xamribbon-add-a-contextual-tab-to-xamribbon.html[Add a Contextual Tab to xamRibbon]