////

|metadata|
{
    "name": "xamribbon-quick-access-toolbar",
    "controlName": ["xamRibbon"],
    "tags": ["Data Presentation","Navigation","Selection"],
    "guid": "{CC652E6E-BE6F-4077-AA72-8A466C650407}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:54.1841899Z"
}
|metadata|
////

= Quick Access Toolbar

The Quick Access Toolbar (QAT) is a little more than a standard toolbar. You'll see the QAT in one of two places: above the ribbon, directly to the right of the Application Menu button, or beneath the Ribbon. What makes this toolbar different from other toolbars, or groups on the Ribbon, is that your end users can add any tool from any group to the QAT; they can even add an entire group to the QAT.

There is only one stipulation to adding tools to the QAT. You can only add a link:{ApiPlatform}ribbon{ApiVersion}~infragistics.windows.ribbon.qatplaceholdertool.html[QatPlaceholderTool] to the QAT. When you add a QatPlaceholder tool to the QAT, you can set the tool's link:{ApiPlatform}ribbon{ApiVersion}~infragistics.windows.ribbon.qatplaceholdertool~targetid.html[TargetID] to the ID of any tool or group currently placed in xamRibbon™ or not in xamRibbon (a tool residing in the link:{ApiPlatform}ribbon{ApiVersion}~infragistics.windows.ribbon.xamribbon~toolsnotinribbon.html[ToolsNotInRibbon] collection). The ToolsNotInRibbon collection was designed specifically with the QAT in mind. Since you can only place a QatPlaceholder tool on the QAT, you need a collection for tools if you don't want those tools placed anywhere else on xamRibbon.

If we've piqued your interest, you can read the following topics to learn much more about xamRibbon's Quick Access Toolbar.

* link:xamribbon-about-quickaccesstoolbar.html[About QuickAccessToolbar]
* link:xamribbon-add-a-tool-or-ribbongroup-to-the-quick-access-toolbar.html[Add a Tool or RibbonGroup to the Quick Access Toolbar]
* link:xamribbon-adding-and-removing-common-tools.html[Adding and Removing Common Tools]