////

|metadata|
{
    "name": "xamribbon-ribbon-tabs",
    "controlName": ["xamRibbon"],
    "tags": ["Grouping"],
    "guid": "{8B852806-94D6-4A0A-910D-863D23E4BE73}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:54.1991929Z"
}
|metadata|
////

= Ribbon Tabs

The main client area of xamRibbon™ consists of one to several Tabs. Each Tab can contain several Groups. Groups contain tools -- separating them into logical sections. Tabs allow you to create several groups of tools, all having to do with a common theme, such as specific tasks in a word-processing application. All Tabs contain Groups; however, not all Tabs are created equal.

Contextual Tabs are a special type of Tab that do not display to the end user by default. In order to display a Contextual Tab, the end user needs to perform a specific task, place the application in a specific state; in other words, the Contextual Tab only displays in certain contexts. For example, you may have a Tab with tools relating to drawing tables, and another Tab for tools that help the end user draw shapes. However, you also have several other Tabs that the end user need to user frequently. The end user may not have a table or drawing in their document at all. Therefore, there is no need to show the Table and Shapes tabs. You may have an Insert Tab that helps the user insert objects into their document, such as tables and drawings. Once the end user clicks the Insert Table button and the application inserts a table and selects it, you can display the Table Tab -- which in this case, would be considered a Contextual Tab because it displays only in the context of Tables.

If we've piqued your interest, you can read the following topics to learn much more about xamRibbon's Tabs.

* link:xamribbon-add-a-tab-to-xamribbon.html[Add a Tab to xamRibbon]
* link:xamribbon-add-a-contextual-tab-to-xamribbon.html[Add a Contextual Tab to xamRibbon]
* link:xamribbon-showing-a-contextual-tab-group-programmatically.html[Show a Contextual Tab Group Programmatically]