////

|metadata|
{
    "name": "xamribbon-about-xamribbonscreentip",
    "controlName": ["xamRibbon"],
    "tags": ["Getting Started"],
    "guid": "{C061C0F8-DF9D-407D-8604-376103CE1CBF}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:54.0921715Z"
}
|metadata|
////

= About xamRibbonScreenTip



The xamRibbon™ Screen Tip is an enhanced ToolTip that you can use for any Ribbon tool that exposes a ToolTip property. You simply set the ToolTip property to an instance of a link:{ApiPlatform}ribbon{ApiVersion}~infragistics.windows.ribbon.xamribbonscreentip.html[xamRibbonScreenTip].

The xamRibbonScreenTip class derives from the xamScreenTip class which derives from Microsoft Windows Presentation Foundation's System.Windows.Controls.ToolTip class. Therefore, you can use xamRibbonScreenTip in the same fashion as a standard .NET Framework ToolTip control. However, unlike the .NET Framework ToolTips, xamRibbon Screen Tips provide added functionality that will restrict its own size so that it conforms to Microsoft® Office® UI guidelines. Along with the auto sizing functionality, xamRibbon Screen Tips allow you to display a header, footer, and an image to give your end users a better idea of what a specific Ribbon tool will do.

== Related Topics

link:xamribbon-add-a-xamribbonscreentip-to-a-ribbon-tool.html[Add a xamRibbonScreenTip to a Ribbon Tool]

link:xamribbon-add-a-simple-tooltip-to-a-ribbon-tool.html[Add a Simple ToolTip to a Ribbon Tool]