////

|metadata|
{
    "name": "xamribbon-using-xamribbon",
    "controlName": ["xamRibbon"],
    "tags": [],
    "guid": "{D6F02478-8EAE-4728-88F4-1A34DF5DE21E}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:54.2291989Z"
}
|metadata|
////

= Using xamRibbon

This section is your gateway to important task-based information that will help you to effectively use the various features and functionalities provided by xamRibbon™ control.

link:xamribbon-application-menu.html[Application Menu]

This section describes the Application Menu area of the xamRibbon control and demonstrates how to add items to it.

link:xamribbon-applicationmenu2010.html[Application Menu 2010]

The topics in this group explain how to create and configure the xamRibbon control’s Application Menu 2010.

link:xamribbon-key-tips.html[Key Tips]

This topic describes the Key Tips functionality of xamRibbon, explaining how and why they are used.

link:xamribbon-quick-access-toolbar.html[Quick Access Toolbar]

This section describes the key features of the Quick Access Toolbar area of xamRibbon.

link:xamribbon-ribbon-group-layout-panels.html[Ribbon Group Layout Panels]

This section explains the different layout panels available within the xamRibbon control.

link:xamribbon-ribbon-groups.html[Ribbon Groups]

This section describes the ribbon group area of xamRibbon, and demonstrates how to add them to ribbon tabs.

link:xamribbon-ribbon-tabs.html[Ribbon Tabs]

This section describes the ribbon tab area of xamRibbon and demonstrates how to add them to xamRibbon.

link:xamribbon-ribbon-window.html[Ribbon Window]

This section explains the purpose of the ribbon window and demonstrates how to display xamRibbon in the ribbon window.

link:xamribbon-screen-tips.html[Screen Tips]

This section explains the purpose of screen tips and how to add them to a ribbon tool.

link:xamribbon-tab-item-area-toolbar.html[Tab Item Area Toolbar (xamRibbon)]

This topic explains how to create and configure the toolbar area positioned next to the tab items.

link:xamribbon-tools.html[Tools]

This section describes the tools that are available within the xamRibbon control.