////

|metadata|
{
    "name": "xamribbon-ribbon-window",
    "controlName": ["xamRibbon"],
    "tags": ["Data Presentation","How Do I"],
    "guid": "{41E15277-5195-4954-9C64-1D6770FF89D6}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:54.2041939Z"
}
|metadata|
////

= Ribbon Window

The xamRibbon™ control must display within the client area of a standard window; however, the xamRibbon Window is our own custom window which derives from System.Window and gives you the polished look you've come to expect from {ProductName} controls. The main advantage of using the xamRibbon Window is that the Ribbon's caption is displayed in the header of the window, this way, the Ribbon looks like it's a part of the window itself, similar to Microsoft® Office® 2007.

Another must-have feature of the xamRibbon Window is a status bar that you can choose to include at the bottom of the window. You can place any application-sensitive information in the status bar such as help, application task progress, or critical information regarding the application itself.

If we've piqued your interest, you can read the following topics to learn much more about xamRibbon's Ribbon Window.

* link:xamribbon-display-xamribbon-in-the-ribbon-window.html[Display xamRibbon in the Ribbon Window]
* link:xamribbon-add-a-status-bar-to-the-ribbon-window.html[Add a Status Bar to the Ribbon Window]