////

|metadata|
{
    "name": "xamribbon-application-menu",
    "controlName": ["xamRibbon"],
    "tags": ["Getting Started"],
    "guid": "{21D39304-8610-4F03-9645-F4E08E2EBE41}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:54.1441819Z"
}
|metadata|
////

= Application Menu

The main menu bar, located at the top of most applications, has always been a gathering place for tools relating to the application as a whole. In the main menu, you would find menu items such as File, Edit, or View. The xamRibbon™ control's Application Menu, in combination with link:{ApiPlatform}ribbon{ApiVersion}~infragistics.windows.ribbon.ribbontabitem.html[Tabs] and link:{ApiPlatform}ribbon{ApiVersion}~infragistics.windows.ribbon.ribbongroup.html[Groups], removes the need for a main menu bar. What was once included in a menu item (i.e. File), you can now place in the Application Menu, with several more options.

The Application Menu includes a popup-style menu that originates from clicking the Application Menu button. Once opened, you'll see that the Application Menu is divided into three separate sections:

* *Items* - The Application Menu's Items collection can contain any group of tools that can execute a command. Add a Button tool for a simple command, add a Menu tool for a list of hierarchical options, or Add a Label tool to keep the Application Menu organized.
* *Recent Items* - This collection of items displays on the right side of the Application Menu. The RecentItems collection's purpose is to display your application's most recently used items, for example, most recently viewed documents or the most recently used tools.
* *Footer toolbar -* The Footer toolbar is located at the bottom of the Application Menu and is designed to contain tools of higher importance, such as the application's Close or Options buttons.

If we've piqued your interest, you can read the following topics to learn much more about xamRibbon's Application Menu.

* link:xamribbon-add-an-image-to-the-application-menu.html[Add an Image to the Application Menu]
* link:xamribbon-add-tools-to-the-application-menu.html[Add Tools to the Application Menu]
* link:xamribbon-add-tools-to-the-footer-toolbar.html[Add Tools to the Footer Toolbar]
* link:xamribbon-display-a-most-recently-used-items-list.html[Display a Most Recently Used Items List]