////

|metadata|
{
    "name": "xamspellchecker-using-xamspellchecker",
    "controlName": ["xamSpellChecker"],
    "tags": [],
    "guid": "{DEB9ECBE-7F7E-4463-A2D3-5A070AB9FF74}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:59.1203759Z"
}
|metadata|
////

= Using xamSpellChecker

This section is your gateway to important conceptual and task-based information that will help you to use the various features and functionalities provided by the xamSpellChecker™ control.

link:xamspellchecker-performance-options.html[Performance Options]

This topic describes how to enhance the performance of xamSpellChecker.

link:xamspellchecker-spelling-options.html[Spelling Options]

This topic explains how to customize the way that the xamSpellChecker control checks for spelling errors.

link:xamspellchecker-how-to-specify-text-to-be-spell-checked.html[How to Specify Text to be Spell Checked]

This topic demonstrates how to identify text to be spell checked by the xamSpellChecker control.

link:xamspellchecker-dictionaries.html[Dictionaries]

This walkthrough demonstrates how to change the default dictionary of the xamSpellChecker control.