////

|metadata|
{
    "name": "xamschedule",
    "controlName": ["xamSchedule"],
    "tags": [],
    "guid": "9a8bc84d-016f-43b4-95d9-cb5aba021fa1",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:58.6003478Z"
}
|metadata|
////

= xamSchedule

This section contains information about xamSchedule™ family of controls, ranging from what the control does and step-by-step procedures on using it in your application.

Click the links below to access important information about xamSchedule.

== link:xamschedule-understanding.html[Understanding xamSchedule]

In this section you'll find information that will help you to better understand the functionalities of xamSchedule.

== link:xamschedule-getting-started.html[Adding xamSchedule to Your Page]

In order to get you up and running as quickly as possible with xamSchedule, we've provided you with information on how to get started using the control.

== link:xamschedule-using.html[Using xamSchedule]

This section contains information on the key features and functionalities provided by xamSchedule.

== link:xamschedule-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with xamSchedule. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.