////

|metadata|
{
    "name": "xamschedule-understanding-data-manager",
    "controlName": ["xamSchedule"],
    "tags": ["Scheduling"],
    "guid": "390ba387-52c2-45ee-93ba-65f97d213b91",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:58.6193218Z"
}
|metadata|
////

= About the Data Manager

The link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.xamscheduledatamanager.html[Data Manager] is a non-visual control that coordinates and manages the communication between the link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.listscheduledataconnector.html[Data Connector] and the views (i.e., the controls displaying the calendar information). It provides the resources, calendars and activities to the views. Activities can be added not only through the Data Connector, but programmatically through the data manager as well. See " link:xamschedule-using-manager-logical-events.html[Handling Data Manager Events]" topic.

The Data Manager exposes settings to determine what operations are allowed as well as settings that define working hour and day information. More information can be found in the link:xamschedule-using-manager.html[Data Manager section] and its subsections.

There can be more than one xamSchedule view retrieving data from a single Data Manager, and this way a single activity change will reflect many views. Also, more than one Data Manager can be created and each of them can be connected to different Data Connectors and have a different set of views.

== Related Topics

link:xamschedule-understanding-data-connector.html[About the Data Connector]

link:xamschedule-understanding-views.html[About the xamSchedule views]

link:xamschedule-understanding-resources-calendars.html[About Resources and Calendars]

link:xamschedule-understanding-activities.html[About Activities]