////

|metadata|
{
    "name": "xamschedule-understanding-data-connector",
    "controlName": ["xamSchedule"],
    "tags": ["Scheduling"],
    "guid": "a0b27919-035d-4e8c-bc58-08fb10fc6a36",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:58.6123516Z"
}
|metadata|
////

= About the Data Connector

Data Connectors are non-visual elements that provide the link:xamschedule-understanding-data-manager.html[Data Manager] with xamSchedule entity objects (e.g., link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.resource.html[Resources], link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.resourcecalendar.html[ResourceCalendars] and link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.activitybase.html[activities]) based on information from a specified data source. Data Connectors also provide information to the xamScheduleDataManager about the capabilities and features that are supported.

The following Data Connectors are provided:

* link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.listscheduledataconnector.html[ListScheduleDataConnector]
* link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.wcflistscheduledataconnector.html[WcfScheduleDataConnector]
* link:{ApiPlatform}controls.schedulesexchangeconnector{ApiVersion}~infragistics.controls.schedules.exchangescheduledataconnector.html[ExchangeScheduleDataConnector]

The List and WcfScheduleDataConnector classes support mapping of properties between data source objects and xamSchedule objects (e.g., Resources, Calendars and Activities) to allow binding to a wide range of data sources. This is described in " link:xamschedule-using-connector-mapping.html[Mapping Fields in Your Backend Data Source]” topic.

In addition, custom data connectors can be created to fulfill specific needs, as described in the “ link:xamschedule-using-connector-custom-connectors.html[Custom Connectors]” topic.

The Data Connector also supports specifying time zone information, described in the " link:xamschedule-using-timezone-support.html[TimeZone Support in xamSchedule]" topic.

== Related Topics

link:xamschedule-understanding-data-manager.html[About the Data Manager]

link:xamschedule-understanding-views.html[About the xamSchedule views]

link:xamschedule-understanding-resources-calendars.html[About Resources and Calendars]

link:xamschedule-understanding-activities.html[About Activities]