////
|metadata|
{
    "name": "xamsparkline-adding-xamsparkline",
    "controlName": ["xamSparkline"],
    "tags": ["Charting","Getting Started"],
    "guid": "81ddee34-34ab-4723-bd2b-ca9a43ccfbcd",
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:59.2873585Z"
}
|metadata|
////

= Adding xamSparkline

== Topic Overview

=== Purpose

This topic explains conceptually how to add the link:{ApiPlatform}controls.charts.xamsparkline{ApiVersion}.html[xamSparkline] control and introduces to the available adding options.

=== Required background

The following table lists the materials required as a prerequisite to understanding this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamsparkline-xamsparkline-overview.html[xamSparkline Overview]
|This topic provides an overview of the _xamSparkline_ control, its benefits, and the supported chart types.

| link:xamsparkline-configuring-xamsparkline.html[Configuring xamSparkline]
|This topic provides an overview of the possible ways to configure the _xamSparkline_ control. Links to the detailed configurations (available in separate topics) are provided as well.

|====

=== In this topic

This topic contains the following sections:

* <<_Ref317075029,Adding a Sparkline>>

** <<Introduction,Introduction>>
** <<_Ref317075452,Requirements>>
** <<_Ref320180895,Options for adding the xamSparkline control>>

* <<_Ref317075104,Related Content>>

[[_Ref317075029]]
== Adding a Sparkline

=== Introduction

Sparkline can be displayed in {PlatformName} application as a stand-alone control, in small spaces such as grid cells, or in-line with text. The  _xamSparkline_   control can be added through XAML, as well as in-code (C# or Visual Basic).

In order to determine what data is to be displayed, you need a data source with at least two numeric fields in the class as the data points. This is handled by the ItemsSource and link:xamsparkline-xamsparkline-property-reference.html#ValueMemberPath[ValueMemberPath] properties, respectively. These are the minimum set of properties you need to configure for the  _xamSparkline_   control.

The project requirements for adding the  _xamSparkline_   control include adding assembly references and namespaces as well as some data requirements.

The  _xamSparkline_   supports any one-dimensional data source, as long as the data contains at least two numeric fields in order to render the chart.

[[_Ref317075452]]

=== Requirements

The following table summarizes the requirements for adding the  _xamSparkline_   control.

[options="header", cols="a,a"]
|====
|Requirements|References / Description

|Assembly references
|Add the following assembly references in your project: 

* {ApiPlatform}Controls.Charts.XamSparkline.{ApiVersion} 

* {ApiPlatform}DataVisualization.{ApiVersion} 

* {ApiPlatform}{ApiVersion}

|Namespaces
|*In XAML:* 

[source,xaml]
---- 
Namespaces xmlns:ig="http://schemas.infragistics.com/xaml"
---- 

|Data
|One-dimensional data that contains numeric values. 

*Note:* With the Win/Loss type of Sparkline, only two values will be used for thechart – the highest one and the lowest one. The rest of the values in the data set will be ignored.

|====

[[_Ref320022805]]

=== Options for adding the xamSparkline control

The following table lists the ways in which you can add the  _xamSparkline_   control.

[options="header", cols="a,a"]
|====
|Example|Description

| link:xamsparkline-adding-a-sparkline-to-a-page.html[Adding xamSparkline to a Page]
|You can add the _xamSparkline_ control directly to a Page using one-dimensional data.

ifdef::sl,wpf[]
| link:xamgrid-sparkline-column.html[Sparkline Column]
|You can add the _xamSparkline_ control to _xamGrid_™ cells using the Sparkline column type.
endif::sl,wpf[]

|====

[[_Ref317075039]]

[[_Ref317075104]]
== Related Content

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamsparkline-xamsparkline-property-reference.html[xamSparkline Property Reference]
|This topic explains the featured properties of the _xamSparkline_ control.

ifdef::sl,wpf[]
| link:xamgrid-sparkline-column.html[Sparkline Column]
|This topic introduces the Sparkline column type of the _xamGrid_ control and demonstrates its use.
endif::sl,wpf[]

|====