////

|metadata|
{
    "name": "xamslider",
    "controlName": ["xamSlider"],
    "tags": [],
    "guid": "{A700DB6F-4447-4D1F-9FA9-5370CB9FFB0F}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:58.9913329Z"
}
|metadata|
////

= xamSlider

This section gives you an overview of the use of xamSlider™. This section contains valuable information about xamSlider, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish common tasks using the control. Click the links below to access important information about the xamSlider control.

== link:xamslider-about-xamslider.html[About xamSlider]

In this section you’ll find any information that will help you to better understand the functionalities of the xamSlider control, as well as why you would want to use it as part of building your applications.

== link:xamslider-getting-started-with-xamslider.html[Getting Started with xamSlider]

In order to get you up and running as quickly as possible with the xamSlider control, we've provided you with information on how to get started using the control (e.g., adding a single-value slider to your application).

== link:xamslider-using-xamslider.html[Using xamSlider]

This section contains information on the key features and functionalities provided by the xamSlider control.

== link:xamslider-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamSlider control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the {PlatformName} help.