////

|metadata|
{
    "name": "xamsyntaxeditor-supported-languages",
    "controlName": ["xamSyntaxEditor"],
    "tags": ["Editing","Layouts","Templating"],
    "guid": "e24a4ba4-3967-4b10-93c5-0c4ceb092061",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:59.4143967Z"
}
|metadata|
////

= Supported Languages (xamSyntaxEditor)

== Topic Overview

=== Purpose

This topic lists the languages supported by the  _xamSyntaxEditor™_   and shows you how to use each of them.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamsyntaxeditor-overview.html[ _xamSyntaxEditor_ Overview]
|In this topic, you will find information to help you better understand the _xamSyntaxEditor’s_ functions.

| link:xamsyntaxeditor-editing-support-overview.html[Editing Support Overview]
|This topic covers the text editing capabilities of the _xamSyntaxEditor_ control from both the developer and user’s perspective.

|====

=== In this topic

This topic contains the following sections:

* <<_Ref330377555, Supported Languages >>
** <<_Ref330377581,Plain Text>>
** <<_Ref330377728,C# Language>>
** <<_Ref330377735,Visual Basic Language>>
** <<_Ref876376384,Transact-SQL>>

* <<_Ref330377754, Code Examples >>
** <<_Ref330377753,Code Example: Setting Plain Text Language>>
** <<_Ref330377762,Code Example: Setting C# Language>>
** <<_Ref330377777,Code Example: Setting Visual Basic Language>>
** <<_Ref924657653,Code Example: Setting Transact-SQL Language>>

* <<_Ref330377785, Related Content >>

[[_Ref330377555]]
== Supported Languages

=== Supported languages summary chart

The  _xamSyntaxEditor_   supports several predefined syntax highlighting languages. Additional information on using supported languages follows.

.Note
[NOTE]
====
Certain languages (for example, Visual Basic) modify the case of keywords within a document. To ensure that these modifications are intentionally made to documents containing text targeting a different language, set the document’s language prior to link:xamsyntaxeditor-configuring-initial-content.html[loading the document content].
====

[options="header", cols="a,a"]
|====
|Language|Colorization Details

|<<_Ref330377581,Plain Text>>
|No special colorization used.

|<<_Ref330377728,C# Language>>
|Uses the C# language colorization scheme, which is similar to MS Visual Studio.

|<<_Ref330377735,Visual Basic Language>>
|Uses the Visual Basic language colorization scheme, which is similar to MS Visual Studio.

|<<_Ref876376384,Transact-SQL Language>>
|Uses the Transact-SQL (T-SQL) language colorization scheme, which is similar to MS Visual Studio.

|====

.Note
[NOTE]
====
The internal grammatical structure of these languages, including the structure of the syntax tree created for documents parsed with them, is subject to change. With this in mind, if you are writing code to inspect or traverse a syntax tree you should use the nested SymbolNames class constants in each language definition to identify the name of each node's symbol (rather than the symbol name as a string literal), so that future changes to these symbol names will be highlighted via compilation errors. In addition, it is good practice to write logic to test assumptions and debug assert about the number and type of child nodes on a particular node so changes to a node’s child structure in the future will be detected and handled gracefully.
====

[[_Ref330377581]]
== Plain Text

=== Overview

Uses no special colorization.

=== Property settings

[options="header", cols="a,a,a"]
|====
|In order to:|Use this property:|And set it to either:

|Set plain text language
| link:{ApiPlatform}documents.textdocument{ApiVersion}~infragistics.documents.textdocument~language.html[Language]
|
* New instance of the link:{ApiPlatform}documents.textdocument{ApiVersion}~infragistics.documents.parsing.plaintextlanguage_members.html[PlainTextLanguage] class 

* link:{ApiPlatform}documents.textdocument{ApiVersion}~infragistics.documents.parsing.plaintextlanguage~instance.html[PlainTextLanguage.Instance] 

* Don’t set the `Language` property at all 

|====

[[_Ref330377728]]
== C# Language

=== Overview

Uses the C# language colorization scheme, which is similar to MS Visual Studio.

=== Property settings

[options="header", cols="a,a,a"]
|====
|In order to:|Use this property:|And set it to either:

|Set C# language
|`Language`
|
* New instance of the link:{ApiPlatform}documents.textdocument.csharp{ApiVersion}~infragistics.documents.parsing.csharplanguage_members.html[CSharpLanguage] class 

* link:{ApiPlatform}documents.textdocument.csharp{ApiVersion}~infragistics.documents.parsing.csharplanguage~instance.html[CSharpLanguage.Instance] 

|====

[[_Ref330377735]]
== Visual Basic Language

=== Overview

Uses the Visual Basic language colorization scheme, which is similar to MS Visual Studio.

=== Property settings

[options="header", cols="a,a,a"]
|====
|In order to:|Use this property:|And set it to either:

|Set Visual Basic language
|`Language`
|
* New instance of the link:{ApiPlatform}documents.textdocument.visualbasic{ApiVersion}~infragistics.documents.parsing.visualbasiclanguage_members.html[VisualBasicLanguage] class 

* link:{ApiPlatform}documents.textdocument.visualbasic{ApiVersion}~infragistics.documents.parsing.visualbasiclanguage~instance.html[VisualBasicLanguage.Instance] 

|====

[[_Ref876376384]]
== Transact-SQL Language

=== Overview

Uses the Transact-SQL (TSQL) language colorization scheme, which is similar to MS Visual Studio.

=== Property settings

[options="header", cols="a,a,a"]
|====
|In order to:|Use this property:|And set it to either:

|Set Transact-SQL language
|`Language`
|
* New instance of the link:{ApiPlatform}documents.textdocument.tsql{ApiVersion}~infragistics.documents.parsing.tsqllanguage_members.html[TSqlLanguage] class 

* link:{ApiPlatform}documents.textdocument.tsql{ApiVersion}~infragistics.documents.parsing.tsqllanguage~instance.html[TSqlLanguage.Instance] 

|====

[[_Ref330377754]]
== Code Examples

=== Code examples summary

The following table lists the code examples included in this topic.

[options="header", cols="a,a"]
|====
|Example|Description

|<<_Ref330377753,Setting Plain Text Language>>
|This example shows how to set the _TextDocument’s_ language to plain text.

|<<_Ref330377762,Setting C# Language>>
|This example shows how to set the _TextDocument’s_ language to C#.

|<<_Ref330377777,Setting Visual Basic Language>>
|This example shows how to set the _TextDocument’s_ language to Visual Basic.

|<<_Ref924657653,Setting Transact-SQL Language>>
|This example shows how to set the _TextDocument’s_ language to Transact-SQL.

|====

[[_Ref330377753]]
== Code Example: Setting Plain Text Language

=== Description

This example shows how to set the TextDocument’s language to plain text.

=== Code snippets

*In XAML:*

[source,xaml]
----
<ig:XamSyntaxEditor x:Name="xamSyntaxEditor1">
    <ig:XamSyntaxEditor.Document>
        <ig:TextDocument>
            <ig:TextDocument.Language>
                <ig:PlainTextLanguage />
            </ig:TextDocument.Language>
        </ig:TextDocument>
    </ig:XamSyntaxEditor.Document>
</ig:XamSyntaxEditor>
----

*In C#:*

[source,csharp]
----
using Infragistics.Controls.Editors;
using Infragistics.Documents;
using Infragistics.Documents.Parsing;
XamSyntaxEditor xamSyntaxEditor1 = new XamSyntaxEditor();
xamSyntaxEditor1.Document = new TextDocument();
xamSyntaxEditor1.Document.Language = PlainTextLanguage.Instance;
----

*In Visual Basic:*

[source,vb]
----
Imports Infragistics.Controls.Editors
Imports Infragistics.Documents
Imports Infragistics.Documents.Parsing
Dim xamSyntaxEditor1 As New XamSyntaxEditor()
xamSyntaxEditor1.Document = New TextDocument()
xamSyntaxEditor1.Document.Language = PlainTextLanguage.Instance
----

[[_Ref330377762]]
== Code Example: Setting C# Language

=== Description

This example shows how to set the  _TextDocument’s_   language to C#.

=== Code snippets

*In XAML:*

[source,xaml]
----
<ig:XamSyntaxEditor x:Name="xamSyntaxEditor1">
    <ig:XamSyntaxEditor.Document>
        <ig:TextDocument>
            <ig:TextDocument.Language>
                <ig:CSharpLanguage />
            </ig:TextDocument.Language>
        </ig:TextDocument>
    </ig:XamSyntaxEditor.Document>
</ig:XamSyntaxEditor>
----

*In C#:*

[source,csharp]
----
using Infragistics.Controls.Editors;
using Infragistics.Documents;
using Infragistics.Documents.Parsing;
XamSyntaxEditor xamSyntaxEditor1 = new XamSyntaxEditor();
xamSyntaxEditor1.Document = new TextDocument();
xamSyntaxEditor1.Document.Language = CSharpLanguage.Instance;
----

*In Visual Basic:*

[source,vb]
----
Imports Infragistics.Controls.Editors
Imports Infragistics.Documents
Imports Infragistics.Documents.Parsing
Dim xamSyntaxEditor1 As New XamSyntaxEditor()
xamSyntaxEditor1.Document = New TextDocument()
xamSyntaxEditor1.Document.Language = CSharpLanguage.Instance
----

[[_Ref330377777]]
== Code Example: Setting Visual Basic Language

=== Description

This example shows how to set the TextDocument’s language to Visual Basic.

=== Code snippets

*In XAML:*

[source,xaml]
----
<ig:XamSyntaxEditor x:Name="xamSyntaxEditor1">
    <ig:XamSyntaxEditor.Document>
        <ig:TextDocument>
            <ig:TextDocument.Language>
                <ig:VisualBasicLanguage />
            </ig:TextDocument.Language>
        </ig:TextDocument>
    </ig:XamSyntaxEditor.Document>
</ig:XamSyntaxEditor>
----

*In C#:*

[source,csharp]
----
using Infragistics.Controls.Editors;
using Infragistics.Documents;
using Infragistics.Documents.Parsing;
XamSyntaxEditor xamSyntaxEditor1 = new XamSyntaxEditor();
xamSyntaxEditor1.Document = new TextDocument();
xamSyntaxEditor1.Document.Language = VisualBasicLanguage.Instance;
----

*In Visual Basic:*

[source,vb]
----
Imports Infragistics.Controls.Editors
Imports Infragistics.Documents
Imports Infragistics.Documents.Parsing
Dim xamSyntaxEditor1 As New XamSyntaxEditor()
xamSyntaxEditor1.Document = New TextDocument()
xamSyntaxEditor1.Document.Language = VisualBasicLanguage.Instance
----

[[_Ref924657653]]
== Code Example: Setting Transact-SQL Language

=== Description

This example shows how to set the TextDocument’s language to Transact-SQL.

=== Code snippets

*In XAML:*

[source,xaml]
----
<ig:XamSyntaxEditor x:Name="xamSyntaxEditor1">
    <ig:XamSyntaxEditor.Document>
        <ig:TextDocument>
            <ig:TextDocument.Language>
                <ig:TSqlLanguage />
            </ig:TextDocument.Language>
        </ig:TextDocument>
    </ig:XamSyntaxEditor.Document>
</ig:XamSyntaxEditor>
----

*In C#:*

[source,csharp]
----
using Infragistics.Controls.Editors;
using Infragistics.Documents;
using Infragistics.Documents.Parsing;
XamSyntaxEditor xamSyntaxEditor1 = new XamSyntaxEditor();
xamSyntaxEditor1.Document = new TextDocument();
xamSyntaxEditor1.Document.Language = TSqlLanguage.Instance;
----

*In Visual Basic:*

[source,vb]
----
Imports Infragistics.Controls.Editors
Imports Infragistics.Documents
Imports Infragistics.Documents.Parsing
Dim xamSyntaxEditor1 As New XamSyntaxEditor()
xamSyntaxEditor1.Document = New TextDocument()
xamSyntaxEditor1.Document.Language = TSqlLanguage.Instance
----

[[_Ref330377785]]
== Related Content

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamsyntaxeditor-changing-default-classification-types-appearance.html[Changing Default Classification Types Appearance]
|This topic provides information on how to change the colors and other appearance attributes assigned to language elements by the _xamSyntaxEditor_ .

|====

=== Samples

The following samples provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Sample|Purpose

| pick:[sl=" link:{SamplesURL}/syntax-editor/#/load-external-file[Load External File]"] pick:[wpf=" link:{SamplesURL}/syntax-editor/load-external-file[Load External File]"] 
|This sample demonstrates loading of external files of different types in the _xamSyntaxEditor_ .

|====