////

|metadata|
{
    "name": "xamschedule-using-manager-logical-events",
    "controlName": ["xamSchedule"],
    "tags": ["Events","Scheduling"],
    "guid": "89c33901-889b-4099-9ca2-d75cdc3cd46d",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:58.7533287Z"
}
|metadata|
////

= Handling Data Manager Events

The xamSchedule view controls, link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.xamdayview.html[xamDayView], link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.xammonthview.html[xamMonthView] and link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.xamscheduleview.html[xamScheduleView], access data through the link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.xamscheduledatamanager.html[xamScheduleDataManager] class. Multiple view controls can share a xamScheduleDataManager by setting their link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.schedulecontrolbase~datamanager.html[DataManager] properties to the same instance.

The DataManager exposes a set of events that are raised when activities are changed either through UI interaction, via one on the view controls or dialogs, or through code by calling the DataManager’s link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.xamscheduledatamanager~beginedit.html[BeginEdit], link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.xamscheduledatamanager~begineditwithcopy.html[BeginEditWithCopy] or link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.xamscheduledatamanager~createnew.html[CreateNew] methods, then setting some properties on the activity and then calling the link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.xamscheduledatamanager~endedit.html[EndEdit] method. DataManager’s link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.xamscheduledatamanager~remove.html[Remove] method also raises the associated activity events.

There are also events raised before dialogs or errors are displayed.

*Note:* the events ending in "...ing" can be cancelled by setting the Cancel property of the event arguments to true. Canceling the event prevents the data manager from proceeding with the operation in progress.

The following xaml snippet shows how to listen for the various events exposed off xamScheduleDataManager:

*In XAML:*

----
<ig:XamScheduleDataManager
    ActivityDialogDisplaying=
        "XamScheduleDataManager_ActivityDialogDisplaying"
    ActivityRecurrenceChooserDialogDisplaying=
        "XamScheduleDataManager_ActivityRecurrenceChooserDialogDsplyng"                    
    ActivityAdding=
        "XamScheduleDataManager_ActivityAdding"
    ActivityAdded=
        "XamScheduleDataManager_ActivityAdded"
    ActivityChanging=
        "XamScheduleDataManager_ActivityChanging"
    ActivityChanged=
        "XamScheduleDataManager_ActivityChanged"                   
    ActivityRemoving=
        "XamScheduleDataManager_ActivityRemoving"
    ActivityRemoved=
        "XamScheduleDataManager_ActivityRemoved"
    ActivitiesDragged=
        "XamScheduleDataManager_ActivitiesDragged"
    ActivitiesDragging=
        "XamScheduleDataManager_ActivitiesDragging"
    ActivityResized=
        "XamScheduleDataManager_ActivityResized"
    ActivityResizing=
        "XamScheduleDataManager_ActivityResizing"
    Error=
        "XamScheduleDataManager_Error"
    ErrorDisplaying=
        "XamScheduleDataManager_ErrorDisplaing"
    ReminderActivated=
        "XamScheduleDataManager_ReminderActivated"
    ReminderDialogDisplaying=
        "XamScheduleDataManager_ReminderDialogDisplaying"
>
----

== Related Topics

link:xamschedule-understanding-data-manager.html[About the Data Manager]

link:xamschedule-understanding-activities.html[About Activities]