////

|metadata|
{
    "name": "xamslider-using-xamslider",
    "controlName": ["xamSlider"],
    "tags": [],
    "guid": "{F76AA50B-8E3B-46A6-8028-14A68582532E}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:59.0233702Z"
}
|metadata|
////

= Using xamSlider

This section is your gateway to important task-based information that will help you to effectively use the various features and functionalities provided by xamSlider™ control.

link:xamslider-interaction-modes.html[Interaction Modes]

This topic demonstrates how to set the xamSlider control's interaction modes.

link:xamslider-xamslider-thumbs.html[xamSlider Thumbs]

This topic demonstrates how to add thumbs to the xamSlider control and how to set the different properties.

link:xamslider-xamslider-tick-marks.html[xamSlider Tick Marks]

This topic demonstrates how to add tick marks to the xamSlider control and how to set the different properties.

link:xamslider-value-tick-marks.html[Value Tick Marks]

This walk through demonstrates how to override the tick mark's default setting and display the value of the tick mark instead.

link:xamslider-retrieve-the-thumb-values.html[Retrieve the Thumb Values]

This topic demonstrates how you can retrieve the thumb's value.

link:xamslider-programmatically-add-or-remove-thumbs-at-runtime.html[Programmatically Add or Remove Thumbs at Runtime]

This topic demonstrates how you can add or remove thumbs using procedural code.

pick:[win-phone=" link:xamslider-displaying-thumb-values.html[Displaying Thumb Values]"]

ifdef::win-phone[]
This topic demonstrates how to combine the xamSlider with a callout (xamInfoBox™) to display the thumb's actual value.
endif::win-phone[]

pick:[win-phone=" link:xamslider-configuring-touch-area.html[Configuring Touch Area]"]

ifdef::win-phone[]
This topic demonstrates how to configure the size of the touch area allowing user interactions with the control.
endif::win-phone[]