////

|metadata|
{
    "name": "xamschedule-using-manager-permission",
    "controlName": ["xamSchedule"],
    "tags": ["Appointments","How Do I","Recurrences","Scheduling"],
    "guid": "9f4f8a71-38bb-4641-971d-8f6d2107ec19",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:58.7653294Z"
}
|metadata|
////

= Permission

link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.xamscheduledatamanager.html[XamScheduleDataManager] exposes properties that let you control whether the user is allowed to perform certain operations. These properties are exposed by the XamScheduleDataManager via its link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.xamscheduledatamanager~settings.html[Settings] property, which is of the type link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.schedulesettings.html[ScheduleSettings] class. The following is a list of properties that the ScheduleSettings class exposes related to user permissions.

* link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.schedulesettings~allowcalendarclosing.html[AllowCalendarClosing] – Determines whether the user is allowed to close calendars via the UI. This property can affect the visibility of the close button on the calendar tabs. Setting the property to False will hide the buttons if the view control’s link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.schedulecontrolbase~showcalendarclosebutton.html[ShowCalendarCloseButton] is set to its default value of null.
* link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.schedulesettings~appointmentsettings.html[AppointmentSettings] – Contains settings for appointments
* link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.schedulesettings~journalsettings.html[JournalSettings] – Contains settings for journals
* link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.schedulesettings~tasksettings.html[TaskSettings] – Contains settings for tasks

AppointmentSettings, JournalSettings and TaskSettings all expose the following properties:

* link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.activitysettings~allowadd.html[AllowAdd] – Specifies whether the user is allowed to add an activity – appointment, journal or task – depending on whether the property belongs to AppointmentSettings, JournalSettings or TaskSettings respectively.
* link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.activitysettings~allowedit.html[AllowEdit] – Specifies whether the user is allowed to modify an existing activity.
* link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.activitysettings~allowdragging.html[AllowDragging] – Specifies whether the user is allowed to drag activities. Dragging offers a convenient way for the user to update the activity’s time or make a copy of an activity by holding down the Ctrl key when the activity is dropped.
* link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.activitysettings~allowrecurring.html[AllowRecurring] – Specifies whether the user is allowed to create recurring activities.
* link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.activitysettings~allowremove.html[AllowRemove] – Specifies whether the user is allowed to remove activities.
* link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.activitysettings~allowresizing.html[AllowResizing] – Specifies whether the user is allowed to resize activities. Resizing an activity offers a convenient way for the user to change the start or the end time of the activity.
* link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.activitysettings~allowtimezoneneutral.html[AllowTimeZoneNeutral] – Specifies whether the user can create time-zone neutral activities. Time-zone neutral activities are activities that do not have a specific time zone associated with them and do not start at a specific UTC time. Instead they have a floating start time that starts at the same ‘local’ time in different time zones. Note that if AllowTimeZoneNeutral is set to ‘false’ on AppointmentSettings then the ‘All Day Event’ checkbox will not be displayed on the appointment dialog.

In addition to the above properties, link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.resource.html[Resource] and link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.activitybase.html[ActivityBase] objects expose the following properties that affect user permissions.

* Resource. link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.resource~islocked.html[IsLocked] – When set to True, prevents the user from modifying – including adding and removing – activities of this resource.
* ActivityBase. link:{ApiPlatform}controls.schedules{ApiVersion}~infragistics.controls.schedules.activitybase~islocked.html[IsLocked] – When set to True, prevents the user from modifying or removing the activity.

If you want to conditionally make a determination, for example based on the context of the activity, whether the user should be allowed to perform an operation, then one option is to hook into the event on the XamScheduleDataManager associated with the operation. For example, to prevent the user from adding, removing or committing changes to activities of other resources, you can cancel the ActivityAdding, ActivityRemoving or ActivityChanging event respectively by checking the activity of the event args.

*In XAML:*

----
<ig:XamScheduleDataManager
    Name="DataManager"
    CurrentUserId="own1" 
    DataConnector="{Binding ElementName=connector}">
    <ig:XamScheduleDataManager.Settings>
        <ig:ScheduleSettings AllowCalendarClosing=">
            <ig:ScheduleSettings.AppointmentSettings>
                <ig:AppointmentSettings 
                    AllowDragging="WithinCalendar"
                    AllowRecurring="
                    AllowResizing="StartAndEnd" 
                    AllowTimeZoneNeutral=" />
            </ig:ScheduleSettings.AppointmentSettings>
            <ig:ScheduleSettings.JournalSettings>
                <ig:JournalSettings
                    AllowAdd="
                    AllowRemove="
                    AllowEdit=" />
            </ig:ScheduleSettings.JournalSettings>
            <ig:ScheduleSettings.TaskSettings>
                <ig:TaskSettings
                    AllowRemove="
                    AllowTimeZoneNeutral="
                    AllowRecurring=" />
            </ig:ScheduleSettings.TaskSettings>
        </ig:ScheduleSettings>
    </ig:XamScheduleDataManager.Settings>
</ig:XamScheduleDataManager>
----

*In Visual Basic:*

----
Dim settings As New ScheduleSettings()
settings.AllowCalendarClosing = False
' Create a new AppointmentSettings object.
Dim appointmentSettings As New AppointmentSettings()
appointmentSettings.AllowDragging =_
    AllowActivityDragging.WithinCalendar
appointmentSettings.AllowRecurring = False
appointmentSettings.AllowResizing =_
    AllowActivityResizing.StartAndEnd
appointmentSettings.AllowTimeZoneNeutral = False
' Set the AppointmentSettings property of the ScheduleSettings.
settings.AppointmentSettings = appointmentSettings
' Create a new JournalSettings object.
Dim journalSettings As New JournalSettings()
journalSettings.AllowAdd = False
journalSettings.AllowRemove = False
journalSettings.AllowEdit = False
' Set the JournalSettings property of the ScheduleSettings.
settings.JournalSettings = journalSettings
' Create a new JournalSettings object.
Dim taskSettings As New TaskSettings()
taskSettings.AllowRemove = False
taskSettings.AllowTimeZoneNeutral = False
taskSettings.AllowRecurring = False
' Set the TaskSettings property of the ScheduleSettings.
settings.TaskSettings = taskSettings
' Set the Settings property to the ScheduleSettings object.
_dataManager.Settings = settings
----

*In C#:*

----
ScheduleSettings settings = new ScheduleSettings();
settings.AllowCalendarClosing = false;
// Create a new AppointmentSettings object.
AppointmentSettings appointmentSettings =
    new AppointmentSettings();
appointmentSettings.AllowDragging =
    AllowActivityDragging.WithinCalendar;
appointmentSettings.AllowRecurring = false;
appointmentSettings.AllowResizing =
    AllowActivityResizing.StartAndEnd;
appointmentSettings.AllowTimeZoneNeutral = false;
// Set the AppointmentSettings property of the ScheduleSettings.
settings.AppointmentSettings = appointmentSettings;
// Create a new JournalSettings object.
JournalSettings journalSettings = new JournalSettings();
journalSettings.AllowAdd = false;
journalSettings.AllowRemove = false;
journalSettings.AllowEdit = false;
// Set the JournalSettings property of the ScheduleSettings.
settings.JournalSettings = journalSettings;
// Create a new JournalSettings object.
TaskSettings taskSettings = new TaskSettings();
taskSettings.AllowRemove = false;
taskSettings.AllowTimeZoneNeutral = false;
taskSettings.AllowRecurring = false;
// Set the TaskSettings property of the ScheduleSettings.
settings.TaskSettings = taskSettings;
// Set the Settings property to the ScheduleSettings object.
_dataManager.Settings = settings;
----

== Related Topics

link:xamschedule-understanding-data-manager.html[About the Data Manager]

link:xamschedule-understanding-activities.html[About Activities]