////
|metadata|
{
    "name": "xamschedule-using-activities-tzna",
    "controlName": ["xamSchedule"],
    "tags": ["Appointments","How Do I","Scheduling"],
    "guid": "04bf507b-90b6-4ad3-b844-e343465a7571",
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:58.7863207Z"
}
|metadata|
////

= What is a Time Zone Neutral Activity ?

The link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.activitybase~start.html[Start] and link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.activitybase~end.html[End] time of link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.activitybase.html[activities] are defined as UTC (coordinated universal time) values. Normally, when xamSchedule link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.schedulecontrolbase.html[views] display an activity, the times are converted to the local time zone so that the user sees the activity relative to their time zone.

For example, an activity that was defined to start at 5pm by a user whose local time zone is set to Eastern U.S.Time will store its start time as 10:00pm UTC time. Then if it is displayed by a user in California whose local time zone is set to Pacific Time it will be displayed as starting at 2pm.

Some activities, however, are not time zone dependent but instead are interpreted as a relative or "floating" time.

For example, an activity that represents a holiday should be observed on a specific calendar date but does not start at a specific time of a specific time zone. To define an activity as floating/time zone neutral, the link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.activitybase~istimezoneneutral.html[IsTimeZoneNeutral] property must be set to true. So a time zone neutral activity that represents a holiday whose start time is 12am UTC would be displayed at 12am regardless of the local time zone of the view.

.Note
[NOTE]
====
When IsTimeZoneNeutral is set to true on an activity, the link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.activitybase~starttimezoneid.html[StartTimeZoneId] and link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.activitybase~endtimezoneid.html[EndTimeZoneId] property values are ignored.
====

The link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.activitysettings~allowtimezoneneutral.html[AllowTimeZoneNeutral] property of link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.appointmentsettings.html[AppointmentSettings] may be set to false to prevent the end user from creating time zone neutral appointment. In this case the "All Day Event" checkbox in the appointment dialog is hidden. This is because checking the "All Day Event" checkbox sets the link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.activitybase~istimezoneneutral.html[isTimeZoneNeutral] property to true as well as setting the start and end times to span a day.

== Related Topics

link:xamschedule-using-activities-appointments.html[Appointments]

link:xamschedule-using-activities-tasks.html[Tasks]

link:xamschedule-using-activities-journals.html[Journals]

link:xamschedule-using-activities-recurrent.html[Recurrent Activities]

link:xamschedule-using-activities-reminders.html[Reminders]