////

|metadata|
{
    "name": "xamschedule-using-manager",
    "controlName": ["xamSchedule"],
    "tags": [],
    "guid": "6c0770dd-7685-4acf-9012-4fbed3919cd8",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:58.7143261Z"
}
|metadata|
////

= The Data Manager

Click on the following links to learn about the different features of link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.xamscheduledatamanager.html[xamScheduleDataManager]:

link:xamschedule-using-manager-working-hours.html[Working Hours]

link:xamschedule-using-manager-logical-day.html[Logical Day and Timeslots]

link:xamschedule-using-manager-logical-currentuser.html[Setting the CurrentUser and how it affects control behavior]

link:xamschedule-using-manager-logical-events.html[Handling Data Manager Events]

link:xamschedule-using-manager-errors.html[Errors]

link:xamschedule-using-manager-permission.html[Permission]

link:xamschedule-using-manager-daysettings.html[Day Settings]