////

|metadata|
{
    "name": "xamspellchecker",
    "controlName": ["xamSpellChecker"],
    "tags": [],
    "guid": "{99D06FCF-2DF9-4B42-8F59-44FED0A4C551}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:59.1133399Z"
}
|metadata|
////

= xamSpellChecker

This section gives you an overview of the use of xamSpellChecker™. This section contains valuable information about xamSpellChecker, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish common tasks using the control.Click the links below to access important information about the xamSpellChecker control.

== link:xamspellchecker-about-xamspellchecker.html[About xamSpellChecker]

In this section you’ll find any information that will help you to better understand the functionalities of the xamSpellChecker control, as well as why you would want to use it as part of building your applications.

== link:xamspellchecker-adding-xamspellchecker-to-your-page.html[Adding xamSpellChecker to Your Page]

In order to get you up and running as quickly as possible with the xamSpellChecker control, we've provided you with information on how to get started using the control.

== link:xamspellchecker-using-xamspellchecker.html[Using xamSpellChecker]

This section contains information on the key features and functionalities provided by the xamSpellChecker control.

== link:xamspellchecker-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamSpellChecker control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the {ProductName} help.