////

|metadata|
{
    "name": "xamschedule-understanding-resources-calendars",
    "controlName": ["xamSchedule"],
    "tags": ["Scheduling"],
    "guid": "5f848dcb-861b-4a2e-af49-10bc835022ab",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:58.6313217Z"
}
|metadata|
////

= About Resources and Calendars

XamSchedule components are designed to display, create and manipulate activities . In order to display these entities there needs to be some organization. The first level is accomplished through the link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.activitybase~owningresourceid.html[OwningResourceId] property of an activity – it refers to a link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.resource.html[Resource] entity, which represents, for example, a person or a conference room. Every Resource needs a unique link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.resource~id.html[Id] in order to be referenced as an owner. The second level of organization is done via the link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.activitybase~owningcalendarid.html[OwningCalendarId] property, which identifies a specific link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.resourcecalendar.html[ResourceCalendar] – every activity is assigned to one and only one calendar.

.Note:
[NOTE]
====
Each Resource can have one or more ResourceCalendars.
====

This lets the developer organize the appointments of a certain owner into one or more ResourceCalendars.

.Note:
[NOTE]
====
The minimum required properties of a ResourceCalendar are its link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.resourcecalendar~id.html[Id] and link:{ApiPlatform}controls.schedules.v{ProductVersion}~infragistics.controls.schedules.resourcecalendar~owningresourceid.html[OwningResourceId].
====

In summary, a Resource can have multiple ResourceCalendars (one of which can be specified as the PrimaryCalendar). Every ResourceCalendar can have multiple activities.

The controls expose various properties which govern which ResourceCalendar(s) are displayed in the UI.

== Related Topics

link:xamschedule-understanding-data-connector.html[About the Data Connector]

link:xamschedule-understanding-data-manager.html[About the Data Manager]

link:xamschedule-understanding-views.html[About the xamSchedule views]

link:xamschedule-understanding-activities.html[About Activities]