////

|metadata|
{
    "name": "xamtagcloud-using-xamtagcloud",
    "controlName": ["xamTagCloud"],
    "tags": [],
    "guid": "{DD7295DB-B737-4A6C-9387-7E068A3F3D84}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:59.5293631Z"
}
|metadata|
////

= Using xamTagCloud

This section is your gateway to important conceptual and task-based information that will help you to use the various features and functionalities provided by the xamTagCloud™ control.

link:xamtagcloud-add-cloud-items-to-xamtagcloud.html[Add Cloud Items to xamTagCloud]

This topic explains how to populate the xamTagCloud control with cloud items.

link:xamtagcloud-add-navigation-uris-to-cloud-items2.html[Add Navigation URIs to Cloud Items]

This topic explains how add navigation URIs to cloud items.

link:xamtagcloud-add-spaces-between-cloud-items.html[Add Spaces Between Cloud Items]

This topic demonstrates how to specify a distance between each cloud item.

link:xamtagcloud-xamtagcloud-events.html[Handle xamTagCloud Events]

This topic describes each of xamTagCloud's events and demonstrates how to handle them.

link:xamtagcloud-setting-minimum-and-maximum-scale-values.html[Setting Minimum and Maximum Scale Values]

This topic explains how xamTagCloud’s scale is used to determine the size of the tags based on the value of the weight property and demonstrates how to set these properties.

link:xamtagcloud-smooth-scaling.html[Smooth Scaling]

This topic demonstrates how the xamTagCloud control’s UseSmoothScaling property is used to determine the calculated scaled size of the cloud item.

link:xamtagcloud-working-with-scalebreaks-collection.html[Working with ScaleBreaks Collection]

This topic demonstrates how to group a range of weight values on the same scale break by using the ScaleBreaks collection.