////

|metadata|
{
    "name": "xamtreemap-value-mappers",
    "controlName": ["xamTreemap"],
    "tags": ["How Do I"],
    "guid": "823be5e4-8950-48df-a45e-3742293e00e7",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:59.8283797Z"
}
|metadata|
////

= Value Mappers

This section provides detailed information about the xamTreemap™ control's value mapping functionality.

link:xamtreemap-colormapper.html[ColorMapper]

This topic will teach you how to map colors to the nodes of the xamTreemap control using the ColorMapper.

link:xamtreemap-radialcolormapper.html[RadialColorMapper]

In this topic you will learn how to map radial color brushes to the nodes of the xamTreemap control using the RadialColorMapper.

link:xamtreemap-groupvaluemapper.html[GroupValueMapper]

This topic will guide you how to map values to the different groups of nodes in the xamTreemap control using the GroupValueMapper.

link:xamtreemap-doublemapper.html[DoubleMapper]

In this topic you will learn how to map numeric values to the nodes of the xamTreemap control using the DoubleMapper.

link:xamtreemap-custom-value-mappers.html[xamTreemap Custom Value Mappers]

This topic will show you how to create a custom Value Mapper.