////

|metadata|
{
    "name": "xamtagcloud-api-overview",
    "controlName": ["xamTagCloud"],
    "tags": ["API"],
    "guid": "{FECE0C70-832E-43C1-B267-C4F49A75E7CA}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:59.5353635Z"
}
|metadata|
////

= API Overview

This section lists each namespace that is relevant to the xamTagCloud™ control. We also give you several key classes that you will be using while programming with this control. The namespaces and classes on this page link directly into our API documentation.

[cols="a,a"]
|====
|*xamTagCloud Namespaces*
|*Key Classes*

| link:{ApiPlatform}controls.menus.xamtagcloud{ApiVersion}~infragistics.automationpeers_namespace.html[Infragistics.AutomationPeers] 

link:{ApiPlatform}controls.menus.xamtagcloud{ApiVersion}~infragistics.controls.menus_namespace.html[Infragistics.Controls.Menus]
| link:{ApiPlatform}controls.menus.xamtagcloud{ApiVersion}~infragistics.controls.menus.xamtagcloud.html[XamTagCloud] 

link:{ApiPlatform}controls.menus.xamtagcloud{ApiVersion}~infragistics.controls.menus.xamtagclouditem.html[XamTagCloudItem]

|====