////

|metadata|
{
    "name": "xamtagcloud",
    "controlName": ["xamTagCloud"],
    "tags": [],
    "guid": "{F56932BF-F375-4553-B49E-AECCED35A665}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:59.5223632Z"
}
|metadata|
////

= xamTagCloud

This section gives you an overview of the use of xamTagCloud™. This section contains valuable information about xamTagCloud, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish common tasks using the control. Click the links below to access important information about the xamTagCloud control.

== link:xamtagcloud-about-xamtagcloud.html[About xamTagCloud]

In this section you’ll find any information that will help you to better understand the functionalities of the xamTagCloud control, as well as why you would want to use it as part of building your applications.

== link:xamtagcloud-adding-xamtagcloud-to-your-page.html[Adding xamTagCloud To Your Page]

This topic explains how to add the xamTagCloud control to your page using procedural code and XAML.

== link:xamtagcloud-binding-xamtagcloud-to-data.html[Binding xamTagCloud to Data]

This topic demonstrates how to bind the xamTagCloud control to data using procedural code and XAML.

== link:xamtagcloud-using-xamtagcloud.html[Using xamTagCloud]

This section contains information on the key features and functionalities provided by the xamTagCloud control.

== link:xamtagcloud-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamTagCloud control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the {ProductName} help.