////

|metadata|
{
    "name": "xamtreegrid-conf-filtering",
    "tags": ["Filtering"],
    "controlName": ["xamTreeGrid"],
    "guid": "7f722621-3d80-4cf9-b583-4deb579cf5f7",  
    "buildFlags": [],
    "createdOn": "2015-02-06T12:35:33.4304661Z"
}
|metadata|
////

= Configuring Filtering (xamTreeGrid)

== Topic Overview

=== Purpose

This topic explains how to configure the filtering feature of the control.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamtreegrid-features-overview.html[Features Overview (xamTreeGrid)]
|This topic explains the features supported by the control from developer perspective.

| link:xamtreegrid-visual-elements-overview.html[Visual Elements Overview (xamTreeGrid)]
|This topic provides an overview of the visual elements of the control.

| link:xamdatapresenter-about-record-filtering.html[About Record Filtering (xamDataPresenter)]
|This topic provides an overview of the filtering feature and summarize the main objects and properties related to the filtering feature

|====

== Filtering Summary

=== Filtering summary

The filtering feature of the link:{ApiPlatform}datapresenter.v{ProductVersion}~infragistics.windows.datapresenter.xamtreegrid.html[xamTreeGrid] control filters records against a specified filtering criteria and performs a filter action (for example hiding, disabling or reducing the opacity of records that don’t match the filter criteria). You have the option to specify the filter action performed by the control by choosing a value from the link:{ApiPlatform}datapresenter.v{ProductVersion}~infragistics.windows.datapresenter.recordfilteraction.html[RecordFilterAction] enumeration.

.Note
[NOTE]
====
When the filter action is set to Hide, if some nested level records match the filter criteria but their ancestor records don't match the filter criteria then the ancestor records will be displayed with a reduced opacity.
====

If you set the filter action to `Hide` (which is also the default value) you can still set the control to show filtered out nested (i.e. descendant) records with a reduced opacity when their parent records are matching the filter criteria by choosing the respective value from the link:{ApiPlatform}datapresenter.v{ProductVersion}~infragistics.windows.datapresenter.treeviewfilterresultsdisplaymode.html[TreeViewFilterResultsDisplayMode] enumeration.

=== Filtering configuration summary

The following table explains briefly the configurable aspects of the  _xamTreeGrid_   control's filtering and maps them to the properties that configure them.

[options="header", cols="a,a,a"]
|====
|Configurable aspect|Details|Properties

|Action to perform on filtered items
|Specify the filter action performed over the records which does not match the filter criteria.
| link:{ApiPlatform}datapresenter.v{ProductVersion}~infragistics.windows.datapresenter.fieldlayoutsettings~filteraction.html[XamTreeGrid.FieldLayoutSettings.FilterAction]

|Visibility of filtered out child records
|Configure the visibility of child records which does not match the filter criteria of a parent record which match the filtering criteria.
| link:{ApiPlatform}datapresenter.v{ProductVersion}~infragistics.windows.datapresenter.treeviewsettings~filterresultsdisplaymode.html[XamTreeGrid.ViewSettings.FilterResultsDisplayMode]

|====

=== Code example

The following code example shows how to enable record filtering and configure the control to show filtered out nested records of parent which match the filter criteria.

*In XAML:*

[source,xaml]
----
<igDP:XamTreeGrid>
  <igDP:XamTreeGrid.FieldSettings>
    <igDP:FieldSettings AllowRecordFiltering="True" />
  </igDP:XamTreeGrid.FieldSettings>
  <igDP:XamTreeGrid.FieldLayoutSetting>
    <igDP:FieldLayoutSetting FilterAction="Hide" />
  </igDP:XamTreeGrid.FieldLayoutSetting>
  <igDP:XamTreeGrid.ViewSettings>
    <igDP:TreeViewSettings FilterResultDisplayMode="ShowWithAncestorAndDescendants" />
  </igDP:XamTreeGrid.ViewSettings>
</igDP:XamTreeGrid>
----

== Related Content

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamtreegrid-conf-tree-field.html[Configuring Tree Field (xamTreeGrid)]
|This topic explains how to configure the control's tree field.

| link:xamtreegrid-conf-expansion-indicators.html[Configuring Expansion Indicators (xamTreeGrid)]
|This topic explains how to configure the expansion indicators' behavior.

| link:xamtreegrid-conf-indentation-per-level.html[Configuring Indentation per Level (xamTreeGrid)]
|This topic explains how to set the indentation used to render the child records.

| link:xamtreegrid-conf-selection.html[Configuring Selection (xamTreeGrid)]
|This topic explains how to configure the selection behavior for child level records.

| link:xamtreegrid-conf-summaries.html[Configuring Summaries (xamTreeGrid)]
|This topic explains the specifics of the summaries support of the control.

|====

=== Sample

The following sample provides additional information related to this topic.

[options="header", cols="a,a"]
|====
|Sample|Purpose

| link:{SamplesURL}/tree-grid/filtering[Filtering]
|This sample demonstrates the filtering influence over the parent-child related records.

|====