////

|metadata|
{
    "name": "xamtreegrid-api-reference",
    "tags": ["API"],
    "controlName": ["xamTreeGrid"],
    "guid": "887ff725-5b63-407a-b8e5-6a32c729677a",  
    "buildFlags": [],
    "createdOn": "2015-02-06T14:16:31.3641574Z"
}
|metadata|
////

= API Reference (xamTreeGrid)

=== Introduction

This topic provides reference information about the key classes related to the control.

=== xamSpreadsheet API reference chart

The following table lists the most notable namespaces related to the the  _xamTreeGrid_   control.

[options="header", cols="a,a"]
|====
|Namespace|Description

| link:{ApiPlatform}datapresenter.v{ProductVersion}~infragistics.windows.datapresenter_namespace.html[Infragistics.Windows.DataPresenter]
|The Data Presenter namespace.

|====

The following table lists the most notable classes related to the the  _xamTreeGrid_   control.

[options="header", cols="a,a"]
|====
|Class|Description

| link:{ApiPlatform}datapresenter.v{ProductVersion}~infragistics.windows.datapresenter.xamtreegrid.html[XamTreeGrid]
|The xamTreeGrid control's class.

|====