////

|metadata|
{
    "name": "xamtabcontrol-using-xamtabcontrol",
    "controlName": ["xamTabControl"],
    "tags": [],
    "guid": "{FD95B990-FFA6-477D-8525-916C99A69624}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:54.4722475Z"
}
|metadata|
////

= Using xamTabControl

This section is your gateway to important task-based information that will help you to effectively use the various features and functionalities provided by xamTabControl™.

link:xamtabcontrol-add-a-tab-to-xamtabcontrol.html[Add a Tab to xamTabControl]

This topic describes how you can add a tab to a xamTabControl and work with TabItem and TabItemEx objects.

link:xamtabcontrol-add-content-to-a-tab.html[Add Content to a Tab]

This topic describes how you can add content to a tab in xamTabControl.

link:xamtabcontrol-close-a-tab.html[Close a Tab]

This topic describes how you can close a tab in xamTabControl.

link:xamtabcontrol-enable-multiple-tab-rows.html[Enable Multiple Tab Rows]

This topic describes how you can modify tab layouts and create multiple rows.

link:xamtabcontrol-removing-a-closed-tab.html[Removing a Closed Tab]

This topic describes how you can handle the TabItemEx object's Closed event and remove the TabItemEx object from xamTabControl's Items collection.

link:xamtabcontrol-select-a-tab.html[Select a Tab]

This topic describes how you can select a tab in XAML and in code-behind.

link:xamtabcontrol-tabs-dragging-and-reordering.html[Tabs Dragging and Reordering (xamTabControl)]

This topic explains how to configure the tabs dragging feature which can be used to reorder tabs.