////

|metadata|
{
    "name": "xamtreemap-getting-started-with-xamtreemap",
    "controlName": ["xamTreemap"],
    "tags": ["Getting Started","How Do I"],
    "guid": "d0146086-c5fb-45ea-b51a-458fc0af62ac",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:59.7453753Z"
}
|metadata|
////

= Getting Started with xamTreemap

Click on a topic below to find information on how to get up and running quickly with the link:{ApiPlatform}controls.charts.xamtreemap.v{ProductVersion}~infragistics.controls.charts.xamtreemap.html[xamTreemap]™ control. You will learn how to create a simple  pick:[sl,win-phone="page"]  pick:[wpf="application"]  using the control.

link:xamtreemap-adding-xamtreemap-using-xaml.html[Adding xamTreemap Using XAML Code]

This topic will guide you how to add the xamTreemap control to your application using XAML code.

link:xamtreemap-adding-xamtreemap-using-procedural.html[Adding xamTreemap Using Procedural Code]

This topic will guide you how to add the xamTreemap control to your application using procedural code.

link:xamtreemap-adding-xamtreemap-using-blend.html[Adding xamTreemap Using Expression Blend]

This topic demonstrates how to create a xamTreemap using Expression Blend™.

== Related Topics

link:xamtreemap-understanding-xamtreemap.html[Understanding xamTreemap]

link:xamtreemap-using-xamtreemap.html[Using xamTreemap]

link:xamtreemap-api-overview.html[API Overview]