////

|metadata|
{
    "name": "xamtexteditor-about-xamtexteditor",
    "controlName": ["xamTextEditor"],
    "tags": ["Getting Started"],
    "guid": "{288BA5BB-A142-4CB0-9ED2-2216CB07FEDD}",  
    "buildFlags": [],
    "createdOn": "2012-09-05T19:05:30.2469781Z"
}
|metadata|
////

= About xamTextEditor

The xamTextEditor™ control is a simple text box control that end users can use to input any type of text. Use the xamTextEditor control either as a stand-alone editor or in a Field of the xamDataGrid™ control. As a Field in xamDataGrid, xamTextEditor assists end users in data input while still keeping the proper format of a specific grid column.

xamTextEditor supports multiple data types via its link:{ApiPlatform}editors{ApiVersion}~infragistics.windows.editors.valueeditor~valuetype.html[ValueType] property. The editor will automatically parse and validate the input text to the value type. For example, you can set the ValueType to DateTime and the xamTextEditor will automatically parse the user's input to DateTime objects. If the user's input is not in correct DateTime format, it will consider the input invalid and prompt the user accordingly.