////

|metadata|
{
    "name": "xamtagcloud-add-navigation-uris-to-cloud-items2",
    "controlName": ["xamTagCloud"],
    "tags": ["How Do I","Navigation"],
    "guid": "{8B9B5D6F-D5EF-42EE-8D67-0183E6587C9D}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:59.5733657Z"
}
|metadata|
////

= Add Navigation URIs to Cloud Items

You can add Uniform Resource Identifiers (URI) to the cloud items in your xamTagCloud™ control. This allows your end users to click on a cloud item and navigate to a URI you have defined.

To set the URI of a cloud item, you can set the link:{ApiPlatform}controls.menus.xamtagcloud.v{ProductVersion}~infragistics.controls.menus.xamtagclouditem.html[XamTagCloudItem] object’s NavigateUri property, as demonstrated in the following code snippet.

*In XAML:*

----
<ig:XamTagCloud x:Name="xamTagCloud">
   <ig:XamTagCloudItem Content = "Silverlight" Weight = "10" NavigateUri = "http://www.infragistics.com/products/silverlight" />
…
</ig:XamTagCloud>
----

*In Visual Basic:*

----
Dim cloudItemURI As New XamTagCloudItem
cloudItemURI.Content = "Silverlight"
cloudItemURI.Weight = 10
cloudItemURI.NavigateUri = New Uri("http://www.infragistics.com/products/silverlight")
----

*In C#:*

----
CloudItem uriCloudItem = new XamTagCloudItem ();
uriCloudItem.Content = "Silverlight";
uriCloudItem.Weight = 10;
uriCloudItem.NavigateUri = new Uri(http://www.infragistics.com/products/silverlight);
----

== *Related Topics*

link:xamtagcloud-add-cloud-items-to-xamtagcloud.html[Add Cloud Items to xamTagCloud]

link:xamtagcloud-add-spaces-between-cloud-items.html[Add Spaces Between Cloud Items]

link:xamtagcloud-xamtagcloud-events.html[xamTagCloud Events]

link:xamtagcloud-setting-minimum-and-maximum-scale-values.html[Setting Minimum and Maximum Scale Values]

link:xamtagcloud-smooth-scaling.html[Smooth Scaling]

link:xamtagcloud-working-with-scalebreaks-collection.html[Working with ScaleBreaks Collection]