////

|metadata|
{
    "name": "xamtreemap-features",
    "controlName": ["xamTreemap"],
    "tags": ["Charting"],
    "guid": "fb9e94c8-b126-4356-bc45-2adb0ba1090f",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:59.822419Z"
}
|metadata|
////

= Features

This section provides an overview of the features of the xamTreemap™ control.

link:xamtreemap-events.html[Events]

In this topic you will learn how to handle the events raised by the xamTreemap control.

link:xamtreemap-layouts.html[Layouts]

This topic will introduce to you the different layout types and orientations of the xamTreemap control.

link:xamtreemap-showing-depth.html[Showing Depth]

This topic will guide you how to use the xamTreemap control's Showing Depth feature.

link:xamtreemap-item-minimum-size.html[Item Minimum Size]

This topic is an introduction to the Item Minimum Size feature of the xamTreemap control.

link:xamtreemap-dataminimum-and-datamaximum.html[DataMinimum and DataMaximum]

In this topic you will learn how to use the DataMinimum and DataMaximum properties of the Range Mappers.