////

|metadata|
{
    "name": "xamtreegrid-conf-tree-field",
    "tags": ["Layouts","How Do I"],
    "controlName": ["xamTreeGrid"],
    "guid": "d507749e-b724-473b-a712-18ab550d7d0c",  
    "buildFlags": [],
    "createdOn": "2015-02-06T12:27:52.3694846Z"
}
|metadata|
////

= Configuring Tree Field (xamTreeGrid)

== Topic Overview

=== Purpose

This topic explains how to configure the control's tree field.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamtreegrid-features-overview.html[Features Overview (xamTreeGrid)]
|This topic explains the features supported by the control from developer perspective.

| link:xamtreegrid-visual-elements-overview.html[Visual Elements Overview (xamTreeGrid)]
|This topic provides an overview of the visual elements of the control.

|====

== Tree Field Configuration Summary

=== Tree field summary

The link:{ApiPlatform}datapresenter.v{ProductVersion}~infragistics.windows.datapresenter.xamtreegrid.html[xamTreeGrid] control allows you to specify the field in which the tree will be placed. The value must match the name of the field as set in the field layout. Depending of the  _xamTreeGrid's_   `FlowDirection` property the tree is visually placed on the left or on the right side of the field's content by default.

=== Tree field configuration summary

The following table explains briefly the configurable aspect of the xamTreeGrid control and maps it to the properties that configure it.

[options="header", cols="a,a,a"]
|====
|Configurable aspect|Details|Properties

|[[_Hlk356484826]] 

Tree field
|Used to specify the tree field.
| link:{ApiPlatform}datapresenter.v{ProductVersion}~infragistics.windows.datapresenter.treeviewsettings~treefieldname.html[XamTreeGrid.ViewSettings.TreeFieldName]

|====

.Note
[NOTE]
====
If `TreeFieldName` property is not specified then the first or primary field will be used as the tree field.
====

=== Code example

The following code example show how to set the tree field.

*In XAML:*

[source,xaml]
----
<igDP:XamTreeGrid>
  <igDP:XamTreeGrid.FieldLayouts>
    <igDP:XamTreeGrid.FieldLayout>
      <igDP:Field Name="ID" Label="Customer ID" />
      <igDP:Field Name="Name" Label="Customer Name" />
      <igDP:Field Name="Address" Label="Customer Address" />
    </igDP:XamTreeGrid.FieldLayout>
  </igDP:XamTreeGrid.FieldLayouts>
  <igDP:XamTreeGrid.ViewSettings>
    <igDP:TreeViewSettings TreeFieldName="Name" />
  </igDP:XamTreeGrid.ViewSettings>
</igDP:XamTreeGrid>
----

== Related Content

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:xamtreegrid-conf-expansion-indicators.html[Configuring Expansion Indicators (xamTreeGrid)]
|This topic explains how to configure the expansion indicators' behavior.

| link:xamtreegrid-conf-indentation-per-level.html[Configuring Indentation per Level (xamTreeGrid)]
|This topic explains how to set the indentation used to render the child records.

| link:xamtreegrid-conf-selection.html[Configuring Selection (xamTreeGrid)]
|This topic explains how to configure the selection behavior for child level records.

| link:xamtreegrid-conf-filtering.html[Configuring Filtering (xamTreeGrid)]
|This topic explains how to configure the filtering feature of the control.

| link:xamtreegrid-conf-summaries.html[Configuring Summaries (xamTreeGrid)]
|This topic explains the specifics of the summaries support of the control.

|====

=== Sample

The following sample provides additional information related to this topic.

[options="header", cols="a,a"]
|====
|Sample|Purpose

| link:{SamplesURL}/tree-grid/configuring[Configuring]
|This sample demonstrates how to configure the control.

|====