////
|metadata|
{
    "name": "xamtimeline",
    "controlName": ["xamTimeline"],
    "tags": ["Getting Started"],
    "guid": "{0B457D88-EB27-4B51-8E1D-4A5567F06FBA}",
    "buildFlags": [],
    "createdOn": "2016-05-25T18:22:00.1734083Z"
}
|metadata|
////

= xamTimeline

This section gives you an overview of the use of link:{ApiPlatform}controls.timelines.xamtimeline{ApiVersion}~infragistics.controls.timelines.xamtimeline.html[xamTimeline]™ control. This section contains valuable information about xamTimeline, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish common tasks using the control.

Click the links below to access important information about the xamTimeline control.

== Understanding Timeline

In this section you’ll find any information that will help you to better understand the functionalities of the xamTimeline control, as well as why you would want to use it as part of building your applications.

* link:xamtimeline-understanding-xamwebtimeline.html[Understanding Timeline]

== Getting Started with xamTimeline

Click the links below to find information on how you can get up and running quickly with the xamTimeline control:

* link:xamtimeline-binding-to-data-with-xamtimeline.html[Data Binding]
* link:xamtimeline-display-date-time-series.html[Displaying Date Time Series]
* link:xamtimeline-display-numeric-time-series.html[Displaying Numeric Timeline]

== Using xamTimeline

This section is your gateway to important conceptual and task-based information that will help you to use the various features and functionalities provided by the xamTimeline control.

* link:xamtimeline-axis.html[Customizing Axis]
* link:xamtimeline-about-formatting-xamwebtimeline.html[Formatting Timeline]
* link:xamtimeline-style-xamwebtimeline.html[Styling Timeline]
* link:xamtimeline-xamwebzoombar.html[Navigating Timeline with Zoombar]
* link:xamtimeline-auto-adjust-labels.html[Auto Adjust Labels]

== link:xamtimeline-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the xamTimeline control. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.