////

|metadata|
{
    "name": "xamtimeline-styles",
    "controlName": ["xamTimeline"],
    "tags": ["Styling"],
    "guid": "{D0795AF1-186D-4F2D-BEFD-5CB8BC6E5032}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:59.9793969Z"
}
|metadata|
////

= Styles

This section provides you with useful information about task-based procedures on styling xamTimeline.

link:xamtimeline-style-xamwebtimeline.html[Styling xamTimeline]

This topic introduces the elements of the xamTimeline control which can be styled.

link:xamtimeline-style-time-series.html[Styling Time Series]

This topic will guide you how to style the Time Series of the xamTimeline control.

link:xamtimeline-style-the-axis.html[Styling Axis]

This section provides detailed information about the elements of the xamTimeline control's Axis.

link:xamtimeline-style-legend-and-legend-items.html[Styling Legend and Legend Items]

This topic will show you how to style the Legend and the Legend Items of the xamTimeline control.

link:xamtimeline-style-event-titles.html[Styling Event Titles]

This topic will show you how to style the Event Titles of the xamTimeline control.