////

|metadata|
{
    "name": "xamtilemanager",
    "controlName": ["xamTileManager"],
    "tags": ["Layouts"],
    "guid": "033b3442-e0ef-4c62-9686-b60dfdd086dd",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:59.6113676Z"
}
|metadata|
////

= xamTileManager

This section contains information about xamTileManager™, ranging from what the control does and step-by-step procedures on using it in your application.

Click the links below to access important information about xamTileManager.

== link:xamtilemanager-about-xamtilemanager.html[About xamTileManager]

In this section you'll find an overview of the features provided by xamTileManager.

== link:xamtilemanager-adding-xamtilemanager-to-your-application.html[Adding xamTileManager to Your Application]

In order to get you up and running as quickly as possible with xamTileManager, we've provided you with information on how to get started using the control.

== link:xamtilemanager-using-xamtilemanager.html[Using xamTileManager]

This section contains information on the key features and functionalities provided by xamTileManager.

== link:xamtilemanager-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with xamTileManager. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.