////

|metadata|
{
    "name": "xamtabcontrol",
    "controlName": ["xamTabControl"],
    "tags": [],
    "guid": "{91BA9C46-FA27-41F4-B649-41BBFE9DEE10}",  
    "buildFlags": [],
    "createdOn": "2012-01-30T19:39:54.4362403Z"
}
|metadata|
////

= xamTabControl

This section contains information about xamTabControl™, ranging from what the control does and step-by-step procedures on using it in your application.

Click the links below to access important information about xamTabControl.

== link:xamtabcontrol-about-xamtabcontrol.html[About xamTabControl]

In this section you'll find information that will help you to better understand the functionalities of xamTabControl.

== link:xamtabcontrol-adding-xamtabcontrol-to-your-page-.html[Adding xamTabControl to Your Application]

In order to get you up and running as quickly as possible with xamTabControl, we've provided you with information on how to get started using the control.

== link:xamtabcontrol-using-xamtabcontrol.html[Using xamTabControl]

This section contains information on the key features and functionalities provided by xamTabControl.

== link:xamtabcontrol-about-styling-xamtabcontrol.html[Styling xamTabControl]

This topic describes some styling points that can help you to customize the xamTabControl's look.

== link:xamtabcontrol-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with xamTabControl. The namespaces and classes listed in this topic link conveniently into the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.