////

|metadata|
{
    "name": "xamtexteditor",
    "controlName": ["xamTextEditor"],
    "tags": [],
    "guid": "{110B7C7A-A0B7-49CA-ABEF-6C0FAE9CDF75}",  
    "buildFlags": [],
    "createdOn": "2012-09-05T19:05:30.2419781Z"
}
|metadata|
////

= xamTextEditor

If you're looking for an area that houses all of the overview/task-based information related to the xamTextEditor™ control, you've come to the right place. This section contains valuable information about xamTextEditor, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the xamTextEditor control.

* link:xamtexteditor-about-xamtexteditor.html[About xamTextEditor]
* link:xameditors-overview-of-the-valueeditor-class.html[Overview of the ValueEditor Class]
* link:xamtexteditor-using-xamtexteditor-as-a-field-in-xamdatagrid.html[Using xamTextEditor as a Field in xamDataGrid]
* link:xameditors-enabling-right-to-left-support.html[Enabling Right to Left Support]
* link:xameditors-working-with-the-isalwaysineditmode-property-and-the-editors.html[Working with the IsAlwaysInEditMode Property and the Editors]
* link:xamtexteditor-api-overview.html[API Overview]