////

|metadata|
{
    "name": "xamtreemap-using-xamtreemap",
    "controlName": ["xamTreemap"],
    "tags": ["Getting Started"],
    "guid": "9e28a483-dbb0-4803-ad84-15b63da94d29",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:59.7523786Z"
}
|metadata|
////

= Using xamTreemap

In this section, you will find important task-based information that will help you to make effective use of the various features of the link:{ApiPlatform}controls.charts.xamtreemap{ApiVersion}~infragistics.controls.charts.xamtreemap.html[xamTreemap]™ control.

link:xamtreemap-data-binding.html[Data Binding]

In this topic you will learn how to bind data to the xamTreemap control.

link:xamtreemap-node-binders.html[Node Binders]

In this topic you will learn how to effectively use Node Binders.

link:xamtreemap-wpf-bind-xamtreemap-to-ado-net-entity-data-model.html[Bind xamTreemap to ADO.NET Entity Data Model]
pick:[sl,wpf="This topic will guide you through the steps of binding your xamTreemap to data from a database."]

link:xamtreemap-value-mappers.html[Value Mappers]

This topic category will introduce to you the value mapping capabilities of the xamTreemap control.

link:xamtreemap-features.html[Features]

In this topic category you will learn how to use xamTreemap control's features.

link:xamtreemap-changing-the-style-of-the-nodes.html[Changing the Style of the Nodes]

This topic will guide you how to style the nodes of the xamTreemap control.

link:xamtreemap-data-drill-down.html[Data Drill-down]

In this topic you will learn how to use the xamTreemap control to drill-down data.

== Related Topics

link:xamtreemap-understanding-xamtreemap.html[Understanding xamTreemap]

link:xamtreemap-getting-started-with-xamtreemap.html[Getting Started with xamTreemap]

link:xamtreemap-api-overview.html[API Overview]