////

|metadata|
{
    "name": "xamwebmap-creating-and-editing-custom-shapefiles",
    "controlName": ["xamMap"],
    "tags": ["How Do I","Tips and Tricks"],
    "guid": "{506F2F2B-8E3C-445F-958F-CEB992EC4F8C}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:57.1032272Z"
}
|metadata|
////

= Creating and Editing Custom Shapefiles

The xamMap™ control can be used to render more than just geographic maps. Some examples of non-geographic renderings include: Flow charts, floor plans, seating charts, wiring diagrams, office layouts, and organizational charts. All that is needed is a GIS shapefile which describes how the rendering should look.

*Creating custom shapefiles from CAD vector graphics files*

[start=1]
. Create the rendering using a CAD tool (Microsoft® Visio®, AutoDesk® AutoCAD®, etc.)
[start=2]
. Save the vector graphics tool output to CAD format (.DXF or .DWG)
[start=3]
. Convert the .DFX or .DWG file to the shapefile format (.SHP) using a conversion tool.

.Note:
[NOTE]
====
The Shapefile Tool list contained on this page is provided solely for informational purposes. Infragistics does not endorse or support any 3rd party Shapefile Tools. Infragistics does not warrant any 3rd party Shapefile Tools for any reason, including data accuracy or fitness for any use
====

*CAD to Shapefile conversion utilities*

CAD2Shape - link:http://www.guthcad.com/cad2shape.htm[http://www.guthcad.com/cad2shape.htm]

DXFtoShape - link:http://www.wanderingidea.com[http://www.wanderingidea.com]

*Shapefile Editors*

MapWindow - link:http://www.mapwindow.org[http://www.mapwindow.org]

Dbfeditor - link:http://dbfeditor.com[http://dbfeditor.com]

OpenOffice - link:http://openoffice.org[http://openoffice.org]