////

|metadata|
{
    "name": "xamwebmap-using-xamwebmap",
    "controlName": ["xamMap"],
    "tags": [],
    "guid": "{A7D61F5A-B783-460B-A032-CCEBF2010848}",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:21:57.2932378Z"
}
|metadata|
////

= Using xamMap

This section is your gateway to important conceptual and task-based information that will help you to use the various features and functionalities provided by the link:{ApiPlatform}controls.maps.xammap.v{ProductVersion}~infragistics.controls.maps.xammap.html[xamMap]™ control.

* link:xamwebmap-accessing-data.html[Accessing Data]
* link:xamwebmap-geo-imagery-integration.html[Geo-Imagery Integration]
* link:xamwebmap-customize-map-with-value-templates.html[Display Value Template]
* link:xamwebmap-map-panes.html[Display Map Panes]
* link:xamwebmap-map-elements.html[Display Map Elements]
* link:xamwebmap-map-elements-color-map-elements.html[Color Map Elements]
* link:xammap-map-window-animation.html[Using Map Window Animation]
* link:xamwebmap-using-multiple-layers.html[Using Multiple Layers]