////

|metadata|
{
    "name": "xamzoombar-api-overview",
    "controlName": ["xamZoombar"],
    "tags": ["API","Navigation"],
    "guid": "82def050-0acb-4ad6-9263-3440a05ae785",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:22:00.2294101Z"
}
|metadata|
////

= API Overview

This section lists each namespace that is relevant to the xamZoombar™ control. There are also several key classes listed you will use while programming with this control. The namespaces and classes listed on this page link directly into our API documentation.

[options="header", cols="a,a"]
|====
|Namespace:|Key Classes:

| link:{ApiPlatform}datavisualization.v{ProductVersion}~infragistics.controls_namespace.html[Infragistics.Controls]
| link:{ApiPlatform}datavisualization.v{ProductVersion}~infragistics.controls.xamzoombar.html[XamZoombar] 

link:{ApiPlatform}datavisualization.v{ProductVersion}~infragistics.controls.range.html[Range] 

link:{ApiPlatform}datavisualization.v{ProductVersion}~infragistics.controls.zoomchangedeventargs.html[ZoomChangedEventArgs] 

link:{ApiPlatform}datavisualization.v{ProductVersion}~infragistics.controls.zoomchangeeventargs.html[ZoomChangeEventArgs]

|====