////

|metadata|
{
    "name": "xamzoombar",
    "controlName": ["xamZoombar"],
    "tags": [],
    "guid": "d5ffa46c-7132-43a8-9778-e932b146247d",  
    "buildFlags": [],
    "createdOn": "2016-05-25T18:22:00.2354108Z"
}
|metadata|
////

= xamZoombar

The link:{ApiPlatform}datavisualization.v{ProductVersion}~infragistics.controls.xamzoombar.html[xamZoombar]™ is a control that provides your users with an intuitive user interface for dynamically changing scale and scroll through a range of data. Users can magnify a preview area in which they are interested or drag the edges of the thumb pad to adjust the range currently being displayed. The xamZoombar provides navigation functionality in the link:{ApiPlatform}controls.charts.xamdatachart.v{ProductVersion}~infragistics.controls.charts.xamdatachart.html[xamDataChart] and link:{ApiPlatform}controls.timelines.xamtimeline.v{ProductVersion}~infragistics.controls.timelines.xamtimeline.html[xamTimeline] controls. In addition, you can use the xamZoombar as a stand-alone navigation control.

== Main Features

* Seamless Integration – The xamZoombar seamlessly integrates pan and zoom behavior into the chart and timeline controls.
* Multiple Orientations – You can have the xamZoombar appear vertically or horizontally.
* Panning – Users can scroll the range they currently view from side to side or up and down by dragging the thumb or scrolling at either end of the control.
* Zooming – Users can adjust the display scale by dragging the edges of the thumb to either make the current display cover a larger range (zoom out) or a smaller range (zoom in).

== link:xamzoombar-getting-started-with-xamzoombar.html[Getting Started with xamZoombar]

In order to get you up and running as quickly as possible with the xamZoombar control, we’ve provided you with information on how to get started using the control.

== link:xamzoombar-using-xamzoombar.html[Using xamZoombar]

This section contains valuable information about the xamZoombar control, ranging from what the control does and why you would want to use it in your application to step-by-step procedures on how to accomplish common tasks using the control.

== link:xamzoombar-api-overview.html[API Overview]

The API Overview topic lists the namespaces and classes that you will be working with while programming with the xamZoombar control. The namespaces and classes listed in this topic link conveniently to the link:api-reference-guide.html[API Reference Guide] section of the {ProductName} help.